In [1]:
import pyranges
import pandas
import scanpy
import hdf5plugin
import anndata
import cellrank
import matplotlib
from matplotlib import pyplot
import cellrank
import numpy
import gseapy
import pygam
import seaborn
import pydeseq2
import pydeseq2.dds
import pydeseq2.ds
import scipy

In [2]:
# Load data from Cellrank and SDEvelo

working_directory = "RNA Sequencing Data/"
base_name = "cellrank_version_5"
adata = scanpy.read_h5ad(
    working_directory+f"/{base_name}_anndata.h5ad"
)
driver_df = pandas.read_csv(
    working_directory+f"{base_name}_driver_genes.csv",
    index_col=0
)

In [3]:
# Load adata with raw counts and filter

adata_raw = scanpy.read_h5ad(
    working_directory+f"/splice_counts_mm10.h5ad"
)

# Calculate proportion of mitochondrial genes
adata_raw.var["mt"] = adata_raw.var_names.str.startswith("mt-")
scanpy.pp.calculate_qc_metrics(
    adata_raw, qc_vars=["mt"], inplace=True, percent_top=[], log1p=False
)

scanpy.pp.calculate_qc_metrics(
    adata_raw, inplace=True, percent_top=[], log1p=False
)

# Filter cells by counts per cell, total counts and percent mitochondrial
included_cells = (adata_raw.obs["n_genes_by_counts"] >= 200)*(adata_raw.obs['total_counts'] <= 150000)*(adata_raw.obs['pct_counts_mt'] < 10)
adata_raw = adata_raw[included_cells]
print(adata_raw)

View of AnnData object with n_obs × n_vars = 12791 × 48526
    obs: 'barcode', 'batch', 'sample', 'group', 'day', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt'
    var: 'ensemble_ids', 'gene_symbol', 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts'
    uns: 'sample_colors'
    obsm: 'X_fdl', 'X_umap'
    layers: 'ambiguous', 'matrix', 'spliced', 'unspliced'

# Differential expression pseudobulk analysis with PyDEseq2

Article describing PyDESeq2: https://academic.oup.com/bioinformatics/article/39/9/btad547/7260507

Article describing DESeq2: https://link.springer.com/article/10.1186/s13059-014-0550-8

In [4]:
filtered_adata = adata_raw[:, adata.var_names].copy()
filtered_adata.X = filtered_adata.X.toarray()

In [5]:
# Combine counts within samples

sample_names = adata.obs["sample"].unique()

pseudobulk_rows = []
pseudobulk_index = []
sample_metadata_list = []

for sample in sample_names:
    cells_mask = filtered_adata.obs["sample"] == sample
    sample_X = filtered_adata.X[cells_mask]
    summed_counts = sample_X.sum(axis=0)
        
    pseudobulk_rows.append(summed_counts)
    pseudobulk_index.append(sample)
    
    # Determine the group of the sample
    group = adata.obs.loc[cells_mask, "group"].iloc[0]
    day = adata.obs.loc[cells_mask, "day"].iloc[0]
    sample_metadata_list.append({"sample": sample, "group": group, "day": day})

# Create the counts dataframe
counts_df = pandas.DataFrame(
    data=pseudobulk_rows,
    index=pseudobulk_index,
    columns=adata.var_names
)

# Create metadata dataframe
metadata_df = pandas.DataFrame(sample_metadata_list).set_index("sample")

In [6]:
# Differential expression analysis with pydeseq2

reprogramming_adata = adata[adata.obs["group"].isin({"Hic2", "control"})].copy()
inference = pydeseq2.dds.DefaultInference(n_cpus=8)
dds = pydeseq2.dds.DeseqDataSet(
    counts=counts_df,
    metadata=metadata_df,
    design="~group",
    refit_cooks=True,
    inference=inference
)

# Fit model
dds.deseq2()

Using None as control genes, passed at DeseqDataSet initialization

Fitting size factors...
... done in 0.00 seconds.

Fitting dispersions...
... done in 0.32 seconds.

Fitting dispersion trend curve...
... done in 0.04 seconds.

Fitting MAP dispersions...
... done in 0.38 seconds.

Fitting LFCs...
... done in 0.22 seconds.

Calculating cook's distance...
... done in 0.00 seconds.

Replacing 0 outlier genes.

In [7]:
stat_results = pydeseq2.ds.DeseqStats(dds, contrast=["group", "Hic2", "control"], inference=inference)

# compute p-values and adjusted p-values
stat_results.summary()

Log2 fold change & Wald test p-value: group Hic2 vs control
                 baseMean  log2FoldChange     lfcSE      stat    pvalue  \
gene_names
Rb1cc1        2239.163976       -0.283591  0.244634 -1.159246  0.246356
Fam150a         33.706046        0.335673  1.152714  0.291203  0.770896
Prex2          155.234879        1.573466  0.503496  3.125081  0.001778
Sulf1          677.858231        0.077258  0.591976  0.130508  0.896164
Msc            423.997047        2.369996  0.716943  3.305699  0.000947
...                   ...             ...       ...       ...       ...
Egfl6          166.625885        0.470281  0.781868  0.601483  0.547518
Tmsb4x      115027.155006        0.654934  0.384154  1.704876  0.088218
Usp9y           21.430362        2.368054  1.032823  2.292798  0.021860
Erdr1         1123.037550        0.974630  0.549626  1.773260  0.076186
AC168977.1       7.812825       -0.624215  1.416380 -0.440712  0.659422

                padj
gene_names
Rb1cc1      0.512643
Fam150a     0.902655
Prex2       0.021744
Sulf1       0.955788
Msc         0.013162
...              ...
Egfl6       0.770009
Tmsb4x      0.283622
Usp9y       0.123956
Erdr1       0.260079
AC168977.1  0.834466

[2000 rows x 6 columns]

Running Wald tests...
... done in 0.12 seconds.

In [8]:
# Whether genes of interest are up- or downregulated

stem_cell_tfs = ['Jarid2', 'Klf2', 'Mycn', 'Rest', 'Sall1', 'Tcf7l1', 'Tcf7l2',
       'Tfcp2l1', 'Tsc22d1', 'Zfp42']
dead_end_tfs = ['Barx2', 'Dmrtc2', 'Hmgb3', 'Hoxa7', 'Myc', 'Ovol1', 'Phox2a',
       'Tlx2', 'Tshz1', 'Zbtb7c']
genes_of_interest = stem_cell_tfs + dead_end_tfs
stat_results.results_df.loc[genes_of_interest].sort_values("padj")

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
gene_names,,,,,,
Ovol1,340.259652,-3.484112,0.724528,-4.808799,0.000002,0.000080
Tlx2,762.591789,-3.304927,0.750462,-4.403856,0.000011,0.000357
Dmrtc2,884.994216,-3.374380,0.829364,-4.068636,0.000047,0.001226
Hmgb3,1503.378041,-1.429928,0.386190,-3.702652,0.000213,0.004153
Zbtb7c,747.489340,-1.675318,0.482144,-3.474728,0.000511,0.008153
Barx2,241.839421,-2.414571,0.841142,-2.870587,0.004097,0.040247
Phox2a,449.720898,-1.572235,0.579984,-2.710826,0.006712,0.056524
Tcf7l1,1565.285438,1.031554,0.439377,2.347767,0.018886,0.115094
Myc,2758.170812,-0.940123,0.450300,-2.087771,0.036818,0.167710
Tsc22d1,2188.416999,0.626121,0.351872,1.779403,0.075174,0.259703
Tcf7l2,2614.142627,0.791799,0.449216,1.762624,0.077964,0.263825
Hoxa7,618.152729,-1.011286,0.633558,-1.596200,0.110444,0.326755
Rest,5401.685374,0.599170,0.380174,1.576044,0.115016,0.332576
Tshz1,765.033510,-0.792628,0.528061,-1.501017,0.133351,0.365822
Sall1,739.313786,0.729678,0.644497,1.132166,0.257564,0.525669
Jarid2,4416.564879,0.645687,0.623086,1.036274,0.300075,0.568855
Mycn,723.052794,0.726848,0.708118,1.026450,0.304679,0.571238
Zfp42,7623.251096,0.683980,0.691410,0.989255,0.322539,0.588913
Klf2,5153.233819,0.487965,0.599262,0.814276,0.415487,0.670220
Tfcp2l1,1415.720197,0.146903,0.793152,0.185214,0.853061,0.936874

In [9]:
# Most upregulated in control

stat_results.results_df.query("padj < 0.05 and log2FoldChange < 0").sort_values("log2FoldChange").head(50)

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
gene_names,,,,,,
2310046K23Rik,37.150773,-8.101822,1.859812,-4.356259,1.323045e-05,4.361563e-04
Padi4,81.129161,-5.525528,0.887838,-6.223574,4.859564e-10,9.451853e-08
Mal2,397.453478,-5.088056,0.869783,-5.849797,4.921734e-09,7.363671e-07
Vsig8,70.732354,-4.959581,0.871917,-5.688136,1.284334e-08,1.561268e-06
Prss32,1024.286463,-4.922016,0.986613,-4.988802,6.075483e-07,3.938938e-05
Krt14,1462.170985,-4.686814,0.675246,-6.940899,3.896137e-12,1.262998e-09
Ly6g6c,5682.670391,-4.670438,0.962784,-4.850971,1.228587e-06,6.827435e-05
Lgals7,9929.055723,-4.641645,0.854930,-5.429268,5.658576e-08,4.785187e-06
Pkp1,401.631709,-4.622098,0.650179,-7.108967,1.169150e-12,4.547994e-10
S100a14,1376.369277,-4.516044,0.968108,-4.664812,3.088997e-06,1.335133e-04
Rtn4r,785.992916,-4.428201,0.498475,-8.883500,6.478885e-19,1.260143e-15
Kcnn4,648.801955,-4.392052,0.513962,-8.545479,1.280040e-17,1.244839e-14
Krt17,4166.080818,-4.366984,0.823371,-5.303786,1.134250e-07,7.878988e-06
Gpx2,1563.952543,-4.364635,0.927770,-4.704435,2.545694e-06,1.151482e-04
Mal,2423.561482,-4.192244,0.579921,-7.228987,4.866085e-13,2.366134e-10
Krt6a,228.010654,-4.110728,0.741095,-5.546829,2.908976e-08,2.977873e-06
Rab25,860.863747,-4.086347,0.902470,-4.527960,5.955575e-06,2.204335e-04
Lad1,816.576826,-4.044778,0.649112,-6.231251,4.627261e-10,9.451853e-08
Lmo1,2558.607593,-4.003371,0.592149,-6.760747,1.372817e-11,3.814471e-09
Serpinb6c,591.929290,-3.994460,0.812673,-4.915213,8.868587e-07,5.227091e-05
Edn2,115.436984,-3.989054,0.889034,-4.486951,7.224971e-06,2.555012e-04
Prok2,22.965498,-3.965861,0.804601,-4.928979,8.266034e-07,5.024199e-05
Them5,217.904392,-3.921043,0.860180,-4.558400,5.154482e-06,1.965778e-04
Slc23a3,28.360139,-3.859353,0.939943,-4.105943,4.026679e-05,1.097639e-03
Plek2,522.750782,-3.817724,0.693505,-5.504966,3.692388e-08,3.419855e-06
Chl1,31.048524,-3.793933,0.815884,-4.650088,3.317933e-06,1.373060e-04
Fermt3,732.972656,-3.767921,0.867199,-4.344934,1.393176e-05,4.516211e-04
Nectin4,215.064532,-3.640039,0.816045,-4.460588,8.173516e-06,2.838837e-04
Tgm3,73.597564,-3.521010,0.857977,-4.103854,4.063239e-05,1.097639e-03
Sdcbp2,523.941358,-3.490029,0.624626,-5.587389,2.305096e-08,2.490784e-06
Ovol1,340.259652,-3.484112,0.724528,-4.808799,1.518397e-06,7.981844e-05
Prkaa2,593.112304,-3.452522,0.515965,-6.691384,2.210699e-11,5.374762e-09
Chst13,485.798244,-3.380278,0.693332,-4.875408,1.085836e-06,6.211621e-05
Dmrtc2,884.994216,-3.374380,0.829364,-4.068636,4.728912e-05,1.226364e-03
Chit1,36.381579,-3.366540,0.780194,-4.315002,1.596016e-05,4.927382e-04
Myl7,934.077975,-3.333973,0.622228,-5.358122,8.409128e-08,6.057687e-06
Tlx2,762.591789,-3.304927,0.750462,-4.403856,1.063436e-05,3.568447e-04
Amn,260.074724,-3.275745,0.743859,-4.403718,1.064113e-05,3.568447e-04
Slurp1,704.880099,-3.190673,0.936651,-3.406471,6.580861e-04,9.943827e-03
Dsg3,11.323480,-3.189526,0.971728,-3.282325,1.029549e-03,1.400331e-02
Gatm,561.844899,-3.162412,0.571331,-5.535166,3.109338e-08,3.023832e-06
Cyth4,21.517209,-3.132995,0.836369,-3.745949,1.797130e-04,3.641059e-03
Nrip3,384.240846,-3.018945,0.628863,-4.800640,1.581596e-06,8.095273e-05
Ccdc109b,550.132485,-2.990963,0.715420,-4.180711,2.905995e-05,8.436060e-04
Alox12b,327.447318,-2.978651,0.942253,-3.161203,1.571191e-03,1.958953e-02
Fbp2,389.243579,-2.942744,0.797906,-3.688083,2.259500e-04,4.309343e-03
Urah,1385.647595,-2.912973,0.618422,-4.710330,2.473159e-06,1.145308e-04
Mbp,95.100352,-2.908114,0.806750,-3.604728,3.124806e-04,5.475448e-03
Hsd17b2,47.252009,-2.862395,0.931938,-3.071445,2.130254e-03,2.451683e-02
Ptprv,1079.029714,-2.857724,0.500475,-5.710024,1.129602e-08,1.561268e-06

In [10]:
# Most upregulated in Hic2

stat_results.results_df.query("padj < 0.05 and log2FoldChange > 0").sort_values("log2FoldChange", ascending=False).head(50)

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
gene_names,,,,,,
Xist,792.024515,3.977165,1.005491,3.955448,7.639151e-05,1.857269e-03
Cd36,25.023779,3.873931,1.143431,3.387989,7.040699e-04,1.029636e-02
Marc1,24.456462,3.576419,0.892136,4.008825,6.102151e-05,1.522021e-03
Stra8,89.375272,3.541480,1.127707,3.140425,1.687032e-03,2.089985e-02
Xirp2,83.190523,3.082889,0.872794,3.532207,4.121060e-04,6.909881e-03
Cdh5,19.222726,3.024164,1.058710,2.856462,4.283913e-03,4.166105e-02
Spink6,436.255228,2.897080,0.983585,2.945431,3.225055e-03,3.465597e-02
Myl3,35.093383,2.895067,0.861486,3.360551,7.778707e-04,1.119690e-02
Bhmt,39.421950,2.885319,1.006768,2.865921,4.157980e-03,4.063955e-02
Sept4,109.194570,2.835527,1.019765,2.780571,5.426347e-03,4.931890e-02
3830417A13Rik,179.165853,2.828486,0.870070,3.250874,1.150510e-03,1.532699e-02
Hand1,107.404338,2.811928,0.935994,3.004215,2.662672e-03,2.942555e-02
Apobec2,305.258330,2.629227,0.715753,3.673375,2.393680e-04,4.476642e-03
Nefh,322.626688,2.599575,0.434808,5.978668,2.249689e-09,3.646370e-07
Gulo,116.968786,2.591274,0.911267,2.843593,4.460793e-03,4.274011e-02
Nup62cl,554.476949,2.499195,0.544563,4.589357,4.446129e-06,1.729544e-04
Lrp2,138.926494,2.445878,0.759983,3.218331,1.289389e-03,1.682592e-02
Folr1,1770.720347,2.438302,0.712032,3.424428,6.160950e-04,9.540823e-03
Rec114,205.429660,2.435092,0.697860,3.489372,4.841564e-04,7.847368e-03
Aldh1l1,73.653034,2.427889,0.722852,3.358764,7.829198e-04,1.119690e-02
Nrxn1,182.160517,2.414257,0.752630,3.207759,1.337734e-03,1.723107e-02
Msc,423.997047,2.369996,0.716943,3.305699,9.473992e-04,1.316208e-02
Ltc4s,111.877044,2.366903,0.798177,2.965386,3.023037e-03,3.278690e-02
Fgfbp1,4362.318838,2.350174,0.597120,3.935851,8.290245e-05,1.990682e-03
Lmo2,58.387519,2.312130,0.588037,3.931943,8.426200e-05,1.998653e-03
Klhl13,1888.489864,2.299637,0.606464,3.791879,1.495115e-04,3.093616e-03
Tnnt1,517.722938,2.282810,0.594246,3.841525,1.222725e-04,2.672135e-03
Mdk,5020.403514,2.249833,0.443572,5.072077,3.934962e-07,2.639139e-05
Rbp4,242.892952,2.229979,0.802563,2.778573,5.459822e-03,4.939234e-02
Calcoco2,1077.338400,2.225425,0.782560,2.843775,4.458248e-03,4.274011e-02
Slc1a2,18.430733,2.221650,0.588311,3.776319,1.591634e-04,3.258662e-03
Dnmt3l,1963.192554,2.135246,0.749945,2.847202,4.410530e-03,4.267901e-02
Fxyd6,2310.756509,2.116505,0.579214,3.654101,2.580848e-04,4.780714e-03
Peg10,1648.151905,2.100340,0.523937,4.008764,6.103733e-05,1.522021e-03
Snhg11,586.742442,2.097211,0.753153,2.784573,5.359818e-03,4.917380e-02
Cubn,23.541103,2.094027,0.727490,2.878425,3.996661e-03,3.990094e-02
Nostrin,92.594591,2.091927,0.611160,3.422880,6.196151e-04,9.540823e-03
Eras,524.910689,2.086408,0.674359,3.093913,1.975357e-03,2.314499e-02
Igll1,54.946372,2.070590,0.609573,3.396784,6.818266e-04,1.012330e-02
Cdo1,577.792410,2.051270,0.472997,4.336750,1.446049e-05,4.610762e-04
Ifi27l2a,3358.679116,2.043173,0.600418,3.402918,6.667028e-04,9.974900e-03
Limch1,358.804382,2.030862,0.525423,3.865196,1.109998e-04,2.539937e-03
Des,472.780764,1.972510,0.553247,3.565335,3.633918e-04,6.199974e-03
1500009L16Rik,1379.527449,1.971310,0.408461,4.826186,1.391728e-06,7.519195e-05
Cotl1,1020.687532,1.945478,0.476191,4.085501,4.398179e-05,1.171844e-03
Ms4a10,55.813072,1.937841,0.498289,3.888988,1.006631e-04,2.330831e-03
Mfap5,2552.857687,1.931960,0.473721,4.078265,4.537295e-05,1.192573e-03
Aspa,207.692877,1.899137,0.401147,4.734266,2.198491e-06,1.069016e-04
Itih5,174.294032,1.895624,0.595095,3.185414,1.445472e-03,1.837545e-02
Ramp3,440.570481,1.844973,0.327087,5.640610,1.694490e-08,1.938695e-06

# Differential expression in bulk data with PyDEseq2

Article describing PyDESeq2: https://academic.oup.com/bioinformatics/article/39/9/btad547/7260507

Article describing DESeq2: https://link.springer.com/article/10.1186/s13059-014-0550-8

In [11]:
bulk_counts = pandas.read_csv("RNA Sequencing Data/Bulk RNA sequencing data Hic2/counts2.tsv", sep="\t", index_col=0).T
samples = bulk_counts.index.to_list()
print(samples)

['Day2_BFP_Rep1', 'Day2_BFP_Rep2', 'Day2_BFP_Rep3', 'Day2_Hic2_Rep1', 'Day2_Hic2_Rep2', 'Day2_Hic2_Rep3', 'Day4_BFP_Rep1', 'Day4_BFP_Rep1-2', 'Day4_BFP_Rep2', 'Day4_BFP_Rep3', 'Day4_Hic2_Rep1', 'Day4_Hic2_Rep1-2', 'Day4_Hic2_Rep2', 'Day4_Hic2_Rep3', 'Day6_BFP_Rep1', 'Day6_BFP_Rep2', 'Day6_BFP_Rep3', 'Day6_Hic2_Rep1', 'Day6_Hic2_Rep2', 'Day6_Hic2_Rep3', 'Day10_BFP_Rep1', 'Day10_BFP_Rep2', 'Day10_BFP_Rep3', 'Day10_Hic2_Rep1', 'Day10_Hic2_Rep2', 'Day10_Hic2_Rep3', 'ESC_BFP_Rep1', 'ESC_BFP_Rep2', 'ESC_BFP_Rep3', 'ESC_Hic2-gRNA_Rep1', 'ESC_Hic2-gRNA_Rep2', 'ESC_Hic2-gRNA_Rep3', 'ESC_Zeo-gRNA_Rep1', 'ESC_Zeo-gRNA_Rep2', 'ESC_Zeo-gRNA_Rep3', 'iPSC_BFP_Rep1', 'iPSC_BFP_Rep2', 'iPSC_BFP_Rep3', 'iPSC_Hic2_Rep1', 'iPSC_Hic2_Rep2', 'iPSC_Hic2_Rep3', 'MEF_BFP_Rep1', 'MEF_BFP_Rep2', 'MEF_BFP_Rep3', 'MEF_Hic2_Rep1', 'MEF_Hic2_Rep2', 'MEF_Hic2_Rep3']

In [12]:
# Create metadata dataframe

sample_metadata_list = []

for sample in samples:
    sample_name_list = sample.split("_")
    if ("Day" in sample_name_list[0]):
        day = int(sample_name_list[0][3:])
        experiment = "reprogramming"
    else:
        day = 0
        experiment = sample_name_list[0]
    group = sample_name_list[1]
    replicate_list = sample_name_list[2][3:].split("-")
    replicate = replicate_list[0]
    if len(replicate_list) == 2:
        batch = int(replicate_list[1])
    else:
        batch = 1 if experiment in {"reprogramming", "MEF"} else 2
    
    sample_metadata_list.append({"sample": sample, "day": day, "experiment": experiment, "group": group, "replicate": replicate, "batch": batch})

# Create metadata dataframe
metadata_df = pandas.DataFrame(sample_metadata_list).set_index("sample")

metadata_df

                    day     experiment      group replicate  batch
sample
Day2_BFP_Rep1         2  reprogramming        BFP         1      1
Day2_BFP_Rep2         2  reprogramming        BFP         2      1
Day2_BFP_Rep3         2  reprogramming        BFP         3      1
Day2_Hic2_Rep1        2  reprogramming       Hic2         1      1
Day2_Hic2_Rep2        2  reprogramming       Hic2         2      1
Day2_Hic2_Rep3        2  reprogramming       Hic2         3      1
Day4_BFP_Rep1         4  reprogramming        BFP         1      1
Day4_BFP_Rep1-2       4  reprogramming        BFP         1      2
Day4_BFP_Rep2         4  reprogramming        BFP         2      1
Day4_BFP_Rep3         4  reprogramming        BFP         3      1
Day4_Hic2_Rep1        4  reprogramming       Hic2         1      1
Day4_Hic2_Rep1-2      4  reprogramming       Hic2         1      2
Day4_Hic2_Rep2        4  reprogramming       Hic2         2      1
Day4_Hic2_Rep3        4  reprogramming       Hic2         3      1
Day6_BFP_Rep1         6  reprogramming        BFP         1      1
Day6_BFP_Rep2         6  reprogramming        BFP         2      1
Day6_BFP_Rep3         6  reprogramming        BFP         3      1
Day6_Hic2_Rep1        6  reprogramming       Hic2         1      1
Day6_Hic2_Rep2        6  reprogramming       Hic2         2      1
Day6_Hic2_Rep3        6  reprogramming       Hic2         3      1
Day10_BFP_Rep1       10  reprogramming        BFP         1      1
Day10_BFP_Rep2       10  reprogramming        BFP         2      1
Day10_BFP_Rep3       10  reprogramming        BFP         3      1
Day10_Hic2_Rep1      10  reprogramming       Hic2         1      1
Day10_Hic2_Rep2      10  reprogramming       Hic2         2      1
Day10_Hic2_Rep3      10  reprogramming       Hic2         3      1
ESC_BFP_Rep1          0            ESC        BFP         1      2
ESC_BFP_Rep2          0            ESC        BFP         2      2
ESC_BFP_Rep3          0            ESC        BFP         3      2
ESC_Hic2-gRNA_Rep1    0            ESC  Hic2-gRNA         1      2
ESC_Hic2-gRNA_Rep2    0            ESC  Hic2-gRNA         2      2
ESC_Hic2-gRNA_Rep3    0            ESC  Hic2-gRNA         3      2
ESC_Zeo-gRNA_Rep1     0            ESC   Zeo-gRNA         1      2
ESC_Zeo-gRNA_Rep2     0            ESC   Zeo-gRNA         2      2
ESC_Zeo-gRNA_Rep3     0            ESC   Zeo-gRNA         3      2
iPSC_BFP_Rep1         0           iPSC        BFP         1      2
iPSC_BFP_Rep2         0           iPSC        BFP         2      2
iPSC_BFP_Rep3         0           iPSC        BFP         3      2
iPSC_Hic2_Rep1        0           iPSC       Hic2         1      2
iPSC_Hic2_Rep2        0           iPSC       Hic2         2      2
iPSC_Hic2_Rep3        0           iPSC       Hic2         3      2
MEF_BFP_Rep1          0            MEF        BFP         1      1
MEF_BFP_Rep2          0            MEF        BFP         2      1
MEF_BFP_Rep3          0            MEF        BFP         3      1
MEF_Hic2_Rep1         0            MEF       Hic2         1      1
MEF_Hic2_Rep2         0            MEF       Hic2         2      1
MEF_Hic2_Rep3         0            MEF       Hic2         3      1

In [13]:
# Fix duplicated columns
duplicated_columns = bulk_counts.columns[bulk_counts.columns.duplicated()].to_list()
print(duplicated_columns)

# These likely result from Excel misinterpreting gene names as dates, possibly MARC1 and MARC2. They can be ignored.
bulk_counts = bulk_counts.drop(columns=duplicated_columns)

['Mar-01', 'Mar-02']

In [14]:
# Find columns that are also in the adata object

variable_genes = adata.var.index.to_numpy()
common_genes = numpy.intersect1d(variable_genes, bulk_counts.columns.to_numpy())

## Differential expression during the reprogramming experiment

In [15]:
reprogramming_samples = metadata_df.query("experiment == \"reprogramming\"").index.to_list()
print(metadata_df.loc[reprogramming_samples])

                  day     experiment group replicate  batch
sample
Day2_BFP_Rep1       2  reprogramming   BFP         1      1
Day2_BFP_Rep2       2  reprogramming   BFP         2      1
Day2_BFP_Rep3       2  reprogramming   BFP         3      1
Day2_Hic2_Rep1      2  reprogramming  Hic2         1      1
Day2_Hic2_Rep2      2  reprogramming  Hic2         2      1
Day2_Hic2_Rep3      2  reprogramming  Hic2         3      1
Day4_BFP_Rep1       4  reprogramming   BFP         1      1
Day4_BFP_Rep1-2     4  reprogramming   BFP         1      2
Day4_BFP_Rep2       4  reprogramming   BFP         2      1
Day4_BFP_Rep3       4  reprogramming   BFP         3      1
Day4_Hic2_Rep1      4  reprogramming  Hic2         1      1
Day4_Hic2_Rep1-2    4  reprogramming  Hic2         1      2
Day4_Hic2_Rep2      4  reprogramming  Hic2         2      1
Day4_Hic2_Rep3      4  reprogramming  Hic2         3      1
Day6_BFP_Rep1       6  reprogramming   BFP         1      1
Day6_BFP_Rep2       6  reprogramming   BFP         2      1
Day6_BFP_Rep3       6  reprogramming   BFP         3      1
Day6_Hic2_Rep1      6  reprogramming  Hic2         1      1
Day6_Hic2_Rep2      6  reprogramming  Hic2         2      1
Day6_Hic2_Rep3      6  reprogramming  Hic2         3      1
Day10_BFP_Rep1     10  reprogramming   BFP         1      1
Day10_BFP_Rep2     10  reprogramming   BFP         2      1
Day10_BFP_Rep3     10  reprogramming   BFP         3      1
Day10_Hic2_Rep1    10  reprogramming  Hic2         1      1
Day10_Hic2_Rep2    10  reprogramming  Hic2         2      1
Day10_Hic2_Rep3    10  reprogramming  Hic2         3      1

In [16]:
# Fit differential expression model

inference = pydeseq2.dds.DefaultInference(n_cpus=16)
dds = pydeseq2.dds.DeseqDataSet(
    counts=bulk_counts.loc[reprogramming_samples],
    metadata=metadata_df.loc[reprogramming_samples],
    design="~C(day) + C(batch) + group",
    refit_cooks=True,
    inference=inference
)

dds.deseq2()

# Calculate statistics
reprogramming_de_stats = pydeseq2.ds.DeseqStats(dds, contrast=["group", "Hic2", "BFP"], inference=inference)
reprogramming_de_stats.summary()

Using None as control genes, passed at DeseqDataSet initialization

Fitting size factors...
... done in 0.04 seconds.

Fitting dispersions...
... done in 2.22 seconds.

Fitting dispersion trend curve...
... done in 0.51 seconds.

Fitting MAP dispersions...
... done in 2.02 seconds.

Fitting LFCs...
... done in 2.30 seconds.

Calculating cook's distance...
... done in 0.05 seconds.

Replacing 0 outlier genes.

Running Wald tests...

Log2 fold change & Wald test p-value: group Hic2 vs BFP
                baseMean  log2FoldChange     lfcSE      stat        pvalue  \
Gnai3       18118.223009       -0.237734  0.046419 -5.121532  3.030633e-07
Pbsn            0.000000             NaN       NaN       NaN           NaN
Cdc45        1046.343936        0.800273  0.094942  8.429116  3.482852e-17
H19          4548.672607        0.729453  0.114614  6.364408  1.960450e-10
Scml2         183.121673       -0.602971  0.144454 -4.174135  2.991209e-05
...                  ...             ...       ...       ...           ...
BX571804.1      0.000000             NaN       NaN       NaN           NaN
AC154773.1      0.000000             NaN       NaN       NaN           NaN
AL662853.1      0.286036        0.360430  3.104910  0.116084  9.075861e-01
AC145556.1      0.781459       -1.160610  1.788140 -0.649060  5.162997e-01
CT868734.1      0.000000             NaN       NaN       NaN           NaN

                    padj
Gnai3       1.868561e-06
Pbsn                 NaN
Cdc45       7.204903e-16
H19         1.857909e-09
Scml2       1.325471e-04
...                  ...
BX571804.1           NaN
AC154773.1           NaN
AL662853.1           NaN
AC145556.1           NaN
CT868734.1           NaN

[54534 rows x 6 columns]

... done in 1.89 seconds.

In [18]:
# Whether genes of interest are up- or downregulated

reprogramming_de_stats.results_df.loc[genes_of_interest].sort_values("padj")

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
Zbtb7c,1521.129230,-0.943320,0.058151,-16.221943,3.528526e-59,8.875744e-57
Sall1,914.264618,1.516870,0.152381,9.954437,2.411844e-23,8.706573e-22
Barx2,270.806735,-1.207086,0.122707,-9.837179,7.786359e-23,2.699537e-21
Zfp42,2688.373406,1.344900,0.149763,8.980156,2.703821e-19,6.666513e-18
Hmgb3,1523.258054,-0.857015,0.103484,-8.281647,1.214838e-16,2.360299e-15
Ovol1,680.945017,-1.451013,0.185601,-7.817914,5.370601e-15,8.644510e-14
Tcf7l1,582.207950,1.263931,0.164272,7.694150,1.424378e-14,2.177080e-13
Tlx2,585.037236,-1.107785,0.157145,-7.049422,1.796624e-12,2.177406e-11
Tfcp2l1,2321.616881,1.502553,0.225386,6.666573,2.618455e-11,2.759063e-10
Tcf7l2,1162.635586,0.753992,0.117507,6.416592,1.393588e-10,1.340578e-09
Jarid2,2140.717811,0.820343,0.135571,6.051022,1.439299e-09,1.214135e-08
Hoxa7,295.011074,-1.072721,0.196214,-5.467103,4.574495e-08,3.138826e-07
Dmrtc2,104.620388,-0.917730,0.202759,-4.526214,6.004984e-06,3.002863e-05
Rest,2085.826504,0.492894,0.113039,4.360393,1.298291e-05,6.121253e-05
Phox2a,183.685399,-0.313819,0.079289,-3.957924,7.560415e-05,3.123642e-04
Myc,18952.909643,-0.137470,0.083679,-1.642833,1.004176e-01,1.902238e-01
Tshz1,1363.593308,-0.223540,0.148095,-1.509436,1.311875e-01,2.357446e-01
Mycn,298.071539,0.170911,0.176144,0.970293,3.319002e-01,4.827383e-01
Klf2,244.316224,-0.180294,0.236014,-0.763910,4.449206e-01,5.962700e-01
Tsc22d1,3285.236273,0.063317,0.120392,0.525922,5.989421e-01,7.309035e-01

In [19]:
# Higher expression in control

reprogramming_de_stats.results_df.loc[common_genes].query("padj < 0.05 and log2FoldChange < 0").sort_values("log2FoldChange").head(50)

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
2310046K23Rik,121.261593,-5.026695,0.526483,-9.547682,1.326310e-21,4.142749e-20
Krt14,5110.427482,-4.106556,0.314381,-13.062360,5.402643e-39,5.300643e-37
Krt6a,8104.897532,-3.767656,0.231002,-16.310079,8.368502e-60,2.198591e-57
Mlc1,6.222436,-3.765394,0.772700,-4.873032,1.098985e-06,6.230041e-06
Slurp1,817.514135,-3.661155,0.243806,-15.016651,5.712186e-51,9.931224e-49
Sel1l3,35.552444,-3.592158,0.570257,-6.299195,2.991958e-10,2.773220e-09
Chit1,745.571491,-3.592043,0.181281,-19.814787,2.219452e-87,2.099158e-84
Mmp13,74.221433,-3.585201,0.291299,-12.307646,8.239182e-35,6.537431e-33
Krt17,5304.148465,-3.505668,0.151732,-23.104406,4.181106e-118,1.098469e-114
Fam180a,50.590588,-3.467625,0.341159,-10.164249,2.863197e-24,1.124589e-22
Lypd2,29.596562,-3.364678,0.420701,-7.997789,1.266727e-15,2.176727e-14
S100a4,635.795977,-3.333922,0.277218,-12.026353,2.583206e-33,1.873617e-31
Gfap,34.695146,-3.051857,0.512517,-5.954650,2.606287e-09,2.128693e-08
Krt16,4807.327708,-3.035999,0.169454,-17.916394,8.784150e-72,3.643881e-69
Pantr1,1.645327,-2.991019,1.038461,-2.880242,3.973703e-03,1.158119e-02
Cyth4,154.543246,-2.982082,0.220056,-13.551484,7.764411e-42,8.826418e-40
Tgm3,95.263220,-2.959092,0.276241,-10.711981,8.942789e-27,4.246029e-25
Acod1,183.948894,-2.891975,0.306381,-9.439134,3.758727e-21,1.116521e-19
Fas,136.515811,-2.869016,0.263123,-10.903723,1.106356e-27,5.542330e-26
Vsig8,218.067548,-2.861439,0.174166,-16.429352,1.179126e-60,3.168230e-58
Lgals7,1045.989920,-2.852198,0.155777,-18.309466,6.954909e-75,3.498911e-72
Cd53,35.011190,-2.838016,0.485941,-5.840246,5.212387e-09,4.074278e-08
Kif1a,410.312517,-2.834751,0.212314,-13.351701,1.157749e-40,1.205946e-38
Lilrb4a,3.185908,-2.814272,0.948590,-2.966795,3.009214e-03,9.022682e-03
Ptgs1,443.286706,-2.785622,0.171022,-16.288068,1.199602e-59,3.116988e-57
Ramp1,4.928841,-2.737310,0.762926,-3.587911,3.333379e-04,1.215948e-03
Padi4,325.936446,-2.704642,0.330620,-8.180512,2.826408e-16,5.308214e-15
Fermt3,722.130121,-2.697049,0.127462,-21.159600,2.251226e-99,3.548682e-96
Cnn1,72.273911,-2.696505,0.315121,-8.557041,1.158010e-17,2.493730e-16
Upk3b,777.598858,-2.690275,0.254550,-10.568746,4.160186e-26,1.880833e-24
Rab25,75.182075,-2.647381,0.241788,-10.949184,6.704902e-28,3.394805e-26
Prok2,49.529964,-2.639078,0.261774,-10.081513,6.669140e-24,2.519038e-22
Rtn4r,945.036806,-2.632157,0.153454,-17.152707,5.999204e-66,1.970155e-63
Gm8994,16.170070,-2.622987,0.566018,-4.634104,3.584871e-06,1.857237e-05
Dsg3,1442.809217,-2.615226,0.177498,-14.733800,3.910848e-49,6.206174e-47
Gpx2,411.576364,-2.582672,0.161770,-15.965108,2.236529e-57,5.566602e-55
Ly6g6c,1619.300369,-2.579183,0.135474,-19.038204,8.230171e-81,5.259524e-78
Gpm6a,157.332102,-2.571634,0.384503,-6.688198,2.259347e-11,2.411840e-10
Edn2,126.441139,-2.567301,0.219320,-11.705717,1.191474e-31,7.739669e-30
Kcnn4,586.350923,-2.563120,0.197094,-13.004560,1.152596e-38,1.112373e-36
Ehf,147.726657,-2.550276,0.199724,-12.768995,2.442871e-37,2.230181e-35
Pkp1,2909.631813,-2.548214,0.098846,-25.779740,1.496395e-146,1.769113e-142
Mal2,1414.525483,-2.539277,0.107040,-23.722602,2.107776e-124,6.229796e-121
Col2a1,435.806977,-2.531633,0.463879,-5.457525,4.828173e-08,3.298719e-07
Paqr5,88.472256,-2.483270,0.257794,-9.632754,5.814948e-22,1.863068e-20
Prss32,308.741124,-2.452161,0.137686,-17.809855,5.926270e-71,2.375028e-68
Sult2b1,232.481783,-2.424468,0.126188,-19.213201,2.870130e-82,2.056492e-79
Adgrg2,253.169818,-2.375604,0.365534,-6.498992,8.086007e-11,7.993045e-10
Chl1,662.700241,-2.370794,0.159735,-14.842087,7.828246e-50,1.276544e-47
Bnc1,109.319585,-2.364595,0.314648,-7.515047,5.689055e-14,8.098597e-13

The high upregulation of 2310046K23Rik, also known as Small proline rich protein 5 (Sprr5) is very interesting.

Function of human Sprr5 according to Uniprot: "Positively regulates keratinocyte differentiation by inducing genes associated with epidermal differentiation".

In [20]:
# Higher expression with Hic2

reprogramming_de_stats.results_df.loc[common_genes].query("padj < 0.05 and log2FoldChange > 0").sort_values("log2FoldChange", ascending=False).head(50)

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
Ifi27l2a,60.427621,4.964874,0.849305,5.845811,5.041075e-09,3.957378e-08
Eras,129.003245,4.766440,0.745645,6.392374,1.633294e-10,1.556959e-09
3830417A13Rik,274.669327,4.546757,0.306071,14.855229,6.434730e-50,1.071473e-47
Oasl2,329.182784,4.419285,0.438522,10.077691,6.933599e-24,2.609246e-22
Pramef12,591.836100,4.304483,0.708941,6.071709,1.265565e-09,1.073508e-08
Dnmt3l,2023.817274,4.146114,0.878535,4.719352,2.365970e-06,1.268270e-05
Nr0b1,399.205895,4.031501,0.463751,8.693253,3.522062e-18,7.916269e-17
Napsa,4.379697,4.014911,1.029909,3.898317,9.686348e-05,3.921139e-04
Cdh5,11.450055,3.893308,0.550767,7.068885,1.561839e-12,1.900653e-11
Gm13119,27.830769,3.853006,0.458546,8.402669,4.364452e-17,8.934847e-16
Oc90,65.467582,3.726041,0.445047,8.372243,5.653151e-17,1.142468e-15
Xirp2,201.954137,3.552851,0.366211,9.701647,2.966715e-22,9.824646e-21
Rhox6,843.856049,3.497290,0.578944,6.040810,1.533424e-09,1.287565e-08
Rhox9,443.080480,3.371150,0.860592,3.917244,8.956711e-05,3.652033e-04
Ifi44,85.364130,3.191233,0.550913,5.792623,6.929571e-09,5.335386e-08
Msc,393.658370,3.127482,0.163321,19.149323,9.805399e-82,6.819078e-79
Triml2,443.860259,3.125697,0.534643,5.846327,5.025470e-09,3.947749e-08
Gulo,85.436805,3.054613,0.337745,9.044132,1.508584e-19,3.827304e-18
Fgfbp1,1285.708241,3.035683,0.180225,16.843824,1.164611e-63,3.623320e-61
Isg15,188.394009,2.994927,0.277783,10.781534,4.208082e-27,2.047327e-25
Nefh,335.998784,2.933564,0.192661,15.226598,2.355329e-52,4.419981e-50
Mdk,443.711480,2.886874,0.218122,13.235118,5.501025e-40,5.606540e-38
Rtp4,96.476905,2.884328,0.482601,5.976626,2.278065e-09,1.872257e-08
Bhmt,211.717439,2.876332,0.584604,4.920134,8.648520e-07,4.982803e-06
Smyd1,607.598844,2.866995,0.468909,6.114177,9.705625e-10,8.390841e-09
Calcoco2,359.354547,2.792392,0.414160,6.742306,1.558923e-11,1.705519e-10
Cyct,11.355528,2.747193,0.656223,4.186370,2.834510e-05,1.261709e-04
Ifit3,78.258653,2.727286,0.531092,5.135245,2.817769e-07,1.746884e-06
Fgf8,14.487642,2.693382,0.566636,4.753283,2.001401e-06,1.087638e-05
Hrc,226.265561,2.692569,0.334377,8.052486,8.112884e-16,1.425179e-14
Prtg,91.589416,2.670374,0.329348,8.108057,5.143573e-16,9.319523e-15
Apobec2,37.796629,2.649309,0.459248,5.768800,7.983780e-09,6.101373e-08
Rsad2,101.635670,2.634645,0.396480,6.645087,3.030384e-11,3.160716e-10
Usp18,75.666675,2.627379,0.526935,4.986153,6.159347e-07,3.629149e-06
Pramel6,32.955419,2.602657,0.552368,4.711819,2.455152e-06,1.312801e-05
Aard,156.616636,2.584949,0.772097,3.347957,8.140950e-04,2.763715e-03
Gng3,168.878149,2.556263,0.346726,7.372578,1.673592e-13,2.261262e-12
Gdf3,793.392687,2.459679,0.431772,5.696706,1.221440e-08,9.082058e-08
Serpinb9e,5.521220,2.454891,1.046842,2.345044,1.902486e-02,4.662065e-02
Dppa1,11.644146,2.435997,0.681471,3.574619,3.507385e-04,1.274291e-03
Ifit1,115.641867,2.433911,0.474439,5.130079,2.896210e-07,1.793163e-06
Zfp936,263.575857,2.415428,0.687576,3.512959,4.431453e-04,1.582088e-03
Ninl,359.944766,2.394328,0.363023,6.595519,4.237716e-11,4.352772e-10
Triml1,156.575471,2.393034,0.467244,5.121593,3.029653e-07,1.868514e-06
Hand1,197.547415,2.391584,0.512543,4.666114,3.069493e-06,1.611773e-05
Nanog,1323.501794,2.370827,0.257670,9.201027,3.545454e-20,9.461880e-19
Dppa2,670.676987,2.361603,0.459424,5.140357,2.742171e-07,1.703590e-06
Rbpms2,901.729924,2.334365,0.271350,8.602781,7.780756e-18,1.697195e-16
Rbp4,214.452097,2.324890,0.195477,11.893400,1.280844e-32,8.933795e-31
Stra8,46.459730,2.289561,0.898556,2.548045,1.083286e-02,2.837205e-02

## Differential expression in day 2

In [21]:
day_2_samples = metadata_df.query("experiment == \"reprogramming\" and day == 2").index.to_list()
print(metadata_df.loc[day_2_samples])

                day     experiment group replicate  batch
sample
Day2_BFP_Rep1     2  reprogramming   BFP         1      1
Day2_BFP_Rep2     2  reprogramming   BFP         2      1
Day2_BFP_Rep3     2  reprogramming   BFP         3      1
Day2_Hic2_Rep1    2  reprogramming  Hic2         1      1
Day2_Hic2_Rep2    2  reprogramming  Hic2         2      1
Day2_Hic2_Rep3    2  reprogramming  Hic2         3      1

In [22]:
# Fit differential expression model

inference = pydeseq2.dds.DefaultInference(n_cpus=16)
dds = pydeseq2.dds.DeseqDataSet(
    counts=bulk_counts.loc[day_2_samples],
    metadata=metadata_df.loc[day_2_samples],
    design="~group",
    refit_cooks=True,
    inference=inference
)

dds.deseq2()

# Calculate statistics
day_2_de_stats = pydeseq2.ds.DeseqStats(dds, contrast=["group", "Hic2", "BFP"], inference=inference)
day_2_de_stats.summary()

Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.23 seconds.

Fitting dispersion trend curve...
... done in 0.47 seconds.

Fitting MAP dispersions...
... done in 1.42 seconds.

Fitting LFCs...
... done in 1.80 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 0 outlier genes.

Running Wald tests...

Log2 fold change & Wald test p-value: group Hic2 vs BFP
                baseMean  log2FoldChange     lfcSE      stat        pvalue  \
Gnai3       22128.672245       -0.120252  0.037410 -3.214455  1.306925e-03
Pbsn            0.000000             NaN       NaN       NaN           NaN
Cdc45         690.247113        0.478694  0.089751  5.333594  9.628743e-08
H19          2598.156315        0.973740  0.318548  3.056811  2.237051e-03
Scml2         286.322931       -0.440445  0.153644 -2.866664  4.148229e-03
...                  ...             ...       ...       ...           ...
BX571804.1      0.000000             NaN       NaN       NaN           NaN
AC154773.1      0.000000             NaN       NaN       NaN           NaN
AL662853.1      0.000000             NaN       NaN       NaN           NaN
AC145556.1      1.836549       -1.380029  2.047491 -0.674010  5.003051e-01
CT868734.1      0.000000             NaN       NaN       NaN           NaN

                padj
Gnai3       0.006083
Pbsn             NaN
Cdc45       0.000001
H19         0.009774
Scml2       0.016740
...              ...
BX571804.1       NaN
AC154773.1       NaN
AL662853.1       NaN
AC145556.1       NaN
CT868734.1       NaN

[54534 rows x 6 columns]

... done in 2.06 seconds.

In [23]:
# Whether genes of interest are up- or downregulated

day_2_de_stats.results_df.loc[genes_of_interest].sort_values("padj")

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
Zbtb7c,1545.528898,-0.915841,0.073941,-12.386172,3.105169e-35,2.831547e-33
Tshz1,2793.118088,0.592365,0.057745,10.258316,1.085839e-24,5.497585e-23
Tlx2,536.024936,-1.211808,0.131036,-9.247933,2.288763e-20,8.782740e-19
Ovol1,331.654674,-1.328884,0.146448,-9.074094,1.146274e-19,4.084445e-18
Sall1,384.567579,1.171922,0.130355,8.990206,2.467675e-19,8.559147e-18
Hmgb3,1901.452329,-0.379427,0.067962,-5.582933,2.364953e-08,2.756836e-07
Tcf7l1,469.488292,0.578413,0.116473,4.966068,6.832397e-07,6.384809e-06
Jarid2,1936.496621,0.309273,0.064191,4.817978,1.450205e-06,1.280423e-05
Rest,3240.580307,0.212969,0.063922,3.331709,8.631454e-04,4.206842e-03
Tcf7l2,1152.934163,0.308370,0.097661,3.157558,1.590966e-03,7.230541e-03
Zfp42,145.306929,0.604577,0.208036,2.906121,3.659396e-03,1.500591e-02
Barx2,127.302799,-0.652300,0.226520,-2.879656,3.981088e-03,1.613458e-02
Phox2a,254.454334,-0.424789,0.151417,-2.805420,5.025106e-03,1.981191e-02
Dmrtc2,56.268056,-0.717129,0.302605,-2.369852,1.779522e-02,5.764202e-02
Tfcp2l1,49.729455,0.473909,0.340966,1.389899,1.645595e-01,3.364791e-01
Tsc22d1,2681.427756,-0.083418,0.076703,-1.087539,2.767986e-01,4.830730e-01
Hoxa7,287.346874,-0.110042,0.141340,-0.778563,4.362372e-01,6.481838e-01
Mycn,41.935021,0.198285,0.364847,0.543476,5.868023e-01,7.665290e-01
Klf2,22.334884,-0.211883,0.549893,-0.385316,7.000033e-01,8.418349e-01
Myc,29186.163658,0.007789,0.038392,0.202884,8.392254e-01,9.234528e-01

## Differential expression in day 4

In [26]:
day_4_samples = metadata_df.query("experiment == \"reprogramming\" and day == 4").index.to_list()
print(metadata_df.loc[day_4_samples])

                  day     experiment group replicate  batch
sample
Day4_BFP_Rep1       4  reprogramming   BFP         1      1
Day4_BFP_Rep1-2     4  reprogramming   BFP         1      2
Day4_BFP_Rep2       4  reprogramming   BFP         2      1
Day4_BFP_Rep3       4  reprogramming   BFP         3      1
Day4_Hic2_Rep1      4  reprogramming  Hic2         1      1
Day4_Hic2_Rep1-2    4  reprogramming  Hic2         1      2
Day4_Hic2_Rep2      4  reprogramming  Hic2         2      1
Day4_Hic2_Rep3      4  reprogramming  Hic2         3      1

In [27]:
# Fit differential expression model

inference = pydeseq2.dds.DefaultInference(n_cpus=16)
dds = pydeseq2.dds.DeseqDataSet(
    counts=bulk_counts.loc[day_4_samples],
    metadata=metadata_df.loc[day_4_samples],
    design="~C(day) + C(batch) + group",
    refit_cooks=True,
    inference=inference
)

dds.deseq2()

# Calculate statistics
day_4_de_stats = pydeseq2.ds.DeseqStats(dds, contrast=["group", "Hic2", "BFP"], inference=inference)
day_4_de_stats.summary()

Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.43 seconds.

Fitting dispersion trend curve...
... done in 0.48 seconds.

Fitting MAP dispersions...
... done in 1.52 seconds.

Fitting LFCs...
... done in 1.82 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 0 outlier genes.

Running Wald tests...

Log2 fold change & Wald test p-value: group Hic2 vs BFP
                baseMean  log2FoldChange     lfcSE      stat        pvalue  \
Gnai3       15061.034487       -0.145678  0.048888 -2.979812  2.884256e-03
Pbsn            0.000000             NaN       NaN       NaN           NaN
Cdc45         695.773380        0.949563  0.116376  8.159410  3.366663e-16
H19          3270.342112        0.798852  0.092818  8.606611  7.525230e-18
Scml2         239.054249       -0.541207  0.135172 -4.003823  6.232701e-05
...                  ...             ...       ...       ...           ...
BX571804.1      0.000000             NaN       NaN       NaN           NaN
AC154773.1      0.000000             NaN       NaN       NaN           NaN
AL662853.1      0.863819        1.292333  2.205131  0.586057  5.578371e-01
AC145556.1      0.339300        0.601040  3.320829  0.180991  8.563748e-01
CT868734.1      0.000000             NaN       NaN       NaN           NaN

                    padj
Gnai3       7.882933e-03
Pbsn                 NaN
Cdc45       3.668566e-15
H19         9.364109e-17
Scml2       2.251457e-04
...                  ...
BX571804.1           NaN
AC154773.1           NaN
AL662853.1           NaN
AC145556.1           NaN
CT868734.1           NaN

[54534 rows x 6 columns]

... done in 1.97 seconds.

In [28]:
# Whether genes of interest are up- or downregulated

day_4_de_stats.results_df.loc[genes_of_interest].sort_values("padj")

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
Sall1,860.094175,1.705273,0.072756,23.438206,1.743830e-121,4.738640e-119
Zbtb7c,1758.713380,-1.095422,0.053464,-20.488793,2.710318e-93,3.954336e-91
Zfp42,427.157105,1.555553,0.137043,11.350841,7.345297e-30,1.878581e-28
Ovol1,796.688716,-0.757347,0.083485,-9.071703,1.171713e-19,1.685762e-18
Tcf7l1,356.692664,0.890082,0.107501,8.279757,1.234273e-16,1.398221e-15
Barx2,216.086538,-1.102030,0.133419,-8.259913,1.457781e-16,1.641155e-15
Tfcp2l1,213.209667,1.694083,0.213364,7.939867,2.023974e-15,2.080339e-14
Jarid2,2093.237750,0.371469,0.057566,6.452891,1.097362e-10,7.454858e-10
Tlx2,726.747089,-0.622547,0.103229,-6.030721,1.632299e-09,9.887027e-09
Hmgb3,1424.268916,-0.524054,0.092642,-5.656765,1.542528e-08,8.474356e-08
Tsc22d1,2253.604151,-0.450058,0.082281,-5.469797,4.505522e-08,2.356160e-07
Hoxa7,280.197745,-0.606157,0.129811,-4.669544,3.018685e-06,1.294598e-05
Tcf7l2,1416.614372,0.360014,0.088429,4.071212,4.676907e-05,1.719163e-04
Rest,2465.829179,0.222705,0.061301,3.633005,2.801392e-04,9.175752e-04
Phox2a,213.382075,-0.244853,0.126752,-1.931753,5.338997e-02,1.074571e-01
Dmrtc2,87.013683,-0.503283,0.283587,-1.774704,7.594683e-02,1.453352e-01
Klf2,23.574220,-0.749347,0.510424,-1.468087,1.420807e-01,2.445132e-01
Tshz1,1796.923222,0.075990,0.060576,1.254454,2.096769e-01,3.365289e-01
Myc,26936.522194,0.047518,0.053495,0.888270,3.743956e-01,5.242637e-01
Mycn,33.238168,-0.224741,0.314028,-0.715670,4.741952e-01,6.228718e-01

## Differential expression in day 6

In [31]:
day_6_samples = metadata_df.query("experiment == \"reprogramming\" and day == 6").index.to_list()
print(metadata_df.loc[day_6_samples])

                day     experiment group replicate  batch
sample
Day6_BFP_Rep1     6  reprogramming   BFP         1      1
Day6_BFP_Rep2     6  reprogramming   BFP         2      1
Day6_BFP_Rep3     6  reprogramming   BFP         3      1
Day6_Hic2_Rep1    6  reprogramming  Hic2         1      1
Day6_Hic2_Rep2    6  reprogramming  Hic2         2      1
Day6_Hic2_Rep3    6  reprogramming  Hic2         3      1

In [32]:
# Fit differential expression model

inference = pydeseq2.dds.DefaultInference(n_cpus=16)
dds = pydeseq2.dds.DeseqDataSet(
    counts=bulk_counts.loc[day_6_samples],
    metadata=metadata_df.loc[day_6_samples],
    design="~group",
    refit_cooks=True,
    inference=inference
)

dds.deseq2()

# Calculate statistics
day_6_de_stats = pydeseq2.ds.DeseqStats(dds, contrast=["group", "Hic2", "BFP"], inference=inference)
day_6_de_stats.summary()

Fitting size factors...

Using None as control genes, passed at DeseqDataSet initialization

... done in 0.01 seconds.

Fitting dispersions...
... done in 1.43 seconds.

Fitting dispersion trend curve...
... done in 0.45 seconds.

Fitting MAP dispersions...
... done in 1.36 seconds.

Fitting LFCs...
... done in 1.69 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 0 outlier genes.

Running Wald tests...

Log2 fold change & Wald test p-value: group Hic2 vs BFP
                baseMean  log2FoldChange     lfcSE      stat        pvalue  \
Gnai3       22363.371052       -0.307583  0.093112 -3.303380  9.552682e-04
Pbsn            0.000000             NaN       NaN       NaN           NaN
Cdc45        1137.191588        1.182272  0.128137  9.226605  2.793445e-20
H19          3896.764956        0.465219  0.336784  1.381358  1.671688e-01
Scml2          82.045704       -1.696386  0.424089 -4.000073  6.332304e-05
...                  ...             ...       ...       ...           ...
BX571804.1      0.000000             NaN       NaN       NaN           NaN
AC154773.1      0.000000             NaN       NaN       NaN           NaN
AL662853.1      0.000000             NaN       NaN       NaN           NaN
AC145556.1      1.191800       -3.722858  4.235882 -0.878886  3.794630e-01
CT868734.1      0.000000             NaN       NaN       NaN           NaN

                    padj
Gnai3       4.349148e-03
Pbsn                 NaN
Cdc45       1.155026e-18
H19         3.136980e-01
Scml2       3.829907e-04
...                  ...
BX571804.1           NaN
AC154773.1           NaN
AL662853.1           NaN
AC145556.1           NaN
CT868734.1           NaN

[54534 rows x 6 columns]

... done in 1.97 seconds.

In [33]:
# Whether genes of interest are up- or downregulated

day_6_de_stats.results_df.loc[genes_of_interest].sort_values("padj")

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
Tfcp2l1,2117.184424,2.836544,0.194685,14.569883,4.366368e-48,9.687480e-46
Sall1,907.920856,2.474940,0.207610,11.921127,9.185780e-33,9.132071e-31
Hmgb3,1381.829875,-1.399331,0.131310,-10.656667,1.623102e-26,1.028888e-24
Zfp42,1517.458376,1.986789,0.195344,10.170728,2.678989e-24,1.441978e-22
Tcf7l1,432.475319,2.128565,0.227501,9.356281,8.259261e-21,3.560681e-19
Jarid2,950.743533,1.499336,0.176889,8.476130,2.328088e-17,7.436864e-16
Ovol1,1018.742043,-1.117075,0.136306,-8.195337,2.498920e-16,7.170798e-15
Tcf7l2,1105.221422,1.159597,0.143769,8.065703,7.281554e-16,2.007171e-14
Barx2,405.059500,-1.650595,0.232617,-7.095765,1.286382e-12,2.571775e-11
Hoxa7,313.793281,-1.449888,0.251804,-5.758012,8.511049e-09,1.033655e-07
Zbtb7c,1391.874437,-0.754481,0.137692,-5.479469,4.266053e-08,4.644662e-07
Dmrtc2,166.591200,-1.445171,0.382070,-3.782476,1.552758e-04,8.573395e-04
Tlx2,807.056504,-0.684695,0.206666,-3.313061,9.228072e-04,4.214014e-03
Tshz1,440.060650,-0.614942,0.236266,-2.602758,9.247726e-03,3.074632e-02
Rest,734.498038,0.501719,0.206539,2.429180,1.513303e-02,4.640406e-02
Mycn,81.515126,0.619466,0.506077,1.224056,2.209310e-01,3.845210e-01
Phox2a,182.230359,-0.336527,0.287202,-1.171746,2.412990e-01,4.097392e-01
Myc,11581.386808,-0.006990,0.122604,-0.057013,9.545344e-01,9.778617e-01
Tsc22d1,2818.969342,-0.005903,0.123954,-0.047626,9.620146e-01,9.822613e-01
Klf2,71.144448,-0.015460,0.551643,-0.028025,9.776426e-01,9.902155e-01

## Day 10 differential expression

In [36]:
day_10_samples = metadata_df.query("experiment == \"reprogramming\" and day == 10").index.to_list()
print(metadata_df.loc[day_10_samples])

                 day     experiment group replicate  batch
sample
Day10_BFP_Rep1    10  reprogramming   BFP         1      1
Day10_BFP_Rep2    10  reprogramming   BFP         2      1
Day10_BFP_Rep3    10  reprogramming   BFP         3      1
Day10_Hic2_Rep1   10  reprogramming  Hic2         1      1
Day10_Hic2_Rep2   10  reprogramming  Hic2         2      1
Day10_Hic2_Rep3   10  reprogramming  Hic2         3      1

In [37]:
# Fit differential expression model

inference = pydeseq2.dds.DefaultInference(n_cpus=16)
dds = pydeseq2.dds.DeseqDataSet(
    counts=bulk_counts.loc[day_10_samples],
    metadata=metadata_df.loc[day_10_samples],
    design="~group",
    refit_cooks=True,
    inference=inference
)

dds.deseq2()

# Calculate statistics
day_10_de_stats = pydeseq2.ds.DeseqStats(dds, contrast=["group", "Hic2", "BFP"], inference=inference)
day_10_de_stats.summary()

Fitting size factors...

Using None as control genes, passed at DeseqDataSet initialization

... done in 0.01 seconds.

Fitting dispersions...
... done in 1.41 seconds.

Fitting dispersion trend curve...
... done in 0.47 seconds.

Fitting MAP dispersions...
... done in 1.34 seconds.

Fitting LFCs...
... done in 1.67 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 0 outlier genes.

Running Wald tests...

Log2 fold change & Wald test p-value: group Hic2 vs BFP
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
Gnai3       14599.801326       -0.486742  0.110552 -4.402836  0.000011
Pbsn            0.000000             NaN       NaN       NaN       NaN
Cdc45        1823.385673        0.472664  0.184033  2.568364  0.010218
H19          9032.655059        0.583415  0.142092  4.105908  0.000040
Scml2         103.792330        0.022729  0.348827  0.065159  0.948047
...                  ...             ...       ...       ...       ...
BX571804.1      0.000000             NaN       NaN       NaN       NaN
AC154773.1      0.000000             NaN       NaN       NaN       NaN
AL662853.1      0.000000             NaN       NaN       NaN       NaN
AC145556.1      0.000000             NaN       NaN       NaN       NaN
CT868734.1      0.000000             NaN       NaN       NaN       NaN

                padj
Gnai3       0.000073
Pbsn             NaN
Cdc45       0.031130
H19         0.000241
Scml2       0.973732
...              ...
BX571804.1       NaN
AC154773.1       NaN
AL662853.1       NaN
AC145556.1       NaN
CT868734.1       NaN

[54534 rows x 6 columns]

... done in 1.94 seconds.

In [38]:
# Whether genes of interest are up- or downregulated

day_10_de_stats.results_df.loc[genes_of_interest].sort_values("padj")

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
Ovol1,523.721234,-3.065469,0.268917,-11.399329,4.213554e-30,6.988580e-28
Hmgb3,1472.708056,-1.320122,0.129233,-10.215083,1.697342e-24,1.507255e-22
Hoxa7,313.478151,-2.416212,0.312123,-7.741205,9.847861e-15,3.224090e-13
Tsc22d1,5885.198478,0.899993,0.124330,7.238765,4.527873e-13,1.159055e-11
Tlx2,203.466775,-2.257631,0.325591,-6.933944,4.092656e-12,8.966760e-11
Zbtb7c,1304.171701,-1.035031,0.166461,-6.217862,5.039730e-10,7.762267e-09
Tcf7l2,855.164257,1.246685,0.210027,5.935833,2.923581e-09,3.977853e-08
Jarid2,3614.193957,1.191620,0.206203,5.778867,7.520533e-09,9.462670e-08
Barx2,362.418536,-1.480871,0.260520,-5.684284,1.313622e-08,1.579573e-07
Myc,4748.397004,-0.749060,0.137089,-5.464030,4.654450e-08,5.109965e-07
Tfcp2l1,7868.664234,0.826629,0.151594,5.452904,4.955369e-08,5.396056e-07
Rest,1771.812577,1.061015,0.201475,5.266234,1.392506e-07,1.389667e-06
Tshz1,274.181791,-1.192926,0.265548,-4.492322,7.045080e-06,4.994267e-05
Sall1,1519.512035,0.591997,0.148707,3.980959,6.863791e-05,3.882453e-04
Tcf7l1,1172.874479,1.517226,0.460463,3.294998,9.842254e-04,4.115087e-03
Zfp42,9691.541140,1.050634,0.340533,3.085260,2.033742e-03,7.750697e-03
Dmrtc2,116.750189,-1.187116,0.478949,-2.478586,1.319044e-02,3.850458e-02
Klf2,967.860470,0.206307,0.223071,0.924847,3.550455e-01,5.243125e-01
Phox2a,73.237558,-0.356797,0.434728,-0.820735,4.117971e-01,5.805252e-01
Mycn,1165.146541,0.084670,0.254114,0.333199,7.389842e-01,8.466772e-01

## Differential expression in MEFs

In [112]:
mef_samples = metadata_df.query("experiment == \"MEF\"").index.to_list()
print(metadata_df.loc[mef_samples])

               day experiment group replicate  batch
sample
MEF_BFP_Rep1     0        MEF   BFP         1      1
MEF_BFP_Rep2     0        MEF   BFP         2      1
MEF_BFP_Rep3     0        MEF   BFP         3      1
MEF_Hic2_Rep1    0        MEF  Hic2         1      1
MEF_Hic2_Rep2    0        MEF  Hic2         2      1
MEF_Hic2_Rep3    0        MEF  Hic2         3      1

In [53]:
# Fit differential expression model

inference = pydeseq2.dds.DefaultInference(n_cpus=8)
dds = pydeseq2.dds.DeseqDataSet(
    counts=bulk_counts.loc[mef_samples, common_genes],
    metadata=metadata_df.loc[mef_samples],
    design="~group",
    refit_cooks=True,
    inference=inference
)

dds.deseq2()

# Calculate statistics
mef_de_stats = pydeseq2.ds.DeseqStats(dds, contrast=["group", "Hic2", "BFP"], inference=inference)
mef_de_stats.summary()

Fitting size factors...
... done in 0.00 seconds.

Fitting dispersions...

Using None as control genes, passed at DeseqDataSet initialization

... done in 0.19 seconds.

Fitting dispersion trend curve...
... done in 0.04 seconds.

Fitting MAP dispersions...
... done in 0.22 seconds.

Fitting LFCs...
... done in 0.25 seconds.

Calculating cook's distance...
... done in 0.00 seconds.

Replacing 0 outlier genes.

Running Wald tests...
... done in 0.17 seconds.

Log2 fold change & Wald test p-value: group Hic2 vs BFP
                  baseMean  log2FoldChange     lfcSE      stat        pvalue  \
0610040J01Rik    21.265536       -0.403483  0.497757 -0.810603  4.175938e-01
1110008L16Rik   324.582825        0.239663  0.203499  1.177710  2.389124e-01
1110038B12Rik  1234.185766        0.028475  0.202006  0.140961  8.879011e-01
1500009L16Rik   289.683772        0.891146  0.162259  5.492105  3.971718e-08
1500015O10Rik    71.716345       -1.477486  0.287123 -5.145826  2.663468e-07
...                    ...             ...       ...       ...           ...
Zmiz1          6521.568472        0.028579  0.138333  0.206597  8.363244e-01
Zp3               0.667739       -2.910684  3.596741 -0.809256  4.183680e-01
Zscan4a           0.000000             NaN       NaN       NaN           NaN
Zscan4c           0.000000             NaN       NaN       NaN           NaN
Zscan4e           0.000000             NaN       NaN       NaN           NaN

                       padj
0610040J01Rik  6.072510e-01
1110008L16Rik  4.144157e-01
1110038B12Rik  9.430233e-01
1500009L16Rik  9.174892e-07
1500015O10Rik  4.944416e-06
...                     ...
Zmiz1          9.128375e-01
Zp3                     NaN
Zscan4a                 NaN
Zscan4c                 NaN
Zscan4e                 NaN

[1942 rows x 6 columns]

In [54]:
# Whether genes of interest are up- or downregulated

mef_de_stats.results_df.loc[genes_of_interest].sort_values("padj")

             baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
Tcf7l2    1461.158516        0.411018  0.150840  2.724854  0.006433  0.026791
Hoxa7      806.661901        0.347961  0.135321  2.571375  0.010130  0.038594
Zbtb7c     124.670887       -0.638847  0.262957 -2.429475  0.015121  0.051838
Klf2       196.442771       -0.859362  0.378279 -2.271767  0.023101  0.072763
Barx2       38.210838        1.025243  0.494220  2.074465  0.038036  0.105690
Tfcp2l1     51.991721       -0.552028  0.295294 -1.869417  0.061565  0.152600
Tshz1     5079.950345        0.259353  0.145896  1.777661  0.075460  0.178275
Sall1      197.029590        0.269536  0.172807  1.559752  0.118818  0.252543
Tcf7l1    1334.422051        0.255627  0.184698  1.384022  0.166352  0.321822
Hmgb3     1384.007209        0.229583  0.172175  1.333433  0.182390  0.345154
Phox2a       4.811675       -1.445185  1.179266 -1.225496  0.220388  0.393229
Jarid2    1710.511176        0.214631  0.177746  1.207515  0.227234  0.401339
Mycn       496.409316       -0.169110  0.202020 -0.837098  0.402538  0.591767
Myc       1182.246111        0.144334  0.391946  0.368249  0.712688  0.832980
Zfp42        9.307759        0.266531  0.812171  0.328171  0.742782  0.847692
Tsc22d1  10098.536833       -0.015511  0.101388 -0.152981  0.878413  0.939704
Rest      3211.145221       -0.011507  0.109141 -0.105436  0.916030  0.962355
Dmrtc2       0.164095       -1.048783  4.427910 -0.236857  0.812768       NaN
Ovol1        0.328191       -1.890241  4.330183 -0.436527  0.662455       NaN
Tlx2         0.928365       -0.233589  2.056549 -0.113583  0.909568       NaN

## Differential expression in ESCs

In [113]:
esc_samples = metadata_df.query("experiment == \"ESC\"").index.to_list()
print(metadata_df.loc[esc_samples])

                    day experiment      group replicate  batch
sample
ESC_BFP_Rep1          0        ESC        BFP         1      2
ESC_BFP_Rep2          0        ESC        BFP         2      2
ESC_BFP_Rep3          0        ESC        BFP         3      2
ESC_Hic2-gRNA_Rep1    0        ESC  Hic2-gRNA         1      2
ESC_Hic2-gRNA_Rep2    0        ESC  Hic2-gRNA         2      2
ESC_Hic2-gRNA_Rep3    0        ESC  Hic2-gRNA         3      2
ESC_Zeo-gRNA_Rep1     0        ESC   Zeo-gRNA         1      2
ESC_Zeo-gRNA_Rep2     0        ESC   Zeo-gRNA         2      2
ESC_Zeo-gRNA_Rep3     0        ESC   Zeo-gRNA         3      2

In [115]:
# Fit differential expression model

inference = pydeseq2.dds.DefaultInference(n_cpus=8)
dds = pydeseq2.dds.DeseqDataSet(
    counts=bulk_counts.loc[esc_samples, common_genes],
    metadata=metadata_df.loc[esc_samples],
    design="~group",
    refit_cooks=True,
    inference=inference
)

dds.deseq2()

# Calculate statistics
esc_de_stats = pydeseq2.ds.DeseqStats(dds, contrast=["group", "Zeo-gRNA", "Hic2-gRNA"], inference=inference)
# This is a knockout experiments so the order of samples is reversed
esc_de_stats.summary()

Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.26 seconds.

Fitting dispersion trend curve...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.30 seconds.

Fitting LFCs...
... done in 0.20 seconds.

Log2 fold change & Wald test p-value: group Zeo-gRNA vs Hic2-gRNA
                  baseMean  log2FoldChange     lfcSE      stat        pvalue  \
0610040J01Rik    51.921452       -0.527384  0.290160 -1.817561  6.913131e-02
1110008L16Rik   722.601741        0.083498  0.148153  0.563595  5.730299e-01
1110038B12Rik  1389.865872        0.755943  0.127443  5.931615  2.999698e-09
1500009L16Rik   154.560178        0.125743  0.267273  0.470467  6.380211e-01
1500015O10Rik     5.207505       -3.085208  1.198319 -2.574613  1.003523e-02
...                    ...             ...       ...       ...           ...
Zmiz1           785.722730       -1.124409  0.246163 -4.567739  4.930129e-06
Zp3              97.979012        0.822176  0.307450  2.674180  7.491220e-03
Zscan4a         177.497754       -0.543751  0.570026 -0.953905  3.401316e-01
Zscan4c         205.143733       -0.600216  0.857092 -0.700293  4.837443e-01
Zscan4e         210.310155       -0.010496  0.606083 -0.017317  9.861835e-01

                       padj
0610040J01Rik  1.219341e-01
1110008L16Rik  6.859657e-01
1110038B12Rik  1.945293e-08
1500009L16Rik  7.416351e-01
1500015O10Rik  2.219330e-02
...                     ...
Zmiz1          2.044344e-05
Zp3            1.716116e-02
Zscan4a        4.580226e-01
Zscan4c        6.099846e-01
Zscan4e        9.930919e-01

[1942 rows x 6 columns]

Calculating cook's distance...
... done in 0.00 seconds.

Replacing 0 outlier genes.

Running Wald tests...
... done in 0.11 seconds.

In [116]:
# Whether genes of interest are up- or downregulated

esc_de_stats.results_df.loc[genes_of_interest].sort_values("padj")

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
Myc,883.743218,3.686952,0.161470,22.833730,2.120667e-115,5.225930e-113
Tfcp2l1,7033.005586,2.041081,0.153019,13.338782,1.376903e-40,7.917192e-39
Zfp42,12778.669838,1.464963,0.128270,11.420961,3.285796e-30,1.111372e-28
Rest,6352.040976,0.464189,0.076798,6.044300,1.500605e-09,1.023140e-08
Mycn,4152.026270,-1.605242,0.297809,-5.390168,7.039168e-08,3.891848e-07
Hoxa7,13.261125,2.789823,0.685144,4.071877,4.663576e-05,1.665563e-04
Hmgb3,626.869728,-0.439919,0.110975,-3.964125,7.366551e-05,2.536387e-04
Sall1,7012.419627,-0.270905,0.075207,-3.602135,3.156144e-04,9.704719e-04
Dmrtc2,44.013304,-1.193261,0.374995,-3.182070,1.462266e-03,3.935115e-03
Tcf7l1,2084.262946,0.484475,0.157901,3.068215,2.153415e-03,5.611239e-03
Phox2a,25.843821,-1.156821,0.476167,-2.429444,1.512200e-02,3.216455e-02
Klf2,4961.094181,0.280519,0.116275,2.412551,1.584134e-02,3.352921e-02
Tshz1,17.896568,1.091930,0.467955,2.333409,1.962668e-02,4.040098e-02
Tsc22d1,4150.446132,0.545665,0.272372,2.003382,4.513631e-02,8.381747e-02
Tcf7l2,164.324577,0.314795,0.173881,1.810403,7.023334e-02,1.234990e-01
Tlx2,1.255591,2.752973,2.023177,1.360718,1.736028e-01,2.657186e-01
Jarid2,17639.350788,0.159998,0.128374,1.246340,2.126396e-01,3.127053e-01
Ovol1,11.798808,-0.642798,0.586747,-1.095528,2.732852e-01,3.842029e-01
Zbtb7c,179.913966,-0.200119,0.307518,-0.650756,5.152038e-01,6.379946e-01
Barx2,2.469207,-0.671832,1.345733,-0.499231,6.176167e-01,7.267317e-01

## Differential expresion in iPSCs

In [103]:
ipsc_samples = metadata_df.query("experiment == \"iPSC\"").index.to_list()
print(metadata_df.loc[ipsc_samples])

                day experiment group replicate  batch
sample
iPSC_BFP_Rep1     0       iPSC   BFP         1      2
iPSC_BFP_Rep2     0       iPSC   BFP         2      2
iPSC_BFP_Rep3     0       iPSC   BFP         3      2
iPSC_Hic2_Rep1    0       iPSC  Hic2         1      2
iPSC_Hic2_Rep2    0       iPSC  Hic2         2      2
iPSC_Hic2_Rep3    0       iPSC  Hic2         3      2

In [104]:
# Fit differential expression model

inference = pydeseq2.dds.DefaultInference(n_cpus=16)
dds = pydeseq2.dds.DeseqDataSet(
    counts=bulk_counts.loc[ipsc_samples, common_genes],
    metadata=metadata_df.loc[ipsc_samples],
    design="~group",
    refit_cooks=True,
    inference=inference
)

dds.deseq2()

# Calculate statistics
ipsc_de_stats = pydeseq2.ds.DeseqStats(dds, contrast=["group", "Hic2", "BFP"], inference=inference)
ipsc_de_stats.summary()

Fitting size factors...
... done in 0.00 seconds.

Fitting dispersions...

Using None as control genes, passed at DeseqDataSet initialization

... done in 0.16 seconds.

Fitting dispersion trend curve...
... done in 0.04 seconds.

Fitting MAP dispersions...
... done in 0.18 seconds.

Fitting LFCs...
... done in 0.20 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 0 outlier genes.

Running Wald tests...

Log2 fold change & Wald test p-value: group Hic2 vs BFP
                  baseMean  log2FoldChange     lfcSE      stat    pvalue  \
0610040J01Rik    26.488640        0.462650  0.436792  1.059199  0.289509
1110008L16Rik   729.462893        0.112113  0.186731  0.600398  0.548241
1110038B12Rik  1456.620150       -0.303012  0.274482 -1.103940  0.269619
1500009L16Rik   174.852541        0.036534  0.311481  0.117293  0.906628
1500015O10Rik     5.495177        0.981877  1.028843  0.954350  0.339906
...                    ...             ...       ...       ...       ...
Zmiz1           846.252400       -0.033096  0.378258 -0.087497  0.930277
Zp3              83.709293       -0.156560  0.549123 -0.285110  0.775560
Zscan4a         179.665409        0.237048  0.545430  0.434607  0.663847
Zscan4c         221.557134       -0.104361  0.609409 -0.171250  0.864028
Zscan4e         276.388521        0.371044  0.624233  0.594400  0.552244

                   padj
0610040J01Rik  0.999831
1110008L16Rik  0.999831
1110038B12Rik  0.999831
1500009L16Rik  0.999831
1500015O10Rik  0.999831
...                 ...
Zmiz1          0.999831
Zp3            0.999831
Zscan4a        0.999831
Zscan4c        0.999831
Zscan4e        0.999831

[1942 rows x 6 columns]

... done in 0.19 seconds.

In [105]:
# Whether genes of interest are up- or downregulated

ipsc_de_stats.results_df.loc[genes_of_interest].sort_values("padj")

             baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
Jarid2   17850.319954       -0.088999  0.213711 -0.416446  0.677083  0.999831
Klf2      3946.622489       -0.417831  0.203246 -2.055793  0.039803  0.999831
Mycn      3669.443563        0.243947  0.352910  0.691243  0.489413  0.999831
Rest      5847.264157       -0.146764  0.159514 -0.920066  0.357538  0.999831
Sall1     6139.554237       -0.174725  0.236438 -0.738989  0.459914  0.999831
Tcf7l1    2070.087210       -0.124286  0.235025 -0.528822  0.596929  0.999831
Tcf7l2     178.452354       -0.002236  0.255286 -0.008758  0.993012  0.999831
Tfcp2l1   4497.177490       -0.584142  0.270778 -2.157269  0.030985  0.999831
Tsc22d1   3170.164716       -0.180439  0.287943 -0.626648  0.530890  0.999831
Zfp42    11362.164991       -0.421458  0.227255 -1.854563  0.063659  0.999831
Barx2        2.415515        1.424515  1.365755  1.043023  0.296937  0.999831
Dmrtc2      27.915394       -0.047290  0.610964 -0.077402  0.938304  0.999831
Hmgb3      537.786183        0.168083  0.193392  0.869127  0.384778  0.999831
Hoxa7       19.991987       -1.395663  0.611899 -2.280870  0.022556  0.999831
Myc       1028.096760       -0.569568  0.410852 -1.386310  0.165652  0.999831
Ovol1       11.178110       -0.665319  0.653880 -1.017493  0.308919  0.999831
Phox2a      23.020624       -0.356097  0.518262 -0.687099  0.492021  0.999831
Tlx2         0.510881       -0.921635  3.015734 -0.305609  0.759902  0.999831
Tshz1       16.171232       -1.179486  0.657608 -1.793599  0.072877  0.999831
Zbtb7c      93.007201        0.265514  0.404395  0.656570  0.511457  0.999831

## Combined differential expression in bulk data

In [125]:
reprogramming_de_stats.results_df

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
Gnai3,18118.223009,-0.237734,0.046419,-5.121532,3.030633e-07,1.868561e-06
Pbsn,0.000000,NaN,NaN,NaN,NaN,NaN
Cdc45,1046.343936,0.800273,0.094942,8.429116,3.482852e-17,7.204903e-16
H19,4548.672607,0.729453,0.114614,6.364408,1.960450e-10,1.857909e-09
Scml2,183.121673,-0.602971,0.144454,-4.174135,2.991209e-05,1.325471e-04
...,...,...,...,...,...,...
BX571804.1,0.000000,NaN,NaN,NaN,NaN,NaN
AC154773.1,0.000000,NaN,NaN,NaN,NaN,NaN
AL662853.1,0.286036,0.360430,3.104910,0.116084,9.075861e-01,NaN
AC145556.1,0.781459,-1.160610,1.788140,-0.649060,5.162997e-01,NaN
CT868734.1,0.000000,NaN,NaN,NaN,NaN,NaN

In [135]:
# Combine all results into one dataframe

stats_dict = {
    "Reprogramming": reprogramming_de_stats,
    "Day 2": day_2_de_stats,
    "Day 4": day_4_de_stats,
    "Day 6": day_6_de_stats,
    "Day 10": day_10_de_stats,
    "MEF": mef_de_stats,
    "mESC": esc_de_stats,
    "iPSC": ipsc_de_stats
}

bulk_de = pandas.DataFrame(index=reprogramming_de_stats.results_df.index)
for experiment, stats in stats_dict.items():
    bulk_de[f"{experiment} LFC"] = stats.results_df["log2FoldChange"]
    bulk_de[f"{experiment} p value"] = stats.results_df["pvalue"]
    bulk_de[f"{experiment} p adjusted"] = stats.results_df["padj"]
    bulk_de[f"{experiment} base mean"] = stats.results_df["baseMean"]

lfc_columns = bulk_de.columns.str.contains("LFC")
reduced_columns = ["Reprogramming LFC", "Reprogramming p adjusted", "MEF LFC", "MEF p adjusted", "mESC LFC", "mESC p adjusted", "iPSC LFC", "iPSC p adjusted"]
p_val_columns = bulk_de.columns.str.contains("p value")
p_adj_columns = bulk_de.columns.str.contains("p adjusted")
mean_columns = bulk_de.columns.str.contains("base mean")

In [136]:
# Dead end drivers LFC

bulk_de.loc[dead_end_tfs, reduced_columns]

,Reprogramming LFC,Reprogramming p adjusted,MEF LFC,MEF p adjusted,mESC LFC,mESC p adjusted,iPSC LFC,iPSC p adjusted
Barx2,-1.207086,2.699537e-21,1.025243,0.105690,-0.671832,7.267317e-01,1.424515,0.999831
Dmrtc2,-0.917730,3.002863e-05,-1.048783,NaN,-1.193261,3.935115e-03,-0.047290,0.999831
Hmgb3,-0.857015,2.360299e-15,0.229583,0.345154,-0.439919,2.536387e-04,0.168083,0.999831
Hoxa7,-1.072721,3.138826e-07,0.347961,0.038594,2.789823,1.665563e-04,-1.395663,0.999831
Myc,-0.137470,1.902238e-01,0.144334,0.832980,3.686952,5.225930e-113,-0.569568,0.999831
Ovol1,-1.451013,8.644510e-14,-1.890241,NaN,-0.642798,3.842029e-01,-0.665319,0.999831
Phox2a,-0.313819,3.123642e-04,-1.445185,0.393229,-1.156821,3.216455e-02,-0.356097,0.999831
Tlx2,-1.107785,2.177406e-11,-0.233589,NaN,2.752973,2.657186e-01,-0.921635,0.999831
Tshz1,-0.223540,2.357446e-01,0.259353,0.178275,1.091930,4.040098e-02,-1.179486,0.999831
Zbtb7c,-0.943320,8.875744e-57,-0.638847,0.051838,-0.200119,6.379946e-01,0.265514,0.999831

All except Myc and Tshz1 are significantly downregulated during reprogramming. Most drivers are low in MEFs, stem cells or both so they have high p-values.

Evidence for drivers:
- Barx2: Downregulated in reprogramming, upregulated by Hic2 KO in mESCs but not significantly due to low counts. Could be direct target but there is insufficient evidence.
- Dmrtc2: Downregulated in reprogramming, upregulated by Hic2 KO in mESCs. Probably direct target.
- Hmgb3: Downregulated in reprogramming, upregulated by Hic2 KO in mESCs. Probably direct target.
- Hoxa7: Downregulated in reprogramming, but upregulated in MEFs and downregulated by Hic2 KO in mESCs. Probably not direct target.
- Myc: Downregulated late in reprogramming, but strongly downregulated by Hic2 KO in mESCs. Probably indirect in one of the experiments.
- Ovol1: Downregulated in reprogramming and in the other cells, but too few counts for significance at end points. Could be direct target.
- Phox2a: Downregulated in reprogramming, upregulated by Hic2 KO in mESCs. Probably direct target.
- Tlx2: Downregulated in reprogramming, almost no counts in other cells. Could be direct target, insufficient evidence.
- Tshz1: Upregulated early in reprogramming, downregulated late in reprogramming, upregulated in mESCs. Probably not direct target.
- Zbt7c: Downregulated in reprogramming, downregulated in MEFs and mESCs but not significantly. Could be direct target.

This analysis supports Dmrtc2, Hmgb3 and Phox2a as direct targets, and Barx2, Ovol1, Tlx2 and Zbtb7c could be direct targets.

Hoxa7, Myc and Tshz1 are probably not direct targets based on this analysis.

In [137]:
# Absolute counts for the dead end drivers

bulk_counts[dead_end_tfs]

,Barx2,Dmrtc2,Hmgb3,Hoxa7,Myc,Ovol1,Phox2a,Tlx2,Tshz1,Zbtb7c
Day2_BFP_Rep1,133,58,2030,284,25073,388,255,674,1900,1763
Day2_BFP_Rep2,223,87,2449,357,35224,669,337,780,2856,2551
Day2_BFP_Rep3,102,56,1663,217,23219,336,239,654,1687,1525
Day2_Hic2_Rep1,116,57,2381,407,41371,266,302,496,4547,1598
Day2_Hic2_Rep2,130,45,1863,283,31895,222,219,319,3853,1112
Day2_Hic2_Rep3,78,37,1244,224,23322,140,189,257,2660,844
Day4_BFP_Rep1,355,93,1899,404,30761,1166,257,939,2243,2928
Day4_BFP_Rep1-2,186,45,989,217,17157,603,159,549,1230,1711
Day4_BFP_Rep2,312,164,1919,330,27347,1056,234,994,1569,2222
Day4_BFP_Rep3,350,116,2084,434,32940,1293,288,1110,2090,2872
Day4_Hic2_Rep1,134,74,1228,258,29607,630,214,627,2016,1188
Day4_Hic2_Rep1-2,101,39,792,170,18845,397,143,368,1316,780
Day4_Hic2_Rep2,151,100,1208,191,28907,669,203,645,1899,1206
Day4_Hic2_Rep3,188,91,1694,306,37376,790,251,770,2460,1514
Day6_BFP_Rep1,567,164,1773,499,8388,1317,174,780,406,1425
Day6_BFP_Rep2,804,399,2144,461,13837,1589,237,1262,537,1964
Day6_BFP_Rep3,485,184,2091,410,12822,1280,201,967,653,1866
Day6_Hic2_Rep1,266,84,871,241,13619,707,185,921,308,1086
Day6_Hic2_Rep2,165,66,654,142,10933,600,127,465,331,963
Day6_Hic2_Rep3,175,123,808,139,10959,663,183,543,417,1119
Day10_BFP_Rep1,490,108,2516,810,7662,1231,97,399,531,2217
Day10_BFP_Rep2,396,122,1720,363,4309,477,72,253,259,1215
Day10_BFP_Rep3,751,265,2226,481,6491,1238,83,389,401,2011
Day10_Hic2_Rep1,158,59,897,120,3627,117,41,57,154,726
Day10_Hic2_Rep2,315,157,1127,159,5302,148,118,142,280,1305
Day10_Hic2_Rep3,138,29,598,43,2320,82,49,36,105,663
ESC_BFP_Rep1,2,24,495,9,1233,11,18,3,18,114
ESC_BFP_Rep2,0,44,435,7,1156,7,17,0,23,120
ESC_BFP_Rep3,2,26,576,22,1528,13,28,1,16,94
ESC_Hic2-gRNA_Rep1,2,57,814,3,122,10,62,1,16,162
ESC_Hic2-gRNA_Rep2,7,93,922,1,76,26,34,0,8,342
ESC_Hic2-gRNA_Rep3,4,88,979,8,125,16,38,0,13,282
ESC_Zeo-gRNA_Rep1,6,31,619,23,1222,6,28,3,19,236
ESC_Zeo-gRNA_Rep2,1,30,502,20,1084,12,8,2,25,176
ESC_Zeo-gRNA_Rep3,0,24,515,24,1083,9,14,1,20,151
iPSC_BFP_Rep1,1,26,437,34,1159,10,20,1,19,76
iPSC_BFP_Rep2,0,13,514,36,1217,19,31,0,15,70
iPSC_BFP_Rep3,3,47,573,16,1314,12,27,1,34,109
iPSC_Hic2_Rep1,5,32,670,7,460,6,35,0,16,174
iPSC_Hic2_Rep2,3,38,558,13,1061,10,17,0,4,77
iPSC_Hic2_Rep3,3,15,524,13,938,10,12,1,11,71
MEF_BFP_Rep1,16,0,1318,725,1313,0,5,1,4157,137
MEF_BFP_Rep2,30,0,1184,638,919,0,10,1,4710,171
MEF_BFP_Rep3,28,1,1210,709,1039,2,5,1,4626,135
MEF_Hic2_Rep1,21,0,1337,654,1548,0,5,0,3780,59
MEF_Hic2_Rep2,61,0,1699,1142,1056,0,2,0,7147,116
MEF_Hic2_Rep3,90,0,1586,1082,997,0,0,3,6836,141

In [138]:
# Differential expression of reprogramming drivers

bulk_de.loc[stem_cell_tfs, reduced_columns]

,Reprogramming LFC,Reprogramming p adjusted,MEF LFC,MEF p adjusted,mESC LFC,mESC p adjusted,iPSC LFC,iPSC p adjusted
Jarid2,0.820343,1.214135e-08,0.214631,0.401339,0.159998,3.127053e-01,-0.088999,0.999831
Klf2,-0.180294,5.962700e-01,-0.859362,0.072763,0.280519,3.352921e-02,-0.417831,0.999831
Mycn,0.170911,4.827383e-01,-0.169110,0.591767,-1.605242,3.891848e-07,0.243947,0.999831
Rest,0.492894,6.121253e-05,-0.011507,0.962355,0.464189,1.023140e-08,-0.146764,0.999831
Sall1,1.516870,8.706573e-22,0.269536,0.252543,-0.270905,9.704719e-04,-0.174725,0.999831
Tcf7l1,1.263931,2.177080e-13,0.255627,0.321822,0.484475,5.611239e-03,-0.124286,0.999831
Tcf7l2,0.753992,1.340578e-09,0.411018,0.026791,0.314795,1.234990e-01,-0.002236,0.999831
Tfcp2l1,1.502553,2.759063e-10,-0.552028,0.152600,2.041081,7.917192e-39,-0.584142,0.999831
Tsc22d1,0.063317,7.309035e-01,-0.015511,0.939704,0.545665,8.381747e-02,-0.180439,0.999831
Zfp42,1.344900,6.666513e-18,0.266531,0.847692,1.464963,1.111372e-28,-0.421458,0.999831

In [139]:
# Absolute counts for stem cell drivers

bulk_counts[stem_cell_tfs]

,Jarid2,Klf2,Mycn,Rest,Sall1,Tcf7l1,Tcf7l2,Tfcp2l1,Tsc22d1,Zfp42
Day2_BFP_Rep1,1538,19,39,2638,190,315,907,30,2491,89
Day2_BFP_Rep2,2185,47,55,3534,321,500,1303,44,3724,137
Day2_BFP_Rep3,1275,9,21,2409,177,279,764,43,1854,103
Day2_Hic2_Rep1,2945,35,56,4665,740,820,1545,89,3760,220
Day2_Hic2_Rep2,2325,26,51,3688,628,591,1413,62,2849,228
Day2_Hic2_Rep3,1769,11,39,2992,400,451,1152,42,2027,129
Day4_BFP_Rep1,2205,23,51,2895,513,331,1657,110,3365,224
Day4_BFP_Rep1-2,1269,10,23,1617,279,167,895,59,1881,136
Day4_BFP_Rep2,1787,51,26,1976,379,201,998,108,1979,270
Day4_BFP_Rep3,2156,39,50,2810,478,334,1532,138,3472,248
Day4_Hic2_Rep1,2449,27,26,2845,1362,496,1624,286,2034,651
Day4_Hic2_Rep1-2,1576,14,19,1724,869,312,1046,179,1312,382
Day4_Hic2_Rep2,2658,8,36,3024,1459,478,1912,539,2055,758
Day4_Hic2_Rep3,3241,22,51,3584,1862,671,2105,373,2574,924
Day6_BFP_Rep1,378,57,56,501,192,107,575,459,2864,407
Day6_BFP_Rep2,634,131,104,555,260,181,728,716,2733,926
Day6_BFP_Rep3,490,32,36,759,377,197,747,399,2823,533
Day6_Hic2_Rep1,1327,59,60,757,1518,773,1565,2875,2926,2404
Day6_Hic2_Rep2,1551,99,125,939,1585,708,1524,4296,3089,2331
Day6_Hic2_Rep3,1394,56,111,915,1587,675,1573,4039,2573,2657
Day10_BFP_Rep1,1743,780,887,1021,1230,489,450,5041,4054,5073
Day10_BFP_Rep2,2745,1055,1481,1379,1258,882,388,5970,4102,7718
Day10_BFP_Rep3,1999,834,949,1005,1162,393,713,5994,4233,5842
Day10_Hic2_Rep1,5113,1245,1407,2441,1730,1741,1036,8847,7014,14231
Day10_Hic2_Rep2,6103,1198,1298,2837,2523,2286,1883,15410,10812,14133
Day10_Hic2_Rep3,4095,730,918,1986,1420,1341,895,7528,6023,10875
ESC_BFP_Rep1,17540,4366,1945,6729,6450,2064,196,7343,4232,13567
ESC_BFP_Rep2,15794,4245,1837,5731,6041,1721,186,6575,3837,12245
ESC_BFP_Rep3,23829,6106,5268,7789,8214,2978,222,6036,3503,15402
ESC_Hic2-gRNA_Rep1,15823,5485,8131,5754,8570,2142,163,3258,5157,6300
ESC_Hic2-gRNA_Rep2,19980,5020,8168,5676,8911,1702,139,2937,2313,8414
ESC_Hic2-gRNA_Rep3,18532,4822,8343,6108,8799,1835,134,3347,4372,7388
ESC_Zeo-gRNA_Rep1,17975,5320,2405,7419,6437,2256,179,11561,5036,18232
ESC_Zeo-gRNA_Rep2,16148,4867,2152,6227,5702,2136,132,10133,4448,16053
ESC_Zeo-gRNA_Rep3,15491,5015,2061,6138,5658,2090,134,10348,4580,15623
iPSC_BFP_Rep1,18553,4155,3771,5831,6490,2119,161,4598,2698,11785
iPSC_BFP_Rep2,19084,4470,4040,6282,6775,2182,153,4905,2824,12530
iPSC_BFP_Rep3,17512,4944,2204,6334,6253,2177,224,6763,4657,14823
iPSC_Hic2_Rep1,16825,3508,3478,6228,5295,1807,200,3248,3947,9122
iPSC_Hic2_Rep2,17621,3840,4570,5274,5930,2253,171,3783,2679,10614
iPSC_Hic2_Rep3,18145,2987,3995,5516,6251,1950,176,3866,2601,9765
MEF_BFP_Rep1,1355,309,585,3000,176,1088,1052,72,9665,12
MEF_BFP_Rep2,1578,202,439,3202,158,1195,1234,52,9284,4
MEF_BFP_Rep3,1695,225,507,3201,187,1271,1382,56,10709,9
MEF_Hic2_Rep1,1186,163,416,2588,181,903,1221,33,7411,2
MEF_Hic2_Rep2,2301,109,490,3790,238,1892,1922,53,11957,15
MEF_Hic2_Rep3,2449,141,543,3667,255,1914,2168,47,12576,18

## Save differential expression results

In [140]:
bulk_de.to_csv("RNA Sequencing Data/bulk_differential_expression.csv")
metadata_df.to_csv("RNA Sequencing Data/bulk_sequencing_metadata.csv")

# Differential expression with SCVI-tools