In [1]:
import pyranges
import pandas
import scanpy
import hdf5plugin
import anndata
import cellrank
import matplotlib
from matplotlib import pyplot
import cellrank
import numpy
import gseapy
import pygam
import seaborn
import pydeseq2
import pydeseq2.dds
import pydeseq2.ds
import scipy

In [2]:
# Load data from Cellrank and SDEvelo

working_directory = "RNA Sequencing Data/"
base_name = "cellrank_1.4"
adata = scanpy.read_h5ad(
    working_directory+f"/{base_name} cells.h5ad"
)
dead_end_adata = scanpy.read_h5ad(
    working_directory+f"/{base_name} dead end genes.h5ad"
)
mESC_adata = scanpy.read_h5ad(
    working_directory+f"/{base_name} mESC genes.h5ad"
)
driver_df = pandas.read_csv(
    working_directory+f"{base_name} driver genes.csv",
    index_col=0
)

In [3]:
# Load adata with raw counts and filter

adata_raw = scanpy.read_h5ad(
    working_directory+f"/splice_counts_mm10.h5ad"
)

# Calculate proportion of mitochondrial genes
adata_raw.var["mt"] = adata_raw.var_names.str.startswith("mt-")
scanpy.pp.calculate_qc_metrics(
    adata_raw, qc_vars=["mt"], inplace=True, percent_top=[], log1p=False
)

scanpy.pp.calculate_qc_metrics(
    adata_raw, inplace=True, percent_top=[], log1p=False
)

# Filter cells by counts per cell, total counts and percent mitochondrial
included_cells = (adata_raw.obs["n_genes_by_counts"] >= 200)*(adata_raw.obs['total_counts'] <= 150000)*(adata_raw.obs['pct_counts_mt'] < 10)
adata_raw = adata_raw[included_cells]
print(adata_raw)

View of AnnData object with n_obs × n_vars = 12791 × 48526
    obs: 'barcode', 'batch', 'sample', 'group', 'day', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt'
    var: 'ensemble_ids', 'gene_symbol', 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts'
    uns: 'sample_colors'
    obsm: 'X_fdl', 'X_umap'
    layers: 'ambiguous', 'matrix', 'spliced', 'unspliced'

# Differential expression pseudobulk analysis with PyDEseq2

In [97]:
filtered_adata = adata_raw[:, adata.var_names].copy()
filtered_adata.X = filtered_adata.X.toarray()

In [98]:
# Combine counts within samples

sample_names = adata.obs["sample"].unique()

pseudobulk_rows = []
pseudobulk_index = []
sample_metadata_list = []

for sample in sample_names:
    cells_mask = filtered_adata.obs["sample"] == sample
    sample_X = filtered_adata.X[cells_mask]
    summed_counts = sample_X.sum(axis=0)
        
    pseudobulk_rows.append(summed_counts)
    pseudobulk_index.append(sample)
    
    # Determine the group of the sample
    group = adata.obs.loc[cells_mask, "group"].iloc[0]
    day = adata.obs.loc[cells_mask, "day"].iloc[0]
    sample_metadata_list.append({"sample": sample, "group": group, "day": day})

# Create the counts dataframe
counts_df = pandas.DataFrame(
    data=pseudobulk_rows,
    index=pseudobulk_index,
    columns=adata.var_names
)

# Create metadata dataframe
metadata_df = pandas.DataFrame(sample_metadata_list).set_index("sample")

In [100]:
# Differential expression analysis with pydeseq2

reprogramming_adata = adata[adata.obs["group"].isin({"Hic2", "control"})].copy()
inference = pydeseq2.dds.DefaultInference(n_cpus=8)
dds = pydeseq2.dds.DeseqDataSet(
    counts=counts_df,
    metadata=metadata_df,
    design="~group",
    refit_cooks=True,
    inference=inference
)

# Fit model
dds.deseq2()

Using None as control genes, passed at DeseqDataSet initialization

Fitting size factors...
... done in 0.00 seconds.

Fitting dispersions...
... done in 0.83 seconds.

Fitting dispersion trend curve...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.30 seconds.

Fitting LFCs...
... done in 0.19 seconds.

Calculating cook's distance...
... done in 0.00 seconds.

Replacing 0 outlier genes.

In [7]:
stat_results = pydeseq2.ds.DeseqStats(dds, contrast=["group", "Hic2", "control"], inference=inference)

# compute p-values and adjusted p-values
stat_results.summary()

Log2 fold change & Wald test p-value: group Hic2 vs control
                 baseMean  log2FoldChange     lfcSE      stat    pvalue  \
gene_names
Rb1cc1        2239.163976       -0.283591  0.244634 -1.159246  0.246356
Fam150a         33.706046        0.335673  1.152714  0.291203  0.770896
Prex2          155.234879        1.573466  0.503496  3.125081  0.001778
Sulf1          677.858231        0.077258  0.591976  0.130508  0.896164
Msc            423.997047        2.369996  0.716943  3.305699  0.000947
...                   ...             ...       ...       ...       ...
Egfl6          166.625885        0.470281  0.781868  0.601483  0.547518
Tmsb4x      115027.155006        0.654934  0.384154  1.704876  0.088218
Usp9y           21.430362        2.368054  1.032823  2.292798  0.021860
Erdr1         1123.037550        0.974630  0.549626  1.773260  0.076186
AC168977.1       7.812825       -0.624215  1.416380 -0.440712  0.659422

                padj
gene_names
Rb1cc1      0.512643
Fam150a     0.902655
Prex2       0.021744
Sulf1       0.955788
Msc         0.013162
...              ...
Egfl6       0.770009
Tmsb4x      0.283622
Usp9y       0.123956
Erdr1       0.260079
AC168977.1  0.834466

[2000 rows x 6 columns]

Running Wald tests...
... done in 0.11 seconds.

In [8]:
# Whether genes of interest are up- or downregulated

genes_of_interest = ["Krtdap", "Krt8", "Krt14", "Nanog", "Tet1", "Cdh1", "Ovol1", "Atf3", "Hic2", "Sall4", "Shisa8", 'Hmgb3', 'Hoxa7', 'Tlx2', 'Zbtb7c', 'Klf2', 'Mycn', 'Rest', 'Tcf7l1', 'Tcf7l2', 'Tfcp2l1', 'Tsc22d1',
       'Zfp42', 'Zic2']
stat_results.results_df.loc[genes_of_interest].sort_values("padj")

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
gene_names,,,,,,
Krt14,1462.170985,-4.686814,0.675246,-6.940899,3.896137e-12,1.262998e-09
Ovol1,340.259652,-3.484112,0.724528,-4.808799,1.518397e-06,7.981844e-05
Tlx2,762.591789,-3.304927,0.750462,-4.403856,1.063436e-05,3.568447e-04
Atf3,489.743202,-2.159268,0.554218,-3.896062,9.776934e-05,2.291101e-03
Hmgb3,1503.378041,-1.429928,0.386190,-3.702652,2.133573e-04,4.153266e-03
Zbtb7c,747.489340,-1.675318,0.482144,-3.474728,5.113722e-04,8.152614e-03
Cdh1,1715.529009,-2.070593,0.713841,-2.900635,3.724076e-03,3.792319e-02
Hic2,1040.204742,1.227000,0.448022,2.738708,6.168113e-03,5.404045e-02
Tcf7l1,1565.285438,1.031554,0.439377,2.347767,1.888635e-02,1.150939e-01
Krt8,11224.113172,-1.939288,0.828498,-2.340728,1.924616e-02,1.157431e-01
Zic2,378.721448,1.194823,0.612258,1.951501,5.099747e-02,2.049382e-01
Tsc22d1,2188.416999,0.626121,0.351872,1.779403,7.517370e-02,2.597031e-01
Tcf7l2,2614.142627,0.791799,0.449216,1.762624,7.796399e-02,2.638254e-01
Hoxa7,618.152729,-1.011286,0.633558,-1.596200,1.104442e-01,3.267554e-01
Rest,5401.685374,0.599170,0.380174,1.576044,1.150158e-01,3.325757e-01
Tet1,3094.129979,1.001689,0.721369,1.388594,1.649563e-01,4.189669e-01
Shisa8,3573.221427,-0.871269,0.677124,-1.286721,1.981917e-01,4.622097e-01
Mycn,723.052794,0.726848,0.708118,1.026450,3.046794e-01,5.712380e-01
Zfp42,7623.251096,0.683980,0.691410,0.989255,3.225386e-01,5.889130e-01
Nanog,1012.845683,0.774075,0.790444,0.979291,3.274361e-01,5.907822e-01
Klf2,5153.233819,0.487965,0.599262,0.814276,4.154869e-01,6.702200e-01
Krtdap,9871.279263,0.390838,0.818725,0.477374,6.330962e-01,8.216026e-01
Sall4,2112.834385,0.271474,0.768002,0.353481,7.237281e-01,8.726914e-01
Tfcp2l1,1415.720197,0.146903,0.793152,0.185214,8.530613e-01,9.368742e-01

In [142]:
# Most upregulated in control

stat_results.results_df.query("padj < 0.05 and log2FoldChange < 0").sort_values("log2FoldChange").head(50)

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
gene_names,,,,,,
2310046K23Rik,37.150773,-8.101822,1.859812,-4.356259,1.323045e-05,4.361563e-04
Padi4,81.129161,-5.525528,0.887838,-6.223574,4.859564e-10,9.451853e-08
Mal2,397.453478,-5.088056,0.869783,-5.849797,4.921734e-09,7.363671e-07
Vsig8,70.732354,-4.959581,0.871917,-5.688136,1.284334e-08,1.561268e-06
Prss32,1024.286463,-4.922016,0.986613,-4.988802,6.075483e-07,3.938938e-05
Krt14,1462.170985,-4.686814,0.675246,-6.940899,3.896137e-12,1.262998e-09
Ly6g6c,5682.670391,-4.670438,0.962784,-4.850971,1.228587e-06,6.827435e-05
Lgals7,9929.055723,-4.641645,0.854930,-5.429268,5.658576e-08,4.785187e-06
Pkp1,401.631709,-4.622098,0.650179,-7.108967,1.169150e-12,4.547994e-10
S100a14,1376.369277,-4.516044,0.968108,-4.664812,3.088997e-06,1.335133e-04
Rtn4r,785.992916,-4.428201,0.498475,-8.883500,6.478885e-19,1.260143e-15
Kcnn4,648.801955,-4.392052,0.513962,-8.545479,1.280040e-17,1.244839e-14
Krt17,4166.080818,-4.366984,0.823371,-5.303786,1.134250e-07,7.878988e-06
Gpx2,1563.952543,-4.364635,0.927770,-4.704435,2.545694e-06,1.151482e-04
Mal,2423.561482,-4.192244,0.579921,-7.228987,4.866085e-13,2.366134e-10
Krt6a,228.010654,-4.110728,0.741095,-5.546829,2.908976e-08,2.977873e-06
Rab25,860.863747,-4.086347,0.902470,-4.527960,5.955575e-06,2.204335e-04
Lad1,816.576826,-4.044778,0.649112,-6.231251,4.627261e-10,9.451853e-08
Lmo1,2558.607593,-4.003371,0.592149,-6.760747,1.372817e-11,3.814471e-09
Serpinb6c,591.929290,-3.994460,0.812673,-4.915213,8.868587e-07,5.227091e-05
Edn2,115.436984,-3.989054,0.889034,-4.486951,7.224971e-06,2.555012e-04
Prok2,22.965498,-3.965861,0.804601,-4.928979,8.266034e-07,5.024199e-05
Them5,217.904392,-3.921043,0.860180,-4.558400,5.154482e-06,1.965778e-04
Slc23a3,28.360139,-3.859353,0.939943,-4.105943,4.026679e-05,1.097639e-03
Plek2,522.750782,-3.817724,0.693505,-5.504966,3.692388e-08,3.419855e-06
Chl1,31.048524,-3.793933,0.815884,-4.650088,3.317933e-06,1.373060e-04
Fermt3,732.972656,-3.767921,0.867199,-4.344934,1.393176e-05,4.516211e-04
Nectin4,215.064532,-3.640039,0.816045,-4.460588,8.173516e-06,2.838837e-04
Tgm3,73.597564,-3.521010,0.857977,-4.103854,4.063239e-05,1.097639e-03
Sdcbp2,523.941358,-3.490029,0.624626,-5.587389,2.305096e-08,2.490784e-06
Ovol1,340.259652,-3.484112,0.724528,-4.808799,1.518397e-06,7.981844e-05
Prkaa2,593.112304,-3.452522,0.515965,-6.691384,2.210699e-11,5.374762e-09
Chst13,485.798244,-3.380278,0.693332,-4.875408,1.085836e-06,6.211621e-05
Dmrtc2,884.994216,-3.374380,0.829364,-4.068636,4.728912e-05,1.226364e-03
Chit1,36.381579,-3.366540,0.780194,-4.315002,1.596016e-05,4.927382e-04
Myl7,934.077975,-3.333973,0.622228,-5.358122,8.409128e-08,6.057687e-06
Tlx2,762.591789,-3.304927,0.750462,-4.403856,1.063436e-05,3.568447e-04
Amn,260.074724,-3.275745,0.743859,-4.403718,1.064113e-05,3.568447e-04
Slurp1,704.880099,-3.190673,0.936651,-3.406471,6.580861e-04,9.943827e-03
Dsg3,11.323480,-3.189526,0.971728,-3.282325,1.029549e-03,1.400331e-02
Gatm,561.844899,-3.162412,0.571331,-5.535166,3.109338e-08,3.023832e-06
Cyth4,21.517209,-3.132995,0.836369,-3.745949,1.797130e-04,3.641059e-03
Nrip3,384.240846,-3.018945,0.628863,-4.800640,1.581596e-06,8.095273e-05
Ccdc109b,550.132485,-2.990963,0.715420,-4.180711,2.905995e-05,8.436060e-04
Alox12b,327.447318,-2.978651,0.942253,-3.161203,1.571191e-03,1.958953e-02
Fbp2,389.243579,-2.942744,0.797906,-3.688083,2.259500e-04,4.309343e-03
Urah,1385.647595,-2.912973,0.618422,-4.710330,2.473159e-06,1.145308e-04
Mbp,95.100352,-2.908114,0.806750,-3.604728,3.124806e-04,5.475448e-03
Hsd17b2,47.252009,-2.862395,0.931938,-3.071445,2.130254e-03,2.451683e-02
Ptprv,1079.029714,-2.857724,0.500475,-5.710024,1.129602e-08,1.561268e-06

In [145]:
# Most upregulated in Hic2

stat_results.results_df.query("padj < 0.05 and log2FoldChange > 0").sort_values("log2FoldChange", ascending=False).head(50)

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
gene_names,,,,,,
Xist,792.024515,3.977165,1.005491,3.955448,7.639151e-05,1.857269e-03
Cd36,25.023779,3.873931,1.143431,3.387989,7.040699e-04,1.029636e-02
Marc1,24.456462,3.576419,0.892136,4.008825,6.102151e-05,1.522021e-03
Stra8,89.375272,3.541480,1.127707,3.140425,1.687032e-03,2.089985e-02
Xirp2,83.190523,3.082889,0.872794,3.532207,4.121060e-04,6.909881e-03
Cdh5,19.222726,3.024164,1.058710,2.856462,4.283913e-03,4.166105e-02
Spink6,436.255228,2.897080,0.983585,2.945431,3.225055e-03,3.465597e-02
Myl3,35.093383,2.895067,0.861486,3.360551,7.778707e-04,1.119690e-02
Bhmt,39.421950,2.885319,1.006768,2.865921,4.157980e-03,4.063955e-02
Sept4,109.194570,2.835527,1.019765,2.780571,5.426347e-03,4.931890e-02
3830417A13Rik,179.165853,2.828486,0.870070,3.250874,1.150510e-03,1.532699e-02
Hand1,107.404338,2.811928,0.935994,3.004215,2.662672e-03,2.942555e-02
Apobec2,305.258330,2.629227,0.715753,3.673375,2.393680e-04,4.476642e-03
Nefh,322.626688,2.599575,0.434808,5.978668,2.249689e-09,3.646370e-07
Gulo,116.968786,2.591274,0.911267,2.843593,4.460793e-03,4.274011e-02
Nup62cl,554.476949,2.499195,0.544563,4.589357,4.446129e-06,1.729544e-04
Lrp2,138.926494,2.445878,0.759983,3.218331,1.289389e-03,1.682592e-02
Folr1,1770.720347,2.438302,0.712032,3.424428,6.160950e-04,9.540823e-03
Rec114,205.429660,2.435092,0.697860,3.489372,4.841564e-04,7.847368e-03
Aldh1l1,73.653034,2.427889,0.722852,3.358764,7.829198e-04,1.119690e-02
Nrxn1,182.160517,2.414257,0.752630,3.207759,1.337734e-03,1.723107e-02
Msc,423.997047,2.369996,0.716943,3.305699,9.473992e-04,1.316208e-02
Ltc4s,111.877044,2.366903,0.798177,2.965386,3.023037e-03,3.278690e-02
Fgfbp1,4362.318838,2.350174,0.597120,3.935851,8.290245e-05,1.990682e-03
Lmo2,58.387519,2.312130,0.588037,3.931943,8.426200e-05,1.998653e-03
Klhl13,1888.489864,2.299637,0.606464,3.791879,1.495115e-04,3.093616e-03
Tnnt1,517.722938,2.282810,0.594246,3.841525,1.222725e-04,2.672135e-03
Mdk,5020.403514,2.249833,0.443572,5.072077,3.934962e-07,2.639139e-05
Rbp4,242.892952,2.229979,0.802563,2.778573,5.459822e-03,4.939234e-02
Calcoco2,1077.338400,2.225425,0.782560,2.843775,4.458248e-03,4.274011e-02
Slc1a2,18.430733,2.221650,0.588311,3.776319,1.591634e-04,3.258662e-03
Dnmt3l,1963.192554,2.135246,0.749945,2.847202,4.410530e-03,4.267901e-02
Fxyd6,2310.756509,2.116505,0.579214,3.654101,2.580848e-04,4.780714e-03
Peg10,1648.151905,2.100340,0.523937,4.008764,6.103733e-05,1.522021e-03
Snhg11,586.742442,2.097211,0.753153,2.784573,5.359818e-03,4.917380e-02
Cubn,23.541103,2.094027,0.727490,2.878425,3.996661e-03,3.990094e-02
Nostrin,92.594591,2.091927,0.611160,3.422880,6.196151e-04,9.540823e-03
Eras,524.910689,2.086408,0.674359,3.093913,1.975357e-03,2.314499e-02
Igll1,54.946372,2.070590,0.609573,3.396784,6.818266e-04,1.012330e-02
Cdo1,577.792410,2.051270,0.472997,4.336750,1.446049e-05,4.610762e-04
Ifi27l2a,3358.679116,2.043173,0.600418,3.402918,6.667028e-04,9.974900e-03
Limch1,358.804382,2.030862,0.525423,3.865196,1.109998e-04,2.539937e-03
Des,472.780764,1.972510,0.553247,3.565335,3.633918e-04,6.199974e-03
1500009L16Rik,1379.527449,1.971310,0.408461,4.826186,1.391728e-06,7.519195e-05
Cotl1,1020.687532,1.945478,0.476191,4.085501,4.398179e-05,1.171844e-03
Ms4a10,55.813072,1.937841,0.498289,3.888988,1.006631e-04,2.330831e-03
Mfap5,2552.857687,1.931960,0.473721,4.078265,4.537295e-05,1.192573e-03
Aspa,207.692877,1.899137,0.401147,4.734266,2.198491e-06,1.069016e-04
Itih5,174.294032,1.895624,0.595095,3.185414,1.445472e-03,1.837545e-02
Ramp3,440.570481,1.844973,0.327087,5.640610,1.694490e-08,1.938695e-06

# Differential expression in bulk data with PyDEseq2

Article describing PyDESeq2: https://academic.oup.com/bioinformatics/article/39/9/btad547/7260507

Article describing DESeq2: https://link.springer.com/article/10.1186/s13059-014-0550-8

In [105]:
bulk_counts = pandas.read_csv("RNA Sequencing Data/Bulk RNA sequencing data Hic2/counts2.tsv", sep="\t", index_col=0).T
samples = bulk_counts.index.to_list()
print(samples)

['Day2_BFP_Rep1', 'Day2_BFP_Rep2', 'Day2_BFP_Rep3', 'Day2_Hic2_Rep1', 'Day2_Hic2_Rep2', 'Day2_Hic2_Rep3', 'Day4_BFP_Rep1', 'Day4_BFP_Rep1-2', 'Day4_BFP_Rep2', 'Day4_BFP_Rep3', 'Day4_Hic2_Rep1', 'Day4_Hic2_Rep1-2', 'Day4_Hic2_Rep2', 'Day4_Hic2_Rep3', 'Day6_BFP_Rep1', 'Day6_BFP_Rep2', 'Day6_BFP_Rep3', 'Day6_Hic2_Rep1', 'Day6_Hic2_Rep2', 'Day6_Hic2_Rep3', 'Day10_BFP_Rep1', 'Day10_BFP_Rep2', 'Day10_BFP_Rep3', 'Day10_Hic2_Rep1', 'Day10_Hic2_Rep2', 'Day10_Hic2_Rep3', 'ESC_BFP_Rep1', 'ESC_BFP_Rep2', 'ESC_BFP_Rep3', 'ESC_Hic2-gRNA_Rep1', 'ESC_Hic2-gRNA_Rep2', 'ESC_Hic2-gRNA_Rep3', 'ESC_Zeo-gRNA_Rep1', 'ESC_Zeo-gRNA_Rep2', 'ESC_Zeo-gRNA_Rep3', 'iPSC_BFP_Rep1', 'iPSC_BFP_Rep2', 'iPSC_BFP_Rep3', 'iPSC_Hic2_Rep1', 'iPSC_Hic2_Rep2', 'iPSC_Hic2_Rep3', 'MEF_BFP_Rep1', 'MEF_BFP_Rep2', 'MEF_BFP_Rep3', 'MEF_Hic2_Rep1', 'MEF_Hic2_Rep2', 'MEF_Hic2_Rep3']

In [106]:
# Create metadata dataframe

sample_metadata_list = []

for sample in samples:
    sample_name_list = sample.split("_")
    if ("Day" in sample_name_list[0]):
        day = int(sample_name_list[0][3:])
        experiment = "reprogramming"
    else:
        day = 0
        experiment = sample_name_list[0]
    group = sample_name_list[1]
    replicate_list = sample_name_list[2][3:].split("-")
    replicate = replicate_list[0]
    if len(replicate_list) == 2:
        batch = int(replicate_list[1])
    else:
        batch = 1 if experiment in {"reprogramming", "MEF"} else 2
    
    sample_metadata_list.append({"sample": sample, "day": day, "experiment": experiment, "group": group, "replicate": replicate, "batch": batch})

# Create metadata dataframe
metadata_df = pandas.DataFrame(sample_metadata_list).set_index("sample")

metadata_df

                    day     experiment      group replicate  batch
sample
Day2_BFP_Rep1         2  reprogramming        BFP         1      1
Day2_BFP_Rep2         2  reprogramming        BFP         2      1
Day2_BFP_Rep3         2  reprogramming        BFP         3      1
Day2_Hic2_Rep1        2  reprogramming       Hic2         1      1
Day2_Hic2_Rep2        2  reprogramming       Hic2         2      1
Day2_Hic2_Rep3        2  reprogramming       Hic2         3      1
Day4_BFP_Rep1         4  reprogramming        BFP         1      1
Day4_BFP_Rep1-2       4  reprogramming        BFP         1      2
Day4_BFP_Rep2         4  reprogramming        BFP         2      1
Day4_BFP_Rep3         4  reprogramming        BFP         3      1
Day4_Hic2_Rep1        4  reprogramming       Hic2         1      1
Day4_Hic2_Rep1-2      4  reprogramming       Hic2         1      2
Day4_Hic2_Rep2        4  reprogramming       Hic2         2      1
Day4_Hic2_Rep3        4  reprogramming       Hic2         3      1
Day6_BFP_Rep1         6  reprogramming        BFP         1      1
Day6_BFP_Rep2         6  reprogramming        BFP         2      1
Day6_BFP_Rep3         6  reprogramming        BFP         3      1
Day6_Hic2_Rep1        6  reprogramming       Hic2         1      1
Day6_Hic2_Rep2        6  reprogramming       Hic2         2      1
Day6_Hic2_Rep3        6  reprogramming       Hic2         3      1
Day10_BFP_Rep1       10  reprogramming        BFP         1      1
Day10_BFP_Rep2       10  reprogramming        BFP         2      1
Day10_BFP_Rep3       10  reprogramming        BFP         3      1
Day10_Hic2_Rep1      10  reprogramming       Hic2         1      1
Day10_Hic2_Rep2      10  reprogramming       Hic2         2      1
Day10_Hic2_Rep3      10  reprogramming       Hic2         3      1
ESC_BFP_Rep1          0            ESC        BFP         1      2
ESC_BFP_Rep2          0            ESC        BFP         2      2
ESC_BFP_Rep3          0            ESC        BFP         3      2
ESC_Hic2-gRNA_Rep1    0            ESC  Hic2-gRNA         1      2
ESC_Hic2-gRNA_Rep2    0            ESC  Hic2-gRNA         2      2
ESC_Hic2-gRNA_Rep3    0            ESC  Hic2-gRNA         3      2
ESC_Zeo-gRNA_Rep1     0            ESC   Zeo-gRNA         1      2
ESC_Zeo-gRNA_Rep2     0            ESC   Zeo-gRNA         2      2
ESC_Zeo-gRNA_Rep3     0            ESC   Zeo-gRNA         3      2
iPSC_BFP_Rep1         0           iPSC        BFP         1      2
iPSC_BFP_Rep2         0           iPSC        BFP         2      2
iPSC_BFP_Rep3         0           iPSC        BFP         3      2
iPSC_Hic2_Rep1        0           iPSC       Hic2         1      2
iPSC_Hic2_Rep2        0           iPSC       Hic2         2      2
iPSC_Hic2_Rep3        0           iPSC       Hic2         3      2
MEF_BFP_Rep1          0            MEF        BFP         1      1
MEF_BFP_Rep2          0            MEF        BFP         2      1
MEF_BFP_Rep3          0            MEF        BFP         3      1
MEF_Hic2_Rep1         0            MEF       Hic2         1      1
MEF_Hic2_Rep2         0            MEF       Hic2         2      1
MEF_Hic2_Rep3         0            MEF       Hic2         3      1

In [107]:
# Fix duplicated columns
duplicated_columns = bulk_counts.columns[bulk_counts.columns.duplicated()].to_list()
print(duplicated_columns)

# These likely result from Excel misinterpreting gene names as dates, possibly MARC1 and MARC2. They can be ignored.
bulk_counts = bulk_counts.drop(columns=duplicated_columns)

['Mar-01', 'Mar-02']

In [108]:
# Find columns that are also in the adata object

variable_genes = adata.var.index.to_numpy()
common_genes = numpy.intersect1d(variable_genes, bulk_counts.columns.to_numpy())

## Differential expression during the reprogramming experiment

In [109]:
reprogramming_samples = metadata_df.query("experiment == \"reprogramming\"").index.to_list()
print(metadata_df.loc[reprogramming_samples])

                  day     experiment group replicate  batch
sample
Day2_BFP_Rep1       2  reprogramming   BFP         1      1
Day2_BFP_Rep2       2  reprogramming   BFP         2      1
Day2_BFP_Rep3       2  reprogramming   BFP         3      1
Day2_Hic2_Rep1      2  reprogramming  Hic2         1      1
Day2_Hic2_Rep2      2  reprogramming  Hic2         2      1
Day2_Hic2_Rep3      2  reprogramming  Hic2         3      1
Day4_BFP_Rep1       4  reprogramming   BFP         1      1
Day4_BFP_Rep1-2     4  reprogramming   BFP         1      2
Day4_BFP_Rep2       4  reprogramming   BFP         2      1
Day4_BFP_Rep3       4  reprogramming   BFP         3      1
Day4_Hic2_Rep1      4  reprogramming  Hic2         1      1
Day4_Hic2_Rep1-2    4  reprogramming  Hic2         1      2
Day4_Hic2_Rep2      4  reprogramming  Hic2         2      1
Day4_Hic2_Rep3      4  reprogramming  Hic2         3      1
Day6_BFP_Rep1       6  reprogramming   BFP         1      1
Day6_BFP_Rep2       6  reprogramming   BFP         2      1
Day6_BFP_Rep3       6  reprogramming   BFP         3      1
Day6_Hic2_Rep1      6  reprogramming  Hic2         1      1
Day6_Hic2_Rep2      6  reprogramming  Hic2         2      1
Day6_Hic2_Rep3      6  reprogramming  Hic2         3      1
Day10_BFP_Rep1     10  reprogramming   BFP         1      1
Day10_BFP_Rep2     10  reprogramming   BFP         2      1
Day10_BFP_Rep3     10  reprogramming   BFP         3      1
Day10_Hic2_Rep1    10  reprogramming  Hic2         1      1
Day10_Hic2_Rep2    10  reprogramming  Hic2         2      1
Day10_Hic2_Rep3    10  reprogramming  Hic2         3      1

In [125]:
# Fit differential expression model

inference = pydeseq2.dds.DefaultInference(n_cpus=16)
dds = pydeseq2.dds.DeseqDataSet(
    counts=bulk_counts.loc[reprogramming_samples],
    metadata=metadata_df.loc[reprogramming_samples],
    design="~C(day) + C(batch) + group",
    refit_cooks=True,
    inference=inference
)

dds.deseq2()

# Calculate statistics
reprogramming_de_stats = pydeseq2.ds.DeseqStats(dds, contrast=["group", "Hic2", "BFP"], inference=inference)
reprogramming_de_stats.summary()

Fitting size factors...
... done in 0.04 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.93 seconds.

Fitting dispersion trend curve...
... done in 0.51 seconds.

Fitting MAP dispersions...
... done in 2.11 seconds.

Fitting LFCs...
... done in 2.24 seconds.

Calculating cook's distance...
... done in 0.05 seconds.

Replacing 0 outlier genes.

Running Wald tests...

Log2 fold change & Wald test p-value: group Hic2 vs BFP
                baseMean  log2FoldChange     lfcSE      stat        pvalue  \
Gnai3       18118.223009       -0.237734  0.046419 -5.121532  3.030633e-07
Pbsn            0.000000             NaN       NaN       NaN           NaN
Cdc45        1046.343936        0.800273  0.094942  8.429116  3.482852e-17
H19          4548.672607        0.729453  0.114614  6.364408  1.960450e-10
Scml2         183.121673       -0.602971  0.144454 -4.174135  2.991209e-05
...                  ...             ...       ...       ...           ...
BX571804.1      0.000000             NaN       NaN       NaN           NaN
AC154773.1      0.000000             NaN       NaN       NaN           NaN
AL662853.1      0.286036        0.360430  3.104910  0.116084  9.075861e-01
AC145556.1      0.781459       -1.160610  1.788140 -0.649060  5.162997e-01
CT868734.1      0.000000             NaN       NaN       NaN           NaN

                    padj
Gnai3       1.868561e-06
Pbsn                 NaN
Cdc45       7.204903e-16
H19         1.857909e-09
Scml2       1.325471e-04
...                  ...
BX571804.1           NaN
AC154773.1           NaN
AL662853.1           NaN
AC145556.1           NaN
CT868734.1           NaN

[54534 rows x 6 columns]

... done in 2.18 seconds.

In [126]:
# Whether genes of interest are up- or downregulated

genes_of_interest = ["Myc", "Ovol2", "Klf4", "Krtdap", "Krt8", "Krt14", "Nanog", "Tet1", "Cdh1", "Ovol1", "Atf3", "Hic2", "Sall4", "Shisa8", 'Hmgb3', 'Hoxa7', 'Tlx2', 'Zbtb7c', 'Klf2', 'Mycn', 'Rest', 'Tcf7l1', 'Tcf7l2', 'Tfcp2l1', 'Tsc22d1',
       'Zfp42', 'Zic2']
reprogramming_de_stats.results_df.loc[genes_of_interest].sort_values("padj")

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
Hic2,3160.107379,2.198816,0.106077,20.728511,1.916259e-95,2.517219e-92
Zbtb7c,1521.129230,-0.943320,0.058151,-16.221943,3.528526e-59,8.875744e-57
Krt8,21598.666438,-1.363864,0.088721,-15.372461,2.504698e-53,5.018948e-51
Krt14,5110.427482,-4.106556,0.314381,-13.062360,5.402643e-39,5.300643e-37
Nanog,1323.501794,2.370827,0.257670,9.201027,3.545454e-20,9.461880e-19
Zfp42,2688.373406,1.344900,0.149763,8.980156,2.703821e-19,6.666513e-18
Hmgb3,1523.258054,-0.857015,0.103484,-8.281647,1.214838e-16,2.360299e-15
Sall4,1673.703697,0.972394,0.122353,7.947441,1.904039e-15,3.218084e-14
Ovol1,680.945017,-1.451013,0.185601,-7.817914,5.370601e-15,8.644510e-14
Tcf7l1,582.207950,1.263931,0.164272,7.694150,1.424378e-14,2.177080e-13
Tlx2,585.037236,-1.107785,0.157145,-7.049422,1.796624e-12,2.177406e-11
Tfcp2l1,2321.616881,1.502553,0.225386,6.666573,2.618455e-11,2.759063e-10
Tcf7l2,1162.635586,0.753992,0.117507,6.416592,1.393588e-10,1.340578e-09
Cdh1,8959.774174,-0.650625,0.102000,-6.378686,1.786140e-10,1.697479e-09
Zic2,260.881320,0.934213,0.169667,5.506148,3.667703e-08,2.549922e-07
Hoxa7,295.011074,-1.072721,0.196214,-5.467103,4.574495e-08,3.138826e-07
Krtdap,1805.697319,1.238119,0.266848,4.639784,3.487728e-06,1.811672e-05
Rest,2085.826504,0.492894,0.113039,4.360393,1.298291e-05,6.121253e-05
Atf3,742.937707,-1.077951,0.313286,-3.440785,5.800295e-04,2.026418e-03
Tet1,646.478454,0.511292,0.185107,2.762143,5.742333e-03,1.609882e-02
Myc,18952.909643,-0.137470,0.083679,-1.642833,1.004176e-01,1.902238e-01
Ovol2,47.086576,-0.377526,0.246902,-1.529050,1.262522e-01,2.287359e-01
Mycn,298.071539,0.170911,0.176144,0.970293,3.319002e-01,4.827383e-01
Klf2,244.316224,-0.180294,0.236014,-0.763910,4.449206e-01,5.962700e-01
Tsc22d1,3285.236273,0.063317,0.120392,0.525922,5.989421e-01,7.309035e-01
Klf4,22181.280818,-0.025929,0.069824,-0.371350,7.103772e-01,8.158653e-01
Shisa8,2097.998771,-0.013168,0.144476,-0.091146,9.273762e-01,9.565021e-01

In [127]:
# Higher expression in control

reprogramming_de_stats.results_df.loc[common_genes].query("padj < 0.05 and log2FoldChange < 0").sort_values("log2FoldChange").head(50)

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
2310046K23Rik,121.261593,-5.026695,0.526483,-9.547682,1.326310e-21,4.142749e-20
Krt14,5110.427482,-4.106556,0.314381,-13.062360,5.402643e-39,5.300643e-37
Krt6a,8104.897532,-3.767656,0.231002,-16.310079,8.368502e-60,2.198591e-57
Mlc1,6.222436,-3.765394,0.772700,-4.873032,1.098985e-06,6.230041e-06
Slurp1,817.514135,-3.661155,0.243806,-15.016651,5.712186e-51,9.931224e-49
Sel1l3,35.552444,-3.592158,0.570257,-6.299195,2.991958e-10,2.773220e-09
Chit1,745.571491,-3.592043,0.181281,-19.814787,2.219452e-87,2.099158e-84
Mmp13,74.221433,-3.585201,0.291299,-12.307646,8.239182e-35,6.537431e-33
Krt17,5304.148465,-3.505668,0.151732,-23.104406,4.181106e-118,1.098469e-114
Fam180a,50.590588,-3.467625,0.341159,-10.164249,2.863197e-24,1.124589e-22
Lypd2,29.596562,-3.364678,0.420701,-7.997789,1.266727e-15,2.176727e-14
S100a4,635.795977,-3.333922,0.277218,-12.026353,2.583206e-33,1.873617e-31
Gfap,34.695146,-3.051857,0.512517,-5.954650,2.606287e-09,2.128693e-08
Krt16,4807.327708,-3.035999,0.169454,-17.916394,8.784150e-72,3.643881e-69
Pantr1,1.645327,-2.991019,1.038461,-2.880242,3.973703e-03,1.158119e-02
Cyth4,154.543246,-2.982082,0.220056,-13.551484,7.764411e-42,8.826418e-40
Tgm3,95.263220,-2.959092,0.276241,-10.711981,8.942789e-27,4.246029e-25
Acod1,183.948894,-2.891975,0.306381,-9.439134,3.758727e-21,1.116521e-19
Fas,136.515811,-2.869016,0.263123,-10.903723,1.106356e-27,5.542330e-26
Vsig8,218.067548,-2.861439,0.174166,-16.429352,1.179126e-60,3.168230e-58
Lgals7,1045.989920,-2.852198,0.155777,-18.309466,6.954909e-75,3.498911e-72
Cd53,35.011190,-2.838016,0.485941,-5.840246,5.212387e-09,4.074278e-08
Kif1a,410.312517,-2.834751,0.212314,-13.351701,1.157749e-40,1.205946e-38
Lilrb4a,3.185908,-2.814272,0.948590,-2.966795,3.009214e-03,9.022682e-03
Ptgs1,443.286706,-2.785622,0.171022,-16.288068,1.199602e-59,3.116988e-57
Ramp1,4.928841,-2.737310,0.762926,-3.587911,3.333379e-04,1.215948e-03
Padi4,325.936446,-2.704642,0.330620,-8.180512,2.826408e-16,5.308214e-15
Fermt3,722.130121,-2.697049,0.127462,-21.159600,2.251226e-99,3.548682e-96
Cnn1,72.273911,-2.696505,0.315121,-8.557041,1.158010e-17,2.493730e-16
Upk3b,777.598858,-2.690275,0.254550,-10.568746,4.160186e-26,1.880833e-24
Rab25,75.182075,-2.647381,0.241788,-10.949184,6.704902e-28,3.394805e-26
Prok2,49.529964,-2.639078,0.261774,-10.081513,6.669140e-24,2.519038e-22
Rtn4r,945.036806,-2.632157,0.153454,-17.152707,5.999204e-66,1.970155e-63
Gm8994,16.170070,-2.622987,0.566018,-4.634104,3.584871e-06,1.857237e-05
Dsg3,1442.809217,-2.615226,0.177498,-14.733800,3.910848e-49,6.206174e-47
Gpx2,411.576364,-2.582672,0.161770,-15.965108,2.236529e-57,5.566602e-55
Ly6g6c,1619.300369,-2.579183,0.135474,-19.038204,8.230171e-81,5.259524e-78
Gpm6a,157.332102,-2.571634,0.384503,-6.688198,2.259347e-11,2.411840e-10
Edn2,126.441139,-2.567301,0.219320,-11.705717,1.191474e-31,7.739669e-30
Kcnn4,586.350923,-2.563120,0.197094,-13.004560,1.152596e-38,1.112373e-36
Ehf,147.726657,-2.550276,0.199724,-12.768995,2.442871e-37,2.230181e-35
Pkp1,2909.631813,-2.548214,0.098846,-25.779740,1.496395e-146,1.769113e-142
Mal2,1414.525483,-2.539277,0.107040,-23.722602,2.107776e-124,6.229796e-121
Col2a1,435.806977,-2.531633,0.463879,-5.457525,4.828173e-08,3.298719e-07
Paqr5,88.472256,-2.483270,0.257794,-9.632754,5.814948e-22,1.863068e-20
Prss32,308.741124,-2.452161,0.137686,-17.809855,5.926270e-71,2.375028e-68
Sult2b1,232.481783,-2.424468,0.126188,-19.213201,2.870130e-82,2.056492e-79
Adgrg2,253.169818,-2.375604,0.365534,-6.498992,8.086007e-11,7.993045e-10
Chl1,662.700241,-2.370794,0.159735,-14.842087,7.828246e-50,1.276544e-47
Bnc1,109.319585,-2.364595,0.314648,-7.515047,5.689055e-14,8.098597e-13

The high upregulation of 2310046K23Rik, also known as Small proline rich protein 5 (Sprr5) is very interesting.

Function of human Sprr5 according to Uniprot: "Positively regulates keratinocyte differentiation by inducing genes associated with epidermal differentiation".

In [128]:
# Higher expression with Hic2

reprogramming_de_stats.results_df.loc[common_genes].query("padj < 0.05 and log2FoldChange > 0").sort_values("log2FoldChange", ascending=False).head(50)

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
Ifi27l2a,60.427621,4.964874,0.849305,5.845811,5.041075e-09,3.957378e-08
Eras,129.003245,4.766440,0.745645,6.392374,1.633294e-10,1.556959e-09
3830417A13Rik,274.669327,4.546757,0.306071,14.855229,6.434730e-50,1.071473e-47
Oasl2,329.182784,4.419285,0.438522,10.077691,6.933599e-24,2.609246e-22
Pramef12,591.836100,4.304483,0.708941,6.071709,1.265565e-09,1.073508e-08
Dnmt3l,2023.817274,4.146114,0.878535,4.719352,2.365970e-06,1.268270e-05
Nr0b1,399.205895,4.031501,0.463751,8.693253,3.522062e-18,7.916269e-17
Napsa,4.379697,4.014911,1.029909,3.898317,9.686348e-05,3.921139e-04
Cdh5,11.450055,3.893308,0.550767,7.068885,1.561839e-12,1.900653e-11
Gm13119,27.830769,3.853006,0.458546,8.402669,4.364452e-17,8.934847e-16
Oc90,65.467582,3.726041,0.445047,8.372243,5.653151e-17,1.142468e-15
Xirp2,201.954137,3.552851,0.366211,9.701647,2.966715e-22,9.824646e-21
Rhox6,843.856049,3.497290,0.578944,6.040810,1.533424e-09,1.287565e-08
Rhox9,443.080480,3.371150,0.860592,3.917244,8.956711e-05,3.652033e-04
Ifi44,85.364130,3.191233,0.550913,5.792623,6.929571e-09,5.335386e-08
Msc,393.658370,3.127482,0.163321,19.149323,9.805399e-82,6.819078e-79
Triml2,443.860259,3.125697,0.534643,5.846327,5.025470e-09,3.947749e-08
Gulo,85.436805,3.054613,0.337745,9.044132,1.508584e-19,3.827304e-18
Fgfbp1,1285.708241,3.035683,0.180225,16.843824,1.164611e-63,3.623320e-61
Isg15,188.394009,2.994927,0.277783,10.781534,4.208082e-27,2.047327e-25
Nefh,335.998784,2.933564,0.192661,15.226598,2.355329e-52,4.419981e-50
Mdk,443.711480,2.886874,0.218122,13.235118,5.501025e-40,5.606540e-38
Rtp4,96.476905,2.884328,0.482601,5.976626,2.278065e-09,1.872257e-08
Bhmt,211.717439,2.876332,0.584604,4.920134,8.648520e-07,4.982803e-06
Smyd1,607.598844,2.866995,0.468909,6.114177,9.705625e-10,8.390841e-09
Calcoco2,359.354547,2.792392,0.414160,6.742306,1.558923e-11,1.705519e-10
Cyct,11.355528,2.747193,0.656223,4.186370,2.834510e-05,1.261709e-04
Ifit3,78.258653,2.727286,0.531092,5.135245,2.817769e-07,1.746884e-06
Fgf8,14.487642,2.693382,0.566636,4.753283,2.001401e-06,1.087638e-05
Hrc,226.265561,2.692569,0.334377,8.052486,8.112884e-16,1.425179e-14
Prtg,91.589416,2.670374,0.329348,8.108057,5.143573e-16,9.319523e-15
Apobec2,37.796629,2.649309,0.459248,5.768800,7.983780e-09,6.101373e-08
Rsad2,101.635670,2.634645,0.396480,6.645087,3.030384e-11,3.160716e-10
Usp18,75.666675,2.627379,0.526935,4.986153,6.159347e-07,3.629149e-06
Pramel6,32.955419,2.602657,0.552368,4.711819,2.455152e-06,1.312801e-05
Aard,156.616636,2.584949,0.772097,3.347957,8.140950e-04,2.763715e-03
Gng3,168.878149,2.556263,0.346726,7.372578,1.673592e-13,2.261262e-12
Gdf3,793.392687,2.459679,0.431772,5.696706,1.221440e-08,9.082058e-08
Serpinb9e,5.521220,2.454891,1.046842,2.345044,1.902486e-02,4.662065e-02
Dppa1,11.644146,2.435997,0.681471,3.574619,3.507385e-04,1.274291e-03
Ifit1,115.641867,2.433911,0.474439,5.130079,2.896210e-07,1.793163e-06
Zfp936,263.575857,2.415428,0.687576,3.512959,4.431453e-04,1.582088e-03
Ninl,359.944766,2.394328,0.363023,6.595519,4.237716e-11,4.352772e-10
Triml1,156.575471,2.393034,0.467244,5.121593,3.029653e-07,1.868514e-06
Hand1,197.547415,2.391584,0.512543,4.666114,3.069493e-06,1.611773e-05
Nanog,1323.501794,2.370827,0.257670,9.201027,3.545454e-20,9.461880e-19
Dppa2,670.676987,2.361603,0.459424,5.140357,2.742171e-07,1.703590e-06
Rbpms2,901.729924,2.334365,0.271350,8.602781,7.780756e-18,1.697195e-16
Rbp4,214.452097,2.324890,0.195477,11.893400,1.280844e-32,8.933795e-31
Stra8,46.459730,2.289561,0.898556,2.548045,1.083286e-02,2.837205e-02

## Differential expression in day 2

In [ ]:
day_2_samples = metadata_df.query("experiment == \"reprogramming\" and day == 2").index.to_list()
print(metadata_df.loc[day_2_samples])

                day     experiment group replicate  batch
sample
Day2_BFP_Rep1     2  reprogramming   BFP         1      1
Day2_BFP_Rep2     2  reprogramming   BFP         2      1
Day2_BFP_Rep3     2  reprogramming   BFP         3      1
Day2_Hic2_Rep1    2  reprogramming  Hic2         1      1
Day2_Hic2_Rep2    2  reprogramming  Hic2         2      1
Day2_Hic2_Rep3    2  reprogramming  Hic2         3      1

In [121]:
# Fit differential expression model

inference = pydeseq2.dds.DefaultInference(n_cpus=16)
dds = pydeseq2.dds.DeseqDataSet(
    counts=bulk_counts.loc[day_2_samples],
    metadata=metadata_df.loc[day_2_samples],
    design="~group",
    refit_cooks=True,
    inference=inference
)

dds.deseq2()

# Calculate statistics
day_2_de_stats = pydeseq2.ds.DeseqStats(dds, contrast=["group", "Hic2", "BFP"], inference=inference)
day_2_de_stats.summary()

Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.44 seconds.

Fitting dispersion trend curve...
... done in 0.45 seconds.

Fitting MAP dispersions...
... done in 1.43 seconds.

Fitting LFCs...
... done in 1.33 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 0 outlier genes.

Running Wald tests...

Log2 fold change & Wald test p-value: group Hic2 vs BFP
                baseMean  log2FoldChange     lfcSE      stat        pvalue  \
Gnai3       22128.672245       -0.120252  0.037410 -3.214455  1.306925e-03
Pbsn            0.000000             NaN       NaN       NaN           NaN
Cdc45         690.247113        0.478694  0.089751  5.333594  9.628743e-08
H19          2598.156315        0.973740  0.318548  3.056811  2.237051e-03
Scml2         286.322931       -0.440445  0.153644 -2.866664  4.148229e-03
...                  ...             ...       ...       ...           ...
BX571804.1      0.000000             NaN       NaN       NaN           NaN
AC154773.1      0.000000             NaN       NaN       NaN           NaN
AL662853.1      0.000000             NaN       NaN       NaN           NaN
AC145556.1      1.836549       -1.380029  2.047491 -0.674010  5.003051e-01
CT868734.1      0.000000             NaN       NaN       NaN           NaN

                padj
Gnai3       0.006083
Pbsn             NaN
Cdc45       0.000001
H19         0.009774
Scml2       0.016740
...              ...
BX571804.1       NaN
AC154773.1       NaN
AL662853.1       NaN
AC145556.1       NaN
CT868734.1       NaN

[54534 rows x 6 columns]

... done in 2.10 seconds.

In [122]:
# Whether genes of interest are up- or downregulated

genes_of_interest = ["Krtdap", "Krt8", "Krt14", "Nanog", "Tet1", "Cdh1", "Ovol1", "Atf3", "Hic2", "Sall4", "Shisa8", 'Hmgb3', 'Hoxa7', 'Tlx2', 'Zbtb7c', 'Klf2', 'Mycn', 'Rest', 'Tcf7l1', 'Tcf7l2', 'Tfcp2l1', 'Tsc22d1',
       'Zfp42', 'Zic2']
day_2_de_stats.results_df.loc[genes_of_interest].sort_values("padj")

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
Hic2,3149.191898,2.688885,0.076548,35.126718,2.635957e-270,4.470846e-266
Krt8,6886.109100,-1.620890,0.046294,-35.013120,1.420759e-268,1.204875e-264
Krt14,3064.054179,-2.215632,0.087545,-25.308377,2.583242e-141,3.983124e-138
Cdh1,1811.915900,-1.431488,0.080460,-17.791400,8.239497e-71,3.176139e-68
Zbtb7c,1545.528898,-0.915841,0.073941,-12.386172,3.105169e-35,2.831547e-33
Krtdap,638.725020,1.533055,0.138921,11.035443,2.577781e-28,1.607417e-26
Tlx2,536.024936,-1.211808,0.131036,-9.247933,2.288763e-20,8.782740e-19
Ovol1,331.654674,-1.328884,0.146448,-9.074094,1.146274e-19,4.084445e-18
Hmgb3,1901.452329,-0.379427,0.067962,-5.582933,2.364953e-08,2.756836e-07
Tcf7l1,469.488292,0.578413,0.116473,4.966068,6.832397e-07,6.384809e-06
Rest,3240.580307,0.212969,0.063922,3.331709,8.631454e-04,4.206842e-03
Zic2,174.665886,0.599804,0.182250,3.291114,9.979135e-04,4.789736e-03
Tcf7l2,1152.934163,0.308370,0.097661,3.157558,1.590966e-03,7.230541e-03
Zfp42,145.306929,0.604577,0.208036,2.906121,3.659396e-03,1.500591e-02
Nanog,10.651224,2.447234,0.896886,2.728591,6.360551e-03,2.415073e-02
Sall4,174.148942,0.343719,0.198638,1.730378,8.356280e-02,2.019821e-01
Tfcp2l1,49.729455,0.473909,0.340966,1.389899,1.645595e-01,3.364791e-01
Tsc22d1,2681.427756,-0.083418,0.076703,-1.087539,2.767986e-01,4.830730e-01
Shisa8,2538.062376,0.063104,0.071308,0.884947,3.761853e-01,5.904532e-01
Hoxa7,287.346874,-0.110042,0.141340,-0.778563,4.362372e-01,6.481838e-01
Atf3,900.013939,-0.796161,1.093504,-0.728083,4.665628e-01,6.750735e-01
Tet1,265.773487,-0.094492,0.171926,-0.549607,5.825887e-01,7.641366e-01
Mycn,41.935021,0.198285,0.364847,0.543476,5.868023e-01,7.665290e-01
Klf2,22.334884,-0.211883,0.549893,-0.385316,7.000033e-01,8.418349e-01

In [123]:
# Higher expression in control

day_2_de_stats.results_df.loc[common_genes].query("padj < 0.05 and log2FoldChange < 0").sort_values("log2FoldChange").head(50)

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
Cbr2,9.181110,-2.816140,0.937512,-3.003844,2.665916e-03,1.138670e-02
Krt17,1025.852472,-2.815688,0.103277,-27.263386,1.153250e-163,2.794324e-160
Slurp1,241.005104,-2.786119,0.181877,-15.318704,5.734927e-53,1.157977e-50
Fermt3,167.084349,-2.715851,0.236266,-11.494872,1.399881e-30,9.651778e-29
Fam180a,76.626846,-2.688414,0.304611,-8.825742,1.087367e-18,3.591692e-17
Pkp1,1929.939402,-2.591549,0.180137,-14.386529,6.287301e-47,9.437071e-45
Gpx2,25.385435,-2.501531,0.523653,-4.777073,1.778649e-06,1.542314e-05
Ly6g6c,56.906671,-2.430245,0.375380,-6.474090,9.538479e-11,1.489707e-09
Mapk13,240.980212,-2.396511,0.186562,-12.845643,9.099282e-38,9.297164e-36
S100a14,19.860539,-2.368664,0.559988,-4.229849,2.338487e-05,1.645771e-04
Nr5a2,11.798785,-2.364968,0.766987,-3.083452,2.046140e-03,9.030596e-03
Cyth4,167.389745,-2.341889,0.251642,-9.306434,1.321961e-20,5.166310e-19
Krt6a,4797.302666,-2.337251,0.170564,-13.703102,9.727846e-43,1.195609e-40
Mal2,94.669341,-2.332846,0.275218,-8.476349,2.323706e-17,6.902343e-16
Mmp13,16.068091,-2.316111,0.672343,-3.444836,5.714068e-04,2.906395e-03
Chit1,88.066594,-2.306204,0.289621,-7.962821,1.681611e-15,4.276133e-14
2310046K23Rik,22.127730,-2.240043,0.580164,-3.861052,1.129000e-04,6.846252e-04
Cox4i2,9.963094,-2.234392,0.914076,-2.444426,1.450829e-02,4.860263e-02
Krt14,3064.054179,-2.215632,0.087545,-25.308377,2.583242e-141,3.983124e-138
Sel1l3,16.168550,-2.201774,0.680931,-3.233476,1.222937e-03,5.731481e-03
Lgals7,91.238539,-2.195766,0.270364,-8.121520,4.603816e-16,1.225829e-14
Gm8994,31.535068,-2.195324,0.503589,-4.359359,1.304440e-05,9.606863e-05
Prok2,44.040957,-2.145097,0.405692,-5.287505,1.239958e-07,1.319381e-06
Prss32,43.599646,-2.142421,0.374980,-5.713426,1.107240e-08,1.352045e-07
Kcnn4,621.356547,-2.140375,0.108243,-19.773786,5.007378e-87,3.266543e-84
Vsig8,40.043238,-2.048431,0.412532,-4.965503,6.852333e-07,6.399913e-06
Kif1a,670.235950,-2.032605,0.134227,-15.143100,8.415204e-52,1.551416e-49
Rtn4r,1192.414823,-2.029681,0.105845,-19.175888,5.885465e-82,3.119480e-79
Bmp7,36.616017,-1.990365,0.405040,-4.913992,8.924047e-07,8.164011e-06
Krt16,2234.157523,-1.963148,0.067527,-29.071942,8.126832e-186,2.756784e-182
Them5,131.864249,-1.954547,0.239130,-8.173575,2.993841e-16,8.060084e-15
Fas,232.754005,-1.954024,0.170945,-11.430714,2.936851e-30,1.992477e-28
Fam83g,691.024962,-1.952742,0.102056,-19.133951,1.317031e-81,6.769138e-79
Gdf15,34.577321,-1.929746,0.418295,-4.613366,3.961996e-06,3.201496e-05
Fbp2,167.584681,-1.865160,0.203924,-9.146334,5.889824e-20,2.162279e-18
Grin1,64.087595,-1.835196,0.356565,-5.146869,2.648702e-07,2.659836e-06
Tgm3,61.984990,-1.820739,0.347764,-5.235564,1.644818e-07,1.714228e-06
Chst13,172.920397,-1.800014,0.210242,-8.561621,1.112914e-17,3.407245e-16
Igfbp2,301.952971,-1.799834,0.146682,-12.270350,1.306879e-34,1.142576e-32
Dsg3,1043.002466,-1.778018,0.120177,-14.794988,1.578134e-49,2.598711e-47
Ndnf,70.957380,-1.775926,0.305812,-5.807245,6.350905e-09,8.026654e-08
Ptgs1,464.228929,-1.762256,0.151158,-11.658333,2.080752e-31,1.489099e-29
Ctnnal1,673.290710,-1.757565,0.111861,-15.712031,1.251071e-55,2.906769e-53
Wnt4,389.372698,-1.755426,0.149059,-11.776686,5.147719e-32,3.863295e-30
Fads3,1250.191008,-1.753593,0.081675,-21.470315,2.950100e-102,2.943332e-99
Megf6,19.799265,-1.714562,0.563256,-3.044020,2.334399e-03,1.015485e-02
Alox12b,45.487157,-1.687173,0.401076,-4.206619,2.592194e-05,1.806335e-04
Edn2,203.672643,-1.680728,0.228766,-7.346942,2.027926e-13,4.294088e-12
Cisd3,3392.612568,-1.674837,0.057098,-29.332665,3.976198e-189,1.686007e-185
Acod1,34.775011,-1.663859,0.429365,-3.875166,1.065520e-04,6.503163e-04

In [124]:
# Higher expression with Hic2

day_2_de_stats.results_df.loc[common_genes].query("padj < 0.05 and log2FoldChange > 0").sort_values("log2FoldChange", ascending=False).head(50)

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
Oasl2,257.102054,6.886760,1.053968,6.534127,6.398168e-11,1.019307e-09
Ifi44,136.271695,6.128665,1.019703,6.010248,1.852398e-09,2.511473e-08
Nr0b1,23.558192,6.090100,1.121658,5.429550,5.649644e-08,6.283516e-07
Ifi27l2a,11.812878,5.933982,1.613442,3.677840,2.352170e-04,1.325861e-03
Ifit3b,61.723969,5.706857,1.554940,3.670145,2.424129e-04,1.362521e-03
Rsad2,214.173270,5.387152,1.107387,4.864742,1.146061e-06,1.028484e-05
Ifit3,118.796074,5.177538,0.979090,5.288111,1.235858e-07,1.316670e-06
Ifit1,260.327155,4.863718,0.857393,5.672680,1.405806e-08,1.693457e-07
Rtp4,62.698740,4.843640,1.201816,4.030269,5.571313e-05,3.616343e-04
Usp18,120.299860,4.758689,0.881617,5.397683,6.750696e-08,7.444639e-07
Oasl1,102.441445,4.313196,0.841316,5.126723,2.948285e-07,2.919198e-06
Isg15,255.804981,4.192754,0.817276,5.130158,2.894987e-07,2.871454e-06
Mx2,45.144180,4.011146,0.617438,6.496434,8.224621e-11,1.296448e-09
Fgfbp1,429.991866,3.673666,0.159865,22.979853,7.413731e-117,8.981735e-114
Iigp1,31.324786,3.638440,0.628510,5.788991,7.081057e-09,8.909630e-08
Trh,10.678007,3.492380,0.916132,3.812092,1.377956e-04,8.180437e-04
Cxcl10,21.820600,3.178810,0.767918,4.139515,3.480409e-05,2.353717e-04
Fgf8,25.001538,3.008339,0.558050,5.390805,7.014274e-08,7.725266e-07
Msc,351.160959,2.883050,0.170741,16.885493,5.753417e-64,1.876610e-61
Mx1,16.175734,2.833122,0.739450,3.831392,1.274205e-04,7.639373e-04
Hic2,3149.191898,2.688885,0.076548,35.126718,2.635957e-270,4.470846e-266
Ifit1bl1,87.499478,2.684634,0.431903,6.215823,5.105648e-10,7.295442e-09
Nefh,323.510083,2.650728,0.152447,17.387879,1.019377e-67,3.678651e-65
Apod,17.670068,2.619577,0.691426,3.788659,1.514629e-04,8.929308e-04
Ddx60,32.386383,2.540890,0.606240,4.191229,2.774472e-05,1.917597e-04
Nanog,10.651224,2.447234,0.896886,2.728591,6.360551e-03,2.415073e-02
Lgals3bp,372.013914,2.372441,0.699702,3.390643,6.972896e-04,3.480497e-03
Hgf,15.995822,2.259884,0.686263,3.293028,9.911464e-04,4.762276e-03
Ifih1,320.491103,2.171099,0.582163,3.729366,1.919623e-04,1.104809e-03
Trim30a,23.987574,2.148960,0.581655,3.694563,2.202656e-04,1.250309e-03
Tph1,27.459707,2.118486,0.491673,4.308733,1.641922e-05,1.187575e-04
Plet1,70.800360,2.113436,0.304087,6.950109,3.650052e-12,6.721882e-11
Gbp3,470.236271,2.100239,0.796963,2.635302,8.406249e-03,3.072810e-02
Parp14,167.209813,2.063059,0.295881,6.972594,3.111487e-12,5.780277e-11
Itih5,61.114617,1.998278,0.322570,6.194866,5.833471e-10,8.265790e-09
AW551984,1369.764238,1.990690,0.211119,9.429214,4.131718e-21,1.676509e-19
Krt20,1909.892858,1.972599,0.071620,27.542384,5.459887e-167,1.543419e-163
Xirp2,52.787879,1.967821,0.360042,5.465539,4.615034e-08,5.194133e-07
Samd9l,111.461658,1.939589,0.719266,2.696622,7.004670e-03,2.623812e-02
Col8a2,20.405302,1.907768,0.553453,3.447026,5.667949e-04,2.886042e-03
Cd36,15.337225,1.869675,0.699746,2.671936,7.541507e-03,2.797103e-02
Mdk,85.496338,1.810920,0.282972,6.399632,1.557515e-10,2.384206e-09
C430049B03Rik,33.413468,1.809601,0.442466,4.089806,4.317335e-05,2.867907e-04
Ifi204,241.527510,1.781040,0.536966,3.316858,9.103601e-04,4.414128e-03
Slc1a2,58.198878,1.769336,0.323133,5.475562,4.361245e-08,4.924839e-07
Arhgap8,15.439533,1.760657,0.661998,2.659613,7.823046e-03,2.883866e-02
Pcsk2,21.053917,1.756926,0.559349,3.141016,1.683626e-03,7.600739e-03
Aass,36.123864,1.742669,0.404768,4.305352,1.667207e-05,1.204322e-04
Apela,917.897162,1.655067,0.106623,15.522547,2.441637e-54,5.176576e-52
Rbp4,441.472534,1.627963,0.122425,13.297688,2.387356e-40,2.699463e-38

## Differential expression in day 4

In [116]:
day_4_samples = metadata_df.query("experiment == \"reprogramming\" and day == 4").index.to_list()
print(metadata_df.loc[day_4_samples])

                  day     experiment group replicate  batch
sample
Day4_BFP_Rep1       4  reprogramming   BFP         1      1
Day4_BFP_Rep1-2     4  reprogramming   BFP         1      2
Day4_BFP_Rep2       4  reprogramming   BFP         2      1
Day4_BFP_Rep3       4  reprogramming   BFP         3      1
Day4_Hic2_Rep1      4  reprogramming  Hic2         1      1
Day4_Hic2_Rep1-2    4  reprogramming  Hic2         1      2
Day4_Hic2_Rep2      4  reprogramming  Hic2         2      1
Day4_Hic2_Rep3      4  reprogramming  Hic2         3      1

In [117]:
# Fit differential expression model

inference = pydeseq2.dds.DefaultInference(n_cpus=16)
dds = pydeseq2.dds.DeseqDataSet(
    counts=bulk_counts.loc[day_4_samples],
    metadata=metadata_df.loc[day_4_samples],
    design="~C(day) + C(batch) + group",
    refit_cooks=True,
    inference=inference
)

dds.deseq2()

# Calculate statistics
day_4_de_stats = pydeseq2.ds.DeseqStats(dds, contrast=["group", "Hic2", "BFP"], inference=inference)
day_4_de_stats.summary()

Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.37 seconds.

Fitting dispersion trend curve...
... done in 0.48 seconds.

Fitting MAP dispersions...
... done in 1.56 seconds.

Fitting LFCs...
... done in 1.61 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 0 outlier genes.

Running Wald tests...

Log2 fold change & Wald test p-value: group Hic2 vs BFP
                baseMean  log2FoldChange     lfcSE      stat        pvalue  \
Gnai3       15061.034487       -0.145678  0.048888 -2.979812  2.884256e-03
Pbsn            0.000000             NaN       NaN       NaN           NaN
Cdc45         695.773380        0.949563  0.116376  8.159410  3.366663e-16
H19          3270.342112        0.798852  0.092818  8.606611  7.525230e-18
Scml2         239.054249       -0.541207  0.135172 -4.003823  6.232701e-05
...                  ...             ...       ...       ...           ...
BX571804.1      0.000000             NaN       NaN       NaN           NaN
AC154773.1      0.000000             NaN       NaN       NaN           NaN
AL662853.1      0.863819        1.292333  2.205131  0.586057  5.578371e-01
AC145556.1      0.339300        0.601040  3.320829  0.180991  8.563748e-01
CT868734.1      0.000000             NaN       NaN       NaN           NaN

                    padj
Gnai3       7.882933e-03
Pbsn                 NaN
Cdc45       3.668566e-15
H19         9.364109e-17
Scml2       2.251457e-04
...                  ...
BX571804.1           NaN
AC154773.1           NaN
AL662853.1           NaN
AC145556.1           NaN
CT868734.1           NaN

[54534 rows x 6 columns]

... done in 1.96 seconds.

In [118]:
# Whether genes of interest are up- or downregulated

genes_of_interest = ["Krtdap", "Krt8", "Krt14", "Nanog", "Tet1", "Cdh1", "Ovol1", "Atf3", "Hic2", "Sall4", "Shisa8", 'Hmgb3', 'Hoxa7', 'Tlx2', 'Zbtb7c', 'Klf2', 'Mycn', 'Rest', 'Tcf7l1', 'Tcf7l2', 'Tfcp2l1', 'Tsc22d1',
       'Zfp42', 'Zic2']
day_4_de_stats.results_df.loc[genes_of_interest].sort_values("padj")

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
Hic2,3154.780976,2.399564,0.065990,36.362376,1.675002e-289,9.103215e-286
Krtdap,1793.064199,2.325247,0.065549,35.473522,1.258797e-275,4.560833e-272
Krt8,24075.847629,-1.650879,0.059111,-27.928501,1.202923e-171,8.716779e-169
Zbtb7c,1758.713380,-1.095422,0.053464,-20.488793,2.710318e-93,3.954336e-91
Krt14,7186.538884,-4.235427,0.293805,-14.415787,4.117190e-47,2.067058e-45
Zfp42,427.157105,1.555553,0.137043,11.350841,7.345297e-30,1.878581e-28
Sall4,1312.697523,1.117913,0.104806,10.666470,1.460712e-26,3.147117e-25
Nanog,53.434685,3.237392,0.343363,9.428489,4.160391e-21,6.582441e-20
Ovol1,796.688716,-0.757347,0.083485,-9.071703,1.171713e-19,1.685762e-18
Cdh1,10584.047067,-0.565965,0.065088,-8.695453,3.454493e-18,4.417484e-17
Tcf7l1,356.692664,0.890082,0.107501,8.279757,1.234273e-16,1.398221e-15
Tfcp2l1,213.209667,1.694083,0.213364,7.939867,2.023974e-15,2.080339e-14
Tlx2,726.747089,-0.622547,0.103229,-6.030721,1.632299e-09,9.887027e-09
Hmgb3,1424.268916,-0.524054,0.092642,-5.656765,1.542528e-08,8.474356e-08
Tsc22d1,2253.604151,-0.450058,0.082281,-5.469797,4.505522e-08,2.356160e-07
Shisa8,2755.203859,0.402292,0.081622,4.928740,8.276154e-07,3.798887e-06
Hoxa7,280.197745,-0.606157,0.129811,-4.669544,3.018685e-06,1.294598e-05
Zic2,149.992750,0.712985,0.174202,4.092870,4.260670e-05,1.576288e-04
Tcf7l2,1416.614372,0.360014,0.088429,4.071212,4.676907e-05,1.719163e-04
Rest,2465.829179,0.222705,0.061301,3.633005,2.801392e-04,9.175752e-04
Atf3,668.933543,-0.371373,0.123323,-3.011390,2.600542e-03,7.164680e-03
Klf2,23.574220,-0.749347,0.510424,-1.468087,1.420807e-01,2.445132e-01
Tet1,201.402418,-0.144847,0.157900,-0.917334,3.589677e-01,5.079806e-01
Mycn,33.238168,-0.224741,0.314028,-0.715670,4.741952e-01,6.228718e-01

In [119]:
# Higher expression in control

day_4_de_stats.results_df.query("padj < 0.05 and log2FoldChange < 0").sort_values("log2FoldChange").head(50)

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
Zxda,19.182632,-7.144257,2.270178,-3.147003,1.649531e-03,4.716447e-03
Gm5940,5.245388,-5.785067,2.061074,-2.806822,5.003286e-03,1.304172e-02
Gm35507,8.275602,-5.754740,1.447637,-3.975264,7.030127e-05,2.516929e-04
Ly6d,5.064573,-5.744730,1.859937,-3.088669,2.010550e-03,5.663040e-03
Gm44196,4.808731,-5.710786,1.883808,-3.031511,2.433331e-03,6.735189e-03
Lce3b,8.120451,-5.659103,1.449224,-3.904919,9.425678e-05,3.305983e-04
Krt90,350.081052,-5.639549,0.414021,-13.621420,2.987037e-42,1.278252e-40
Myoz2,24.224179,-5.569297,0.840379,-6.627125,3.422872e-11,2.430899e-10
Wnt7a,211.924221,-5.426897,0.483151,-11.232305,2.829978e-29,7.014925e-28
2310046K23Rik,143.752868,-5.419234,0.696467,-7.781036,7.193321e-15,7.082229e-14
Tppp,6.235846,-5.395312,1.511109,-3.570433,3.563919e-04,1.145205e-03
Gm25994,3.637169,-5.344569,2.067447,-2.585106,9.734905e-03,2.378634e-02
Gm8486,3.743123,-5.340373,2.072925,-2.576250,9.987848e-03,2.433055e-02
Foxn1,3.696257,-5.293616,2.034380,-2.602078,9.266068e-03,2.275845e-02
Calm4,3.510841,-5.293467,1.926293,-2.748006,5.995886e-03,1.539260e-02
Cryba2,3.313402,-5.213149,1.937025,-2.691317,7.117048e-03,1.796325e-02
Gm12589,3.198143,-5.144649,1.907267,-2.697393,6.988477e-03,1.767774e-02
Gm13233,3.304230,-5.123938,1.902982,-2.692584,7.090066e-03,1.790555e-02
Creb3l3,15.929952,-5.067314,0.926353,-5.470176,4.495896e-08,2.352257e-07
Crct1,20.093143,-5.047969,0.854111,-5.910203,3.416872e-09,2.005383e-08
Gm13881,2.930401,-5.025353,1.928823,-2.605399,9.176736e-03,2.256199e-02
Sel1l3,69.863304,-5.024111,0.487067,-10.315022,6.026759e-25,1.188890e-23
Prss46,4.967126,-4.982173,1.544473,-3.225809,1.256173e-03,3.668944e-03
Tmem238l,49.673853,-4.980378,0.554875,-8.975671,2.816288e-19,3.937189e-18
Gm12298,2.796469,-4.958292,1.943744,-2.550897,1.074461e-02,2.598766e-02
Orm1,2.781236,-4.932125,2.005190,-2.459680,1.390611e-02,3.261818e-02
2310008N11Rik,3.041349,-4.917771,1.999085,-2.460010,1.389330e-02,3.259514e-02
Acoxl,2.725105,-4.915672,1.940385,-2.533348,1.129786e-02,2.714758e-02
Pglyrp2,4.537353,-4.893306,1.697572,-2.882532,3.944935e-03,1.050581e-02
Mrgprg,7.502504,-4.889245,1.217321,-4.016397,5.909476e-05,2.140388e-04
Lmod2,8.070615,-4.851427,1.311812,-3.698263,2.170799e-04,7.253458e-04
Lrrc26,4.454839,-4.844087,1.531086,-3.163824,1.557110e-03,4.477516e-03
Gm41653,3.017320,-4.812492,1.967564,-2.445914,1.444854e-02,3.377748e-02
Cnfn,19.952261,-4.758959,0.792363,-6.006035,1.901150e-09,1.143583e-08
Gm8994,13.401118,-4.724915,0.847137,-5.577507,2.439895e-08,1.312568e-07
Krt2,4.208939,-4.723383,1.555929,-3.035732,2.399525e-03,6.651782e-03
Myh14,187.908131,-4.722307,0.288046,-16.394270,2.101505e-60,1.569918e-58
Atp13a5,4.119655,-4.712097,1.555716,-3.028892,2.454526e-03,6.789533e-03
Gm45881,9.395898,-4.694023,1.005847,-4.666737,3.060212e-06,1.311115e-05
Gm29865,4.038214,-4.691467,1.629197,-2.879620,3.981550e-03,1.059522e-02
Gm47127,3.968331,-4.686388,1.573388,-2.978533,2.896317e-03,7.911917e-03
Cyp21a1,86.610666,-4.683034,0.416862,-11.234003,2.776110e-29,6.897125e-28
Ooep,2.260031,-4.627025,2.009622,-2.302436,2.131062e-02,4.784381e-02
Tssk1,2.306655,-4.591622,2.009716,-2.284712,2.232975e-02,4.981286e-02
Calr4,5.951299,-4.569361,1.260847,-3.624041,2.900351e-04,9.462814e-04
Defb1,8.184451,-4.560979,1.119443,-4.074330,4.614702e-05,1.697158e-04
Cldn9,8.395693,-4.545624,1.013805,-4.483727,7.335050e-06,3.005780e-05
Tacr3,5.875050,-4.511808,1.247743,-3.615975,2.992194e-04,9.737622e-04
Ces1e,3.495976,-4.507170,1.555599,-2.897385,3.762876e-03,1.005793e-02
Gm11398,2.574786,-4.484835,1.923732,-2.331320,1.973649e-02,4.472549e-02

In [120]:
# Higher expression with Hic2

day_4_de_stats.results_df.loc[common_genes].query("padj < 0.05 and log2FoldChange > 0").sort_values("log2FoldChange", ascending=False).head(50)

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
Gm13119,4.560295,5.567292,1.796201,3.099482,1.938593e-03,5.482405e-03
Eras,11.339190,5.439741,1.109805,4.901528,9.509425e-07,4.331142e-06
Napsa,3.667996,5.312775,1.870530,2.840251,4.507802e-03,1.185952e-02
Oc90,5.969510,5.227858,1.475699,3.542632,3.961549e-04,1.264798e-03
Dnmt3l,5.432173,5.067096,1.517523,3.339058,8.406302e-04,2.533545e-03
Nr0b1,55.178169,5.060812,0.465392,10.874295,1.528328e-27,3.468092e-26
Rhox6,11.462765,4.912741,1.007439,4.876465,1.080041e-06,4.882305e-06
Pramef12,11.219521,4.909294,1.002603,4.896551,9.753340e-07,4.432947e-06
Gulo,3.260914,4.356487,1.595638,2.730248,6.328675e-03,1.616296e-02
Cdh5,3.118053,4.239004,1.556186,2.723970,6.450235e-03,1.645408e-02
Gng3,20.693872,4.197169,0.602276,6.968850,3.195411e-12,2.518674e-11
Oasl2,90.377244,4.192587,0.809688,5.178026,2.242455e-07,1.094493e-06
Fgf8,13.197153,4.163545,0.765524,5.438819,5.363488e-08,2.781414e-07
3830417A13Rik,13.818852,4.102171,0.748069,5.483678,4.165726e-08,2.187409e-07
Triml2,23.932751,3.968494,0.608163,6.525383,6.782797e-11,4.700390e-10
Mdk,165.554679,3.963177,0.215571,18.384514,1.748007e-75,1.938772e-73
Gdf3,47.994271,3.916642,0.396015,9.890142,4.593761e-23,8.145495e-22
Rhox9,9.881296,3.875408,1.073144,3.611265,3.047073e-04,9.895478e-04
Rbp4,274.615715,3.375939,0.160828,20.990964,7.932064e-98,1.336707e-95
Mcf2,12.857902,3.373000,0.728782,4.628270,3.687334e-06,1.563162e-05
Ifi27l2a,8.127915,3.349154,1.010067,3.315775,9.138937e-04,2.734260e-03
Fgfbp1,570.262402,3.287102,0.172780,19.024836,1.062185e-80,1.297238e-78
Nanog,53.434685,3.237392,0.343363,9.428489,4.160391e-21,6.582441e-20
Dppa2,13.969192,3.044072,0.607078,5.014299,5.322712e-07,2.493759e-06
Isg15,69.981008,2.968428,0.346306,8.571699,1.019697e-17,1.254510e-16
Klk13,103.161074,2.929539,0.271708,10.781939,4.189589e-27,9.284146e-26
Msc,220.864172,2.910080,0.149389,19.479931,1.624997e-84,2.140959e-82
Bhmt,10.807291,2.888115,0.690105,4.185040,2.851162e-05,1.078500e-04
Spon1,7.142196,2.868756,0.909019,3.155879,1.600150e-03,4.586112e-03
Nefh,742.979084,2.776921,0.102386,27.121955,5.425305e-162,3.276131e-159
Tie1,99.468188,2.724682,0.256312,10.630342,2.153204e-26,4.589068e-25
Calcoco2,17.364889,2.695051,0.563469,4.782964,1.727290e-06,7.628922e-06
Triml1,15.580061,2.683494,0.548837,4.889415,1.011359e-06,4.589967e-06
Lrmp,20.116931,2.658376,0.467607,5.685067,1.307615e-08,7.227624e-08
Rsad2,64.853448,2.609419,0.423811,6.157041,7.411646e-10,4.625948e-09
Ninj2,3.741450,2.597249,1.077945,2.409444,1.597684e-02,3.704751e-02
Rbpms2,80.341044,2.559445,0.285428,8.967031,3.046133e-19,4.244864e-18
Mmrn2,851.126875,2.471980,0.290637,8.505383,1.809974e-17,2.188377e-16
Palm3,1396.409679,2.452672,0.103001,23.812078,2.503959e-125,7.257809e-123
Cth,1708.971546,2.412385,0.085708,28.146607,2.636869e-174,2.204727e-171
Hic2,3154.780976,2.399564,0.065990,36.362376,1.675002e-289,9.103215e-286
Pcsk2,40.720512,2.380986,0.361531,6.585849,4.522938e-11,3.184072e-10
Fbxo15,113.465884,2.379005,0.278043,8.556254,1.165940e-17,1.427161e-16
Xirp2,84.304931,2.358688,0.266203,8.860497,7.965869e-19,1.063045e-17
Krtdap,1793.064199,2.325247,0.065549,35.473522,1.258797e-275,4.560833e-272
Cotl1,233.301970,2.321422,0.146868,15.806177,2.820731e-56,1.928298e-54
Zp3,89.284433,2.306270,0.261583,8.816605,1.179823e-18,1.558212e-17
Oasl1,32.595292,2.285623,0.386307,5.916591,3.286823e-09,1.932709e-08
Esrrb,737.952662,2.256410,0.296788,7.602780,2.898362e-14,2.712333e-13
Slfn5,838.365576,2.249335,0.096687,23.264107,1.024039e-119,2.619009e-117

## Differential expression in day 6

In [80]:
day_6_samples = metadata_df.query("experiment == \"reprogramming\" and day == 6").index.to_list()
print(metadata_df.loc[day_6_samples])

                day     experiment group replicate  batch
sample
Day6_BFP_Rep1     6  reprogramming   BFP         1      1
Day6_BFP_Rep2     6  reprogramming   BFP         2      1
Day6_BFP_Rep3     6  reprogramming   BFP         3      1
Day6_Hic2_Rep1    6  reprogramming  Hic2         1      1
Day6_Hic2_Rep2    6  reprogramming  Hic2         2      1
Day6_Hic2_Rep3    6  reprogramming  Hic2         3      1

In [129]:
# Fit differential expression model

inference = pydeseq2.dds.DefaultInference(n_cpus=16)
dds = pydeseq2.dds.DeseqDataSet(
    counts=bulk_counts.loc[day_6_samples],
    metadata=metadata_df.loc[day_6_samples],
    design="~group",
    refit_cooks=True,
    inference=inference
)

dds.deseq2()

# Calculate statistics
day_6_de_stats = pydeseq2.ds.DeseqStats(dds, contrast=["group", "Hic2", "BFP"], inference=inference)
day_6_de_stats.summary()

Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.36 seconds.

Fitting dispersion trend curve...
... done in 0.44 seconds.

Fitting MAP dispersions...
... done in 1.32 seconds.

Fitting LFCs...
... done in 1.36 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 0 outlier genes.

Running Wald tests...

Log2 fold change & Wald test p-value: group Hic2 vs BFP
                baseMean  log2FoldChange     lfcSE      stat        pvalue  \
Gnai3       22363.371052       -0.307583  0.093112 -3.303380  9.552682e-04
Pbsn            0.000000             NaN       NaN       NaN           NaN
Cdc45        1137.191588        1.182272  0.128137  9.226605  2.793445e-20
H19          3896.764956        0.465219  0.336784  1.381358  1.671688e-01
Scml2          82.045704       -1.696386  0.424089 -4.000073  6.332304e-05
...                  ...             ...       ...       ...           ...
BX571804.1      0.000000             NaN       NaN       NaN           NaN
AC154773.1      0.000000             NaN       NaN       NaN           NaN
AL662853.1      0.000000             NaN       NaN       NaN           NaN
AC145556.1      1.191800       -3.722858  4.235882 -0.878886  3.794630e-01
CT868734.1      0.000000             NaN       NaN       NaN           NaN

                    padj
Gnai3       4.349148e-03
Pbsn                 NaN
Cdc45       1.155026e-18
H19         3.136980e-01
Scml2       3.829907e-04
...                  ...
BX571804.1           NaN
AC154773.1           NaN
AL662853.1           NaN
AC145556.1           NaN
CT868734.1           NaN

[54534 rows x 6 columns]

... done in 2.01 seconds.

In [130]:
# Whether genes of interest are up- or downregulated

genes_of_interest = ["Krtdap", "Krt8", "Krt14", "Nanog", "Tet1", "Cdh1", "Ovol1", "Atf3", "Hic2", "Sall4", "Shisa8", 'Hmgb3', 'Hoxa7', 'Tlx2', 'Zbtb7c', 'Klf2', 'Mycn', 'Rest', 'Tcf7l1', 'Tcf7l2', 'Tfcp2l1', 'Tsc22d1',
       'Zfp42', 'Zic2']
day_6_de_stats.results_df.loc[genes_of_interest].sort_values("padj")

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
Hic2,2797.623961,2.157327,0.111354,19.373565,1.290083e-83,9.388194e-81
Tfcp2l1,2117.184424,2.836544,0.194685,14.569883,4.366368e-48,9.687480e-46
Krt14,7410.892477,-4.181132,0.287351,-14.550630,5.786792e-48,1.268423e-45
Krtdap,3475.638326,1.373563,0.111199,12.352334,4.731854e-35,5.093883e-33
Hmgb3,1381.829875,-1.399331,0.131310,-10.656667,1.623102e-26,1.028888e-24
Nanog,540.294456,2.516980,0.237262,10.608442,2.722494e-26,1.707943e-24
Zfp42,1517.458376,1.986789,0.195344,10.170728,2.678989e-24,1.441978e-22
Tcf7l1,432.475319,2.128565,0.227501,9.356281,8.259261e-21,3.560681e-19
Sall4,1691.440867,1.498192,0.177879,8.422521,3.684691e-17,1.155786e-15
Krt8,35915.605695,-0.866945,0.105122,-8.247045,1.623600e-16,4.748898e-15
Ovol1,1018.742043,-1.117075,0.136306,-8.195337,2.498920e-16,7.170798e-15
Tcf7l2,1105.221422,1.159597,0.143769,8.065703,7.281554e-16,2.007171e-14
Atf3,881.777759,-1.485929,0.230341,-6.450987,1.111240e-10,1.747345e-09
Hoxa7,313.793281,-1.449888,0.251804,-5.758012,8.511049e-09,1.033655e-07
Zbtb7c,1391.874437,-0.754481,0.137692,-5.479469,4.266053e-08,4.644662e-07
Tlx2,807.056504,-0.684695,0.206666,-3.313061,9.228072e-04,4.214014e-03
Cdh1,11751.186123,-0.285536,0.089130,-3.203577,1.357316e-03,5.937402e-03
Tet1,139.804883,0.944496,0.354019,2.667928,7.632070e-03,2.615269e-02
Rest,734.498038,0.501719,0.206539,2.429180,1.513303e-02,4.640406e-02
Shisa8,2037.825246,0.395274,0.164318,2.405547,1.614826e-02,4.897237e-02
Mycn,81.515126,0.619466,0.506077,1.224056,2.209310e-01,3.845210e-01
Zic2,67.553748,0.490491,0.463105,1.059137,2.895375e-01,4.656979e-01
Tsc22d1,2818.969342,-0.005903,0.123954,-0.047626,9.620146e-01,9.822613e-01
Klf2,71.144448,-0.015460,0.551643,-0.028025,9.776426e-01,9.902155e-01

In [131]:
# Higher expression in control

day_6_de_stats.results_df.loc[common_genes].query("padj < 0.05 and log2FoldChange < 0").sort_values("log2FoldChange").head(50)

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
Gfap,47.669095,-8.078114,1.545994,-5.225190,1.739768e-07,1.698048e-06
Sel1l3,23.755821,-8.039324,2.174451,-3.697174,2.180125e-04,1.170346e-03
Col2a1,45.522950,-8.011511,1.505257,-5.322354,1.024332e-07,1.036467e-06
Lat2,12.345648,-7.095768,2.233821,-3.176516,1.490554e-03,6.430555e-03
Il6,11.332284,-6.972185,2.257527,-3.088416,2.012263e-03,8.352523e-03
2310046K23Rik,241.807171,-6.371918,1.463529,-4.353804,1.337953e-05,9.430989e-05
Cd53,15.917120,-5.545834,1.424303,-3.893717,9.871964e-05,5.714306e-04
Lypd2,40.918428,-5.138319,0.860197,-5.973420,2.323303e-09,3.049628e-08
Mmp13,117.183501,-4.779892,0.492072,-9.713805,2.633189e-22,1.247542e-20
Fam180a,58.557126,-4.468817,0.763884,-5.850122,4.912113e-09,6.154688e-08
Tgm3,67.688212,-4.332270,0.690312,-6.275814,3.478089e-10,5.135777e-09
Palmd,7.020157,-4.320246,1.675823,-2.577985,9.937838e-03,3.264700e-02
Serpinb5,126.558520,-4.295080,0.477109,-9.002303,2.210319e-19,8.501549e-18
Fas,125.262707,-4.260693,1.219014,-3.495196,4.737133e-04,2.328003e-03
Krt14,7410.892477,-4.181132,0.287351,-14.550630,5.786792e-48,1.268423e-45
Gpm6a,275.563579,-4.171826,0.426577,-9.779775,1.375153e-22,6.618562e-21
Mlc1,9.469354,-4.139932,1.607378,-2.575581,1.000717e-02,3.282927e-02
Gldn,9.415527,-4.134465,1.529038,-2.703965,6.851756e-03,2.389381e-02
Chit1,1203.424837,-4.054278,0.188889,-21.463840,3.391107e-102,4.745724e-99
Krt6a,11298.542602,-3.998861,0.339794,-11.768482,5.673608e-32,5.404186e-30
Col4a4,19.636187,-3.954271,1.176666,-3.360572,7.778112e-04,3.620732e-03
S100a4,631.267672,-3.913844,0.293957,-13.314348,1.910337e-40,2.715216e-38
Bnc1,55.271459,-3.860192,0.736067,-5.244352,1.568326e-07,1.540635e-06
Upk3b,1028.658658,-3.857803,0.449024,-8.591526,8.582188e-18,2.844003e-16
Tspan8,193.073157,-3.793682,0.380710,-9.964747,2.174275e-23,1.101855e-21
Slurp1,1536.019852,-3.619497,0.191058,-18.944472,4.904875e-80,3.186943e-77
Ptgs1,455.417598,-3.557293,0.270421,-13.154657,1.600075e-39,2.109432e-37
Prelp,243.717487,-3.532658,0.392446,-9.001633,2.223839e-19,8.535505e-18
Cyth4,134.958878,-3.518601,0.378149,-9.304792,1.342544e-20,5.653913e-19
Cp,54.754800,-3.513763,0.743444,-4.726330,2.286136e-06,1.877728e-05
Prok2,48.604006,-3.498096,0.666756,-5.246441,1.550653e-07,1.524920e-06
Il1rl1,71.135287,-3.377909,0.624585,-5.408249,6.364405e-08,6.739676e-07
Krt17,9662.816060,-3.359035,0.123105,-27.285862,6.242134e-164,3.785438e-160
Lbp,615.489226,-3.358800,0.265822,-12.635512,1.345153e-36,1.568741e-34
Paqr5,155.549791,-3.285368,0.365769,-8.982095,2.656601e-19,1.006907e-17
Sprr1a,266.087413,-3.205486,0.332370,-9.644328,5.195044e-22,2.423421e-20
Luzp2,37.443916,-3.180944,0.916777,-3.469703,5.210335e-04,2.531152e-03
Mgst1,726.056779,-3.149453,0.221245,-14.235123,5.546492e-46,1.096819e-43
Notum,15.119671,-3.139908,1.285903,-2.441793,1.461453e-02,4.507301e-02
Edn1,19.583820,-3.094732,1.106225,-2.797561,5.149009e-03,1.880616e-02
C3,200.197115,-3.084410,0.329676,-9.355895,8.289520e-21,3.565278e-19
Gda,260.396756,-3.083570,0.346206,-8.906761,5.254508e-19,1.950924e-17
Lgals7,1746.889744,-3.058075,0.133713,-22.870394,9.160273e-116,1.515026e-112
E330020D12Rik,15.594451,-3.036710,1.111749,-2.731471,6.305221e-03,2.230381e-02
Hsd17b2,113.307969,-2.961140,0.411435,-7.197106,6.150417e-13,1.268646e-11
Ntf3,33.917821,-2.957774,0.714379,-4.140340,3.467910e-05,2.230965e-04
Adgrg2,163.801256,-2.918592,0.347697,-8.394071,4.695922e-17,1.452941e-15
Ptprv,3496.500452,-2.896791,0.120412,-24.057368,6.989921e-128,1.816680e-124
Gdf15,16.798766,-2.857071,1.067592,-2.676181,7.446633e-03,2.561963e-02
Krt16,6734.638817,-2.842891,0.137811,-20.628873,1.511307e-94,1.617365e-91

In [132]:
# Higher expression with Hic2

day_6_de_stats.results_df.loc[common_genes].query("padj < 0.05 and log2FoldChange > 0").sort_values("log2FoldChange", ascending=False).head(50)

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
Dnmt3l,818.910694,10.672582,0.858088,12.437625,1.632871e-35,1.800413e-33
Dppa3,133.792752,10.501275,1.984438,5.291814,1.211091e-07,1.212624e-06
Pramef12,477.612385,10.484930,1.044874,10.034637,1.073530e-23,5.580209e-22
Eras,87.377929,8.923089,1.450481,6.151812,7.660256e-10,1.086358e-08
Rhox9,284.444808,8.418665,0.697033,12.077853,1.382826e-33,1.413357e-31
Robo4,12.799660,7.117509,2.226828,3.196254,1.392245e-03,6.069760e-03
Wfdc2,64.778082,7.015705,0.976164,7.187018,6.622165e-13,1.359786e-11
Pla2g10,7.546254,6.354666,2.621542,2.424018,1.534985e-02,4.698970e-02
Bhmt,78.678302,6.268316,0.775500,8.082934,6.322708e-16,1.761547e-14
Pramel6,6.254222,6.085642,2.510027,2.424532,1.532813e-02,4.693901e-02
Aard,33.403569,6.030537,1.080556,5.580959,2.391963e-08,2.714721e-07
Smyd1,748.073091,5.990464,0.507336,11.807683,3.562448e-32,3.449552e-30
Dmgdh,52.746107,5.947032,0.913681,6.508869,7.571886e-11,1.216920e-09
Prtg,41.508972,5.919163,0.971011,6.095879,1.088379e-09,1.500067e-08
3830417A13Rik,364.836437,5.858197,0.349007,16.785314,3.125718e-63,1.322469e-60
Rhox6,642.100306,5.843972,0.281087,20.790614,5.263322e-96,6.383708e-93
Ninl,343.181736,5.546469,0.332574,16.677386,1.914147e-62,7.738684e-60
Folr1,965.320914,5.543236,0.227836,24.329950,9.452008e-131,2.866006e-127
Xirp2,283.194444,5.527768,0.418188,13.218378,6.873020e-40,9.472791e-38
Stard8,126.049385,5.446096,1.307052,4.166703,3.090371e-05,2.015888e-04
Triml2,239.902319,5.302888,0.391902,13.531176,1.023732e-41,1.591860e-39
Oc90,93.047952,5.239096,0.618112,8.475962,2.331445e-17,7.436864e-16
Calcoco2,259.553224,5.170447,0.332014,15.572988,1.110946e-54,3.425667e-52
Zfp936,12.607275,5.155031,1.616308,3.189387,1.425749e-03,6.186179e-03
Dppa2,192.157941,5.041666,0.390483,12.911348,3.884418e-38,4.976706e-36
Cyp2b23,26.373345,4.997439,1.107658,4.511718,6.430461e-06,4.846287e-05
Ifi27l2a,11.070746,4.945392,1.854846,2.666201,7.671381e-03,2.627361e-02
Hrc,235.885998,4.888012,0.370245,13.202106,8.531569e-40,1.167029e-37
Triml1,68.585683,4.719369,0.605955,7.788312,6.791022e-15,1.723493e-13
Stra8,8.316727,4.642042,1.760338,2.637018,8.363847e-03,2.834112e-02
Platr3,7.424523,4.393045,1.753845,2.504808,1.225180e-02,3.885930e-02
St8sia1,383.476940,4.349917,0.290239,14.987349,8.882889e-51,2.308663e-48
Nr0b1,164.401558,4.326302,0.368887,11.727986,9.161253e-32,8.503606e-30
Msc,620.561478,4.248915,0.206389,20.586951,3.592772e-94,3.631294e-91
Trap1a,29.750756,4.208192,0.934595,4.502688,6.709921e-06,5.031888e-05
Cyp26a1,45.329492,4.150635,0.760237,5.459662,4.770415e-08,5.141478e-07
Apobec2,15.205656,4.087526,1.306306,3.129073,1.753585e-03,7.388367e-03
Tie1,554.648173,4.080890,0.291162,14.015897,1.246146e-44,2.267114e-42
Ncmap,50.882505,4.046804,0.690077,5.864276,4.510969e-09,5.679451e-08
Nefh,45.104066,4.046733,0.733423,5.517594,3.436720e-08,3.796251e-07
Rhox5,449.150316,3.981835,0.243944,16.322719,6.803637e-60,2.475571e-57
Hand1,81.632368,3.978439,0.529165,7.518340,5.547616e-14,1.272734e-12
Gdf3,705.263050,3.938957,0.246560,15.975639,1.889078e-57,6.484529e-55
Stmn3,43.542134,3.838540,0.846818,4.532898,5.817983e-06,4.419481e-05
Gm13119,52.990881,3.812026,0.729576,5.224990,1.741647e-07,1.698970e-06
Lmo2,12.634577,3.800490,1.340221,2.835720,4.572257e-03,1.695883e-02
Rbpms2,295.892574,3.735356,0.322405,11.585912,4.857706e-31,4.168690e-29
Tex19.1,135.876725,3.728279,0.380331,9.802730,1.095829e-22,5.330593e-21
Igll1,11.945613,3.714731,1.389881,2.672696,7.524434e-03,2.581407e-02
Enpp3,351.702854,3.686769,0.305340,12.074316,1.443588e-33,1.467218e-31

## Day 10 differential expression

In [134]:
day_10_samples = metadata_df.query("experiment == \"reprogramming\" and day == 10").index.to_list()
print(metadata_df.loc[day_10_samples])

                 day     experiment group replicate  batch
sample
Day10_BFP_Rep1    10  reprogramming   BFP         1      1
Day10_BFP_Rep2    10  reprogramming   BFP         2      1
Day10_BFP_Rep3    10  reprogramming   BFP         3      1
Day10_Hic2_Rep1   10  reprogramming  Hic2         1      1
Day10_Hic2_Rep2   10  reprogramming  Hic2         2      1
Day10_Hic2_Rep3   10  reprogramming  Hic2         3      1

In [135]:
# Fit differential expression model

inference = pydeseq2.dds.DefaultInference(n_cpus=16)
dds = pydeseq2.dds.DeseqDataSet(
    counts=bulk_counts.loc[day_10_samples],
    metadata=metadata_df.loc[day_10_samples],
    design="~group",
    refit_cooks=True,
    inference=inference
)

dds.deseq2()

# Calculate statistics
day_10_de_stats = pydeseq2.ds.DeseqStats(dds, contrast=["group", "Hic2", "BFP"], inference=inference)
day_10_de_stats.summary()

Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.38 seconds.

Fitting dispersion trend curve...
... done in 0.45 seconds.

Fitting MAP dispersions...
... done in 1.43 seconds.

Fitting LFCs...
... done in 1.35 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 0 outlier genes.

Running Wald tests...

Log2 fold change & Wald test p-value: group Hic2 vs BFP
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
Gnai3       14599.801326       -0.486742  0.110552 -4.402836  0.000011
Pbsn            0.000000             NaN       NaN       NaN       NaN
Cdc45        1823.385673        0.472664  0.184033  2.568364  0.010218
H19          9032.655059        0.583415  0.142092  4.105908  0.000040
Scml2         103.792330        0.022729  0.348827  0.065159  0.948047
...                  ...             ...       ...       ...       ...
BX571804.1      0.000000             NaN       NaN       NaN       NaN
AC154773.1      0.000000             NaN       NaN       NaN       NaN
AL662853.1      0.000000             NaN       NaN       NaN       NaN
AC145556.1      0.000000             NaN       NaN       NaN       NaN
CT868734.1      0.000000             NaN       NaN       NaN       NaN

                padj
Gnai3       0.000073
Pbsn             NaN
Cdc45       0.031130
H19         0.000241
Scml2       0.973732
...              ...
BX571804.1       NaN
AC154773.1       NaN
AL662853.1       NaN
AC145556.1       NaN
CT868734.1       NaN

[54534 rows x 6 columns]

... done in 1.97 seconds.

In [136]:
# Whether genes of interest are up- or downregulated

genes_of_interest = ["Krtdap", "Krt8", "Krt14", "Nanog", "Tet1", "Cdh1", "Ovol1", "Atf3", "Hic2", "Sall4", "Shisa8", 'Hmgb3', 'Hoxa7', 'Tlx2', 'Zbtb7c', 'Klf2', 'Mycn', 'Rest', 'Tcf7l1', 'Tcf7l2', 'Tfcp2l1', 'Tsc22d1',
       'Zfp42', 'Zic2']
day_10_de_stats.results_df.loc[genes_of_interest].sort_values("padj")

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
Ovol1,523.721234,-3.065469,0.268917,-11.399329,4.213554e-30,6.988580e-28
Hic2,3528.417087,1.412919,0.134361,10.515811,7.304973e-26,7.556882e-24
Hmgb3,1472.708056,-1.320122,0.129233,-10.215083,1.697342e-24,1.507255e-22
Krt8,18156.640526,-1.300506,0.149296,-8.710930,3.013925e-18,1.447045e-16
Hoxa7,313.478151,-2.416212,0.312123,-7.741205,9.847861e-15,3.224090e-13
Krt14,1833.668617,-5.782565,0.751295,-7.696798,1.395177e-14,4.423350e-13
Tsc22d1,5885.198478,0.899993,0.124330,7.238765,4.527873e-13,1.159055e-11
Nanog,5271.214218,1.179392,0.166227,7.095067,1.292888e-12,3.081587e-11
Tlx2,203.466775,-2.257631,0.325591,-6.933944,4.092656e-12,8.966760e-11
Zic2,702.258569,1.868672,0.282547,6.613673,3.748997e-11,6.985944e-10
Zbtb7c,1304.171701,-1.035031,0.166461,-6.217862,5.039730e-10,7.762267e-09
Shisa8,769.567883,-1.189053,0.195144,-6.093194,1.106795e-09,1.618971e-08
Atf3,573.836011,-1.983030,0.329393,-6.020247,1.741510e-09,2.464764e-08
Tcf7l2,855.164257,1.246685,0.210027,5.935833,2.923581e-09,3.977853e-08
Tfcp2l1,7868.664234,0.826629,0.151594,5.452904,4.955369e-08,5.396056e-07
Rest,1771.812577,1.061015,0.201475,5.266234,1.392506e-07,1.389667e-06
Krtdap,1276.834404,-0.980482,0.202501,-4.841861,1.286285e-06,1.073366e-05
Sall4,3655.997299,0.744222,0.156888,4.743648,2.099038e-06,1.682623e-05
Tet1,2184.049626,1.492433,0.386369,3.862714,1.121342e-04,6.039775e-04
Cdh1,10837.602935,-0.455510,0.122886,-3.706759,2.099286e-04,1.054055e-03
Tcf7l1,1172.874479,1.517226,0.460463,3.294998,9.842254e-04,4.115087e-03
Zfp42,9691.541140,1.050634,0.340533,3.085260,2.033742e-03,7.750697e-03
Klf2,967.860470,0.206307,0.223071,0.924847,3.550455e-01,5.243125e-01
Mycn,1165.146541,0.084670,0.254114,0.333199,7.389842e-01,8.466772e-01

In [138]:
# Higher expression in control

day_10_de_stats.results_df.loc[common_genes].query("padj < 0.05 and log2FoldChange < 0").sort_values("log2FoldChange").head(50)

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
Lilrb4a,9.670870,-6.725212,2.376187,-2.830254,4.651113e-03,1.596429e-02
Bfsp2,8.464746,-6.536837,2.364571,-2.764492,5.701150e-03,1.894625e-02
Krt14,1833.668617,-5.782565,0.751295,-7.696798,1.395177e-14,4.423350e-13
2310046K23Rik,66.749600,-5.765423,0.748905,-7.698470,1.377052e-14,4.380693e-13
Lypd2,30.611673,-5.379791,1.034593,-5.199910,1.993845e-07,1.934001e-06
Acod1,365.572994,-5.123413,0.789755,-6.487343,8.736343e-11,1.521959e-09
Mlc1,16.067620,-4.955775,1.282753,-3.863389,1.118248e-04,6.026350e-04
Slurp1,495.962366,-4.856608,0.969936,-5.007144,5.524358e-07,4.958334e-06
Krt6a,5384.824223,-4.785563,0.453454,-10.553586,4.889477e-26,5.137535e-24
Gfap,61.583979,-4.594034,0.575792,-7.978631,1.479650e-15,5.331256e-14
Aqp8,860.344584,-4.524448,0.968036,-4.673842,2.956169e-06,2.287981e-05
Padi4,1092.279217,-4.480895,0.783321,-5.720378,1.062875e-08,1.299663e-07
S100a4,559.081312,-4.405639,0.224237,-19.647269,6.100877e-86,2.448770e-82
Nnat,86.398201,-4.297163,0.601249,-7.147057,8.865788e-13,2.175153e-11
Pglyrp1,61.861837,-4.235255,0.646688,-6.549150,5.786539e-11,1.042460e-09
Kcnn4,424.964917,-4.136344,0.307494,-13.451807,3.004380e-41,1.282870e-38
Krt13,1630.338413,-4.094779,0.546922,-7.486951,7.049207e-14,2.015250e-12
Mmp13,69.537899,-4.072157,0.656717,-6.200780,5.618400e-10,8.600737e-09
Cnn1,63.845928,-3.900650,0.761839,-5.120043,3.054668e-07,2.872733e-06
Dsg3,662.804530,-3.762761,0.519220,-7.246951,4.262591e-13,1.098151e-11
Car6,72.245844,-3.744647,0.617826,-6.061010,1.352692e-09,1.953034e-08
Rtn4r,456.382586,-3.700253,0.329128,-11.242585,2.518957e-29,3.949448e-27
Lmo1,598.078504,-3.689281,0.291573,-12.653013,1.076648e-36,3.131487e-34
Chit1,611.835442,-3.653079,0.261802,-13.953571,2.992382e-44,1.668170e-41
Lgals7,2113.940413,-3.624513,0.511376,-7.087770,1.362897e-12,3.236922e-11
Vsig8,169.684200,-3.552519,0.410796,-8.647893,5.245899e-18,2.425805e-16
Tspan8,446.350686,-3.532247,0.299750,-11.783989,4.720504e-32,9.473580e-30
Krt16,1908.520705,-3.432723,0.222317,-15.440665,8.719596e-54,7.608416e-51
Tgm3,115.726258,-3.395112,0.466381,-7.279690,3.345893e-13,8.754722e-12
Arg1,39.322773,-3.394485,0.632015,-5.370897,7.834585e-08,8.227749e-07
Ehf,153.211815,-3.355060,0.363181,-9.237975,2.512070e-20,1.559752e-18
Edn2,110.186729,-3.353274,0.586233,-5.720037,1.065009e-08,1.300892e-07
Krt17,6133.111283,-3.322227,0.143257,-23.190678,5.654487e-119,5.673995e-115
Serpinb5,108.439548,-3.321479,0.458735,-7.240515,4.469853e-13,1.145664e-11
Krt42,185.649828,-3.288576,0.463849,-7.089760,1.343447e-12,3.194506e-11
Urah,362.238674,-3.288567,0.348600,-9.433630,3.961378e-21,2.667815e-19
C3,147.034220,-3.285561,0.449978,-7.301598,2.843698e-13,7.470094e-12
Gpx2,541.969174,-3.249684,0.275216,-11.807742,3.559935e-32,7.216599e-30
Star,10.381320,-3.233071,1.260980,-2.563935,1.034929e-02,3.145538e-02
Ankrd13b,1103.061462,-3.210086,0.242087,-13.260050,3.946346e-40,1.523062e-37
Gpm6a,54.367336,-3.199785,0.748722,-4.273660,1.922905e-05,1.237281e-04
Dgat2,1854.198369,-3.160886,0.238873,-13.232503,5.695839e-40,2.116848e-37
Tnmd,36.503113,-3.151039,0.922802,-3.414643,6.386566e-04,2.812640e-03
Chl1,389.991531,-3.125684,0.326158,-9.583354,9.394383e-22,6.733424e-20
Pax3,124.767415,-3.124228,0.502770,-6.214026,5.164402e-10,7.929944e-09
Fam180a,13.428072,-3.097249,1.286895,-2.406760,1.609474e-02,4.555787e-02
Zic4,28.984434,-3.078483,0.900312,-3.419351,6.277066e-04,2.769886e-03
Ovol1,523.721234,-3.065469,0.268917,-11.399329,4.213554e-30,6.988580e-28
Trh,7332.199747,-3.017309,0.478772,-6.302179,2.934891e-10,4.696996e-09
Mal,6125.491171,-2.987347,0.178898,-16.698557,1.342726e-62,2.072860e-59

In [139]:
# Higher expression with Hic2

day_10_de_stats.results_df.loc[common_genes].query("padj < 0.05 and log2FoldChange > 0").sort_values("log2FoldChange", ascending=False).head(50)

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
Tex101,64.224640,6.985983,0.949437,7.358024,1.866531e-13,5.014648e-12
Hand1,695.537998,6.115260,0.258542,23.652838,1.103560e-123,2.214734e-119
Ifi27l2a,232.672652,5.887109,1.396644,4.215182,2.495765e-05,1.562108e-04
1700013H16Rik,74.436598,5.801094,1.615614,3.590644,3.298625e-04,1.574693e-03
Gm5091,35.882148,5.670047,0.998624,5.677859,1.363907e-08,1.634164e-07
Cdh5,25.377575,5.192595,1.089449,4.766259,1.876779e-06,1.518753e-05
Cadps,21.525663,4.874195,1.148286,4.244758,2.188291e-05,1.391093e-04
Xirp2,433.072464,4.812337,0.306422,15.704918,1.399590e-55,1.404419e-52
Ifi44,149.483631,4.798597,0.441547,10.867697,1.642963e-27,2.047989e-25
Stra8,196.754285,4.269137,0.410677,10.395368,2.602796e-25,2.548074e-23
Gm13119,62.656945,4.238282,0.591146,7.169600,7.521728e-13,1.859034e-11
Oasl2,1007.804782,4.172202,0.208274,20.032288,2.881120e-89,1.445530e-85
Smc1b,83.789108,4.121608,0.647406,6.366338,1.935951e-10,3.213615e-09
Ifit3b,67.508052,4.064828,0.642880,6.322846,2.567889e-10,4.152696e-09
Lcp1,328.314599,3.980931,0.304197,13.086706,3.922546e-39,1.381080e-36
3830417A13Rik,824.389052,3.942442,0.225384,17.492092,1.646022e-68,3.303401e-65
Ms4a10,53.353533,3.941007,0.819876,4.806833,1.533396e-06,1.262771e-05
Serpinb9e,21.853655,3.916102,0.963420,4.064792,4.807526e-05,2.820293e-04
Dhx58,61.563324,3.876037,0.653107,5.934769,2.942592e-09,4.001008e-08
Nup62cl,2547.910274,3.806233,0.174915,21.760462,5.499162e-105,3.678756e-101
Gata3,104.366637,3.784482,0.454743,8.322253,8.630671e-17,3.534876e-15
Ifit3,144.064614,3.748917,0.416690,8.996890,2.322023e-19,1.266323e-17
Usp26,162.483145,3.745078,1.483003,2.525334,1.155883e-02,3.449943e-02
Smyd1,1876.726048,3.597398,0.184128,19.537489,5.271217e-85,1.763134e-81
Tnnt1,256.367338,3.570763,0.345933,10.322122,5.597213e-25,5.200485e-23
Rtp4,296.250492,3.531376,0.323981,10.899944,1.153282e-27,1.474218e-25
Dazl,785.992668,3.521695,0.733547,4.800913,1.579439e-06,1.296432e-05
Cyct,48.558483,3.511943,0.626359,5.606914,2.059659e-08,2.406013e-07
Cd36,355.621426,3.493871,0.358341,9.750119,1.842524e-22,1.369541e-20
Hrc,506.448657,3.457889,0.289118,11.960118,5.748053e-33,1.296154e-30
Usp18,157.562986,3.446073,0.394184,8.742296,2.284203e-18,1.101963e-16
Alox5ap,59.588679,3.395399,0.610523,5.561459,2.675280e-08,3.066102e-07
Smtnl1,85.220409,3.330366,0.566425,5.879623,4.112020e-09,5.422085e-08
Nostrin,72.360164,3.319952,0.505661,6.565569,5.183460e-11,9.439824e-10
Vnn1,623.305814,3.272129,0.247122,13.240953,5.089868e-40,1.927331e-37
Kdr,103.482929,3.223479,0.427148,7.546516,4.470572e-14,1.313615e-12
C1ql3,60.108164,3.186286,0.735352,4.333011,1.470838e-05,9.761328e-05
Sycp3,381.078100,3.164436,0.655067,4.830705,1.360504e-06,1.131536e-05
Stard8,629.929995,3.162760,0.226461,13.966017,2.512924e-44,1.440911e-41
Prtg,291.208933,3.122386,0.303181,10.298755,7.137914e-25,6.571138e-23
1600025M17Rik,13.248868,3.113350,1.165150,2.672060,7.538721e-03,2.408766e-02
Csf1r,40.235367,3.095060,0.809764,3.822176,1.322791e-04,6.984240e-04
Ncmap,130.989024,3.073138,0.427958,7.180941,6.923321e-13,1.715360e-11
Apobec2,148.226192,3.009267,0.363575,8.276878,1.264471e-16,5.055112e-15
Lrp2,328.008467,2.977783,0.357605,8.327018,8.290400e-17,3.416428e-15
Usp9y,107.896481,2.960169,0.416554,7.106332,1.191672e-12,2.871029e-11
Peg10,21405.927009,2.943272,0.325067,9.054351,1.373823e-19,7.680016e-18
Coch,164.787698,2.942926,0.372237,7.906048,2.656895e-15,9.338217e-14
Ifi27,1051.789342,2.932164,0.176831,16.581774,9.440058e-62,1.353232e-58
Pramef12,2121.974549,2.882272,0.404946,7.117670,1.097671e-12,2.663744e-11

## Differential expression in MEFs

In [64]:
mef_samples = metadata_df.query("experiment == \"MEF\"").index.to_list()
print(metadata_df.loc[mef_samples])

               day experiment group replicate  batch
sample
MEF_BFP_Rep1     0        MEF   BFP         1      1
MEF_BFP_Rep2     0        MEF   BFP         2      1
MEF_BFP_Rep3     0        MEF   BFP         3      1
MEF_Hic2_Rep1    0        MEF  Hic2         1      1
MEF_Hic2_Rep2    0        MEF  Hic2         2      1
MEF_Hic2_Rep3    0        MEF  Hic2         3      1

In [65]:
# Fit differential expression model

inference = pydeseq2.dds.DefaultInference(n_cpus=8)
dds = pydeseq2.dds.DeseqDataSet(
    counts=bulk_counts.loc[mef_samples, common_genes],
    metadata=metadata_df.loc[mef_samples],
    design="~group",
    refit_cooks=True,
    inference=inference
)

dds.deseq2()

# Calculate statistics
stat_results = pydeseq2.ds.DeseqStats(dds, contrast=["group", "Hic2", "BFP"], inference=inference)
stat_results.summary()

Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.20 seconds.

Fitting dispersion trend curve...
... done in 0.04 seconds.

Fitting MAP dispersions...
... done in 0.24 seconds.

Fitting LFCs...
... done in 0.14 seconds.

Calculating cook's distance...
... done in 0.00 seconds.

Replacing 0 outlier genes.

Running Wald tests...

Log2 fold change & Wald test p-value: group Hic2 vs BFP
                  baseMean  log2FoldChange     lfcSE      stat        pvalue  \
0610040J01Rik    21.265536       -0.403483  0.497757 -0.810603  4.175938e-01
1110008L16Rik   324.582825        0.239663  0.203499  1.177710  2.389124e-01
1110038B12Rik  1234.185766        0.028475  0.202006  0.140961  8.879011e-01
1500009L16Rik   289.683772        0.891146  0.162259  5.492105  3.971718e-08
1500015O10Rik    71.716345       -1.477486  0.287123 -5.145826  2.663468e-07
...                    ...             ...       ...       ...           ...
Zmiz1          6521.568472        0.028579  0.138333  0.206597  8.363244e-01
Zp3               0.667739       -2.910684  3.596741 -0.809256  4.183680e-01
Zscan4a           0.000000             NaN       NaN       NaN           NaN
Zscan4c           0.000000             NaN       NaN       NaN           NaN
Zscan4e           0.000000             NaN       NaN       NaN           NaN

                       padj
0610040J01Rik  6.072510e-01
1110008L16Rik  4.144157e-01
1110038B12Rik  9.430233e-01
1500009L16Rik  9.174892e-07
1500015O10Rik  4.944416e-06
...                     ...
Zmiz1          9.128375e-01
Zp3                     NaN
Zscan4a                 NaN
Zscan4c                 NaN
Zscan4e                 NaN

[1942 rows x 6 columns]

... done in 0.11 seconds.

In [66]:
# Whether genes of interest are up- or downregulated

genes_of_interest = ["Krtdap", "Krt8", "Krt14", "Nanog", "Tet1", "Cdh1", "Ovol1", "Atf3", "Hic2", "Sall4", "Shisa8", 'Hmgb3', 'Hoxa7', 'Tlx2', 'Zbtb7c', 'Klf2', 'Mycn', 'Rest', 'Tcf7l1', 'Tcf7l2', 'Tfcp2l1', 'Tsc22d1',
       'Zfp42', 'Zic2']
stat_results.results_df.loc[genes_of_interest].sort_values("padj")

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
Hic2,3534.500069,4.469488,0.174119,25.669161,2.583999e-145,4.509078e-142
Krtdap,57.269042,2.305351,0.457112,5.043291,4.575935e-07,7.677891e-06
Zic2,314.603117,0.660156,0.176438,3.741579,1.828678e-04,1.477334e-03
Tcf7l2,1461.158516,0.411018,0.150840,2.724854,6.432983e-03,2.679130e-02
Hoxa7,806.661901,0.347961,0.135321,2.571375,1.012956e-02,3.859406e-02
Tet1,275.564610,0.472414,0.190623,2.478264,1.320234e-02,4.689391e-02
Zbtb7c,124.670887,-0.638847,0.262957,-2.429475,1.512072e-02,5.183822e-02
Klf2,196.442771,-0.859362,0.378279,-2.271767,2.310061e-02,7.276276e-02
Nanog,12.499910,1.211845,0.582080,2.081924,3.734944e-02,1.045203e-01
Sall4,3.086663,2.999819,1.444811,2.076271,3.786889e-02,1.053927e-01
Tfcp2l1,51.991721,-0.552028,0.295294,-1.869417,6.156486e-02,1.526004e-01
Krt14,8.036087,-1.151215,0.807933,-1.424889,1.541893e-01,3.033375e-01
Tcf7l1,1334.422051,0.255627,0.184698,1.384022,1.663516e-01,3.218222e-01
Hmgb3,1384.007209,0.229583,0.172175,1.333433,1.823896e-01,3.451535e-01
Cdh1,4.630196,-1.186150,0.912306,-1.300167,1.935436e-01,3.618404e-01
Mycn,496.409316,-0.169110,0.202020,-0.837098,4.025375e-01,5.917675e-01
Shisa8,9.915387,0.356759,0.637276,0.559819,5.756031e-01,7.385496e-01
Atf3,200.198133,-0.061719,0.187287,-0.329542,7.417461e-01,8.473340e-01
Zfp42,9.307759,0.266531,0.812171,0.328171,7.427822e-01,8.476925e-01
Tsc22d1,10098.536833,-0.015511,0.101388,-0.152981,8.784133e-01,9.397037e-01
Rest,3211.145221,-0.011507,0.109141,-0.105436,9.160296e-01,9.623550e-01
Krt8,105.808071,-0.004779,0.557709,-0.008568,9.931637e-01,9.963087e-01
Ovol1,0.328191,-1.890241,4.330183,-0.436527,6.624546e-01,NaN
Tlx2,0.928365,-0.233589,2.056549,-0.113583,9.095685e-01,NaN

In [67]:
# Higher expression in control

stat_results.results_df.query("padj < 0.05 and log2FoldChange < 0").sort_values("log2FoldChange").head(50)

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
Chac1,86.435946,-3.177753,0.301851,-10.527550,6.449088e-26,1.125366e-23
Lyz2,19.130831,-2.740876,0.714613,-3.835471,1.253237e-04,1.061601e-03
F5,363.014411,-2.648490,0.453023,-5.846260,5.027480e-09,1.438189e-07
S100a4,4789.558842,-2.458065,0.155282,-15.829698,1.941495e-56,1.693954e-53
Tnmd,20.900485,-2.438697,0.721062,-3.382090,7.193650e-04,4.446867e-03
Lgals7,13.455553,-2.269549,0.680326,-3.335971,8.500207e-04,5.079747e-03
Gdf15,83.102744,-2.232503,0.425322,-5.248976,1.529467e-07,3.103395e-06
Sncg,1073.423977,-2.214171,0.262866,-8.423207,3.663174e-17,3.760140e-15
Mmp13,412.721768,-2.211962,0.236938,-9.335597,1.004238e-20,1.347996e-18
9530053A07Rik,41.139792,-2.187889,0.402724,-5.432725,5.549982e-08,1.181063e-06
Cbr2,57.546357,-2.148961,0.447794,-4.798997,1.594618e-06,2.244039e-05
Fmod,152.701150,-2.116188,0.319666,-6.620004,3.591903e-11,1.694019e-09
Cryab,1033.415325,-2.093006,0.352768,-5.933087,2.972907e-09,9.101269e-08
Ly6a,4305.287315,-2.089439,0.186675,-11.192942,4.415360e-29,1.540961e-26
Kif1a,1195.074256,-2.038704,0.196200,-10.390963,2.725878e-25,4.324234e-23
Cnn1,948.076871,-1.962919,0.410555,-4.781137,1.743066e-06,2.433321e-05
Wfdc2,57.000960,-1.886828,0.611658,-3.084774,2.037066e-03,1.009852e-02
Mapk13,277.793789,-1.880311,0.274829,-6.841743,7.823552e-12,4.137000e-10
Ptp4a3,686.120124,-1.877751,0.159026,-11.807859,3.555002e-32,2.067826e-29
Rarres1,53.605987,-1.874152,0.415882,-4.506447,6.592210e-06,7.879046e-05
Pcp4l1,249.879723,-1.798957,0.166222,-10.822595,2.690498e-27,5.216578e-25
Laptm5,12.173974,-1.797737,0.566941,-3.170944,1.519442e-03,8.183416e-03
Plek2,62.867613,-1.781664,0.421089,-4.231092,2.325591e-05,2.430033e-04
Comp,32.824960,-1.737254,0.575056,-3.021020,2.519250e-03,1.211044e-02
Pkp3,17.526523,-1.730064,0.504538,-3.429009,6.057899e-04,3.830084e-03
Ltbp2,3360.695141,-1.707121,0.227931,-7.489641,6.906219e-14,5.021397e-12
Mgmt,506.240274,-1.697803,0.182951,-9.280079,1.693530e-20,1.970140e-18
Tcea3,74.177213,-1.678534,0.269290,-6.233174,4.570778e-10,1.772446e-08
Ndnf,226.526045,-1.672905,0.367486,-4.552295,5.306395e-06,6.575572e-05
Itgb4,128.815671,-1.670054,0.281672,-5.929077,3.046419e-09,9.165519e-08
Eno3,1254.834223,-1.661247,0.238910,-6.953447,3.564659e-12,2.006558e-10
Fas,439.114620,-1.610378,0.275897,-5.836874,5.318921e-09,1.497019e-07
Prss12,49.465459,-1.609678,0.436986,-3.683591,2.299711e-04,1.807656e-03
Msln,2052.497633,-1.597111,0.407953,-3.914935,9.042850e-05,8.050905e-04
Tmem40,38.835700,-1.583245,0.329821,-4.800322,1.584105e-06,2.244039e-05
Itgbl1,270.248878,-1.582237,0.177325,-8.922787,4.546975e-19,4.959045e-17
Gldn,163.427642,-1.557888,0.330322,-4.716276,2.402007e-06,3.308311e-05
Anxa8,4609.697207,-1.553378,0.152487,-10.186986,2.266836e-24,3.296358e-22
Ddit4l,605.771897,-1.552575,0.203525,-7.628414,2.376592e-14,1.803110e-12
Cadps,22.653154,-1.505196,0.484594,-3.106096,1.895753e-03,9.533399e-03
Angptl2,4123.465620,-1.501269,0.132435,-11.335886,8.714549e-30,3.801722e-27
1500015O10Rik,71.716345,-1.477486,0.287123,-5.145826,2.663468e-07,4.944416e-06
Gm2115,9382.709231,-1.476043,0.136188,-10.838239,2.267956e-27,4.946980e-25
Col2a1,566.117571,-1.469449,0.463688,-3.169048,1.529389e-03,8.211645e-03
Prph,270.770053,-1.441846,0.237412,-6.073170,1.254098e-09,4.376802e-08
Notum,92.866918,-1.431450,0.274533,-5.214120,1.846921e-07,3.621209e-06
Gda,3411.254776,-1.423579,0.248739,-5.723193,1.045401e-08,2.722724e-07
Pla2g16,75.923905,-1.399187,0.248841,-5.622805,1.878818e-08,4.751504e-07
Ppl,241.330775,-1.397105,0.169943,-8.221034,2.017564e-16,1.852973e-14
Kcnn4,380.037774,-1.392488,0.453331,-3.071684,2.128551e-03,1.049243e-02

In [68]:
# Higher expression with Hic2

stat_results.results_df.query("padj < 0.05 and log2FoldChange > 0").sort_values("log2FoldChange", ascending=False).head(50)

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
Ifi27l2a,44.558107,5.176916,0.949596,5.451705,4.988906e-08,1.088205e-06
Hic2,3534.500069,4.469488,0.174119,25.669161,2.583999e-145,4.509078e-142
Isg15,1792.130563,4.261802,0.774550,5.502295,3.748793e-08,8.840059e-07
Oasl2,1080.804964,4.112931,1.144824,3.592631,3.273561e-04,2.370276e-03
Ifi44,1395.079071,4.012075,0.730660,5.491031,3.995942e-08,9.174892e-07
Ap3b2,13.942344,3.912476,1.024189,3.820071,1.334132e-04,1.119260e-03
Rtp4,527.356070,3.723732,0.612262,6.081921,1.187508e-09,4.228984e-08
1600025M17Rik,4.677879,3.687203,1.371406,2.688630,7.174598e-03,2.918339e-02
Nts,8.900478,3.560124,1.001310,3.555464,3.773119e-04,2.644214e-03
Usp18,679.254187,3.545879,0.778479,4.554884,5.241458e-06,6.575572e-05
Bst2,1814.514993,3.491092,0.553141,6.311392,2.765363e-10,1.176966e-08
Fgfbp1,47.957286,3.401177,0.562954,6.041656,1.525403e-09,4.929312e-08
Sp100,98.528447,3.399576,0.672652,5.053987,4.326808e-07,7.378276e-06
Ddx60,190.840716,3.338399,0.911723,3.661636,2.506094e-04,1.926491e-03
3830417A13Rik,10.264646,3.137530,0.899653,3.487490,4.875776e-04,3.222814e-03
Mx2,292.492822,3.063132,0.740062,4.139023,3.487887e-05,3.538583e-04
Gbp3,938.607944,3.057261,0.652770,4.683516,2.819957e-06,3.756355e-05
Cxcl11,6.080221,2.998053,1.059159,2.830598,4.646106e-03,2.031944e-02
Ifit3,1359.081750,2.790520,0.780979,3.573107,3.527709e-04,2.512593e-03
Ifit1,1890.819604,2.762710,0.763484,3.618557,2.962502e-04,2.207905e-03
Oasl1,250.090780,2.743389,0.539258,5.087338,3.631242e-07,6.400523e-06
Cmpk2,354.159517,2.722857,0.548093,4.967871,6.769202e-07,1.083693e-05
Xaf1,1226.135139,2.719060,0.597969,4.547162,5.437425e-06,6.681906e-05
Ccl5,29.179578,2.600587,0.487901,5.330153,9.813031e-08,2.014558e-06
Ifit3b,505.844406,2.597846,0.708170,3.668394,2.440787e-04,1.884590e-03
Ifit1bl1,76.061648,2.499732,0.424399,5.890046,3.860876e-09,1.122871e-07
Ifih1,657.995543,2.480804,0.458526,5.410392,6.288683e-08,1.306399e-06
Gbp7,962.281556,2.451520,0.607735,4.033862,5.486755e-05,5.175345e-04
Trim30a,96.974281,2.439903,0.771869,3.161034,1.572099e-03,8.363760e-03
Bex1,636.357488,2.387513,0.350660,6.808627,9.853467e-12,5.057147e-10
Zbp1,129.479986,2.324011,0.810975,2.865699,4.160902e-03,1.833529e-02
Krtdap,57.269042,2.305351,0.457112,5.043291,4.575935e-07,7.677891e-06
Gbp5,21.920359,2.269219,0.821338,2.762832,5.730222e-03,2.415275e-02
Rsad2,355.685507,2.235349,0.735198,3.040472,2.362075e-03,1.144950e-02
Slfn5,1086.655733,2.214009,0.547086,4.046914,5.189741e-05,4.948687e-04
Dhx58,140.368395,2.192107,0.558995,3.921517,8.799339e-05,7.894941e-04
Stmn4,28.552169,2.175423,0.504368,4.313164,1.609344e-05,1.754979e-04
Dtx1,8.947558,2.088107,0.849535,2.457940,1.397366e-02,4.886581e-02
Phf11d,97.354557,2.078611,0.614607,3.382016,7.195592e-04,4.446867e-03
Parp14,711.711740,2.064667,0.598976,3.446997,5.668552e-04,3.623305e-03
Mdk,1602.808980,1.997564,0.309926,6.445296,1.153746e-10,5.162276e-09
Fbxo15,17.683414,1.977122,0.599373,3.298652,9.715043e-04,5.650917e-03
Lmo2,10.868253,1.974311,0.706816,2.793244,5.218226e-03,2.237298e-02
Iigp1,701.083510,1.946552,0.725606,2.682656,7.304001e-03,2.964065e-02
Rnf213,7926.423697,1.926929,0.408751,4.714191,2.426727e-06,3.308311e-05
Lgals3bp,2562.326605,1.921516,0.454400,4.228685,2.350616e-05,2.441562e-04
Cxcl10,194.148842,1.913854,0.582968,3.282950,1.027269e-03,5.916119e-03
Snhg11,41.654531,1.847861,0.578392,3.194824,1.399162e-03,7.629805e-03
Rbp4,261.306218,1.822823,0.167420,10.887738,1.318755e-27,3.287468e-25
Apol9b,62.806692,1.819462,0.652236,2.789576,5.277717e-03,2.257259e-02

## Differential expression in ESCs

In [75]:
esc_samples = metadata_df.query("experiment == \"ESC\"").index.to_list()
print(metadata_df.loc[esc_samples])

                    day experiment      group replicate  batch
sample
ESC_BFP_Rep1          0        ESC        BFP         1      2
ESC_BFP_Rep2          0        ESC        BFP         2      2
ESC_BFP_Rep3          0        ESC        BFP         3      2
ESC_Hic2-gRNA_Rep1    0        ESC  Hic2-gRNA         1      2
ESC_Hic2-gRNA_Rep2    0        ESC  Hic2-gRNA         2      2
ESC_Hic2-gRNA_Rep3    0        ESC  Hic2-gRNA         3      2
ESC_Zeo-gRNA_Rep1     0        ESC   Zeo-gRNA         1      2
ESC_Zeo-gRNA_Rep2     0        ESC   Zeo-gRNA         2      2
ESC_Zeo-gRNA_Rep3     0        ESC   Zeo-gRNA         3      2

In [76]:
# Fit differential expression model

inference = pydeseq2.dds.DefaultInference(n_cpus=8)
dds = pydeseq2.dds.DeseqDataSet(
    counts=bulk_counts.loc[esc_samples, common_genes],
    metadata=metadata_df.loc[esc_samples],
    design="~group",
    refit_cooks=True,
    inference=inference
)

dds.deseq2()

# Calculate statistics
stat_results = pydeseq2.ds.DeseqStats(dds, contrast=["group", "Hic2-gRNA", "Zeo-gRNA"], inference=inference)
stat_results.summary()

Fitting size factors...
... done in 0.00 seconds.

Fitting dispersions...

Using None as control genes, passed at DeseqDataSet initialization

... done in 0.20 seconds.

Fitting dispersion trend curve...
... done in 0.04 seconds.

Fitting MAP dispersions...
... done in 0.24 seconds.

Fitting LFCs...
... done in 0.17 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 0 outlier genes.

Running Wald tests...

Log2 fold change & Wald test p-value: group Hic2-gRNA vs Zeo-gRNA
                  baseMean  log2FoldChange     lfcSE      stat        pvalue  \
0610040J01Rik    51.921452        0.527384  0.290160  1.817561  6.913131e-02
1110008L16Rik   722.601741       -0.083498  0.148153 -0.563595  5.730299e-01
1110038B12Rik  1389.865872       -0.755943  0.127443 -5.931615  2.999698e-09
1500009L16Rik   154.560178       -0.125743  0.267273 -0.470467  6.380211e-01
1500015O10Rik     5.207505        3.085208  1.198319  2.574613  1.003523e-02
...                    ...             ...       ...       ...           ...
Zmiz1           785.722730        1.124409  0.246163  4.567739  4.930129e-06
Zp3              97.979012       -0.822176  0.307450 -2.674180  7.491220e-03
Zscan4a         177.497754        0.543751  0.570026  0.953905  3.401316e-01
Zscan4c         205.143733        0.600216  0.857092  0.700293  4.837443e-01
Zscan4e         210.310155        0.010496  0.606083  0.017317  9.861835e-01

                       padj
0610040J01Rik  1.219341e-01
1110008L16Rik  6.859657e-01
1110038B12Rik  1.945293e-08
1500009L16Rik  7.416351e-01
1500015O10Rik  2.219330e-02
...                     ...
Zmiz1          2.044344e-05
Zp3            1.716116e-02
Zscan4a        4.580226e-01
Zscan4c        6.099846e-01
Zscan4e        9.930919e-01

[1942 rows x 6 columns]

... done in 0.11 seconds.

In [77]:
# Whether genes of interest are up- or downregulated

genes_of_interest = ["Krtdap", "Krt8", "Krt14", "Nanog", "Tet1", "Cdh1", "Ovol1", "Atf3", "Hic2", "Sall4", "Shisa8", 'Hmgb3', 'Hoxa7', 'Tlx2', 'Zbtb7c', 'Klf2', 'Mycn', 'Rest', 'Tcf7l1', 'Tcf7l2', 'Tfcp2l1', 'Tsc22d1',
       'Zfp42', 'Zic2']
stat_results.results_df.loc[genes_of_interest].sort_values("padj")

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
Nanog,4052.544730,-2.439410,0.090728,-26.886934,3.122445e-159,2.693109e-156
Tfcp2l1,7033.005586,-2.041081,0.153019,-13.338782,1.376903e-40,7.917192e-39
Tet1,12266.356463,-1.048578,0.088047,-11.909249,1.059267e-32,4.060525e-31
Zfp42,12778.669838,-1.464963,0.128270,-11.420961,3.285796e-30,1.111372e-28
Atf3,46.400934,2.926515,0.336155,8.705852,3.151986e-18,4.647159e-17
Rest,6352.040976,-0.464189,0.076798,-6.044300,1.500605e-09,1.023140e-08
Zic2,1306.400655,1.908681,0.318025,6.001669,1.952993e-09,1.305780e-08
Mycn,4152.026270,1.605242,0.297809,5.390168,7.039168e-08,3.891848e-07
Hoxa7,13.261125,-2.789823,0.685144,-4.071877,4.663576e-05,1.665563e-04
Hmgb3,626.869728,0.439919,0.110975,3.964125,7.366551e-05,2.536387e-04
Hic2,3313.520166,0.420721,0.110543,3.805954,1.412587e-04,4.606263e-04
Tcf7l1,2084.262946,-0.484475,0.157901,-3.068215,2.153415e-03,5.611239e-03
Klf2,4961.094181,-0.280519,0.116275,-2.412551,1.584134e-02,3.352921e-02
Cdh1,7358.236893,0.384184,0.186227,2.062991,3.911352e-02,7.422532e-02
Tsc22d1,4150.446132,-0.545665,0.272372,-2.003382,4.513631e-02,8.381747e-02
Tcf7l2,164.324577,-0.314795,0.173881,-1.810403,7.023334e-02,1.234990e-01
Sall4,6324.193570,-0.222038,0.124365,-1.785375,7.420052e-02,1.292672e-01
Tlx2,1.255591,-2.752973,2.023177,-1.360718,1.736028e-01,2.657186e-01
Krt8,146.331602,-0.300935,0.271983,-1.106448,2.685326e-01,3.793765e-01
Ovol1,11.798808,0.642798,0.586747,1.095528,2.732852e-01,3.842029e-01
Zbtb7c,179.913966,0.200119,0.307518,0.650756,5.152038e-01,6.379946e-01
Shisa8,47.479468,-0.180601,0.332237,-0.543590,5.867234e-01,6.989626e-01
Krt14,5.071906,0.462588,0.872369,0.530266,5.959274e-01,7.084595e-01
Krtdap,0.122014,-1.256345,4.425666,-0.283877,7.765047e-01,NaN

In [78]:
# Higher expression in control

stat_results.results_df.query("padj < 0.05 and log2FoldChange < 0").sort_values("log2FoldChange").head(50)

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
Aox3,15.310374,-7.671577,1.993699,-3.847911,1.191294e-04,3.944303e-04
Nostrin,7.526519,-5.966891,2.024740,-2.946991,3.208825e-03,8.022062e-03
Hand1,6.241400,-5.819437,2.181096,-2.668125,7.627591e-03,1.745039e-02
Msc,323.344069,-5.801899,0.366322,-15.838242,1.694922e-56,2.088386e-54
Nkain4,22.767862,-4.461031,0.727754,-6.129863,8.795458e-10,6.133297e-09
Col3a1,2.609835,-4.351009,1.902813,-2.286619,2.221807e-02,4.498377e-02
Calml4,25.678331,-4.303625,0.804977,-5.346268,8.978636e-08,4.901313e-07
Spink1,28.530931,-4.115843,1.006824,-4.087946,4.352089e-05,1.577175e-04
Nanos3,18.706729,-3.985595,0.659684,-6.041673,1.525243e-09,1.035844e-08
Slc6a1,133.897434,-3.946398,0.349372,-11.295696,1.378086e-29,4.402219e-28
Lgals3,555.466181,-3.943649,0.161051,-24.486976,2.033275e-132,7.014799e-130
Pga5,83.278592,-3.870981,0.487298,-7.943773,1.961220e-15,2.349378e-14
Gjb3,644.603374,-3.863318,0.514409,-7.510201,5.903685e-14,6.445479e-13
Gjb5,193.340261,-3.754406,0.448852,-8.364464,6.038872e-17,8.400850e-16
Serpinb9b,58.712077,-3.746425,0.555115,-6.748914,1.489555e-11,1.253406e-10
Myc,883.743218,-3.686952,0.161470,-22.833730,2.120667e-115,5.225930e-113
Rhox5,889.617226,-3.681821,1.189547,-3.095145,1.967164e-03,5.180700e-03
Mylpf,1200.718409,-3.658107,0.235298,-15.546727,1.674460e-54,1.699085e-52
Serpinb1a,7.360209,-3.433852,0.909648,-3.774924,1.600566e-04,5.131925e-04
Lama1,1451.760391,-3.407589,0.190713,-17.867656,2.106617e-71,3.028262e-69
Ngfr,323.005989,-3.393900,0.239619,-14.163737,1.536028e-45,1.059860e-43
4933402E13Rik,69.390022,-3.253777,0.616610,-5.276879,1.314024e-07,6.931778e-07
Cd200,9.497675,-3.199337,0.942892,-3.393110,6.910376e-04,1.967063e-03
Lrrc15,88.858197,-3.181108,0.425107,-7.483076,7.260280e-14,7.827489e-13
Aard,1081.576929,-3.059327,0.198412,-15.419069,1.218487e-53,1.106258e-51
Fgf17,84.736309,-3.046937,0.437124,-6.970418,3.160009e-12,2.839070e-11
Cubn,34.896230,-3.040321,0.545595,-5.572492,2.511213e-08,1.468421e-07
Nup62cl,400.736130,-3.006489,0.161649,-18.598858,3.282248e-77,5.661878e-75
Fgf7,6.608103,-2.961813,1.032500,-2.868585,4.123126e-03,9.892062e-03
Myl4,86.191247,-2.958761,0.604719,-4.892783,9.941998e-07,4.698616e-06
Igf2,30.509499,-2.943063,0.508850,-5.783749,7.305401e-09,4.616050e-08
Edn1,18.400159,-2.924480,0.649829,-4.500382,6.783156e-06,2.753163e-05
S100a13,18.962119,-2.852678,0.479736,-5.946356,2.741767e-09,1.784735e-08
Hbegf,527.691055,-2.815870,0.358424,-7.856257,3.957811e-15,4.612989e-14
Calcoco2,146.027102,-2.794775,0.309635,-9.026039,1.779978e-19,2.981030e-18
Hoxa7,13.261125,-2.789823,0.685144,-4.071877,4.663576e-05,1.665563e-04
Pros1,1033.923299,-2.749852,0.108176,-25.420146,1.510293e-142,6.513140e-140
Lims2,12.811562,-2.698691,0.837602,-3.221926,1.273322e-03,3.460001e-03
Mras,925.539609,-2.678462,0.371882,-7.202445,5.914217e-13,5.731474e-12
Sfmbt2,571.763277,-2.620143,0.262380,-9.986063,1.754104e-23,3.830163e-22
Ckb,4331.633606,-2.605978,0.237131,-10.989619,4.287312e-28,1.232602e-26
Gata6,34.770100,-2.596419,0.438748,-5.917789,3.262982e-09,2.108107e-08
Spink10,63.674394,-2.591695,0.751519,-3.448609,5.634815e-04,1.625427e-03
Plac8,13.266198,-2.574143,0.592980,-4.341028,1.418176e-05,5.547287e-05
Ass1,3879.041304,-2.572631,0.170403,-15.097311,1.686722e-51,1.385522e-49
Pramel7,8.895186,-2.571143,0.882765,-2.912601,3.584319e-03,8.820185e-03
Hspb1,8232.608557,-2.546582,0.186720,-13.638481,2.364333e-42,1.456598e-40
Cyp2s1,215.950707,-2.542971,0.456144,-5.574924,2.476375e-08,1.452975e-07
Nr0b1,3181.242543,-2.518389,0.091956,-27.386972,3.920601e-165,6.763038e-162
Htra1,84.005990,-2.507922,0.475203,-5.277576,1.309038e-07,6.926656e-07

Interestingly, Myc expression is much lower in control cells

In [79]:
# Higher expression with Hic2

stat_results.results_df.query("padj < 0.05 and log2FoldChange > 0").sort_values("log2FoldChange", ascending=False).head(50)

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
Ms4a4d,20.326466,4.825755,1.246411,3.871721,1.080695e-04,3.612788e-04
Tmem176b,3.612990,4.643747,1.610812,2.882861,3.940807e-03,9.534211e-03
Myl3,2.556719,4.126678,1.713033,2.408989,1.599680e-02,3.381676e-02
Lbp,8.501897,4.060805,0.942797,4.307191,1.653408e-05,6.409277e-05
Igfbp5,6.627575,3.910211,1.232140,3.173512,1.506068e-03,4.040385e-03
Mfap2,9.475300,3.895051,0.923540,4.217523,2.470002e-05,9.323313e-05
4930550L24Rik,3.824585,3.843686,1.625766,2.364231,1.806754e-02,3.763326e-02
Enpp2,73.021343,3.801862,0.648664,5.861068,4.598995e-09,2.938247e-08
Fas,12.493819,3.782708,0.793289,4.768384,1.857093e-06,8.452467e-06
Megf10,6.832699,3.764085,1.113708,3.379777,7.254465e-04,2.059033e-03
Tmem176a,3.415303,3.721117,1.329240,2.799431,5.119274e-03,1.208037e-02
Tnn,4.967490,3.651722,1.184888,3.081913,2.056752e-03,5.391941e-03
Sncaip,19.990312,3.614078,0.567322,6.370419,1.885120e-10,1.451710e-09
Gadd45g,179.447144,3.591850,0.662362,5.422788,5.867646e-08,3.286263e-07
Pamr1,25.032198,3.545825,0.494417,7.171733,7.405444e-13,7.136531e-12
Thsd7a,31.251740,3.490795,0.427064,8.173935,2.984914e-16,3.842520e-15
Xist,123.035651,3.440260,0.394010,8.731412,2.515118e-18,3.740153e-17
Serpinh1,2001.743775,3.424417,0.142343,24.057431,6.979289e-128,2.006546e-125
Kif1a,284.472024,3.415603,0.507888,6.725105,1.754662e-11,1.462218e-10
Col2a1,445.620312,3.333446,0.199740,16.688895,1.578645e-62,2.094740e-60
Tmem119,23.226723,3.256565,0.541821,6.010410,1.850546e-09,1.246950e-08
Mrc1,85.567904,3.254699,0.289683,11.235372,2.733403e-29,8.419858e-28
Lef1,640.757447,3.239324,0.560666,5.777638,7.575670e-09,4.717701e-08
Fat3,53.637405,3.211544,0.507550,6.327538,2.491034e-10,1.884664e-09
Tnfaip2,10.598405,3.204763,0.955618,3.353601,7.976720e-04,2.252020e-03
Pdlim3,56.911598,3.197464,0.356883,8.959418,3.263973e-19,5.262012e-18
Il1r1,41.308515,3.158655,0.358833,8.802571,1.337171e-18,2.078035e-17
Thbs4,27.075050,3.100077,0.570003,5.438707,5.366857e-08,3.015579e-07
Prph,165.129124,3.094314,0.267039,11.587510,4.767907e-31,1.713467e-29
Moxd1,40.642269,3.090040,0.489608,6.311254,2.767836e-10,2.075877e-09
Prss12,5.722434,3.086182,1.171342,2.634741,8.420147e-03,1.906136e-02
1500015O10Rik,5.207505,3.085208,1.198319,2.574613,1.003523e-02,2.219330e-02
Gm5091,134.267960,3.077705,0.306823,10.030889,1.115075e-23,2.466032e-22
Rmst,3.481482,3.055941,1.187344,2.573762,1.005995e-02,2.221948e-02
Miat,61.799087,3.036855,0.404330,7.510830,5.875364e-14,6.445479e-13
Smyd1,263.591485,3.030943,0.246038,12.318998,7.157816e-35,2.939817e-33
Abi3bp,32.390480,2.989693,0.420805,7.104700,1.205842e-12,1.130476e-11
Tspan8,32.895601,2.983974,0.533541,5.592778,2.234649e-08,1.315621e-07
Plek,3.617496,2.977230,1.177496,2.528441,1.145704e-02,2.508533e-02
Myl9,17.992152,2.972003,0.570437,5.210046,1.887938e-07,9.809314e-07
Tshz2,9.440583,2.951325,0.800616,3.686318,2.275216e-04,7.128294e-04
Usp9y,21.801869,2.934090,0.624354,4.699404,2.609216e-06,1.145266e-05
Atf3,46.400934,2.926515,0.336155,8.705852,3.151986e-18,4.647159e-17
Card19,140.936245,2.873938,0.222928,12.891799,5.006226e-38,2.467354e-36
Fbln5,14.143496,2.852325,0.607114,4.698169,2.625040e-06,1.149288e-05
Sox10,28.065909,2.852155,0.569124,5.011479,5.401332e-07,2.669713e-06
Padi4,88.344524,2.782892,0.481524,5.779345,7.499217e-09,4.694506e-08
H2-D1,1339.135914,2.750053,0.105390,26.094164,4.246482e-150,2.441727e-147
Astn1,8.751104,2.697097,0.742293,3.633464,2.796413e-04,8.691552e-04
Car6,19.269485,2.680024,0.682222,3.928375,8.552172e-05,2.927083e-04

# Differential expression with SCVI-tools