In [25]:
import scanpy
import anndata
import matplotlib
from matplotlib import pyplot
import hdf5plugin
import numpy
import scvelo
import seaborn
import pandas
import warnings
import cellrank
import gseapy
import decoupler

In [26]:
# Read input file
working_directory = "RNA Sequencing Data/"

# adata = scanpy.read_h5ad(working_directory + "/velocity_sdevelo.h5ad")

# Or read saved anndata objects
base_name = "cellrank_1.3"
adata = scanpy.read_h5ad(
    working_directory+f"/{base_name} cells.h5ad"
)
dead_end_adata = scanpy.read_h5ad(
    working_directory+f"/{base_name} dead end genes.h5ad"
)
mESC_adata = scanpy.read_h5ad(
    working_directory+f"/{base_name} mESC genes.h5ad"
)
driver_df = pandas.read_csv(
    working_directory+f"{base_name} driver genes.csv",
)
full_driver_df = pandas.read_csv(
    working_directory+f"{base_name} raw driver genes.csv",
)

print(adata)

AnnData object with n_obs × n_vars = 12791 × 2000
    obs: 'barcode', 'batch', 'sample', 'group', 'day', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'initial_size_unspliced', 'initial_size_spliced', 'initial_size', 'n_counts', 'latent_time', 'sde_velocity_self_transition', 'manual_root', 'manual_end', 'sde_velocity_pseudotime', 'macrostates_fwd', 'term_states_fwd', 'term_states_fwd_probs', 'init_states_fwd', 'init_states_fwd_probs', 'clusters_gradients', 'fate_probabilities_Day 12 Control', 'fate_probabilities_mESC'
    var: 'ensemble_ids', 'gene_symbol', 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'gene_count_corr', 'means', 'dispersions', 'dispersions_norm', 'highly_variable', 'fit_alpha', 'fit_beta', 'fit_gamma', 'fit_t_', 'fit_sigma_1', 'fit_sigma_2'
    uns: 'T_fwd_params', 'clusters_gradients_colors', 'coarse_fwd', 'eigendecomposition_fwd', 'init_states_fwd_colors', 'lineage_Day 12 Control_trend', 'lineage_mESC_trend', 'log1p', 'macrostates_fwd_colors', 'neighbors', 'pca', 'sample_colors', 'schur_matrix_fwd', 'sde_velocity_graph', 'sde_velocity_graph_neg', 'sde_velocity_params', 'term_states_fwd_colors'
    obsm: 'T_fwd_fdl', 'X_fdl', 'X_pca', 'X_umap', 'init_states_fwd_memberships', 'lineages_fwd', 'macrostates_fwd_memberships', 'schur_vectors_fwd', 'sde_velocity_fdl', 'term_states_fwd_memberships'
    varm: 'PCs', 'terminal_lineage_drivers'
    layers: 'Ms', 'Mu', 'ambiguous', 'matrix', 'pred_s', 'pred_u', 'sde_velocity', 'spliced', 'unspliced'
    obsp: 'connectivities', 'distances'

In [5]:
# Show all possible libraries
names = gseapy.get_library_name(organism="Mouse")
print(names)

['ARCHS4_Cell-lines', 'ARCHS4_IDG_Coexp', 'ARCHS4_Kinases_Coexp', 'ARCHS4_TFs_Coexp', 'ARCHS4_Tissues', 'Achilles_fitness_decrease', 'Achilles_fitness_increase', 'Aging_Perturbations_from_GEO_down', 'Aging_Perturbations_from_GEO_up', 'Allen_Brain_Atlas_10x_scRNA_2021', 'Allen_Brain_Atlas_down', 'Allen_Brain_Atlas_up', 'Azimuth_2023', 'Azimuth_Cell_Types_2021', 'BioCarta_2013', 'BioCarta_2015', 'BioCarta_2016', 'BioPlanet_2019', 'BioPlex_2017', 'CCLE_Proteomics_2020', 'CM4AI_U2OS_Protein_Localization_Assemblies', 'COMPARTMENTS_Curated_2025', 'COMPARTMENTS_Experimental_2025', 'CORUM', 'COVID-19_Related_Gene_Sets', 'COVID-19_Related_Gene_Sets_2021', 'Cancer_Cell_Line_Encyclopedia', 'Carcinogenome', 'CellMarker_2024', 'CellMarker_Augmented_2021', 'ChEA_2013', 'ChEA_2015', 'ChEA_2016', 'ChEA_2022', 'Chromosome_Location', 'Chromosome_Location_hg19', 'ClinVar_2019', 'ClinVar_2025', 'DGIdb_Drug_Targets_2024', 'DSigDB', 'Data_Acquisition_Method_Most_Popular_Genes', 'DepMap_CRISPR_GeneDependency_CellLines_2023', 'DepMap_WG_CRISPR_Screens_Broad_CellLines_2019', 'DepMap_WG_CRISPR_Screens_Sanger_CellLines_2019', 'Descartes_Cell_Types_and_Tissue_2021', 'Diabetes_Perturbations_GEO_2022', 'DisGeNET', 'Disease_Perturbations_from_GEO_down', 'Disease_Perturbations_from_GEO_up', 'Disease_Signatures_from_GEO_down_2014', 'Disease_Signatures_from_GEO_up_2014', 'DrugMatrix', 'Drug_Perturbations_from_GEO_2014', 'Drug_Perturbations_from_GEO_down', 'Drug_Perturbations_from_GEO_up', 'ENCODE_Histone_Modifications_2013', 'ENCODE_Histone_Modifications_2015', 'ENCODE_TF_ChIP-seq_2014', 'ENCODE_TF_ChIP-seq_2015', 'ENCODE_and_ChEA_Consensus_TFs_from_ChIP-X', 'ESCAPE', 'Elsevier_Pathway_Collection', 'Enrichr_Libraries_Most_Popular_Genes', 'Enrichr_Submissions_TF-Gene_Coocurrence', 'Enrichr_Users_Contributed_Lists_2020', 'Epigenomics_Roadmap_HM_ChIP-seq', 'FANTOM6_lncRNA_KD_DEGs', 'GO_Biological_Process_2021', 'GO_Biological_Process_2023', 'GO_Biological_Process_2025', 'GO_Cellular_Component_2021', 'GO_Cellular_Component_2023', 'GO_Cellular_Component_2025', 'GO_Molecular_Function_2021', 'GO_Molecular_Function_2023', 'GO_Molecular_Function_2025', 'GTEx_Aging_Signatures_2021', 'GTEx_Tissue_Expression_Down', 'GTEx_Tissue_Expression_Up', 'GTEx_Tissues_V8_2023', 'GWAS_Catalog_2019', 'GWAS_Catalog_2023', 'GWAS_Catalog_2025', 'GeDiPNet_2023', 'GeneSigDB', 'Gene_Perturbations_from_GEO_down', 'Gene_Perturbations_from_GEO_up', 'Genes_Associated_with_NIH_Grants', 'Genome_Browser_PWMs', 'GlyGen_Glycosylated_Proteins_2022', 'HDSigDB_Human_2021', 'HDSigDB_Mouse_2021', 'HMDB_Metabolites', 'HMS_LINCS_KinomeScan', 'HomoloGene', 'HuBMAP_ASCT_plus_B_augmented_w_RNAseq_Coexpression', 'HuBMAP_ASCTplusB_augmented_2022', 'HumanCyc_2015', 'HumanCyc_2016', 'Human_Gene_Atlas', 'Human_Phenotype_Ontology', 'IDG_Drug_Targets_2022', 'InterPro_Domains_2019', 'JASPAR_PWM_Human_2025', 'JASPAR_PWM_Mouse_2025', 'Jensen_COMPARTMENTS', 'Jensen_DISEASES', 'Jensen_DISEASES_Curated_2025', 'Jensen_DISEASES_Experimental_2025', 'Jensen_TISSUES', 'KEA_2013', 'KEA_2015', 'KEGG_2013', 'KEGG_2015', 'KEGG_2016', 'KEGG_2019_Human', 'KEGG_2019_Mouse', 'KEGG_2021_Human', 'KEGG_2026', 'KOMP2_Mouse_Phenotypes_2022', 'Kinase_Perturbations_from_GEO_down', 'Kinase_Perturbations_from_GEO_up', 'L1000_Kinase_and_GPCR_Perturbations_down', 'L1000_Kinase_and_GPCR_Perturbations_up', 'LINCS_L1000_CRISPR_KO_Consensus_Sigs', 'LINCS_L1000_Chem_Pert_Consensus_Sigs', 'LINCS_L1000_Chem_Pert_down', 'LINCS_L1000_Chem_Pert_up', 'LINCS_L1000_Ligand_Perturbations_down', 'LINCS_L1000_Ligand_Perturbations_up', 'Ligand_Perturbations_from_GEO_down', 'Ligand_Perturbations_from_GEO_up', 'MAGMA_Drugs_and_Diseases', 'MAGNET_2023', 'MCF7_Perturbations_from_GEO_down', 'MCF7_Perturbations_from_GEO_up', 'MGI_Mammalian_Phenotype_Level_4_2021', 'MGI_Mammalian_Phenotype_Level_4_2024', 'MSigDB_Computational', 'MSigDB_Hallmark_2020', 'MSigDB_Oncogenic_Signatures', 'Metabolomics_Workbench_Metabolites_2022', 'Microbe_Perturbations_from_GEO_down', 'Microbe_Perturbations_from_GEO_up', 'MoTrPAC_2023', 'Mouse_Gene_Atlas', 'NCI-60_Cancer_Cell_Lines', 'NCI-Nature_2016', 'NIBR_DRUGseq_2025_down', 'NIBR_DRUGseq_2025_up', 'NURSA_Human_Endogenous_Complexome', 'OMIM_Disease', 'OMIM_Expanded', 'Old_CMAP_down', 'Old_CMAP_up', 'Orphanet_Augmented_2021', 'PFOCR_Pathways_2023', 'PPI_Hub_Proteins', 'PanglaoDB_Augmented_2021', 'Panther_2015', 'Panther_2016', 'PerturbAtlas', 'PerturbAtlas_MouseGenePerturbationSigs', 'PerturbSeq_ReplogleK562', 'PerturbSeq_ReplogleRPE1', 'Pfam_Domains_2019', 'Pfam_InterPro_Domains', 'PheWeb_2019', 'PhenGenI_Association_2021', 'Phosphatase_Substrates_from_DEPOD', 'ProteomicsDB_2020', 'Proteomics_Drug_Atlas_2023', 'RNA-Seq_Disease_Gene_and_Drug_Signatures_from_GEO', 'Rare_Diseases_AutoRIF_ARCHS4_Predictions', 'Rare_Diseases_AutoRIF_Gene_Lists', 'Rare_Diseases_GeneRIF_ARCHS4_Predictions', 'Rare_Diseases_GeneRIF_Gene_Lists', 'Reactome_2022', 'Reactome_Pathways_2024', 'RummaGEO_DrugPerturbations_2025', 'RummaGEO_GenePerturbations_2025', 'Rummagene_kinases', 'Rummagene_signatures', 'Rummagene_transcription_factors', 'SILAC_Phosphoproteomics', 'Sciplex_Drug_Perturbation_Signatures_2025', 'SubCell_BarCode', 'SynGO_2022', 'SynGO_2024', 'SysMyo_Muscle_Gene_Sets', 'TF-LOF_Expression_from_GEO', 'TF_Perturbations_Followed_by_Expression', 'TG_GATES_2020', 'TISSUES_Curated_2025', 'TISSUES_Experimental_2025', 'TRANSFAC_and_JASPAR_PWMs', 'TRRUST_Transcription_Factors_2019', 'Table_Mining_of_CRISPR_Studies', 'Tabula_Muris', 'Tabula_Sapiens', 'TargetScan_microRNA', 'TargetScan_microRNA_2017', 'The_Kinase_Library_2023', 'The_Kinase_Library_2024', 'Tissue_Protein_Expression_from_Human_Proteome_Map', 'Tissue_Protein_Expression_from_ProteomicsDB', 'Transcription_Factor_PPIs', 'UK_Biobank_GWAS_v1', 'Virus-Host_PPI_P-HIPSTer_2020', 'VirusMINT', 'Virus_Perturbations_from_GEO_down', 'Virus_Perturbations_from_GEO_up', 'WikiPathway_2021_Human', 'WikiPathway_2023_Human', 'WikiPathways_2013', 'WikiPathways_2015', 'WikiPathways_2016', 'WikiPathways_2019_Human', 'WikiPathways_2019_Mouse', 'WikiPathways_2024_Human', 'WikiPathways_2024_Mouse', 'dbGaP', 'huMAP', 'lncHUB_lncRNA_Co-Expression', 'miRTarBase_2017']

## GO pathway

In [ ]:
rank_data = driver_df[["gene_names", "Day 12 Control_corr"]].sort_values('Day 12 Control_corr', ascending=False).dropna()

# Run GSEA Prerank
pre_res = gseapy.prerank(
    rnk=rank_data, 
    gene_sets="GO_Biological_Process_2025",
    threads=16,
    min_size=5,
    max_size=1000,
    permutation_num=2000
)

2026-01-27 16:58:38,720 [WARNING] Duplicated values found in preranked stats: 0.15% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

In [93]:
# Enriched in dead end

pre_res.res2d.sort_values("NES", ascending=False).head(20)[["Term", "ES", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]] # Top Day 12

,Term,ES,NES,NOM p-val,FWER p-val,FDR q-val
0,Epidermis Development (GO:0008544),0.651482,1.832776,0.002571,0.4625,0.674046
1,Regulation of Trans-Synaptic Signaling (GO:009...,0.794153,1.80454,0.001188,0.591,0.505759
2,Regulation of Glycolytic Process (GO:0006110),0.816355,1.757079,0.004884,0.7985,0.661015
3,Proteolysis Involved in Protein Catabolic Proc...,0.743789,1.755606,0.006105,0.802,0.505198
7,Antigen Processing and Presentation of Exogeno...,0.858336,1.71164,0.010753,0.933,0.504058
5,Antigen Processing and Presentation of Peptide...,0.858336,1.71164,0.010753,0.933,0.504058
6,Antigen Processing and Presentation of Exogeno...,0.858336,1.71164,0.010753,0.933,0.504058
10,Negative Regulation of Myeloid Leukocyte Diffe...,0.761698,1.639885,0.025862,0.993,0.978322
11,Positive Regulation of Purine Nucleotide Catab...,0.871028,1.638279,0.009423,0.993,0.796093
12,Positive Regulation of Glycolytic Process (GO:...,0.871028,1.638279,0.009423,0.993,0.796093
14,Regulation of Stress-Activated MAPK Cascade (G...,0.861747,1.633124,0.012896,0.994,0.762285
19,Negative Regulation of Carbohydrate Metabolic ...,0.847317,1.578296,0.022093,1.0,1.0
20,Protein Catabolic Process (GO:0030163),0.603456,1.575061,0.023839,1.0,1.0
21,Protein Tetramerization (GO:0051262),0.834981,1.561109,0.026997,1.0,1.0
22,Antigen Processing and Presentation of Peptide...,0.844698,1.558732,0.021251,1.0,1.0
23,Positive Regulation of Sprouting Angiogenesis ...,0.736311,1.557553,0.042067,1.0,1.0
25,Positive Regulation of Apoptotic Signaling Pat...,0.654017,1.544717,0.03744,1.0,1.0
28,Peptide Hormone Processing (GO:0016486),0.742655,1.529107,0.059929,1.0,1.0
33,Regulation of Mesenchymal Cell Proliferation (...,0.81018,1.516543,0.037759,1.0,1.0
34,Positive Regulation of ATP Metabolic Process (...,0.765292,1.511824,0.051251,1.0,1.0

In [94]:
# Enriched in iPSC path
pre_res.res2d.sort_values('NES', ascending=True).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]  # Top mESC

,Term,NES,NOM p-val,FWER p-val,FDR q-val
4,Chromatin Organization (GO:0006325),-1.740139,0.003165,0.505,0.951183
8,Protein Polyubiquitination (GO:0000209),-1.69158,0.002494,0.7595,1.0
9,DNA Metabolic Process (GO:0006259),-1.652493,0.011735,0.9115,1.0
13,Male Meiotic Nuclear Division (GO:0007140),-1.636862,0.000833,0.9515,1.0
15,Transcription by RNA Polymerase II (GO:0006366),-1.622618,0.005882,0.971,1.0
16,Transcription Initiation-Coupled Chromatin Rem...,-1.600657,0.006071,0.9885,1.0
17,Regulation of Viral Genome Replication (GO:004...,-1.594757,0.017964,0.99,1.0
18,Regulation of Insulin Secretion (GO:0050796),-1.592842,0.008584,0.9915,1.0
24,Visual System Development (GO:0150063),-1.552395,0.006809,0.9995,1.0
26,Negative Regulation of Bone Remodeling (GO:004...,-1.538782,0.006843,1.0,1.0
27,Female Gamete Generation (GO:0007292),-1.530513,0.023009,1.0,1.0
29,Defense Response to Virus (GO:0051607),-1.525263,0.019716,1.0,1.0
30,Phospholipid Transport (GO:0015914),-1.522557,0.024452,1.0,1.0
31,Regulation of Cholesterol Efflux (GO:0010874),-1.517728,0.011607,1.0,1.0
32,ATP Metabolic Process (GO:0046034),-1.516899,0.019749,1.0,1.0
35,Regulation of Organelle Organization (GO:0033043),-1.509547,0.026339,1.0,1.0
37,Negative Regulation of Protein Phosphorylation...,-1.505112,0.036379,1.0,1.0
38,Carbohydrate Metabolic Process (GO:0005975),-1.503635,0.01815,1.0,1.0
39,Positive Regulation of Protein Secretion (GO:0...,-1.493352,0.038875,1.0,1.0
40,Chromatin Remodeling (GO:0006338),-1.492529,0.046319,1.0,1.0

## MSigDB_Hallmark_2020

In [ ]:
rank_data = driver_df[["gene_names", "Day 12 Control_corr"]].sort_values('Day 12 Control_corr', ascending=False).dropna()

# Run GSEA Prerank
pre_res = gseapy.prerank(
    rnk=rank_data, 
    gene_sets='MSigDB_Hallmark_2020', # Or other libraries
    threads=16,
    min_size=5,
    max_size=1000,
)

2026-01-27 16:55:15,091 [WARNING] Duplicated values found in preranked stats: 0.15% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

In [82]:
# Enriched in dead end

pre_res.res2d.sort_values('NES', ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]] # Top Day 12

                             Term       NES NOM p-val FWER p-val FDR q-val
1                     p53 Pathway  1.606322  0.002924      0.216  0.468555
2         Estrogen Response Early  1.567842  0.008197      0.279   0.31144
3         Cholesterol Homeostasis  1.501034  0.042184      0.433   0.36815
5               Androgen Response  1.439023  0.051213      0.549  0.407197
10            Allograft Rejection  1.373691   0.04058      0.707   0.49942
11         Estrogen Response Late  1.352284  0.043732      0.742  0.462977
12      Unfolded Protein Response  1.334377  0.142512      0.776  0.438806
13           IL-2/STAT5 Signaling  1.286984  0.059155       0.86  0.502488
15               mTORC1 Signaling  1.235123  0.136483      0.924  0.585074
16     Wnt-beta Catenin Signaling  1.231806  0.207254      0.926  0.533818
17       PI3K/AKT/mTOR  Signaling  1.212613  0.195804      0.941  0.528223
18                 Myc Targets V1  1.200497  0.252927      0.951  0.517518
19              KRAS Signaling Dn  1.161955  0.202532       0.97  0.572822
20  TNF-alpha Signaling via NF-kB   1.12592  0.197568      0.988  0.635764
21                      Apoptosis   1.11967  0.216617      0.989  0.610609
22                    Pperoxisome  1.115509  0.320099      0.989  0.582905
23                 UV Response Up  1.096514  0.278689      0.991  0.600241
24          Xenobiotic Metabolism  1.089583  0.288952      0.993  0.586314
25       IL-6/JAK/STAT3 Signaling  1.050556  0.355795      0.995  0.655175
27          Inflammatory Response  1.022172  0.404692      0.997  0.699486

In [34]:
# Enriched in iPSC path
pre_res.res2d.sort_values('NES', ascending=True).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]  # Top mESC

                                 Term       NES NOM p-val FWER p-val FDR q-val
0                     G2-M Checkpoint -1.633575  0.006154       0.13  0.071303
4                     Spermatogenesis -1.468472  0.060914      0.583  0.227339
6                          DNA Repair -1.435013  0.052901      0.684  0.200886
7           Oxidative Phosphorylation -1.399608  0.067395      0.786  0.206339
8                     Mitotic Spindle -1.384391  0.061934      0.822  0.184509
9                         E2F Targets -1.378908  0.078947      0.836  0.161083
14          Interferon Alpha Response -1.272842  0.124611       0.97  0.276491
26                       Adipogenesis -1.022896  0.424961        1.0  0.800266
30               Bile Acid Metabolism -0.923084  0.587931        1.0  0.987823
31          Interferon Gamma Response -0.841091  0.777108        1.0       1.0
32                    Apical Junction -0.803908  0.834337        1.0       1.0
38                        Coagulation -0.766302  0.873089        1.0       1.0
40                     UV Response Dn -0.730427  0.932847        1.0       1.0
41    Reactive Oxygen Species Pathway -0.723649  0.828423        1.0   0.96716
46              Fatty Acid Metabolism -0.655033  0.940226        1.0  0.957446
48  Epithelial Mesenchymal Transition  0.611638       1.0        1.0  0.975172
47                 Hedgehog Signaling  0.622482   0.94621        1.0       1.0
45                Pancreas Beta Cells  0.669188  0.860911        1.0       1.0
44                         Glycolysis  0.678487  0.975138        1.0       1.0
43                     Apical Surface  0.702691  0.874372        1.0       1.0

## ChipSeq targets, ChEA

In [35]:
rank_data = driver_df[["gene_names", "Day 12 Control_corr"]].sort_values('Day 12 Control_corr', ascending=False).dropna()

# Run GSEA Prerank
pre_res = gseapy.prerank(
    rnk=rank_data, 
    gene_sets='ChEA_2022', # Or other libraries
    threads=16,
    min_size=5,
    max_size=1000
)

2026-01-27 16:10:48,957 [WARNING] Duplicated values found in preranked stats: 0.15% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

In [36]:
# Enriched in dead end

pre_res.res2d.sort_values('NES', ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]] # Top Day 12

,Term,NES,NOM p-val,FWER p-val,FDR q-val
24,RARG 19884340 ChIP-ChIP MEFs Mouse,1.723942,0.0,0.23,0.327244
26,JARID2 20075857 ChIP-Seq MESCs Mouse,1.705769,0.0,0.26,0.18913
29,SUZ12 18974828 ChIP-Seq MESCs Mouse,1.683325,0.0,0.309,0.157193
39,MTF2 20144788 ChIP-Seq MESCs Mouse,1.635858,0.0,0.441,0.18633
44,SUZ12 27294783 Chip-Seq ESCs Mouse,1.603422,0.0,0.551,0.203314
49,SUZ12 20075857 ChIP-Seq MESCs Mouse,1.54903,0.0,0.704,0.270837
51,TP63 17297297 ChIP-ChIP HaCaT Human,1.544842,0.007712,0.721,0.240856
54,PITX1 30713093 ChIP-Seq Epithelial Human Tongu...,1.535507,0.031941,0.745,0.228947
58,TP63 30713093 ChIP-Seq Epithelial Human Tongue...,1.501708,0.0,0.829,0.266275
62,JARID2 20064375 ChIP-Seq MESCs Mouse,1.496325,0.0,0.844,0.252339
65,ESR1 26153859 ChIP-Seq MCF-7 Human BreastCancer,1.477689,0.0,0.882,0.262655
71,BMI1 19503595 ChIP-Seq MEFsC Mouse,1.447041,0.006369,0.929,0.310135
74,TFAP2C 20629094 ChIP-Seq MCF-7 Human,1.431722,0.0,0.949,0.319683
76,EED 16625203 ChIP-ChIP MESCs Mouse,1.413322,0.0,0.964,0.341287
77,ESR1 20056654 ChIP-Seq MCF-7 Human BreastCancer,1.408287,0.019868,0.966,0.330479
78,PHC1 16625203 ChIP-ChIP MESCs Mouse,1.402394,0.007194,0.967,0.325378
80,P63 26484246 Chip-Seq KERATINOCYTES Human,1.386507,0.0,0.976,0.35008
85,BMI1 23680149 ChIP-Seq NPCS Mouse,1.371863,0.0,0.984,0.369066
88,WDR5 24793694 ChIP-Seq LNCAP Human,1.362852,0.022876,0.987,0.375116
92,TP53 32428506 ChIP-Seq Human Liver Heptoma,1.354306,0.04712,0.991,0.378695

In [37]:
# Enriched in iPSC path
pre_res.res2d.sort_values('NES', ascending=True).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]  # Top mESC

,Term,NES,NOM p-val,FWER p-val,FDR q-val
0,FOXM1 23109430 ChIP-Seq U2OS Human,-2.080874,0.0,0.0,0.0
1,SMAD1 18555785 ChIP-Seq MESCs Mouse,-2.071709,0.0,0.0,0.0
2,TCF3 18692474 ChIP-Seq MESCs Mouse,-2.031104,0.0,0.0,0.0
3,MYBL2 22936984 ChIP-ChIP MESCs Mouse,-2.028161,0.0,0.0,0.0
4,NACC1 18358816 ChIP-ChIP MESCs Mouse,-2.023993,0.0,0.0,0.0
5,NANOG 18700969 ChIP-ChIP MESCs Mouse,-1.998363,0.0,0.0,0.0
6,NANOG 18555785 ChIP-Seq MESCs Mouse,-1.925791,0.0,0.004,0.000519
7,POU5F1 18358816 ChIP-ChIP MESCs Mouse,-1.924004,0.0,0.004,0.000454
8,SOX2 18692474 ChIP-Seq MESCs Mouse,-1.920891,0.0,0.005,0.000504
9,POU5F1 18700969 ChIP-ChIP MESCs Mouse,-1.909825,0.0,0.008,0.000726
10,SALL4 18804426 ChIP-ChIP MESCs Mouse,-1.901245,0.0,0.008,0.00066
11,SOX2 18358816 ChIP-ChIP MESCs Mouse,-1.869524,0.0,0.012,0.000907
12,TCF3 18692474 ChIP-Seq MEFs Mouse,-1.865587,0.0,0.013,0.000907
13,SOX2 19030024 ChIP-ChIP MESCs Mouse,-1.855895,0.0,0.019,0.001232
14,SOX2 18555785 ChIP-Seq MESCs Mouse,-1.848082,0.0,0.022,0.001331
15,KDM5B 21448134 ChIP-Seq MESCs Mouse,-1.836899,0.0,0.025,0.001418
16,SMAD3 22036565 ChIP-Seq ESCs Mouse,-1.831501,0.0,0.028,0.001495
17,POU5F1 18555785 ChIP-Seq MESCs Mouse,-1.828643,0.0,0.029,0.001462
18,SOX2 18692474 ChIP-Seq MEFs Mouse,-1.818725,0.0,0.035,0.001672
19,MYC 19079543 ChIP-ChIP MESCs Mouse,-1.813193,0.0,0.038,0.00177

## Enriched targets from ChipSeq, Ensembl

In [38]:
rank_data = driver_df[["gene_names", "Day 12 Control_corr"]].sort_values('Day 12 Control_corr', ascending=False).dropna()

# Run GSEA Prerank
pre_res = gseapy.prerank(
    rnk=rank_data, 
    gene_sets='ENCODE_TF_ChIP-seq_2015', # Or other libraries
    threads=16,
    min_size=5,
    max_size=1000
)

2026-01-27 16:10:50,947 [WARNING] Duplicated values found in preranked stats: 0.15% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

In [39]:
# Enriched in dead end

pre_res.res2d.sort_values('NES', ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]] # Top Day 12

                     Term       NES NOM p-val FWER p-val FDR q-val
1         FOSL1 C2C12 mm9  1.958746       0.0      0.018  0.020186
7    SMARCC1 HeLa-S3 hg19  1.727731       0.0      0.194  0.125041
21        ZEB1 HepG2 hg19  1.635747   0.01039      0.407  0.213822
23       TAL1 G1E-ER4 mm9  1.616345       0.0      0.467  0.198496
25         ATF3 K562 hg19  1.570055       0.0      0.601  0.254343
31       EP300 ECC-1 hg19  1.543421       0.0      0.687  0.271576
42   SMARCC2 HeLa-S3 hg19  1.498263  0.016393      0.799  0.347647
46        MAX myocyte mm9   1.47301  0.009375      0.861  0.381852
48       RAD21 ECC-1 hg19  1.462778  0.010239      0.879  0.372444
51      JUND GM12878 hg19  1.447306  0.033766      0.908  0.382076
65       JUND HCT116 hg19  1.403065  0.034286      0.951  0.501693
71        REST ECC-1 hg19  1.383932  0.021407       0.97  0.539601
86      JUND HeLa-S3 hg19  1.356125  0.004016      0.983  0.627232
87       EP300 MCF-7 hg19  1.352328  0.086849      0.984  0.603737
90      ZEB1 GM12878 hg19  1.345177  0.053521      0.985   0.59758
98        JUND MCF-7 hg19  1.333134  0.096953       0.99  0.619948
100     FOSL1 HCT116 hg19  1.332936  0.056047       0.99  0.584206
115       MYOD1 C2C12 mm9  1.304278  0.015267      0.996  0.694672
117     JUND SK-N-SH hg19  1.300723  0.018939      0.996  0.677057
120     REST U-87 MG hg19  1.296762  0.075269      0.996  0.662885

In [40]:
# Enriched in iPSC path
pre_res.res2d.sort_values('NES', ascending=True).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]  # Top mESC

                      Term       NES NOM p-val FWER p-val FDR q-val
0   E2F4 MEL cell line mm9 -2.037136       0.0        0.0       0.0
2         FOXM1 ECC-1 hg19 -1.838486       0.0      0.029  0.014247
3         E2F4 CH12.LX mm9 -1.808197       0.0      0.045   0.01488
4        IRF3 GM12878 hg19 -1.804968       0.0      0.047  0.011635
5        E2F4 HeLa-S3 hg19 -1.739217       0.0      0.154  0.034383
6            SP2 K562 hg19 -1.735894       0.0      0.162   0.03071
8        NFYA GM12878 hg19 -1.717979       0.0      0.212  0.036499
9       NANOG H1-hESC hg19  -1.71797   0.00361      0.212  0.031937
10           FOS K562 hg19 -1.691803       0.0      0.286  0.041263
11        FOXM1 MCF-7 hg19  -1.69142  0.003205      0.287  0.037327
12      FOXM1 GM12878 hg19 -1.688035  0.002994      0.299  0.035833
13          NFYA K562 hg19 -1.680039       0.0      0.327  0.036646
14        CEBPZ HepG2 hg19 -1.672148  0.003091      0.349   0.03748
15       IRF3 HeLa-S3 hg19 -1.667795  0.001416      0.363  0.037246
16         TCF12 A549 hg19 -1.660941   0.00597      0.387  0.038118
17          SP2 HepG2 hg19 -1.653251       0.0      0.411   0.03912
18     STAT5A GM12878 hg19 -1.652919  0.001572      0.412  0.036986
19        SETDB1 U2OS hg19 -1.649696  0.001437      0.423  0.036145
20       E2F4 GM12878 hg19 -1.638899       0.0      0.457  0.038492
22         KAT2B K562 hg19 -1.623781       0.0      0.517  0.044165

## GO pathways with full transcriptome

In [63]:
rank_data = full_driver_df[["gene_names", "Day 12 Control_corr"]].sort_values('Day 12 Control_corr', ascending=False).dropna()

# Run GSEA Prerank
pre_res = gseapy.prerank(
    rnk=rank_data, 
    gene_sets="GO_Biological_Process_2025", # Or other libraries
    threads=16,
    min_size=5,
    max_size=1000
)

2026-01-27 16:35:46,719 [WARNING] Duplicated values found in preranked stats: 1.89% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

In [64]:
# Enriched in dead end

pre_res.res2d.sort_values("NES", ascending=False).head(20)[["Term", "ES", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]] # Top Day 12

,Term,ES,NES,NOM p-val,FWER p-val,FDR q-val
0,Ribosome Biogenesis (GO:0042254),0.727115,2.334127,0.0,0.0,0.0
1,Translation (GO:0006412),0.705754,2.321165,0.0,0.0,0.0
2,Ribonucleoprotein Complex Biogenesis (GO:0022613),0.737203,2.296186,0.0,0.0,0.0
3,Ribosomal Small Subunit Biogenesis (GO:0042274),0.769492,2.270756,0.0,0.0,0.0
4,rRNA Processing (GO:0006364),0.737638,2.258627,0.0,0.0,0.0
5,rRNA Metabolic Process (GO:0016072),0.709495,2.161552,0.0,0.0,0.0
6,Mitochondrial Translation (GO:0032543),0.697643,2.101657,0.0,0.0,0.0
7,Macromolecule Biosynthetic Process (GO:0009059),0.651389,2.101543,0.0,0.0,0.0
8,Mitochondrial Gene Expression (GO:0140053),0.695848,2.095677,0.0,0.0,0.0
9,Cytoplasmic Translation (GO:0002181),0.685243,2.093118,0.0,0.0,0.0
11,Maturation of LSU-rRNA (GO:0000470),0.859512,2.041024,0.0,0.0,0.0
12,Ribosomal Large Subunit Biogenesis (GO:0042273),0.755413,2.011613,0.0,0.001,0.000085
18,Maturation of SSU-rRNA (GO:0030490),0.748379,1.916252,0.0,0.013,0.001337
21,Maturation of SSU-rRNA Frm Tricistronic rRNA T...,0.76152,1.883783,0.0,0.04,0.003432
22,Establishment of Skin Barrier (GO:0061436),0.813827,1.869106,0.0,0.072,0.00552
24,Gene Expression (GO:0010467),0.540933,1.852973,0.0,0.11,0.008369
25,Skin Epidermis Development (GO:0098773),0.787114,1.847835,0.0,0.128,0.0092
26,Ribosome Assembly (GO:0042255),0.688781,1.845721,0.0,0.132,0.009086
30,COPII-coated Vesicle Budding (GO:0090114),0.689642,1.818501,0.0,0.247,0.017431
32,Translational Elongation (GO:0006414),0.68036,1.804829,0.0,0.32,0.022693

In [65]:
# Enriched in iPSC path
pre_res.res2d.sort_values('NES', ascending=True).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]  # Top mESC

,Term,NES,NOM p-val,FWER p-val,FDR q-val
10,DNA-templated DNA Replication Maintenance of F...,-2.069062,0.0,0.007,0.006767
13,Male Meiotic Nuclear Division (GO:0007140),-1.971685,0.0,0.048,0.025619
14,Gonad Development (GO:0008406),-1.952828,0.0,0.088,0.030937
15,Development of Primary Male Sexual Characteris...,-1.942729,0.0,0.103,0.028036
16,Centromere Complex Assembly (GO:0034508),-1.941575,0.0,0.108,0.023589
17,Response to Estrogen (GO:0043627),-1.938539,0.0,0.116,0.021269
19,Meiosis I (GO:0007127),-1.906419,0.0,0.211,0.036323
20,Male Gonad Development (GO:0008584),-1.895446,0.0,0.261,0.040967
23,Male Gamete Generation (GO:0048232),-1.85393,0.0,0.485,0.080027
27,Meiotic Sister Chromatid Cohesion (GO:0051177),-1.842212,0.0,0.543,0.086913
28,Replication Fork Processing (GO:0031297),-1.831862,0.0,0.596,0.09281
29,Male Meiosis I (GO:0007141),-1.819798,0.0,0.656,0.104089
31,High-Density Lipoprotein Particle Remodeling (...,-1.80978,0.002564,0.717,0.113186
33,DNA Integrity Checkpoint Signaling (GO:0031570),-1.804086,0.0,0.753,0.116012
38,Regulation of Cell Fate Commitment (GO:0010453),-1.788048,0.0,0.82,0.139924
39,Sarcomere Organization (GO:0045214),-1.78227,0.005571,0.852,0.143384
44,"Negative Regulation of Gene Expression, Epigen...",-1.767766,0.0,0.901,0.168218
46,Kinetochore Assembly (GO:0051382),-1.766193,0.002237,0.904,0.162847
47,Constitutive Heterochromatin Formation (GO:014...,-1.76229,0.002695,0.912,0.164351
49,DNA Methylation-Dependent Constitutive Heteroc...,-1.761553,0.004785,0.916,0.158018

## Enrichment analysis instead of ranking

In [41]:
driver_df.columns

Index(['Unnamed: 0', 'gene_names', 'Day 12 Control_corr',
       'Day 12 Control_pval', 'Day 12 Control_qval', 'Day 12 Control_ci_low',
       'Day 12 Control_ci_high', 'mESC_corr', 'mESC_pval', 'mESC_qval',
       'mESC_ci_low', 'mESC_ci_high'],
      dtype='object')

In [47]:
print(driver_df["Day 12 Control_pval"])

0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ...
1995    0.0
1996    0.0
1997    NaN
1998    NaN
1999    NaN
Name: Day 12 Control_pval, Length: 2000, dtype: float64

In [48]:
driver_df["Day 12 Control_pval"] < 0.05

0        True
1        True
2        True
3        True
4        True
        ...
1995     True
1996     True
1997    False
1998    False
1999    False
Name: Day 12 Control_pval, Length: 2000, dtype: bool

In [79]:
dead_end_drivers = driver_df.sort_values("Day 12 Control_corr").head(100)["gene_names"].to_list()
background_genes = adata.var_names.tolist()

# Run Enrichr (ORA)
enr = gseapy.enrichr(
    gene_list=dead_end_drivers,
    gene_sets='GO_Biological_Process_2025',
    background=background_genes,
    organism='mouse',
    outdir=None
)

# Print results
enr.res2d.sort_values('Adjusted P-value').head(10)

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,GO_Biological_Process_2025,Chromatin Organization (GO:0006325),0.000016,0.014716,0,0,9.631714,106.500213,TCF7L1;REST;PHC1;HMGB2;TET1;SYCP3;HMGN2;JARID2
1,GO_Biological_Process_2025,Chromatin Remodeling (GO:0006338),0.000795,0.330041,0,0,9.038278,64.504069,REST;PHC1;MTF2;TET1;JARID2
2,GO_Biological_Process_2025,Male Meiotic Nuclear Division (GO:0007140),0.001128,0.330041,0,0,29.350515,199.217395,DNMT3L;TDRD12;SYCP3
3,GO_Biological_Process_2025,ATP Metabolic Process (GO:0046034),0.002174,0.330041,0,0,19.556701,119.908460,UCP2;ENPP3;ATP1B1
4,GO_Biological_Process_2025,V(D)J Recombination (GO:0033151),0.002476,0.330041,0,0,inf,inf,TCF7L1;HMGB2
5,GO_Biological_Process_2025,Positive Regulation of Amyloid-Beta Clearance ...,0.002476,0.330041,0,0,inf,inf,LRPAP1;APOE
6,GO_Biological_Process_2025,Somatic Recombination of Immunoglobulin Gene S...,0.002476,0.330041,0,0,inf,inf,MSH6;TCF7L1
7,GO_Biological_Process_2025,Protein Polyubiquitination (GO:0000209),0.002969,0.346221,0,0,8.754630,50.948801,ARRDC4;TRIM71;IFI27;NEDD4
240,GO_Biological_Process_2025,Positive Regulation of Neuron Differentiation ...,0.101458,0.381467,0,0,4.287982,9.811376,TCF7L1;REST
239,GO_Biological_Process_2025,Unsaturated Fatty Acid Metabolic Process (GO:0...,0.101458,0.381467,0,0,4.287982,9.811376,GSTM2;GPX4

Less informative than using ranking

## Enriched in clusters

In [18]:
# Enriched among mid_peak_genes
mid_peak_genes = dead_end_adata[dead_end_adata.obs["clusters"] == "1"]

In [19]:
adata.obs["macrostates_fwd"].unique()

[NaN, 'MEF', 'mESC', 'Day 2 Control', 'Day 6 Hic2 OX', 'Day 12 Control']
Categories (5, object): ['MEF', 'Day 2 Control', 'Day 12 Control', 'Day 6 Hic2 OX', 'mESC']

In [20]:
scanpy.tl.rank_genes_groups(adata, groupby='macrostates_fwd', method='wilcoxon')

WARNING: It seems you use rank_genes_groups on the raw count data. Please logarithmize your data before calling rank_genes_groups.

In [21]:
# 1. Select a cluster (e.g., cluster '0')
cluster_id = 'Day 6 Hic2 OX'

# 2. Extract significant genes only (e.g., adjusted p-value < 0.05)
dedf = scanpy.get.rank_genes_groups_df(adata, group=cluster_id)
gene_list = dedf[dedf['pvals_adj'] < 0.05]['names'].tolist()

# 3. Run Enrichr (ORA)
enr = gseapy.enrichr(
    gene_list=gene_list,
    gene_sets='GO_Biological_Process_2023',
    organism='mouse', # 'human', 'mouse', etc.
    outdir=None       # Don't write to disk
)

# 4. View results
enr.res2d.sort_values('Adjusted P-value').head(20)

,Gene_set,Term,Overlap,P-value,Adjusted P-value,Old P-value,Old Adjusted P-value,Odds Ratio,Combined Score,Genes
0,GO_Biological_Process_2023,Cytoplasmic Translation (GO:0002181),8/93,0.000020,0.034007,0,0,7.745213,83.831628,RPS7;RPS18;RPL12;MRPS12;RPL23A;RPL26;RPS10;RPL28
1,GO_Biological_Process_2023,Regulation Of Transforming Growth Factor Beta ...,8/111,0.000071,0.040623,0,0,6.385831,60.967376,BRMS1;CITED2;PEG10;CD109;PMEPA1;TET1;RBBP7;FOLR1
2,GO_Biological_Process_2023,Negative Regulation Of Transmembrane Receptor ...,8/111,0.000071,0.040623,0,0,6.385831,60.967376,BRMS1;PEG10;CD109;PMEPA1;TET1;GDF3;RBBP7;SKIL
3,GO_Biological_Process_2023,Regulation Of Cell Migration (GO:0030334),15/434,0.000346,0.129950,0,0,2.983396,23.771217,ANXA1;CITED2;STAT3;PDGFA;TET1;LAMB1;PLET1;IGF1...
4,GO_Biological_Process_2023,Negative Regulation Of Transforming Growth Fac...,6/77,0.000381,0.129950,0,0,6.901525,54.340290,BRMS1;PEG10;CD109;PMEPA1;TET1;RBBP7
16,GO_Biological_Process_2023,Positive Regulation Of Vesicle Fusion (GO:0031...,2/5,0.001482,0.148832,0,0,53.741497,350.083902,ANXA1;ANXA2
15,GO_Biological_Process_2023,Positive Regulation Of Intrinsic Apoptotic Sig...,2/5,0.001482,0.148832,0,0,53.741497,350.083902,RPS7;RPL26
13,GO_Biological_Process_2023,Negative Regulation Of Cell Motility (GO:2000146),7/133,0.001339,0.148832,0,0,4.543287,30.056202,SFRP1;BRMS1;CITED2;TET1;SPINT2;RBBP7;ARPIN
12,GO_Biological_Process_2023,Epithelial Cell Differentiation (GO:0030855),7/132,0.001282,0.148832,0,0,4.579867,30.498352,UPK1B;TAGLN;ANXA1;BASP1;TAGLN2;GLI1;KRT20
11,GO_Biological_Process_2023,Regulation Of Apoptotic Process (GO:0042981),19/705,0.001263,0.148832,0,0,2.316205,15.458949,MTCH1;BEX1;ANXA1;GADD45B;RIPK3;CITED2;PLAUR;HS...
14,GO_Biological_Process_2023,Positive Regulation Of Stem Cell Population Ma...,4/40,0.001463,0.148832,0,0,9.015546,58.844453,REST;BRMS1;TET1;RBBP7
9,GO_Biological_Process_2023,Regulation Of Angiogenesis (GO:0045765),9/205,0.001048,0.148832,0,0,3.773216,25.886697,SFRP1;RNH1;JUP;ANXA3;VEGFB;ECSCR;HMOX1;HSPB1;DCN
8,GO_Biological_Process_2023,Positive Regulation Of Cell Migration Involved...,3/16,0.000925,0.148832,0,0,18.669609,130.416918,FGFBP1;ANXA1;HMOX1
7,GO_Biological_Process_2023,Peptide Biosynthetic Process (GO:0043043),8/158,0.000793,0.148832,0,0,4.374449,31.233598,RPS7;RPS18;RPL12;MRPS12;RPL23A;RPL26;RPS10;RPL28
6,GO_Biological_Process_2023,Cellular Response To Corticosteroid Stimulus (...,3/15,0.000759,0.148832,0,0,20.226434,145.307338,REST;ANXA1;NR3C1
5,GO_Biological_Process_2023,Response To Organic Cyclic Compound (GO:0014070),5/58,0.000742,0.148832,0,0,7.679713,55.345423,SFRP1;ANXA1;STAT3;CLU;ADA
10,GO_Biological_Process_2023,Membrane Assembly (GO:0071709),4/38,0.001205,0.148832,0,0,9.546841,64.167125,SPAST;ANXA2;CHMP2B;DMKN
17,GO_Biological_Process_2023,Negative Regulation Of Stem Cell Population Ma...,3/20,0.001816,0.172216,0,0,14.273867,90.084218,BRMS1;TET1;RBBP7
18,GO_Biological_Process_2023,Macromolecule Biosynthetic Process (GO:0009059),8/183,0.002025,0.179188,0,0,3.744746,23.225318,RPS7;RPS18;RPL12;MRPS12;RPL23A;RPL26;RPS10;RPL28
19,GO_Biological_Process_2023,Positive Regulation Of Smoothened Signaling Pa...,3/21,0.002099,0.179188,0,0,13.480191,83.119925,SFRP1;RAB34;GLI1

In [16]:
# 1. Select a cluster (e.g., cluster '0')
cluster_id = 'Day 12 Control'

# 2. Extract significant genes only (e.g., adjusted p-value < 0.05)
dedf = scanpy.get.rank_genes_groups_df(adata, group=cluster_id)
gene_list = dedf[dedf['pvals_adj'] < 0.05]['names'].tolist()

# 3. Run Enrichr (ORA)
enr = gseapy.enrichr(
    gene_list=gene_list,
    gene_sets='GO_Biological_Process_2023',
    organism='mouse', # 'human', 'mouse', etc.
    outdir=None       # Don't write to disk
)

# 4. View results
enr.res2d.sort_values('Adjusted P-value').head(20)

,Gene_set,Term,Overlap,P-value,Adjusted P-value,Old P-value,Old Adjusted P-value,Odds Ratio,Combined Score,Genes
0,GO_Biological_Process_2023,Negative Regulation Of Apoptotic Process (GO:0...,44/482,6.091678e-12,1.675212e-08,0,0,3.699373,95.532981,ITGB1;NOTCH1;PRKAA2;TFRC;ARL6IP1;CITED2;LEF1;F...
1,GO_Biological_Process_2023,Regulation Of Apoptotic Process (GO:0042981),54/705,2.198052e-11,3.022321e-08,0,0,3.080108,75.588509,ITGB1;TOP2A;HIP1;RTKN;TFRC;ARL6IP1;CITED2;FHL2...
2,GO_Biological_Process_2023,Negative Regulation Of Programmed Cell Death (...,37/381,5.286951e-11,4.846371e-08,0,0,3.927209,92.930307,PRKAA2;ARL6IP1;TFRC;CITED2;LEF1;FHL2;HSPB1;FST...
3,GO_Biological_Process_2023,Regulation Of Cell Population Proliferation (G...,55/766,1.642621e-10,1.129302e-07,0,0,2.868906,64.635180,COL18A1;BTG2;CDKN1A;IFITM1;BTG1;TFRC;CD81;HMGB...
4,GO_Biological_Process_2023,Supramolecular Fiber Organization (GO:0097435),30/316,6.181530e-09,3.399841e-06,0,0,3.790870,71.653879,COL18A1;HIP1;SH3KBP1;AVIL;STMN4;KRT20;LOXL2;CS...
5,GO_Biological_Process_2023,Positive Regulation Of Cell Population Prolife...,38/483,1.130035e-08,5.179325e-06,0,0,3.107366,56.859923,CDKN1A;NOTCH1;CD81;LEF1;PDGFA;PTN;LAMC1;THBS1;...
6,GO_Biological_Process_2023,Regulation Of Cell Migration (GO:0030334),35/434,2.339911e-08,9.192508e-06,0,0,3.181454,55.899947,ITGB1;BEX4;IFITM1;NOTCH1;SERPINE2;CITED2;LEF1;...
7,GO_Biological_Process_2023,Positive Regulation Of Cell Differentiation (G...,27/283,3.218539e-08,1.106373e-05,0,0,3.796083,65.489095,FBN2;IFITM1;BTG1;LEF1;TWIST1;PTN;LAMC1;NID1;AC...
9,GO_Biological_Process_2023,Positive Regulation Of Epithelial To Mesenchym...,10/47,5.570147e-07,1.531790e-04,0,0,9.534644,137.305299,COL1A1;TCF7L2;NOTCH1;GLIPR2;MDK;LEF1;TWIST1;EM...
8,GO_Biological_Process_2023,Negative Regulation Of Cellular Process (GO:00...,37/537,5.051142e-07,1.531790e-04,0,0,2.679847,38.853712,COL18A1;BTG2;CDKN1A;IFITM1;BTG1;NOTCH1;JADE1;S...
10,GO_Biological_Process_2023,Positive Regulation Of Cellular Process (GO:00...,39/594,8.322306e-07,2.080576e-04,0,0,2.547129,35.657653,PRKAA2;NOTCH1;CITED2;CD81;LEF1;PDGFA;TWIST1;PT...
11,GO_Biological_Process_2023,Collagen Fibril Organization (GO:0030199),9/42,1.939251e-06,4.444116e-04,0,0,9.605841,126.347628,COL1A1;COL18A1;COL3A1;COL1A2;COL5A1;LOX;COL5A2...
12,GO_Biological_Process_2023,Skin Development (GO:0043588),11/68,2.716130e-06,5.325565e-04,0,0,6.813441,87.323117,DSP;COL1A1;ST14;COL3A1;ANXA1;COL1A2;COL5A1;COL...
13,GO_Biological_Process_2023,Positive Regulation Of Cell Migration (GO:0030...,23/272,2.745983e-06,5.325565e-04,0,0,3.301048,42.271143,ITGB1;NOTCH1;HSPA5;LEF1;FN1;PDGFA;TWIST1;LAMB1...
14,GO_Biological_Process_2023,Actin Filament Organization (GO:0007015),16/144,2.904853e-06,5.325565e-04,0,0,4.437500,56.574254,MARCKSL1;HIP1;TPM4;SH3KBP1;AVIL;ACTN1;TPM2;TPM...
15,GO_Biological_Process_2023,Negative Regulation Of Cell Migration (GO:0030...,17/163,3.436141e-06,5.905868e-04,0,0,4.137314,52.052218,IFITM1;LRP1;CITED2;TPM1;TET1;SULF1;GJA1;SFRP1;...
16,GO_Biological_Process_2023,Endoderm Formation (GO:0001706),8/35,4.339618e-06,7.019970e-04,0,0,10.420290,128.666866,MMP14;ITGB5;COL4A2;DUSP1;MMP2;FN1;HMGA2;LAMB1
18,GO_Biological_Process_2023,Mitotic Cytokinesis (GO:0000281),10/59,4.999331e-06,7.235874e-04,0,0,7.195176,87.825806,RTKN;INCENP;CFL1;PLK1;NUSAP1;BIRC5;RHOC;CENPA;...
17,GO_Biological_Process_2023,Cellular Response To Hypoxia (GO:0071456),11/72,4.839949e-06,7.235874e-04,0,0,6.365344,77.902938,SFRP1;NOTCH1;FAM162A;MYC;LMNA;MDM2;TWIST1;AQP3...
20,GO_Biological_Process_2023,Cellular Response To Decreased Oxygen Levels (...,11/73,5.556550e-06,7.276434e-04,0,0,6.262354,75.777821,SFRP1;NOTCH1;FAM162A;MYC;LMNA;MDM2;TWIST1;AQP3...