Environment: `velocity`

In [1]:
import scanpy
import anndata
import matplotlib
from matplotlib import pyplot
import hdf5plugin
import numpy
import scvelo
import seaborn
import pandas
import warnings
import cellrank
import gseapy

In [2]:
# Read input file
working_directory = "RNA Sequencing Data/"

# adata = scanpy.read_h5ad(working_directory + "/velocity_sdevelo.h5ad")

# Or read saved anndata objects
working_directory = "RNA Sequencing Data/"
base_name = "cellrank_version_5"
adata = scanpy.read_h5ad(
    working_directory+f"/{base_name}_anndata.h5ad"
)
driver_df = pandas.read_csv(
    working_directory+f"{base_name}_driver_genes.csv",
    index_col=0
)
combined_driver_df = pandas.read_csv(
    working_directory+f"{base_name}_driver_genes_combined.csv",
    index_col=0
)

In [3]:
# Read ChIP-seq targets
base_name = "ChIP Sequencing Data/chipseq_targets"

hic2_target_scores = pandas.read_csv(f"{base_name}_hic2_scores.csv", index_col=0)
klf4_hic2_target_scores = pandas.read_csv(f"{base_name}_klf4_hic2_scores.csv", index_col=0)
klf4_control_target_scores = pandas.read_csv(f"{base_name}_klf4_control_scores.csv", index_col=0)

hic2_targets = numpy.loadtxt(f"{base_name}_hic2_targets.txt", dtype=numpy.dtypes.StrDType)
klf4_hic2_targets = numpy.loadtxt(f"{base_name}_klf4_hic2_targets.txt", dtype=numpy.dtypes.StrDType)
klf4_control_targets = numpy.loadtxt(f"{base_name}_klf4_control_targets.txt", dtype=numpy.dtypes.StrDType)
klf4_targets = numpy.intersect1d(klf4_hic2_targets, klf4_control_targets)
shared_targets = numpy.intersect1d(hic2_targets, klf4_targets)

In [9]:
# Load bulk differential expression results

bulk_de = pandas.read_csv("RNA Sequencing Data/bulk_differential_expression_combined.csv", index_col=0)
bulk_metadata = pandas.read_csv("RNA Sequencing Data/bulk_sequencing_metadata.csv", index_col=0)
samples = bulk_metadata.index.to_list()
reprogramming_columns = bulk_de.columns[bulk_de.columns.str.contains("Reprogramming")]
reprogramming_de = pandas.read_csv("RNA Sequencing Data/bulk_differential_expression_reprogramming.csv", index_col=0)
mef_de = pandas.read_csv("RNA Sequencing Data/bulk_differential_expression_mef.csv", index_col=0)
mesc_de = pandas.read_csv("RNA Sequencing Data/bulk_differential_expression_mesc.csv", index_col=0)
ipsc_de = pandas.read_csv("RNA Sequencing Data/bulk_differential_expression_ipsc.csv", index_col=0)

In [ ]:
# Variable genes and Cellrank drivers
variable_genes = adata.var_names.to_numpy()
variable_in_bulk = numpy.intersect1d(variable_genes, bulk_de.index.to_numpy())
stem_cell_drivers = driver_df.sort_values("Day 12 Control_corr", ascending=True).head(100).index.to_numpy()
dead_end_drivers = driver_df.sort_values("Day 12 Control_corr", ascending=False).head(100).index.to_numpy()
differentially_expressed_genes = reprogramming_de.loc[variable_in_bulk].query("padj < 0.05").index.to_numpy()

In [18]:
# Load list of transcription factors

tf_df = pandas.read_csv("ChIP Sequencing Data/Mus_musculus_TF.txt", sep="\t")
tf_array = tf_df["Symbol"].to_numpy()

# All target transcription factors
target_tfs = numpy.intersect1d(shared_targets, tf_array)

# Target transcription factors for which Hic2 changes expression significantly
de_target_tfs = numpy.intersect1d(target_tfs, differentially_expressed_genes)

de_dead_end_drivers = numpy.intersect1d(de_target_tfs, dead_end_drivers)
de_stem_cell_drivers = numpy.intersect1d(de_target_tfs, stem_cell_drivers)

In [21]:
genes_of_interest = de_dead_end_drivers.tolist() + de_stem_cell_drivers.tolist() + ["Klf4", "Myc", "Hic2"]

In [4]:
# Show all possible libraries
names = gseapy.get_library_name(organism="Mouse")
print(names)

['ARCHS4_Cell-lines', 'ARCHS4_IDG_Coexp', 'ARCHS4_Kinases_Coexp', 'ARCHS4_TFs_Coexp', 'ARCHS4_Tissues', 'Achilles_fitness_decrease', 'Achilles_fitness_increase', 'Aging_Perturbations_from_GEO_down', 'Aging_Perturbations_from_GEO_up', 'Allen_Brain_Atlas_10x_scRNA_2021', 'Allen_Brain_Atlas_down', 'Allen_Brain_Atlas_up', 'Azimuth_2023', 'Azimuth_Cell_Types_2021', 'BioCarta_2013', 'BioCarta_2015', 'BioCarta_2016', 'BioPlanet_2019', 'BioPlex_2017', 'CCLE_Proteomics_2020', 'CM4AI_U2OS_Protein_Localization_Assemblies', 'COMPARTMENTS_Curated_2025', 'COMPARTMENTS_Experimental_2025', 'CORUM', 'COVID-19_Related_Gene_Sets', 'COVID-19_Related_Gene_Sets_2021', 'Cancer_Cell_Line_Encyclopedia', 'Carcinogenome', 'CellMarker_2024', 'CellMarker_Augmented_2021', 'ChEA_2013', 'ChEA_2015', 'ChEA_2016', 'ChEA_2022', 'Chromosome_Location', 'Chromosome_Location_hg19', 'ClinVar_2019', 'ClinVar_2025', 'DGIdb_Drug_Targets_2024', 'DSigDB', 'Data_Acquisition_Method_Most_Popular_Genes', 'DepMap_CRISPR_GeneDependency_CellLines_2023', 'DepMap_WG_CRISPR_Screens_Broad_CellLines_2019', 'DepMap_WG_CRISPR_Screens_Sanger_CellLines_2019', 'Descartes_Cell_Types_and_Tissue_2021', 'Diabetes_Perturbations_GEO_2022', 'DisGeNET', 'Disease_Perturbations_from_GEO_down', 'Disease_Perturbations_from_GEO_up', 'Disease_Signatures_from_GEO_down_2014', 'Disease_Signatures_from_GEO_up_2014', 'DrugMatrix', 'Drug_Perturbations_from_GEO_2014', 'Drug_Perturbations_from_GEO_down', 'Drug_Perturbations_from_GEO_up', 'ENCODE_Histone_Modifications_2013', 'ENCODE_Histone_Modifications_2015', 'ENCODE_TF_ChIP-seq_2014', 'ENCODE_TF_ChIP-seq_2015', 'ENCODE_and_ChEA_Consensus_TFs_from_ChIP-X', 'ESCAPE', 'Elsevier_Pathway_Collection', 'Enrichr_Libraries_Most_Popular_Genes', 'Enrichr_Submissions_TF-Gene_Coocurrence', 'Enrichr_Users_Contributed_Lists_2020', 'Epigenomics_Roadmap_HM_ChIP-seq', 'FANTOM6_lncRNA_KD_DEGs', 'GO_Biological_Process_2021', 'GO_Biological_Process_2023', 'GO_Biological_Process_2025', 'GO_Cellular_Component_2021', 'GO_Cellular_Component_2023', 'GO_Cellular_Component_2025', 'GO_Molecular_Function_2021', 'GO_Molecular_Function_2023', 'GO_Molecular_Function_2025', 'GTEx_Aging_Signatures_2021', 'GTEx_Tissue_Expression_Down', 'GTEx_Tissue_Expression_Up', 'GTEx_Tissues_V8_2023', 'GWAS_Catalog_2019', 'GWAS_Catalog_2023', 'GWAS_Catalog_2025', 'GeDiPNet_2023', 'GeneSigDB', 'Gene_Perturbations_from_GEO_down', 'Gene_Perturbations_from_GEO_up', 'Genes_Associated_with_NIH_Grants', 'Genome_Browser_PWMs', 'GlyGen_Glycosylated_Proteins_2022', 'HDSigDB_Human_2021', 'HDSigDB_Mouse_2021', 'HMDB_Metabolites', 'HMS_LINCS_KinomeScan', 'HomoloGene', 'HuBMAP_ASCT_plus_B_augmented_w_RNAseq_Coexpression', 'HuBMAP_ASCTplusB_augmented_2022', 'HumanCyc_2015', 'HumanCyc_2016', 'Human_Gene_Atlas', 'Human_Phenotype_Ontology', 'IDG_Drug_Targets_2022', 'InterPro_Domains_2019', 'JASPAR_PWM_Human_2025', 'JASPAR_PWM_Mouse_2025', 'Jensen_COMPARTMENTS', 'Jensen_DISEASES', 'Jensen_DISEASES_Curated_2025', 'Jensen_DISEASES_Experimental_2025', 'Jensen_TISSUES', 'KEA_2013', 'KEA_2015', 'KEGG_2013', 'KEGG_2015', 'KEGG_2016', 'KEGG_2019_Human', 'KEGG_2019_Mouse', 'KEGG_2021_Human', 'KEGG_2026', 'KOMP2_Mouse_Phenotypes_2022', 'Kinase_Perturbations_from_GEO_down', 'Kinase_Perturbations_from_GEO_up', 'L1000_Kinase_and_GPCR_Perturbations_down', 'L1000_Kinase_and_GPCR_Perturbations_up', 'LINCS_L1000_CRISPR_KO_Consensus_Sigs', 'LINCS_L1000_Chem_Pert_Consensus_Sigs', 'LINCS_L1000_Chem_Pert_down', 'LINCS_L1000_Chem_Pert_up', 'LINCS_L1000_Ligand_Perturbations_down', 'LINCS_L1000_Ligand_Perturbations_up', 'Ligand_Perturbations_from_GEO_down', 'Ligand_Perturbations_from_GEO_up', 'MAGMA_Drugs_and_Diseases', 'MAGNET_2023', 'MCF7_Perturbations_from_GEO_down', 'MCF7_Perturbations_from_GEO_up', 'MGI_Mammalian_Phenotype_Level_4_2021', 'MGI_Mammalian_Phenotype_Level_4_2024', 'MSigDB_Computational', 'MSigDB_Hallmark_2020', 'MSigDB_Oncogenic_Signatures', 'Metabolomics_Workbench_Metabolites_2022', 'Microbe_Perturbations_from_GEO_down', 'Microbe_Perturbations_from_GEO_up', 'MoTrPAC_2023', 'Mouse_Gene_Atlas', 'NCI-60_Cancer_Cell_Lines', 'NCI-Nature_2016', 'NIBR_DRUGseq_2025_down', 'NIBR_DRUGseq_2025_up', 'NURSA_Human_Endogenous_Complexome', 'OMIM_Disease', 'OMIM_Expanded', 'Old_CMAP_down', 'Old_CMAP_up', 'Orphanet_Augmented_2021', 'PFOCR_Pathways_2023', 'PPI_Hub_Proteins', 'PanglaoDB_Augmented_2021', 'Panther_2015', 'Panther_2016', 'PerturbAtlas', 'PerturbAtlas_MouseGenePerturbationSigs', 'PerturbSeq_ReplogleK562', 'PerturbSeq_ReplogleRPE1', 'Pfam_Domains_2019', 'Pfam_InterPro_Domains', 'PheWeb_2019', 'PhenGenI_Association_2021', 'Phosphatase_Substrates_from_DEPOD', 'ProteomicsDB_2020', 'Proteomics_Drug_Atlas_2023', 'RNA-Seq_Disease_Gene_and_Drug_Signatures_from_GEO', 'Rare_Diseases_AutoRIF_ARCHS4_Predictions', 'Rare_Diseases_AutoRIF_Gene_Lists', 'Rare_Diseases_GeneRIF_ARCHS4_Predictions', 'Rare_Diseases_GeneRIF_Gene_Lists', 'Reactome_2022', 'Reactome_Pathways_2024', 'RummaGEO_DrugPerturbations_2025', 'RummaGEO_GenePerturbations_2025', 'Rummagene_kinases', 'Rummagene_signatures', 'Rummagene_transcription_factors', 'SILAC_Phosphoproteomics', 'Sciplex_Drug_Perturbation_Signatures_2025', 'SubCell_BarCode', 'SynGO_2022', 'SynGO_2024', 'SysMyo_Muscle_Gene_Sets', 'TF-LOF_Expression_from_GEO', 'TF_Perturbations_Followed_by_Expression', 'TG_GATES_2020', 'TISSUES_Curated_2025', 'TISSUES_Experimental_2025', 'TRANSFAC_and_JASPAR_PWMs', 'TRRUST_Transcription_Factors_2019', 'Table_Mining_of_CRISPR_Studies', 'Tabula_Muris', 'Tabula_Sapiens', 'TargetScan_microRNA', 'TargetScan_microRNA_2017', 'The_Kinase_Library_2023', 'The_Kinase_Library_2024', 'Tissue_Protein_Expression_from_Human_Proteome_Map', 'Tissue_Protein_Expression_from_ProteomicsDB', 'Transcription_Factor_PPIs', 'UK_Biobank_GWAS_v1', 'Virus-Host_PPI_P-HIPSTer_2020', 'VirusMINT', 'Virus_Perturbations_from_GEO_down', 'Virus_Perturbations_from_GEO_up', 'WikiPathway_2021_Human', 'WikiPathway_2023_Human', 'WikiPathways_2013', 'WikiPathways_2015', 'WikiPathways_2016', 'WikiPathways_2019_Human', 'WikiPathways_2019_Mouse', 'WikiPathways_2024_Human', 'WikiPathways_2024_Mouse', 'dbGaP', 'huMAP', 'lncHUB_lncRNA_Co-Expression', 'miRTarBase_2017']

# Gene set enrichment for Cellrank drivers

## GO pathway

In [5]:
rank_data = driver_df[["gene_names", "Day 12 Control_corr"]].sort_values('Day 12 Control_corr', ascending=False).dropna()

# Run GSEA Prerank
pre_res = gseapy.prerank(
    rnk=rank_data, 
    gene_sets="GO_Biological_Process_2025",
    threads=16,
    min_size=5,
    max_size=1000,
    permutation_num=2000
)

2026-02-02 11:08:53,006 [WARNING] Duplicated values found in preranked stats: 0.15% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

In [6]:
# Enriched in dead end

pre_res.res2d.sort_values("NES", ascending=False).head(20)[["Term", "ES", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]] # Top Day 12

,Term,ES,NES,NOM p-val,FWER p-val,FDR q-val
0,Epidermis Development (GO:0008544),0.65148,1.832768,0.002571,0.4625,0.673351
1,Regulation of Trans-Synaptic Signaling (GO:009...,0.794156,1.804547,0.001188,0.593,0.504901
2,Regulation of Glycolytic Process (GO:0006110),0.816355,1.756093,0.00489,0.802,0.66826
3,Proteolysis Involved in Protein Catabolic Proc...,0.743789,1.755604,0.006105,0.803,0.504452
7,Antigen Processing and Presentation of Exogeno...,0.858342,1.711653,0.010753,0.935,0.505029
5,Antigen Processing and Presentation of Exogeno...,0.858342,1.711653,0.010753,0.935,0.505029
6,Antigen Processing and Presentation of Peptide...,0.858342,1.711653,0.010753,0.935,0.505029
10,Negative Regulation of Myeloid Leukocyte Diffe...,0.761694,1.639877,0.025862,0.9925,0.978021
11,Positive Regulation of Purine Nucleotide Catab...,0.871029,1.638283,0.009423,0.9925,0.795758
12,Positive Regulation of Glycolytic Process (GO:...,0.871029,1.638283,0.009423,0.9925,0.795758
14,Regulation of Stress-Activated MAPK Cascade (G...,0.861742,1.633115,0.012896,0.9935,0.762007
19,Negative Regulation of Carbohydrate Metabolic ...,0.847319,1.5783,0.022093,1.0,1.0
20,Protein Catabolic Process (GO:0030163),0.603459,1.575067,0.023839,1.0,1.0
21,Protein Tetramerization (GO:0051262),0.83498,1.561108,0.026997,1.0,1.0
22,Antigen Processing and Presentation of Peptide...,0.844698,1.558734,0.021251,1.0,1.0
23,Positive Regulation of Sprouting Angiogenesis ...,0.736308,1.557546,0.042067,1.0,1.0
25,Positive Regulation of Apoptotic Signaling Pat...,0.654014,1.544708,0.03744,1.0,1.0
28,Peptide Hormone Processing (GO:0016486),0.742659,1.529114,0.059929,1.0,1.0
33,Regulation of Mesenchymal Cell Proliferation (...,0.810176,1.516539,0.037759,1.0,1.0
34,Positive Regulation of ATP Metabolic Process (...,0.765289,1.51182,0.051251,1.0,1.0

In [7]:
# Enriched in iPSC path
pre_res.res2d.sort_values('NES', ascending=True).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]  # Top mESC

,Term,NES,NOM p-val,FWER p-val,FDR q-val
4,Chromatin Organization (GO:0006325),-1.740148,0.003165,0.508,0.95249
8,Protein Polyubiquitination (GO:0000209),-1.69159,0.002494,0.7605,1.0
9,DNA Metabolic Process (GO:0006259),-1.652498,0.011735,0.9135,1.0
13,Male Meiotic Nuclear Division (GO:0007140),-1.636868,0.000833,0.9525,1.0
15,Transcription by RNA Polymerase II (GO:0006366),-1.626133,0.004149,0.9685,1.0
16,Transcription Initiation-Coupled Chromatin Rem...,-1.600658,0.006071,0.9885,1.0
17,Regulation of Viral Genome Replication (GO:004...,-1.594761,0.017964,0.991,1.0
18,Regulation of Insulin Secretion (GO:0050796),-1.592851,0.008584,0.992,1.0
24,Visual System Development (GO:0150063),-1.552392,0.006809,0.999,1.0
26,Negative Regulation of Bone Remodeling (GO:004...,-1.538783,0.006843,1.0,1.0
27,Female Gamete Generation (GO:0007292),-1.530514,0.023009,1.0,1.0
29,Defense Response to Virus (GO:0051607),-1.525263,0.019716,1.0,1.0
30,Phospholipid Transport (GO:0015914),-1.522562,0.024452,1.0,1.0
31,Regulation of Cholesterol Efflux (GO:0010874),-1.517735,0.011607,1.0,1.0
32,ATP Metabolic Process (GO:0046034),-1.516903,0.019749,1.0,1.0
35,Regulation of Organelle Organization (GO:0033043),-1.509551,0.026339,1.0,1.0
37,Negative Regulation of Protein Phosphorylation...,-1.505115,0.036379,1.0,1.0
38,Carbohydrate Metabolic Process (GO:0005975),-1.503639,0.01815,1.0,1.0
39,Positive Regulation of Protein Secretion (GO:0...,-1.49335,0.038875,1.0,1.0
40,Chromatin Remodeling (GO:0006338),-1.492531,0.046319,1.0,1.0

## GO molecular function

In [8]:
rank_data = driver_df[["gene_names", "Day 12 Control_corr"]].sort_values('Day 12 Control_corr', ascending=False).dropna()

# Run GSEA Prerank
pre_res = gseapy.prerank(
    rnk=rank_data, 
    gene_sets="GO_Molecular_Function_2025",
    threads=16,
    min_size=5,
    max_size=1000,
    permutation_num=2000
)

2026-02-02 11:09:29,168 [WARNING] Duplicated values found in preranked stats: 0.15% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

In [9]:
# Enriched in dead end

pre_res.res2d.sort_values("NES", ascending=False).head(20)[["Term", "ES", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]] # Top Day 12

,Term,ES,NES,NOM p-val,FWER p-val,FDR q-val
0,Chemokine Receptor Binding (GO:0042379),0.785248,1.921597,0.0,0.0225,0.028389
1,Cysteine-Type Endopeptidase Activity (GO:0004197),0.679228,1.680922,0.014252,0.457,0.374682
3,Exopeptidase Activity (GO:0008238),0.800233,1.647327,0.023284,0.577,0.36138
4,Chemokine Activity (GO:0008009),0.710391,1.628463,0.024643,0.6415,0.330893
6,Cysteine-Type Peptidase Activity (GO:0008234),0.613392,1.593236,0.02439,0.7675,0.376664
7,Carboxypeptidase Activity (GO:0004180),0.763355,1.589139,0.029817,0.781,0.326742
11,Monoatomic Cation Channel Activity (GO:0005261),0.663853,1.555057,0.040342,0.8685,0.377016
12,GTP Binding (GO:0005525),0.534418,1.522445,0.021978,0.933,0.429786
13,Phosphatase Binding (GO:0019902),0.674406,1.491764,0.068075,0.9625,0.476126
14,Guanyl Ribonucleotide Binding (GO:0032561),0.489552,1.46521,0.035088,0.9835,0.516413
15,Endopeptidase Activity (GO:0004175),0.43109,1.452261,0.018362,0.9875,0.511636
18,G Protein-Coupled Peptide Receptor Activity (G...,0.673691,1.410032,0.092994,0.996,0.608802
19,Alcohol Dehydrogenase (NADP+) Activity (GO:000...,0.744777,1.403588,0.10782,0.9965,0.583026
22,Metalloexopeptidase Activity (GO:0008235),0.599792,1.355053,0.129545,0.9995,0.700199
28,Metallocarboxypeptidase Activity (GO:0004181),0.681644,1.290891,0.204152,1.0,0.881024
33,SH3 Domain Binding (GO:0017124),0.607021,1.261696,0.214876,1.0,0.938479
34,Protein Serine/Threonine Kinase Activator Acti...,0.544584,1.261308,0.190594,1.0,0.884976
35,Calcium Channel Activity (GO:0005262),0.603794,1.259642,0.209639,1.0,0.841226
37,Phosphatase Activator Activity (GO:0019211),0.672701,1.251967,0.223934,1.0,0.822577
39,Protein Kinase Activator Activity (GO:0030295),0.457253,1.239939,0.156331,1.0,0.821889

In [10]:
# Enriched in iPSC path
pre_res.res2d.sort_values('NES', ascending=True).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]  # Top mESC

,Term,NES,NOM p-val,FWER p-val,FDR q-val
2,mRNA Binding (GO:0003729),-1.662355,0.006809,0.282,0.370934
5,Iron Ion Binding (GO:0005506),-1.598965,0.004992,0.549,0.462834
8,2-Oxoglutarate-Dependent Dioxygenase Activity ...,-1.5827,0.007765,0.616,0.371886
9,Methylated Histone Binding (GO:0035064),-1.558144,0.009821,0.73,0.304556
10,Methylation-Dependent Protein Binding (GO:0140...,-1.558144,0.009821,0.73,0.304556
16,Protein Kinase C Binding (GO:0005080),-1.430195,0.064378,0.9865,0.924556
17,Guanyl-Nucleotide Exchange Factor Activity (GO...,-1.423662,0.079723,0.9915,0.841862
20,Single-Stranded DNA Binding (GO:0003697),-1.375777,0.094872,0.998,1.0
21,Ubiquitin Binding (GO:0043130),-1.359001,0.102322,0.999,1.0
23,GTPase Regulator Activity (GO:0030695),-1.328511,0.101404,1.0,1.0
24,Nuclear Receptor Binding (GO:0016922),-1.299989,0.14346,1.0,1.0
25,Epidermal Growth Factor Receptor Binding (GO:0...,-1.299211,0.124783,1.0,1.0
26,Ubiquitin-Like Ligase-Substrate Adaptor Activi...,-1.298579,0.150895,1.0,1.0
27,GTPase Activator Activity (GO:0005096),-1.297614,0.130506,1.0,1.0
29,Protein Serine/Threonine Kinase Inhibitor Acti...,-1.288885,0.154321,1.0,1.0
30,Ubiquitin-Protein Transferase Activity (GO:000...,-1.277568,0.128874,1.0,1.0
31,RNA Polymerase II-specific DNA-binding Transcr...,-1.273207,0.111806,1.0,1.0
32,Inorganic Cation Transmembrane Transporter Act...,-1.265459,0.172145,1.0,0.987834
36,Endopeptidase Activator Activity (GO:0061133),-1.253259,0.179595,1.0,1.0
38,Magnesium Ion Binding (GO:0000287),-1.246738,0.180051,1.0,0.987402

## MSigDB_Hallmark_2020

In [11]:
rank_data = driver_df[["gene_names", "Day 12 Control_corr"]].sort_values('Day 12 Control_corr', ascending=False).dropna()

# Run GSEA Prerank
pre_res = gseapy.prerank(
    rnk=rank_data, 
    gene_sets='MSigDB_Hallmark_2020', # Or other libraries
    threads=16,
    min_size=5,
    max_size=1000,
)

2026-02-02 11:09:46,565 [WARNING] Duplicated values found in preranked stats: 0.15% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

In [12]:
# Enriched in dead end

pre_res.res2d.sort_values('NES', ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]] # Top Day 12

                             Term       NES NOM p-val FWER p-val FDR q-val
1                     p53 Pathway  1.606321  0.002924      0.215  0.471552
2         Estrogen Response Early  1.566862  0.008086      0.284  0.317462
3         Cholesterol Homeostasis  1.501027  0.042184      0.433  0.370063
5               Androgen Response   1.43902  0.051213      0.555  0.410751
10            Allograft Rejection  1.363014  0.043732      0.738  0.535044
11         Estrogen Response Late  1.361683  0.043732       0.74  0.449274
12      Unfolded Protein Response  1.334365  0.142512      0.781  0.440256
13           IL-2/STAT5 Signaling  1.286976  0.059155      0.868  0.505433
15               mTORC1 Signaling  1.235128  0.136483      0.931  0.588099
16     Wnt-beta Catenin Signaling  1.231807  0.207254      0.935  0.536715
17       PI3K/AKT/mTOR  Signaling  1.212622  0.195804      0.953  0.532648
18                 Myc Targets V1  1.200494  0.252927      0.959  0.521523
19              KRAS Signaling Dn  1.161954  0.202532      0.973  0.576087
20  TNF-alpha Signaling via NF-kB  1.125914  0.197568      0.986  0.636648
21                    Pperoxisome  1.115511  0.320099       0.99  0.623909
22                      Apoptosis  1.115361  0.210526       0.99  0.585263
23                 UV Response Up   1.09651  0.278689       0.99  0.600197
24          Xenobiotic Metabolism  1.089579  0.288952      0.991   0.58552
25       IL-6/JAK/STAT3 Signaling  1.050553  0.355795      0.996    0.6573
27          Inflammatory Response  1.019662  0.403561      0.998  0.705935

In [13]:
# Enriched in iPSC path
pre_res.res2d.sort_values('NES', ascending=True).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]  # Top mESC

                                 Term       NES NOM p-val FWER p-val FDR q-val
0                     G2-M Checkpoint -1.633574  0.006154      0.136  0.073812
4                     Spermatogenesis -1.468485  0.060914      0.584  0.227791
6                          DNA Repair -1.435023  0.052901      0.678  0.197484
7           Oxidative Phosphorylation -1.399611  0.067395      0.779  0.204328
8                     Mitotic Spindle  -1.38439  0.061934      0.817  0.182331
9                         E2F Targets -1.378906  0.078947      0.831  0.159193
14          Interferon Alpha Response -1.272851  0.124611      0.967  0.275207
26                       Adipogenesis -1.022899  0.424961        1.0  0.798308
30               Bile Acid Metabolism -0.923083  0.587931        1.0  0.989322
31          Interferon Gamma Response -0.839844   0.77259        1.0       1.0
32                    Apical Junction -0.803911  0.834337        1.0       1.0
38                        Coagulation -0.760211     0.875        1.0       1.0
40                     UV Response Dn -0.730438  0.932847        1.0       1.0
41    Reactive Oxygen Species Pathway -0.723653  0.828423        1.0  0.968008
46              Fatty Acid Metabolism -0.647092  0.942717        1.0  0.961122
48  Epithelial Mesenchymal Transition  0.609131       1.0        1.0  0.976084
47                 Hedgehog Signaling  0.620506  0.946602        1.0       1.0
45                Pancreas Beta Cells  0.669182  0.860911        1.0       1.0
44                         Glycolysis  0.678488  0.975138        1.0       1.0
43                     Apical Surface  0.702693  0.874372        1.0       1.0

## Cell types

In [14]:
rank_data = driver_df[["gene_names", "Day 12 Control_corr"]].sort_values('Day 12 Control_corr', ascending=False).dropna()

# Run GSEA Prerank
pre_res = gseapy.prerank(
    rnk=rank_data, 
    gene_sets='PanglaoDB_Augmented_2021', # Or other libraries
    threads=16,
    min_size=5,
    max_size=1000,
)

# Enriched in dead end

pre_res.res2d.sort_values('NES', ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]] # Top Day 12

2026-02-02 11:10:02,435 [WARNING] Duplicated values found in preranked stats: 0.15% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

                        Term       NES NOM p-val FWER p-val FDR q-val
0        Gastric Chief Cells  2.220668       0.0        0.0       0.0
1      Salivary Mucous Cells  2.177413       0.0        0.0       0.0
2             Cholangiocytes  2.036495       0.0      0.003  0.001335
3   Mammary Epithelial Cells  2.030373       0.0      0.004  0.001335
4              Keratinocytes  1.999058       0.0      0.011  0.003203
5   Luminal Epithelial Cells  1.982635       0.0      0.016  0.003782
6             Foveolar Cells  1.968645       0.0      0.018  0.003623
8            Microfold Cells  1.925072       0.0      0.023  0.004004
9                  Sebocytes  1.910495       0.0      0.026  0.004152
10          Epithelial Cells  1.905622       0.0      0.029  0.004137
11          Urothelial Cells  1.898278  0.002445       0.03  0.004004
12               Trichocytes  1.881104   0.00271      0.039  0.004671
13    Trophoblast Stem Cells  1.872717       0.0      0.042  0.004928
14       Airway Goblet Cells  1.869159       0.0      0.044  0.005053
15              Goblet Cells  1.830768       0.0       0.07  0.007207
16              Hepatoblasts  1.798959  0.002681        0.1  0.010093
17              Ductal Cells  1.798245       0.0      0.102  0.009657
18              Merkel Cells  1.745493  0.005376      0.194  0.017795
19           Principal Cells  1.733442  0.005602      0.215  0.019528
21         Trophoblast Cells  1.705674  0.002755      0.272  0.024291

In [15]:
# Enriched in iPSC path
pre_res.res2d.sort_values('NES', ascending=True).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]  # Top mESC

                         Term       NES NOM p-val FWER p-val FDR q-val
7      Pluripotent Stem Cells -1.965991       0.0      0.002   0.00242
20             Epiblast Cells -1.723253  0.001567      0.147  0.079066
23       Embryonic Stem Cells -1.569442  0.002994      0.639  0.357948
24        Gamma Delta T Cells -1.568614  0.015385      0.641  0.270075
27              Oxyphil Cells -1.466755  0.054098      0.918  0.547491
30         Adrenergic Neurons -1.414405  0.055456      0.969  0.700029
31            Ependymal Cells  -1.40723  0.076285      0.972  0.635755
32                   Myocytes -1.403557  0.047544      0.974  0.573631
36                 Osteocytes -1.338558  0.067976      0.996  0.828668
39                  Microglia -1.309889  0.071429      0.999  0.903691
40      Proximal Tubule Cells -1.292699  0.152318        1.0  0.916959
42             Decidual Cells -1.250572   0.15873        1.0       1.0
44                Delta Cells -1.221862  0.177953        1.0       1.0
46              Reticulocytes -1.207186   0.22735        1.0       1.0
47           Gamma (PP) Cells  -1.20344    0.1952        1.0       1.0
51         T Regulatory Cells  -1.14458   0.25641        1.0       1.0
54                 Germ Cells -1.112678  0.309836        1.0       1.0
55  T Follicular Helper Cells -1.107958   0.31962        1.0       1.0
57                Eosinophils -1.104164  0.293578        1.0       1.0
58                Neutrophils -1.100323  0.331269        1.0       1.0

Epithelial markers are strongly enriched among the control drivers

## ChipSeq targets, ChEA

In [16]:
rank_data = driver_df[["gene_names", "Day 12 Control_corr"]].sort_values('Day 12 Control_corr', ascending=False).dropna()

# Run GSEA Prerank
pre_res = gseapy.prerank(
    rnk=rank_data, 
    gene_sets='ChEA_2022', # Or other libraries
    threads=16,
    min_size=5,
    max_size=1000
)

2026-02-02 11:10:14,662 [WARNING] Duplicated values found in preranked stats: 0.15% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

In [17]:
# Enriched in dead end

pre_res.res2d.sort_values('NES', ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]] # Top Day 12

,Term,NES,NOM p-val,FWER p-val,FDR q-val
24,RARG 19884340 ChIP-ChIP MEFs Mouse,1.730881,0.0,0.221,0.318778
26,JARID2 20075857 ChIP-Seq MESCs Mouse,1.713658,0.0,0.248,0.183671
29,SUZ12 18974828 ChIP-Seq MESCs Mouse,1.686985,0.0,0.3,0.154408
38,MTF2 20144788 ChIP-Seq MESCs Mouse,1.639123,0.0,0.429,0.183671
42,SUZ12 27294783 Chip-Seq ESCs Mouse,1.612293,0.0,0.503,0.183546
49,SUZ12 20075857 ChIP-Seq MESCs Mouse,1.550556,0.0,0.699,0.267101
51,TP63 17297297 ChIP-ChIP HaCaT Human,1.54484,0.007712,0.72,0.24104
52,PITX1 30713093 ChIP-Seq Epithelial Human Tongu...,1.543706,0.027569,0.724,0.212
58,TP63 30713093 ChIP-Seq Epithelial Human Tongue...,1.507623,0.0,0.819,0.253473
62,JARID2 20064375 ChIP-Seq MESCs Mouse,1.493164,0.0,0.852,0.25689
64,ESR1 26153859 ChIP-Seq MCF-7 Human BreastCancer,1.476982,0.0,0.889,0.26263
71,BMI1 19503595 ChIP-Seq MEFsC Mouse,1.447041,0.006369,0.931,0.309335
74,TFAP2C 20629094 ChIP-Seq MCF-7 Human,1.438241,0.0,0.942,0.305368
76,EED 16625203 ChIP-ChIP MESCs Mouse,1.415037,0.010381,0.963,0.339146
77,ESR1 20056654 ChIP-Seq MCF-7 Human BreastCancer,1.408286,0.019868,0.965,0.332973
78,PHC1 16625203 ChIP-ChIP MESCs Mouse,1.401036,0.010949,0.97,0.330919
80,P63 26484246 Chip-Seq KERATINOCYTES Human,1.387926,0.0,0.977,0.345001
85,BMI1 23680149 ChIP-Seq NPCS Mouse,1.371994,0.0,0.987,0.370524
88,WDR5 24793694 ChIP-Seq LNCAP Human,1.362843,0.022876,0.991,0.376845
92,TP53 32428506 ChIP-Seq Human Liver Heptoma,1.354299,0.04712,0.992,0.380479

In [18]:
# Enriched in iPSC path
pre_res.res2d.sort_values('NES', ascending=True).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]  # Top mESC

,Term,NES,NOM p-val,FWER p-val,FDR q-val
0,FOXM1 23109430 ChIP-Seq U2OS Human,-2.069772,0.0,0.0,0.0
1,SMAD1 18555785 ChIP-Seq MESCs Mouse,-2.06917,0.0,0.0,0.0
2,TCF3 18692474 ChIP-Seq MESCs Mouse,-2.031116,0.0,0.0,0.0
3,MYBL2 22936984 ChIP-ChIP MESCs Mouse,-2.028174,0.0,0.0,0.0
4,NACC1 18358816 ChIP-ChIP MESCs Mouse,-2.026743,0.0,0.0,0.0
5,NANOG 18700969 ChIP-ChIP MESCs Mouse,-1.998373,0.0,0.0,0.0
6,NANOG 18555785 ChIP-Seq MESCs Mouse,-1.925797,0.0,0.004,0.000518
7,SOX2 18692474 ChIP-Seq MESCs Mouse,-1.921982,0.0,0.004,0.000454
8,POU5F1 18358816 ChIP-ChIP MESCs Mouse,-1.919393,0.0,0.005,0.000504
9,POU5F1 18700969 ChIP-ChIP MESCs Mouse,-1.909834,0.0,0.006,0.000544
10,SALL4 18804426 ChIP-ChIP MESCs Mouse,-1.902568,0.0,0.006,0.000495
11,SOX2 18358816 ChIP-ChIP MESCs Mouse,-1.868639,0.0,0.014,0.001058
12,TCF3 18692474 ChIP-Seq MEFs Mouse,-1.865596,0.0,0.014,0.000977
13,SOX2 19030024 ChIP-ChIP MESCs Mouse,-1.858952,0.0,0.016,0.001037
14,SOX2 18555785 ChIP-Seq MESCs Mouse,-1.846268,0.0,0.022,0.001331
15,KDM5B 21448134 ChIP-Seq MESCs Mouse,-1.835099,0.0,0.027,0.001531
16,SMAD3 22036565 ChIP-Seq ESCs Mouse,-1.830427,0.0,0.031,0.001654
17,POU5F1 18555785 ChIP-Seq MESCs Mouse,-1.82865,0.0,0.031,0.001562
18,SOX2 18692474 ChIP-Seq MEFs Mouse,-1.821246,0.0,0.036,0.001719
19,MYC 19079543 ChIP-ChIP MESCs Mouse,-1.812203,0.0,0.042,0.001996

## Enriched targets from ChipSeq, Ensembl

In [19]:
rank_data = driver_df[["gene_names", "Day 12 Control_corr"]].sort_values('Day 12 Control_corr', ascending=False).dropna()

# Run GSEA Prerank
pre_res = gseapy.prerank(
    rnk=rank_data, 
    gene_sets='ENCODE_TF_ChIP-seq_2015', # Or other libraries
    threads=16,
    min_size=5,
    max_size=1000
)

2026-02-02 11:11:13,634 [WARNING] Duplicated values found in preranked stats: 0.15% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

In [20]:
# Enriched in dead end

pre_res.res2d.sort_values('NES', ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]] # Top Day 12

                     Term       NES NOM p-val FWER p-val FDR q-val
1         FOSL1 C2C12 mm9   1.96268       0.0      0.019  0.021294
8    SMARCC1 HeLa-S3 hg19  1.723216       0.0      0.208  0.135609
21        ZEB1 HepG2 hg19  1.635744   0.01039      0.412  0.216301
23       TAL1 G1E-ER4 mm9  1.616329       0.0      0.468  0.200051
25         ATF3 K562 hg19  1.570052       0.0      0.611  0.257993
31       EP300 ECC-1 hg19  1.540566  0.003077      0.698  0.279623
42   SMARCC2 HeLa-S3 hg19  1.498257  0.016393      0.799  0.350949
46        MAX myocyte mm9   1.47301  0.009375       0.86  0.381329
48       RAD21 ECC-1 hg19  1.462772  0.010239      0.878  0.370713
52      JUND GM12878 hg19  1.447306  0.033766      0.904  0.381609
65       JUND HCT116 hg19  1.403056  0.034286      0.951  0.504228
75        REST ECC-1 hg19  1.376335  0.009346      0.973  0.574842
87      JUND HeLa-S3 hg19  1.355251  0.008163       0.98  0.632697
88       EP300 MCF-7 hg19  1.352326  0.086849      0.981  0.603755
90      ZEB1 GM12878 hg19  1.345172  0.053521      0.983  0.597052
98        JUND MCF-7 hg19  1.333123  0.096953      0.989  0.618364
100     FOSL1 HCT116 hg19  1.332924  0.056047      0.989  0.582913
116     JUND SK-N-SH hg19  1.301097  0.015873      0.997   0.71098
117       MYOD1 C2C12 mm9  1.297376  0.012195      0.997  0.694854
123     REST U-87 MG hg19  1.291483  0.093085      0.997  0.692725

In [21]:
# Enriched in iPSC path
pre_res.res2d.sort_values('NES', ascending=True).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]  # Top mESC

                      Term       NES NOM p-val FWER p-val FDR q-val
0   E2F4 MEL cell line mm9 -2.037147       0.0        0.0       0.0
2         FOXM1 ECC-1 hg19 -1.840812       0.0      0.028  0.013301
3        IRF3 GM12878 hg19 -1.807172       0.0      0.046  0.015201
4         E2F4 CH12.LX mm9 -1.804058       0.0      0.048  0.011876
5       NANOG H1-hESC hg19 -1.740666  0.001751      0.147  0.033442
6        E2F4 HeLa-S3 hg19 -1.736897       0.0      0.155  0.029926
7            SP2 K562 hg19 -1.735902       0.0      0.158  0.026194
9        NFYA GM12878 hg19 -1.717984       0.0      0.213  0.031945
10           FOS K562 hg19 -1.694223       0.0      0.281  0.040535
11        FOXM1 MCF-7 hg19 -1.691418  0.003205      0.289  0.037812
12      FOXM1 GM12878 hg19 -1.688037  0.002994      0.296  0.035756
13          NFYA K562 hg19 -1.680696       0.0      0.321   0.03626
14        CEBPZ HepG2 hg19 -1.672155  0.003091      0.345  0.037344
15       IRF3 HeLa-S3 hg19 -1.667803  0.001416      0.354  0.036848
16         TCF12 A549 hg19  -1.66095   0.00597      0.375  0.037305
17        SETDB1 U2OS hg19 -1.654646  0.001429      0.401   0.03818
18          SP2 HepG2 hg19 -1.653259       0.0      0.407  0.036437
19     STAT5A GM12878 hg19 -1.652922  0.001572      0.408  0.034518
20       E2F4 GM12878 hg19 -1.638903       0.0      0.453  0.038702
22         KAT2B K562 hg19 -1.623784       0.0       0.52  0.044462

## TF Perturbation followed by expression

In [11]:
rank_data = driver_df[["gene_names", "Day 12 Control_corr"]].sort_values('Day 12 Control_corr', ascending=False).dropna()

# Run GSEA Prerank
pre_res = gseapy.prerank(
    rnk=rank_data, 
    gene_sets="TF_Perturbations_Followed_by_Expression",
    threads=16,
    min_size=5,
    max_size=1000
)

2026-02-06 14:50:11,378 [WARNING] Duplicated values found in preranked stats: 0.15% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

In [12]:
# Enriched in dead end

pre_res.res2d.sort_values('NES', ascending=False).head(30) # Top Day 12

,Name,Term,ES,NES,NOM p-val,FDR q-val,FWER p-val,Tag %,Gene %,Lead_genes
19,prerank,IRF6 KO MOUSE GSE5800 CREEDSID GENE 153 UP,0.540459,1.909149,0.0,0.15048,0.125,29/70,15.17%,Lgals7;S100a16;Prr13;Lad1;Dsp;Gsto1;Pkp1;Perp;...
24,prerank,PPARA KO MOUSE GSE6864 CREEDSID GENE 981 UP,0.537065,1.893438,0.0,0.098468,0.164,27/67,13.87%,Ctsz;Prr13;Lad1;Gsto1;Ifi30;Cdkn1a;Krt8;Dgat2;...
25,prerank,HSF1 KO MOUSE GSE41005 CREEDSID GENE 2143 DOWN,0.692002,1.888126,0.0,0.070022,0.174,9/20,5.66%,Lad1;Ccnd2;Fabp5;Pla2g12a;Tuba4a;Ifrd1;Myc;Atf...
32,prerank,PPARA KO MOUSE GSE6864 CREEDSID GENE 1371 DOWN,0.525552,1.856044,0.0,0.082562,0.245,27/68,13.87%,Ctsz;Prr13;Lad1;Gsto1;Ifi30;Cdkn1a;Krt8;Dgat2;...
36,prerank,OVOL2 OE MOUSE GSE55074 CREEDSID GENE 2603 DOWN,0.525539,1.837582,0.0,0.079785,0.294,26/56,14.02%,Lgals7;S100a16;Dsp;Gsto1;Ccnd2;Pkp1;Perp;Fabp5...
37,prerank,PPARA DEFICIENCY MOUSE GSE6864 CREEDSID GENE 6...,0.517132,1.823507,0.0,0.076755,0.324,26/67,13.87%,Ctsz;Prr13;Lad1;Dsp;Gsto1;Krt8;Sat1;Tuba4a;Mis...
42,prerank,MYC KD HUMAN GSE22139 CREEDSID GENE 712 DOWN,0.632107,1.799886,0.0,0.085411,0.402,13/22,13.92%,Ccnd2;Fabp5;Ifrd1;Myc;Tmem147;Zfas1;Snhg1;Ppa1...
46,prerank,YY1 KD MOUSE GSE31784 CREEDSID GENE 1333 UP,0.551954,1.78812,0.0,0.085213,0.447,16/40,14.02%,Lad1;Gsto1;Ly6g6c;Dgat2;Tubb3;Gpx2;Gatm;Pcolce...
50,prerank,MYC OE MOUSE GSE55272 CREEDSID GENE 1822 DOWN,0.528913,1.771201,0.0,0.089211,0.496,13/50,6.06%,Lgals7;Dsp;Mal2;Perp;Ly6g6c;Ovol1;Anxa8;Krt17;...
53,prerank,PPARG OE MOUSE GSE2192 CREEDSID GENE 863 UP,0.528059,1.765647,0.002994,0.084733,0.512,21/48,13.82%,Nupr1;Fabp5;Pla2g12a;Cdkn1a;Mgst3;Tmem147;Tob1...
54,prerank,NFE2L2 KO MOUSE GSE18344 CREEDSID GENE 965 DOWN,0.494241,1.752983,0.0,0.089884,0.557,13/65,6.26%,Tmem238;Uchl1;Lad1;Gsto1;Tppp3;Aldh3a1;Gpx2;Mi...
58,prerank,ESR2 KO MOUSE GSE1050 CREEDSID GENE 901 UP,0.637616,1.735298,0.005089,0.100993,0.619,6/21,5.36%,Homer2;Gsto1;Pla2g12a;Tuba4a;Mgst3;Ablim1
59,prerank,KLF1 KO MOUSE GSE36427 CREEDSID GENE 1562 DOWN,0.594337,1.73016,0.01269,0.098896,0.639,10/26,8.11%,Prr13;Homer2;Kcnn4;B2m;Plek2;Ifrd1;Ptp4a3;Mgst...
64,prerank,RUNX1 KO MOUSE GSE47375 CREEDSID GENE 2899 UP,0.467313,1.719015,0.0,0.102148,0.675,29/91,14.27%,Lgals7;S100a16;Lad1;Kcnn4;Pkp1;Fabp5;Cdkn1a;Kr...
71,prerank,KLF3 KO MOUSE GSE35592 CREEDSID GENE 2672 UP,0.491377,1.703009,0.00303,0.112776,0.73,25/57,15.92%,Crip2;Prr13;Dkkl1;Tppp3;Cdkn1a;Nrip3;Plek2;Lmn...
81,prerank,MBD3 KD MOUSE GSE31008 CREEDSID GENE 1325 UP,0.461809,1.668713,0.0,0.150354,0.833,25/78,12.42%,Lgals7;Lad1;Crb3;Mal2;Perp;Gpx2;Tnfrsf13c;S100...
83,prerank,NR1I2 KO MOUSE GSE23780 CREEDSID GENE 2165 DOWN,0.633347,1.661774,0.012563,0.150124,0.846,6/17,17.58%,Tppp3;Cdkn1a;Alox12b;Map4k1;Pdlim4;Scara5
84,prerank,HNF4A MUT MOUSE GSE3116 CREEDSID GENE 850 DOWN,0.481316,1.658569,0.0,0.146945,0.849,26/55,19.03%,Rtn4r;Ifi30;Krt8;Spint2;Gatm;Smpdl3a;Mgst3;Ggh...
87,prerank,HSF1 KD HUMAN GSE3697 CREEDSID GENE 782 UP,0.479211,1.641145,0.005935,0.166373,0.897,21/57,16.88%,Dsp;Nupr1;Sat1;Plek2;Ifrd1;Krt17;Smagp;Krt14;A...
89,prerank,OVOL1 KO MOUSE GSE55071 CREEDSID GENE 2560 UP,0.471385,1.637352,0.009231,0.164367,0.901,21/60,17.03%,Lgals7;Mal2;Fabp5;Ly6g6c;Krt17;Myc;Ggh;Krt14;C...
90,prerank,KDM2B KD MOUSE GSE41298 CREEDSID GENE 1376 UP,0.457187,1.637179,0.0,0.157021,0.901,26/67,18.73%,Crip2;Gsto1;Ccnd2;Perp;Krt8;Gatm;Cbr3;Myc;Anxa...
95,prerank,FOXP3 OE SW780 HUMAN GSE81157 RNASEQ DOWN,0.479116,1.619195,0.002933,0.17683,0.928,13/50,7.36%,Lad1;Dsp;Perp;Cdkn1a;Cd44;Tuba4a;Lmna;Krt17;Kr...
96,prerank,PAX5 OE HUMAN GSE44244 CREEDSID GENE 575 DOWN,0.63849,1.617816,0.018229,0.171733,0.932,8/16,12.77%,Psmb10;Emp3;Emb;Gng2;Tubgcp3;Abracl;Atf5;Tenm3
105,prerank,OVOL1 KO MOUSE GSE55072 CREEDSID GENE 2617 UP,0.442328,1.578942,0.006369,0.236493,0.97,30/71,17.28%,Mal2;Gsto1;Pkp1;Nupr1;Fabp5;Ly6g6c;B2m;Emp2;Sp...
110,prerank,PPARA KO MOUSE GSE6864 CREEDSID GENE 1373 UP,0.441236,1.568027,0.008333,0.250827,0.981,22/71,13.67%,Ctsz;Prr13;Ifi30;Cgref1;B2m;Krt8;Tuba4a;Gpx2;M...
111,prerank,NR3C1 KO MOUSE GSE23724 CREEDSID GENE 3014 DOWN,0.455144,1.567396,0.016575,0.242578,0.982,18/56,12.97%,Mal2;Gsto1;Cgref1;Krt8;Tuba4a;Ifrd1;Krt13;Myl7...
115,prerank,REST KD MOUSE GSE28141 CREEDSID GENE 1331 DOWN,0.441873,1.541513,0.002717,0.29318,0.993,23/57,17.28%,Crb3;Ifi30;Nupr1;Krt8;Spink2;Ctsb;Pcolce;Emp3;...
119,prerank,HEY2 KO MOUSE GSE6526 CREEDSID GENE 1511 UP,0.421241,1.534906,0.003096,0.289537,0.993,30/78,17.68%,S100a16;Pkp1;Cdkn1a;Cd44;Sat1;Anxa8;Tuba4a;Ifr...
118,prerank,HEY2 KO MOUSE GSE6526 CREEDSID GENE 1512 DOWN,0.421241,1.534906,0.003096,0.289537,0.993,30/78,17.68%,S100a16;Pkp1;Cdkn1a;Cd44;Sat1;Anxa8;Tuba4a;Ifr...
120,prerank,RARA KD HUMAN GSE26298 CREEDSID GENE 69 UP,0.419748,1.534216,0.003096,0.28167,0.993,31/85,13.87%,S100a16;Prr13;Dsp;Mal2;Ifi30;Cdkn1a;B2m;Krt8;S...

Many proteins related to Ovol1 appear, including Myc, Ovol2 and Ovol1 itself. Directions are inconsistent.

In [5]:
# Enriched in iPSC path
pre_res.res2d.sort_values('NES', ascending=True).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]  # Top mESC

,Term,NES,NOM p-val,FWER p-val,FDR q-val
0,NEUROG3 OE MOUSE GSE3653 CREEDSID GENE 1660 DOWN,-2.450379,0.0,0.0,0.0
1,NEUROG3 OE MOUSE GSE3653 CREEDSID GENE 2289 DOWN,-2.450205,0.0,0.0,0.0
2,MTF2 KD MOUSE GSE16364 CREEDSID GENE 1355 UP,-2.41091,0.0,0.0,0.0
3,ZFP42 KD MOUSE GSE9978 CREEDSID GENE 1334 UP,-2.360429,0.0,0.0,0.0
4,ZFX KO MOUSE GSE7069 CREEDSID GENE 177 DOWN,-2.248554,0.0,0.0,0.0
5,ZFP42 KD MOUSE GSE9978 CREEDSID GENE 1335 UP,-2.243119,0.0,0.0,0.0
6,MSGN1 OE MOUSE GSE29848 CREEDSID GENE 1629 DOWN,-2.189715,0.0,0.001,0.000142
7,NEUROG3 OE MOUSE GSE3653 CREEDSID GENE 2585 DOWN,-2.117429,0.0,0.002,0.000249
8,FOXD3 OE MOUSE GSE58960 CREEDSID GENE 1415 DOWN,-2.116637,0.0,0.002,0.000221
9,SOX2 KD MOUSE GSE39771 CREEDSID GENE 1757 DOWN,-2.112671,0.0,0.002,0.000199
10,SRF MUT MOUSE GSE1948 CREEDSID GENE 1400 DOWN,-2.088768,0.0,0.003,0.000271
11,KLF5 KO MOUSE GSE9244 CREEDSID GENE 580 DOWN,-2.007697,0.0,0.01,0.000829
12,SRF MUT MOUSE GSE1948 CREEDSID GENE 1395 UP,-1.977791,0.0,0.015,0.001148
13,GTF2I KO MOUSE GSE48790 CREEDSID GENE 1452 UP,-1.960666,0.0,0.019,0.001421
14,FOXD3 KO MOUSE GSE58960 CREEDSID GENE 1417 DOWN,-1.956398,0.0,0.02,0.001393
15,NEUROG3 OE MOUSE GSE3653 CREEDSID GENE 1658 DOWN,-1.942579,0.0,0.025,0.001679
16,CHD1 KO 22RV1 HUMAN GSE84610 RNASEQ DOWN,-1.939705,0.0,0.025,0.00158
17,MSGN1 OE MOUSE GSE29848 CREEDSID GENE 1630 DOWN,-1.923176,0.0,0.035,0.002045
18,TET1 KD MOUSE GSE26830 CREEDSID GENE 1353 DOWN,-1.91126,0.0,0.042,0.002356
20,PCGF6 KD MOUSE GSE56126 CREEDSID GENE 1340 DOWN,-1.90781,0.0,0.047,0.002537

## Test if specific gene sets are enriched

In [33]:
# Get libraries

panglao_lib = gseapy.get_library(name='PanglaoDB_Augmented_2021', organism='Mouse')
go_lib = gseapy.get_library(name='GO_Biological_Process_2025', organism='Mouse')
go_molecular_function = gseapy.get_library(name='GO_Molecular_Function_2025', organism='Mouse')
hallmark_lib = gseapy.get_library(name='MSigDB_Hallmark_2020', organism='Mouse')

In [34]:
target_sets = {
    "Apoptosis Activation": go_lib["Positive Regulation of Apoptotic Process (GO:0043065)"],
    "Apoptosis Inhibition": go_lib["Negative Regulation of Apoptotic Process (GO:0043066)"],
    "Cell Cycle Inhibition": go_lib["Negative Regulation of Cell Cycle (GO:0045786)"],
    "Cell Cycle Activation": go_lib["Positive Regulation of Cell Cycle (GO:0045787)"],
    "Apoptosis Signaling Inhibition": go_lib["Negative Regulation of Apoptotic Signaling Pathway (GO:2001234)"],
    "Apoptosis Signaling Activation": go_lib["Positive Regulation of Apoptotic Signaling Pathway (GO:2001235)"],
    "Stem Cell Proliferation": go_lib["Positive Regulation of Stem Cell Proliferation (GO:2000648)"],
    "Stem Cell Inhibited Proliferation": go_lib["Negative Regulation of Stem Cell Population Maintenance (GO:1902455)"],
    "Stem Cell Inhibited Differentiation": go_lib["Negative Regulation of Stem Cell Differentiation (GO:2000737)"],
    "Stem Cell Differentiation": go_lib["Positive Regulation of Stem Cell Differentiation (GO:2000738)"],
    "DNA Damage Response": go_lib["DNA Damage Response (GO:0006974)"],
    "DNA_Repair": hallmark_lib['DNA Repair'],
    "P53_Pathway": hallmark_lib['p53 Pathway'],
    "Keratinocytes": panglao_lib["Keratinocytes"],
    "Epithelial cells": panglao_lib["Epithelial Cells"]
}

rank_data = driver_df[["gene_names", "Day 12 Control_corr"]].sort_values('Day 12 Control_corr', ascending=False).dropna()

# Run GSEA Prerank
pre_res = gseapy.prerank(
    rnk=rank_data, 
    gene_sets=target_sets,
    threads=16,
    min_size=5,
    max_size=2000,
    permutation_num=1000,
    seed=0
)

pre_res.res2d.sort_values("NES", ascending=False).head(20)

2026-02-02 11:19:48,524 [WARNING] Duplicated values found in preranked stats: 0.15% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

,Name,Term,ES,NES,NOM p-val,FDR q-val,FWER p-val,Tag %,Gene %,Lead_genes
0,prerank,Keratinocytes,0.624645,2.0251,0.0,0.001222,0.001,22/41,17.03%,Lgals7;Lad1;Pkp1;Perp;Ovol1;Anxa8;S100a14;Krt1...
1,prerank,Epithelial cells,0.541295,1.924159,0.0,0.001222,0.002,32/67,19.08%,Lad1;Crb3;Mal2;Ovol1;Krt8;Dgat2;Gpx2;Misp;S100...
2,prerank,P53_Pathway,0.465473,1.60209,0.003289,0.032179,0.078,24/60,18.48%,Ccnd2;Ifi30;Nupr1;Perp;Cdkn1a;Sat1;Gpx2;Krt17;...
3,prerank,Apoptosis Signaling Activation,0.654014,1.540293,0.045024,0.038187,0.118,5/11,16.88%,Nupr1;Bbc3;App;Tnfrsf12a;Ddit3
7,prerank,Apoptosis Inhibition,0.210775,0.79448,0.944444,0.966599,0.978,18/107,15.12%,Ccnd2;Nupr1;Prkaa2;Cd44;Myc;Anxa5;Tmbim1;Ddah2...
10,prerank,Cell Cycle Inhibition,0.281041,0.694447,0.905,0.916497,0.988,1/14,1.40%,Nupr1
12,prerank,Apoptosis Signaling Inhibition,-0.238535,-0.560375,0.964346,0.984178,1.0,4/14,33.20%,Tcf7l2;Bmp4;Thbs1;Clu
11,prerank,Stem Cell Proliferation,-0.283705,-0.572438,0.962838,1.0,1.0,1/8,7.46%,Nanog
9,prerank,Cell Cycle Activation,-0.29015,-0.707803,0.871545,1.0,1.0,2/16,4.96%,Tcf7l1;Cited2
8,prerank,Apoptosis Activation,-0.241989,-0.775089,0.896603,1.0,1.0,29/63,37.66%,Dlc1;Rest;Gadd45b;Top2a;Bnip3;Tsc22d1;Sfrp1;Ec...
6,prerank,DNA Damage Response,-0.337952,-0.92416,0.543974,1.0,0.996,11/24,21.48%,Ash2l;Msh6;Nedd4;Top2a;Acer2;Fam111a;Brca1;Fbx...
5,prerank,Stem Cell Differentiation,-0.533121,-0.985243,0.517921,1.0,0.978,2/6,22.28%,Tcf15;Nr5a2
4,prerank,DNA_Repair,-0.722468,-1.421948,0.058419,0.313226,0.302,5/7,24.39%,Gpx4;Arl6ip1;Bcam;Pold4;Cda

# Differential expression analysis with Scanpy

Scanpy uses a Wilcoxon rank sum test.

In [5]:
# Assign each cell to the most likely macrostate

macrostates = adata.uns["coarse_fwd"].obs["coarse_init_dist"].index.to_list()
macrostate_assignment = [macrostates[numpy.argmax(macrostate_probabilities)] for macrostate_probabilities in adata.obsm["macrostates_fwd_memberships"]]
adata.obs["macrostate"] = macrostate_assignment
adata.uns["macrostate_colors"] = [
    adata.uns["macrostates_fwd_colors"][5],
    adata.uns["macrostates_fwd_colors"][2],
    adata.uns["macrostates_fwd_colors"][3],
    adata.uns["macrostates_fwd_colors"][4],
    adata.uns["macrostates_fwd_colors"][1],
    adata.uns["macrostates_fwd_colors"][0],
    adata.uns["macrostates_fwd_colors"][6]
]

## Comparison between all macrostates

In [13]:
# perform differential expression using the standard wilcoxon rank-sum test
scanpy.tl.rank_genes_groups(
    adata,
    groupby="macrostate",
    method="wilcoxon",
    use_raw=False,
    key_added="macrostate_rank_genes"
)

# extract the results into a dataframe for a specific target macrostate
dead_end_rank_df = scanpy.get.rank_genes_groups_df(
    adata,
    key="macrostate_rank_genes",
    group="Day 12 Control"
)
dead_end_rank_df.index = dead_end_rank_df["names"]
dead_end_rank_df = dead_end_rank_df.drop(columns="names")

control_rank_df = scanpy.get.rank_genes_groups_df(
    adata,
    key="macrostate_rank_genes",
    group="Day 4 Control"
)
control_rank_df.index = control_rank_df["names"]
control_rank_df = control_rank_df.drop(columns="names")

In [36]:
dead_end_rank_df.head(20)

                  scores  logfoldchanges          pvals      pvals_adj
names
Zfas1          26.189415        2.912675  3.507877e-151  7.015755e-148
2410006H16Rik  25.884188        2.383039  1.003519e-147  1.003519e-144
Snhg1          24.932861        2.789920  3.276535e-137  2.184357e-134
1110038B12Rik  24.600237        2.454037  1.255827e-133  6.279133e-131
Snhg12         24.165182        3.138035  5.170944e-129  2.068378e-126
Gas5           23.397280        1.672911  4.554957e-121  1.518319e-118
Ifrd1          22.545397        2.568011  1.490053e-112  4.257295e-110
Cdkn1a         21.841169        2.205297  9.431106e-106  2.357776e-103
Ppp1r15a       21.520761        2.846743  9.951511e-103  2.211447e-100
Aqp3           21.424622        4.537375  7.877358e-102   1.575472e-99
Crb3           21.262957        2.924304  2.501539e-100   4.548253e-98
Bbc3           20.421621        2.746830   1.074389e-92   1.652905e-90
Perp           19.625084        2.268659   9.442086e-86   1.258945e-83
Dkkl1          19.578817        3.210852   2.343994e-85   2.929992e-83
Lgals7         19.447018        3.746449   3.088836e-84   3.251406e-82
Cstb           19.170475        1.550161   6.531087e-82   6.220083e-80
Atf3           18.789471        4.924244   9.209480e-79   8.372254e-77
Dsp            18.772705        2.404867   1.262886e-78   1.057323e-76
Tmem43         18.663662        2.369165   9.779289e-78   7.823431e-76
Gch1           18.633204        3.026248   1.728618e-77   1.329706e-75

In [37]:
# Most upregulated transcription factors in dead end

dead_end_rank_df.loc[numpy.intersect1d(tf_array, adata.var_names)].sort_values("scores", ascending=False).head(30)

            scores  logfoldchanges         pvals     pvals_adj
names
Atf3     18.789471        4.924244  9.209480e-79  8.372254e-77
Maff     14.781541        3.392600  1.927055e-49  5.416949e-48
Ddit3    13.226619        2.166627  6.159631e-40  1.140672e-38
Myc      12.562806        1.828156  3.381229e-36  5.162181e-35
Ovol1    12.100735        2.972715  1.046704e-33  1.443730e-32
Klf10    12.000822        1.918085  3.517865e-33  4.753872e-32
Arid3a   10.603693        1.693256  2.864403e-26  2.822072e-25
Zbtb7c   10.598906        1.849738  3.014877e-26  2.955762e-25
Junb     10.341942        1.311702  4.552173e-25  4.234580e-24
Zbtb10   10.224051        2.126627  1.547362e-24  1.369347e-23
Crebrf    8.973886        1.998747  2.862334e-19  1.889330e-18
Klf4      8.294026        1.242020  1.094780e-16  6.185198e-16
Phox2a    7.614943        2.153333  2.638079e-14  1.253244e-13
Zfp296    7.220187        1.331148  5.191626e-13  2.297180e-12
Bhlhe40   6.915652        1.692661  4.657153e-12  1.944531e-11
Barx2     6.472987        2.666481  9.608440e-11  3.660358e-10
Hes1      5.985631        1.224554  2.155524e-09  7.549997e-09
Zfp750    5.818898        3.017764  5.923691e-09  1.994509e-08
Rora      5.491565        2.064828  3.983887e-08  1.235314e-07
Dmrtc2    5.071731        1.206740  3.942134e-07  1.124717e-06
Fosl2     4.655017        1.037758  3.239530e-06  8.469360e-06
Tlx2      4.417089        0.874272  1.000390e-05  2.513543e-05
Gata2     4.296226        2.146550  1.737303e-05  4.252883e-05
Zfhx3     4.086668        0.396962  4.376116e-05  1.028464e-04
Klf6      4.005980        0.701633  6.176074e-05  1.427994e-04
Lef1      3.979739        1.373406  6.899086e-05  1.587822e-04
Hoxa9     3.939977        0.952770  8.148932e-05  1.852030e-04
Pax8      3.912894        5.944145  9.119650e-05  2.065606e-04
Hopx      3.820691        1.268440  1.330782e-04  2.960584e-04
Tet2      3.521431        0.745068  4.292236e-04  9.161657e-04

Really exciting! The top three TFs are involved in stress response, suggesting that this macrostate corresponds to high activity of

In [48]:
hic2_target_scores.loc["Klf10"]

chip_score    4.637256
Name: Klf10, dtype: float64

In [44]:
# Most upregulated transcription factors in dead end that are shared targets

dead_end_rank_df.loc[numpy.intersect1d(target_tfs, adata.var_names)].sort_values("scores", ascending=False).head(30)

           scores  logfoldchanges         pvals     pvals_adj
names
Ddit3   13.226619        2.166627  6.159631e-40  1.140672e-38
Myc     12.562806        1.828156  3.381229e-36  5.162181e-35
Ovol1   12.100735        2.972715  1.046704e-33  1.443730e-32
Klf10   12.000822        1.918085  3.517865e-33  4.753872e-32
Arid3a  10.603693        1.693256  2.864403e-26  2.822072e-25
Zbtb7c  10.598906        1.849738  3.014877e-26  2.955762e-25
Junb    10.341942        1.311702  4.552173e-25  4.234580e-24
Klf4     8.294026        1.242020  1.094780e-16  6.185198e-16
Phox2a   7.614943        2.153333  2.638079e-14  1.253244e-13
Zfp296   7.220187        1.331148  5.191626e-13  2.297180e-12
Barx2    6.472987        2.666481  9.608440e-11  3.660358e-10
Fosl2    4.655017        1.037758  3.239530e-06  8.469360e-06
Tlx2     4.417089        0.874272  1.000390e-05  2.513543e-05
Gata2    4.296226        2.146550  1.737303e-05  4.252883e-05
Zfhx3    4.086668        0.396962  4.376116e-05  1.028464e-04
Pou5f1   3.226679        0.674562  1.252360e-03  2.542863e-03
Fosl1    3.133848        0.988354  1.725300e-03  3.416436e-03
Atf5     2.960264        0.496857  3.073757e-03  5.922461e-03
Hoxa7    1.941820        0.450179  5.215889e-02  8.426314e-02
Ehf      1.198227        1.233144  2.308285e-01  3.262594e-01
Tlx3     1.103218        1.058666  2.699326e-01  3.730928e-01
Tfap2c   1.074170        0.414310  2.827465e-01  3.894579e-01
Nr4a1    0.542760        0.430856  5.872950e-01  7.250556e-01
Gata6    0.294290        0.517615  7.685360e-01  8.828673e-01
Tshz1   -0.137669        0.050887  8.905020e-01  9.592936e-01
Dbp     -0.547977        0.012784  5.837078e-01  7.215176e-01
Klf5    -0.570924       -0.076190  5.680508e-01  7.052152e-01
Zim1    -0.654832       -1.837232  5.125761e-01  6.480102e-01
Zfp710  -0.722436       -0.059473  4.700262e-01  6.018262e-01
Tshz2   -0.890135       -0.329163  3.733932e-01  4.935799e-01

In [38]:
# Most downregulated transcription factors in dead end

dead_end_rank_df.loc[numpy.intersect1d(tf_array, adata.var_names)].sort_values("scores", ascending=True).head(30)

             scores  logfoldchanges         pvals     pvals_adj
names
Cenpa    -14.694151       -2.029778  7.027420e-49  1.873979e-47
Hmgb2    -12.436042       -1.655495  1.665552e-35  2.485899e-34
Tcf7l1   -10.125731       -1.699106  4.247917e-24  3.646281e-23
Prrx1     -9.667671       -3.502777  4.136854e-22  3.182196e-21
Jarid2    -9.106974       -1.539088  8.471185e-20  5.782379e-19
Terf1     -8.995116       -1.125859  2.359814e-19  1.578471e-18
Nfib      -8.488363       -2.268551  2.095683e-17  1.240049e-16
Prrx2     -8.243245       -5.525078  1.676023e-16  9.337178e-16
Zeb1      -8.197787       -3.580868  2.448527e-16  1.345345e-15
Twist1    -8.100400       -2.155874  5.477875e-16  2.945094e-15
Mis18bp1  -7.673030       -1.367189  1.679800e-14  8.114978e-14
Klf2      -7.583708       -2.094071  3.358169e-14  1.591549e-13
Id2       -7.550376       -1.184700  4.340032e-14  2.042368e-13
Id3       -7.495310       -3.318421  6.614180e-14  3.069225e-13
Zfp42     -7.309782       -1.655304  2.675775e-13  1.197215e-12
Tcf4      -7.186566       -1.106846  6.644120e-13  2.926925e-12
Cdc5l     -6.540979       -0.656287  6.111730e-11  2.359741e-10
Zfhx4     -6.538495       -1.480847  6.214110e-11  2.390042e-10
Hmgb3     -6.408444       -1.023359  1.470117e-10  5.506056e-10
Nfix      -6.227951       -2.367974  4.725747e-10  1.724725e-09
Tsc22d1   -5.737269       -0.728544  9.621546e-09  3.170196e-08
Nanog     -5.631834       -2.367001  1.783035e-08  5.714856e-08
Creb3l1   -5.540720       -2.650271  3.012301e-08  9.457773e-08
Sall1     -5.400377       -1.482890  6.650108e-08  2.018242e-07
Lin28a    -5.321290       -1.042207  1.030339e-07  3.080237e-07
Nfia      -5.268825       -1.933072  1.373003e-07  4.062138e-07
Mycn      -5.258531       -3.436124  1.452107e-07  4.285233e-07
Rest      -5.134597       -0.644595  2.827485e-07  8.124958e-07
Klf7      -5.008699       -1.349867  5.479909e-07  1.543636e-06
Zfp36l1   -4.837344       -0.572680  1.315858e-06  3.587976e-06

In [39]:
# Most upregulated transcription factors in day 4 control

control_rank_df.loc[numpy.intersect1d(tf_array, adata.var_names)].sort_values("scores", ascending=False).head(30)

           scores  logfoldchanges          pvals      pvals_adj
names
Tlx2    56.619308        4.156113   0.000000e+00   0.000000e+00
Dmrtc2  47.219395        3.756907   0.000000e+00   0.000000e+00
Zbtb7c  43.116035        2.244280   0.000000e+00   0.000000e+00
Hmgb3   39.926929        1.578542   0.000000e+00   0.000000e+00
Myc     39.168621        1.562202   0.000000e+00   0.000000e+00
Ovol1   35.878239        3.140644  6.674091e-282  1.026783e-280
Zbtb32  35.045231        2.059280  4.609327e-269  6.778422e-268
Hoxa9   28.716011        1.644503  2.407959e-181  2.239962e-180
Phox2a  28.670206        2.174598  8.977100e-181  8.273825e-180
Hopx    25.439432        1.816934  9.241419e-143  6.820235e-142
Zfp296  24.941698        0.973205  2.627576e-137  1.890343e-136
Klf10   19.644541        0.667286   6.437581e-86   3.147961e-85
Hoxa7   18.515795        0.826159   1.540081e-76   6.952961e-76
Lef1    17.094074        1.325687   1.642844e-65   6.637753e-65
Fosl1   15.086825        0.802691   1.977283e-51   6.748405e-51
Nr4a1   14.922898        0.694146   2.338905e-50   7.888380e-50
Barx2   14.731534        2.407695   4.044217e-49   1.339145e-48
Cenpa   12.991665        0.515136   1.364260e-38   3.965872e-38
Tshz1   12.974904        0.369741   1.698086e-38   4.921989e-38
Twist2  12.756365        0.812957   2.872983e-37   8.173495e-37
Pou5f1  12.480664        0.613602   9.518884e-36   2.662625e-35
Runx1   12.446761        0.519876   1.456363e-35   4.062379e-35
Tlx3    11.660106        1.660184   2.037899e-31   5.369958e-31
Tet2    11.040770        0.487917   2.429427e-28   6.088790e-28
Ehf     10.153599        2.532096   3.193658e-24   7.594906e-24
Hmga2    9.090936        0.295891   9.819020e-20   2.162780e-19
Atf3     8.887947        0.548021   6.224843e-19   1.347369e-18
Hes1     8.433112        0.257376   3.365910e-17   7.089842e-17
Hoxa10   7.813334        0.370618   5.569468e-15   1.134311e-14
Gata2    7.710498        0.901278   1.253275e-14   2.531868e-14

In [25]:
dead_end_rank_df.loc[genes_of_interest].sort_values("scores", ascending=False)

           scores  logfoldchanges         pvals     pvals_adj
names
Myc     12.562806        1.828156  3.381229e-36  5.162181e-35
Ovol1   12.100735        2.972715  1.046704e-33  1.443730e-32
Zbtb7c  10.598906        1.849738  3.014877e-26  2.955762e-25
Klf4     8.294026        1.242020  1.094780e-16  6.185198e-16
Tlx2     4.417089        0.874272  1.000390e-05  2.513543e-05
Hic2    -1.219937       -0.087063  2.224888e-01  3.171616e-01
Rest    -5.134597       -0.644595  2.827485e-07  8.124958e-07
Zfp42   -7.309782       -1.655304  2.675775e-13  1.197215e-12
Jarid2  -9.106974       -1.539088  8.471185e-20  5.782379e-19
Tcf7l1 -10.125731       -1.699106  4.247917e-24  3.646281e-23

In [23]:
# Cell types in the dead end

pre_res = gseapy.prerank(
    rnk=dead_end_rank_df[["scores"]], 
    gene_sets="PanglaoDB_Augmented_2021",
    threads=32,
    min_size=5,
    max_size=1000
)
pre_res.res2d.sort_values("NES", ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]

2026-03-05 09:45:11,075 [WARNING] Duplicated values found in preranked stats: 3.00% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

                        Term       NES NOM p-val FWER p-val FDR q-val
0   Mammary Epithelial Cells  2.588875       0.0        0.0       0.0
1                Trichocytes  2.454958       0.0        0.0       0.0
2              Keratinocytes  2.450678       0.0        0.0       0.0
3   Luminal Epithelial Cells  2.435519       0.0        0.0       0.0
4        Gastric Chief Cells  2.295272       0.0        0.0       0.0
5            Principal Cells  2.268925       0.0        0.0       0.0
6             Cholangiocytes  2.253806       0.0        0.0       0.0
7      Salivary Mucous Cells  2.175057       0.0        0.0       0.0
8                  Sebocytes  2.173433       0.0        0.0       0.0
9        Airway Goblet Cells  2.135118       0.0        0.0       0.0
10              Goblet Cells  2.103665       0.0      0.001  0.000117
11          Epithelial Cells  2.053371       0.0      0.004  0.000537
12         Trophoblast Cells  2.038128       0.0      0.005  0.000594
13              Ductal Cells  1.991828       0.0      0.009   0.00092
14              Hepatoblasts  1.968511       0.0      0.014  0.001374
19          Urothelial Cells  1.891786       0.0      0.053  0.004829
21               Clara Cells  1.881585   0.00271      0.059  0.005151
23               Basal Cells  1.873168       0.0      0.065  0.005294
25           Microfold Cells  1.841262       0.0      0.096  0.007591
27    Trophoblast Stem Cells  1.814927  0.002793      0.112  0.008692

In [26]:
# MSig Hallmarks in dead end

pre_res = gseapy.prerank(
    rnk=dead_end_rank_df[["scores"]], 
    gene_sets="MSigDB_Hallmark_2020",
    threads=32,
    min_size=5,
    max_size=1000
)
pre_res.res2d.sort_values("NES", ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]

2026-03-05 09:45:47,611 [WARNING] Duplicated values found in preranked stats: 3.00% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

                             Term       NES NOM p-val FWER p-val FDR q-val
0                     p53 Pathway   2.27238       0.0        0.0       0.0
3   TNF-alpha Signaling via NF-kB  1.981754       0.0      0.003  0.002193
6         Estrogen Response Early  1.623119       0.0        0.2  0.107212
7                  UV Response Up  1.613178  0.005952      0.213  0.087354
8                mTORC1 Signaling  1.591396  0.006135       0.24  0.082164
9                         Hypoxia  1.571308       0.0      0.268  0.079678
12              Androgen Response  1.432537  0.041056      0.565   0.18066
14              KRAS Signaling Dn    1.3821  0.082621      0.671  0.221126
17         Estrogen Response Late  1.338374   0.04893      0.782  0.254548
18      Unfolded Protein Response  1.335315  0.135135      0.788  0.232895
20                 Myc Targets V1  1.265891  0.191816      0.895  0.304359
22             TGF-beta Signaling  1.247817  0.156627      0.911  0.302388
25          Xenobiotic Metabolism  1.212866  0.145833      0.941  0.332546
26                Notch Signaling  1.189417  0.250667       0.95  0.345865
27        Cholesterol Homeostasis  1.186966  0.171831       0.95  0.326121
28                heme Metabolism  1.158767  0.225989      0.964  0.349141
29       IL-6/JAK/STAT3 Signaling  1.135154  0.246612      0.976  0.367905
30           IL-2/STAT5 Signaling  1.134056  0.213376      0.976  0.349172
31     Wnt-beta Catenin Signaling  1.130945  0.308483      0.976  0.334641
37                 Apical Surface  1.054794   0.38814      0.994  0.446126

In [27]:
# MSig Hallmarks in day 4 control

pre_res = gseapy.prerank(
    rnk=control_rank_df[["scores"]], 
    gene_sets="MSigDB_Hallmark_2020",
    threads=32,
    min_size=5,
    max_size=1000
)
pre_res.res2d.sort_values("NES", ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]

2026-03-05 09:45:48,469 [WARNING] Duplicated values found in preranked stats: 0.55% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

                          Term       NES NOM p-val FWER p-val FDR q-val
0       Estrogen Response Late  1.650953  0.001751       0.15  0.162436
2      Estrogen Response Early  1.568822  0.010363      0.318  0.192184
4               Myc Targets V1  1.406796   0.09589      0.753  0.486363
5                  E2F Targets  1.397855  0.062278      0.771  0.390271
7                  p53 Pathway  1.348818  0.069027      0.861  0.429322
8   Wnt-beta Catenin Signaling  1.346102  0.142562      0.865  0.364536
9             mTORC1 Signaling  1.345051  0.075134      0.865  0.314888
10             Notch Signaling  1.342163  0.138493       0.87  0.278478
11       Xenobiotic Metabolism  1.282317  0.109319      0.947  0.353098
12           Androgen Response  1.269339   0.15283      0.958  0.341587
13             G2-M Checkpoint  1.229624  0.161525      0.983  0.380934
14    PI3K/AKT/mTOR  Signaling  1.209172  0.208872      0.987  0.386651
17           KRAS Signaling Dn  1.126822  0.283688      0.999  0.527698
19         Allograft Rejection  1.111855  0.273703        1.0  0.524206
20              Apical Surface  1.085981  0.365503        1.0  0.547434
21             heme Metabolism  1.080596  0.344828        1.0  0.524316
23       Fatty Acid Metabolism  1.058745  0.381044        1.0  0.536305
24     Cholesterol Homeostasis  1.044386  0.421642        1.0  0.536783
29        IL-2/STAT5 Signaling  0.992774  0.445545        1.0  0.617584
33              UV Response Up  0.962919  0.525641        1.0  0.648232

In [28]:
# GO biological process in dead end

pre_res = gseapy.prerank(
    rnk=dead_end_rank_df[["scores"]], 
    gene_sets="GO_Biological_Process_2025",
    threads=32,
    min_size=5,
    max_size=1000
)
pre_res.res2d.sort_values("NES", ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]

2026-03-05 09:45:49,209 [WARNING] Duplicated values found in preranked stats: 3.00% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

,Term,NES,NOM p-val,FWER p-val,FDR q-val
0,Positive Regulation of Intrinsic Apoptotic Sig...,1.760335,0.007937,0.85,1.0
5,Regulation of Autophagy (GO:0010506),1.720115,0.004975,0.953,1.0
10,Antigen Processing and Presentation of Exogeno...,1.702887,0.007895,0.971,0.841609
11,Antigen Processing and Presentation of Exogeno...,1.702887,0.007895,0.971,0.841609
9,Antigen Processing and Presentation of Peptide...,1.702887,0.007895,0.971,0.841609
15,Positive Regulation of Sprouting Angiogenesis ...,1.646528,0.023018,0.996,1.0
18,Intracellular Iron Ion Homeostasis (GO:0006879),1.634716,0.026247,0.999,1.0
19,Regulation of Glycolytic Process (GO:0006110),1.62813,0.028796,0.999,1.0
20,Antigen Processing and Presentation of Peptide...,1.623347,0.018182,0.999,1.0
24,Positive Regulation of Neuron Apoptotic Proces...,1.609309,0.039578,1.0,1.0
27,Response to Endoplasmic Reticulum Stress (GO:0...,1.593984,0.027933,1.0,1.0
31,Protein Catabolic Process (GO:0030163),1.584296,0.021164,1.0,1.0
35,Negative Regulation of Transport (GO:0051051),1.558176,0.045822,1.0,1.0
38,Cellular Response to Hypoxia (GO:0071456),1.545509,0.028329,1.0,1.0
39,Cellular Response to Decreased Oxygen Levels (...,1.545509,0.028329,1.0,1.0
42,Anterograde Trans-Synaptic Signaling (GO:0098916),1.542249,0.034574,1.0,1.0
45,Regulation of Intrinsic Apoptotic Signaling Pa...,1.537231,0.067708,1.0,1.0
46,Positive Regulation of Response to Endoplasmic...,1.536927,0.049479,1.0,1.0
50,Signal Transduction by P53 Class Mediator (GO:...,1.521659,0.049505,1.0,1.0
55,Calcium Ion Transmembrane Transport (GO:0070588),1.515867,0.052493,1.0,1.0

In [29]:
# TFs whose targets are upregulated in dead end
pre_res = gseapy.prerank(
    rnk=dead_end_rank_df[["scores"]], 
    gene_sets="TF_Perturbations_Followed_by_Expression",
    threads=32,
    min_size=5,
    max_size=1000
)
pre_res.res2d.sort_values("NES", ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]

2026-03-05 09:45:54,082 [WARNING] Duplicated values found in preranked stats: 3.00% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

,Term,NES,NOM p-val,FWER p-val,FDR q-val
108,MYC OE MOUSE GSE55272 CREEDSID GENE 1822 DOWN,1.967528,0.0,0.056,0.042759
142,IRF6 KO MOUSE GSE5800 CREEDSID GENE 153 UP,1.914332,0.0,0.12,0.045275
143,PLAGL2 DEFICIENCY MOUSE GSE9123 CREEDSID GENE ...,1.913938,0.0,0.12,0.030393
154,ARID3A KD MOUSE GSE56853 CREEDSID GENE 1337 UP,1.90636,0.0,0.135,0.025467
159,HEY2 KO MOUSE GSE6526 CREEDSID GENE 1512 DOWN,1.896851,0.0,0.156,0.019598
158,HEY2 KO MOUSE GSE6526 CREEDSID GENE 1511 UP,1.896851,0.0,0.156,0.019598
171,PPARA KO MOUSE GSE6864 CREEDSID GENE 981 UP,1.874495,0.0,0.217,0.023626
176,FOXO1 KD MOUSE GSE6623 CREEDSID GENE 505 DOWN,1.870261,0.0,0.23,0.022166
187,GLI1 INHIBITION HUMAN GSE36855 CREEDSID GENE 6...,1.858362,0.0,0.257,0.022498
200,PPARA KO MOUSE GSE6864 CREEDSID GENE 1371 DOWN,1.840598,0.0,0.308,0.025027
211,XBP1 KO MOUSE GSE52857 CREEDSID GENE 2765 UP,1.830522,0.0,0.332,0.025324
223,NR1I2 KO MOUSE GSE23780 CREEDSID GENE 2165 DOWN,1.821299,0.002688,0.357,0.025153
243,AIRE KO MOUSE GSE2585 CREEDSID GENE 272 UP,1.803,0.0,0.412,0.02849
299,TFEB OE HUMAN GSE16267 CREEDSID GENE 2976 UP,1.755569,0.0,0.576,0.044736
345,PPARA DEFICIENCY MOUSE GSE6864 CREEDSID GENE 6...,1.702908,0.003077,0.765,0.072565
367,MBD3 KD MOUSE GSE31008 CREEDSID GENE 1325 UP,1.684703,0.0,0.811,0.081864
405,SREBF2 KD HUMAN GSE50588 CREEDSID GENE 2823 UP,1.661303,0.0,0.861,0.096912
406,MYC KD HUMAN GSE22139 CREEDSID GENE 712 DOWN,1.660848,0.010499,0.861,0.092087
433,HOXC13 OE MOUSE GSE2374 CREEDSID GENE 201 DOWN,1.639923,0.0,0.901,0.107296
442,SNAI1 OE HUMAN GSE14773 CREEDSID GENE 371 UP,1.628183,0.00625,0.915,0.113533

In [30]:
# TFs whose targets are downregulated in dead end
pre_res = gseapy.prerank(
    rnk=dead_end_rank_df[["scores"]], 
    gene_sets="TF_Perturbations_Followed_by_Expression",
    threads=32,
    min_size=5,
    max_size=1000
)
pre_res.res2d.sort_values("NES", ascending=True).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]

2026-03-05 09:45:58,331 [WARNING] Duplicated values found in preranked stats: 3.00% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

,Term,NES,NOM p-val,FWER p-val,FDR q-val
0,FOXA1 KD HUMAN GSE25315 CREEDSID GENE 2164 DOWN,-2.463419,0.0,0.0,0.0
1,OVOL2 OE PC3 HUMAN GSE48230 RNASEQ DOWN,-2.452743,0.0,0.0,0.0
2,DNMT1 KO MOUSE GSE31626 CREEDSID GENE 1237 DOWN,-2.417583,0.0,0.0,0.0
3,E2F1 OE HUMAN GSE2715 CREEDSID GENE 1129 DOWN,-2.407181,0.0,0.0,0.0
4,TAL1 KD JURKAT HUMAN GSE72299 RNASEQ DOWN,-2.372448,0.0,0.0,0.0
5,MYB KD HUMAN GSE49286 CREEDSID GENE 1842 DOWN,-2.353719,0.0,0.0,0.0
6,MEIS2 KD KASUMI1 HUMAN GSE81328 RNASEQ UP,-2.337821,0.0,0.0,0.0
7,ZNF750 KD HUMAN GSE38039 CREEDSID GENE 204 UP,-2.336913,0.0,0.0,0.0
8,ZNF750 KD HUMAN GSE38039 CREEDSID GENE 2704 DOWN,-2.336913,0.0,0.0,0.0
9,ZMAT4 SIRNA T47D HUMAN GSE79586 RNASEQ DOWN,-2.332155,0.0,0.0,0.0
10,FLI1 KD HUMAN GSE27524 CREEDSID GENE 1597 DOWN,-2.318018,0.0,0.0,0.0
11,MYCN SHRNA SKNBE2 HUMAN GSE84389 RNASEQ DOWN,-2.316172,0.0,0.0,0.0
12,PRDM16 DEPLETION MOUSE GSE35011 CREEDSID GENE ...,-2.307331,0.0,0.0,0.0
13,NFKB1 INACTIVATION HUMAN GSE20667 CREEDSID GEN...,-2.301931,0.0,0.0,0.0
14,YEATS2 SHRNA H1299 HUMAN GSE90781 RNASEQ DOWN,-2.300333,0.0,0.0,0.0
15,ADAR KD HUVEC HUMAN GSE60217 RNASEQ DOWN,-2.288659,0.0,0.0,0.0
16,TFAP2C SIRNA HUMAN GSE15481 CREEDSID GENE 2893...,-2.264936,0.0,0.0,0.0
17,DNMT1 KO MOUSE GSE31626 CREEDSID GENE 1236 DOWN,-2.261227,0.0,0.0,0.0
18,RC3H1 SIRNA HEK293 HUMAN GSE68611 RNASEQ UP,-2.254065,0.0,0.0,0.0
19,DUX4 OE HUMAN GSE33799 CREEDSID GENE 1430 DOWN,-2.251097,0.0,0.0,0.0

In [31]:
# TFs whose targets are upregulated in control
pre_res = gseapy.prerank(
    rnk=control_rank_df[["scores"]], 
    gene_sets="TF_Perturbations_Followed_by_Expression",
    threads=32,
    min_size=5,
    max_size=1000
)
pre_res.res2d.sort_values("NES", ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]

2026-03-05 09:46:05,247 [WARNING] Duplicated values found in preranked stats: 0.55% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

,Term,NES,NOM p-val,FWER p-val,FDR q-val
7,OVOL2 OE MOUSE GSE55074 CREEDSID GENE 2603 DOWN,2.05011,0.0,0.005,0.003324
9,MYC OE MOUSE GSE55272 CREEDSID GENE 1822 DOWN,2.039413,0.0,0.007,0.002327
10,IRF6 KO MOUSE GSE5800 CREEDSID GENE 153 UP,2.039194,0.0,0.007,0.001551
38,HSF1 KO MOUSE GSE41005 CREEDSID GENE 2143 DOWN,1.856263,0.0,0.234,0.048202
39,YY1 KD MOUSE GSE31784 CREEDSID GENE 1333 UP,1.850319,0.0,0.257,0.042418
56,MBD3 KD MOUSE GSE31008 CREEDSID GENE 1325 UP,1.805803,0.001669,0.429,0.070475
62,PPARA DEFICIENCY MOUSE GSE6864 CREEDSID GENE 6...,1.793981,0.0,0.474,0.06943
63,KLF1 KO MOUSE GSE36427 CREEDSID GENE 1562 DOWN,1.790153,0.001855,0.496,0.06499
65,NFE2L2 KO MOUSE GSE18344 CREEDSID GENE 965 DOWN,1.785133,0.0,0.512,0.061093
78,HNF4A MUT MOUSE GSE3116 CREEDSID GENE 850 DOWN,1.763923,0.0,0.604,0.073135
84,MYC KD HUMAN GSE54872 CREEDSID GENE 1311 DOWN,1.74751,0.007576,0.664,0.082503
95,MYC KD HUMAN GSE22139 CREEDSID GENE 712 DOWN,1.719662,0.003831,0.784,0.107984
101,PPARA KO MOUSE GSE6864 CREEDSID GENE 981 UP,1.704649,0.0,0.826,0.120595
103,PPARA KO MOUSE GSE6864 CREEDSID GENE 1371 DOWN,1.694853,0.001631,0.85,0.125374
104,DEAF1 OE MOUSE GSE12367 CREEDSID GENE 1682 UP,1.691967,0.003745,0.858,0.120473
112,NFE2L2 KO MOUSE GSE18344 CREEDSID GENE 959 DOWN,1.678631,0.0,0.889,0.132432
113,NR3C1 KO MOUSE GSE23724 CREEDSID GENE 3014 DOWN,1.67673,0.001715,0.893,0.127731
115,NFE2L2 KO MOUSE GSE18344 CREEDSID GENE 1263 UP,1.672043,0.004975,0.906,0.126804
118,FOXP1 KD HUMAN GSE51382 CREEDSID GENE 2764 DOWN,1.670945,0.001792,0.908,0.121494
122,NR1I2 KO MOUSE GSE23780 CREEDSID GENE 2165 DOWN,1.664305,0.015595,0.919,0.12383

These results suggest that the control pathway has low Ovol2 activity, which is consistent with high Ovol1 activity as Ovol1 downregulates Ovol2.

## Compare day 12 control with day 4 control

In [40]:
# Compare day 12 control with day 4 control
scanpy.tl.rank_genes_groups(
    adata,
    groupby="macrostate",
    method="wilcoxon",
    use_raw=False,
    reference="Day 4 Control",
    key_added="macrostate_vs_control_rank_genes"
)
dead_end_vs_control_rank_df = scanpy.get.rank_genes_groups_df(
    adata,
    group="Day 12 Control",
    key="macrostate_vs_control_rank_genes"
)
dead_end_vs_control_rank_df.index = dead_end_vs_control_rank_df["names"]
dead_end_vs_control_rank_df = dead_end_vs_control_rank_df.drop(columns="names")
dead_end_vs_control_rank_df.head(30)

                  scores  logfoldchanges          pvals      pvals_adj
names
2410006H16Rik  26.126083        2.549994  1.843133e-150  3.686265e-147
Zfas1          25.591373        2.887306  1.903077e-144  1.903077e-141
1110038B12Rik  25.104904        2.706954  4.396385e-139  2.930924e-136
Snhg1          24.437115        2.785392  6.898948e-132  3.449474e-129
Gas5           24.352331        1.764712  5.476893e-131  2.190757e-128
Snhg12         24.150040        3.244454  7.459324e-129  2.486441e-126
Ppp1r15a       21.102528        2.884851   7.539659e-99   1.507932e-96
Sqstm1         19.848444        2.438090   1.136654e-87   1.623791e-85
Cstb           19.777744        1.662232   4.629430e-87   6.172574e-85
Rps18          19.569803        0.519270   2.797598e-85   3.496997e-83
Ifrd1          19.545010        2.051183   4.549128e-85   5.351915e-83
Bbc3           19.291471        2.545764   6.334500e-83   7.038333e-81
Aqp3           19.283178        3.667204   7.436396e-83   7.827785e-81
Cdkn1a         19.278427        1.397393   8.151741e-83   8.151741e-81
Zfand5         18.958574        2.441425   3.751751e-80   3.262393e-78
Gabarap        18.629305        1.253917   1.859251e-77   1.549376e-75
Ahnak2         18.060299        2.188858   6.546684e-73   4.849396e-71
Atf3           17.293951        4.182650   5.224525e-67   3.483017e-65
Rassf1         17.226147        1.868825   1.690456e-66   1.090617e-64
Ddit3          15.975071        3.221851   1.906363e-57   9.776220e-56
Btg1           15.888432        2.660064   7.621059e-57   3.810530e-55
5430416N02Rik  15.588060        2.431265   8.775829e-55   3.815578e-53
1810032O08Rik  15.483035        3.059274   4.516496e-54   1.921913e-52
Tmem43         15.396733        1.651869   1.721496e-53   7.172898e-52
Cxcl16         14.973992        3.142614   1.086017e-50   4.098178e-49
Maff           14.538376        3.518187   6.921518e-48   2.307173e-46
Mdm2           14.519401        1.977894   9.130484e-48   2.993601e-46
Btg2           14.483277        1.957621   1.545485e-47   4.985435e-46
Renbp          14.397650        2.673156   5.353311e-47   1.699464e-45
Impact         14.345840        1.213049   1.131217e-46   3.535054e-45

In [41]:
# Most upregulated transcription factors in dead end

dead_end_vs_control_rank_df.loc[numpy.intersect1d(tf_array, adata.var_names)].sort_values("scores", ascending=False).head(30)

            scores  logfoldchanges         pvals     pvals_adj
names
Atf3     17.293951        4.182650  5.224525e-67  3.483017e-65
Ddit3    15.975071        3.221851  1.906363e-57  9.776220e-56
Maff     14.538376        3.518187  6.921518e-48  2.307173e-46
Crebrf   11.278059        3.426975  1.684214e-29  2.716475e-28
Zbtb10    9.688887        2.093428  3.361729e-22  3.954976e-21
Junb      9.540514        1.198861  1.421259e-21  1.615067e-20
Arid3a    9.539727        1.519866  1.432088e-21  1.618178e-20
Klf6      9.515185        1.901875  1.813887e-21  2.026689e-20
Klf4      9.149061        1.463191  5.743040e-20  5.771900e-19
Klf10     9.013310        1.398984  1.999277e-19  1.941046e-18
Bhlhe40   8.519645        2.346466  1.600439e-17  1.428963e-16
Rora      7.284762        4.426298  3.222391e-13  2.237771e-12
Ovol1     6.053084        1.239698  1.420988e-09  7.722761e-09
Myc       5.996467        0.733084  2.016562e-09  1.084173e-08
Fosl2     5.336549        1.440460  9.473203e-08  4.479056e-07
Zfp750    4.971072        2.548014  6.658383e-07  2.876191e-06
Hes1      4.402319        1.008520  1.070997e-05  4.119218e-05
Pax8      3.837615        6.719035  1.242349e-04  4.240098e-04
Atf5      3.776979        0.706474  1.587422e-04  5.335873e-04
Zfhx3     3.443773        0.264773  5.736570e-04  1.776028e-03
Esrrb     3.351118        1.652081  8.048614e-04  2.431852e-03
Klf5      3.304284        1.015113  9.521941e-04  2.825502e-03
Barx2     3.283594        1.221190  1.024926e-03  3.020433e-03
Rest      3.244519        0.294803  1.176493e-03  3.435017e-03
Zbtb7c    3.167943        0.454898  1.535217e-03  4.405213e-03
Smad7     3.135474        0.802623  1.715766e-03  4.881269e-03
Tfap2c    3.030702        1.276647  2.439856e-03  6.767977e-03
Zfp296    2.880306        0.636075  3.972896e-03  1.065119e-02
Gata2     2.626909        1.461320  8.616446e-03  2.189694e-02
Zbtb20    2.501334        1.250793  1.237263e-02  3.062531e-02

Top 4 TFs are all involved in stress responses

In [42]:
# Most downregulated transcription factors in dead end

dead_end_vs_control_rank_df.loc[numpy.intersect1d(tf_array, adata.var_names)].sort_values("scores", ascending=True).head(30)

             scores  logfoldchanges         pvals     pvals_adj
names
Cenpa    -18.378662       -2.361419  1.947120e-75  1.557696e-73
Hmgb3    -14.654617       -2.041724  1.258640e-48  4.266575e-47
Hmgb2    -11.795198       -1.436325  4.132265e-32  7.313744e-31
Id2       -8.479613       -1.096260  2.259429e-17  1.990686e-16
Tlx2      -8.452542       -1.106642  2.850273e-17  2.500239e-16
Prrx1     -8.317663       -2.595609  8.971450e-17  7.700815e-16
Mis18bp1  -7.335813       -1.151761  2.203806e-13  1.541123e-12
Terf1     -7.233290       -0.849773  4.714325e-13  3.217969e-12
Zfhx4     -6.941576       -1.290629  3.877483e-12  2.493558e-11
Nfib      -6.733551       -1.549937  1.655713e-11  1.025209e-10
Twist2    -6.236287       -1.747624  4.480797e-10  2.524393e-09
Twist1    -6.073015       -1.395535  1.255308e-09  6.878397e-09
Nfia      -5.823525       -1.717294  5.761910e-09  3.024625e-08
Hmga2     -5.701999       -0.597955  1.184104e-08  6.119400e-08
Nfix      -5.622528       -1.842449  1.881831e-08  9.456439e-08
Dmrtc2    -5.308241       -0.692599  1.106881e-07  5.196625e-07
Egr1      -4.994685       -0.494330  5.893177e-07  2.556693e-06
Prrx2     -4.883111       -4.057743  1.044252e-06  4.443625e-06
Lin28a    -4.755962       -0.766256  1.975033e-06  8.263735e-06
Nr2f2     -4.538492       -0.862550  5.665803e-06  2.252804e-05
Zbtb32    -4.537395       -0.606537  5.695328e-06  2.260051e-05
Jarid2    -4.346265       -0.551580  1.384752e-05  5.255225e-05
Zfp42     -4.107964       -0.588239  3.991626e-05  1.441020e-04
Tcf7l1    -4.097703       -0.527595  4.172700e-05  1.498276e-04
Id3       -3.595407       -1.702959  3.238854e-04  1.043109e-03
Tcf4      -3.255257       -0.346625  1.132897e-03  3.317414e-03
Hoxa10    -3.076693       -0.730383  2.093108e-03  5.879518e-03
Cdc5l     -3.058645       -0.335620  2.223402e-03  6.201959e-03
Nanog     -3.039586       -1.175820  2.369038e-03  6.589814e-03
Tshz1     -2.806822       -0.209857  5.003283e-03  1.323620e-02

In [35]:
dead_end_vs_control_rank_df.loc[genes_of_interest].sort_values("scores", ascending=False)

          scores  logfoldchanges         pvals     pvals_adj
names
Klf4    9.149061        1.463191  5.743040e-20  5.771900e-19
Ovol1   6.053084        1.239698  1.420988e-09  7.722761e-09
Myc     5.996467        0.733084  2.016562e-09  1.084173e-08
Rest    3.244519        0.294803  1.176493e-03  3.435017e-03
Zbtb7c  3.167943        0.454898  1.535217e-03  4.405213e-03
Hic2    1.094972        0.462989  2.735291e-01  4.687730e-01
Tcf7l1 -4.097703       -0.527595  4.172700e-05  1.498276e-04
Zfp42  -4.107964       -0.588239  3.991626e-05  1.441020e-04
Jarid2 -4.346265       -0.551580  1.384752e-05  5.255225e-05
Tlx2   -8.452542       -1.106642  2.850273e-17  2.500239e-16

The dead end state is signified by high expression of Klf4, Myc and Ovol1.

Tlx2 is downregulated in the dead end, suggesting it does not bring cells into the dead end. It could just be correlated with the control pathway.

In [ ]:
# Cell types in the dead end

pre_res = gseapy.prerank(
    rnk=dead_end_vs_control_rank_df[["scores"]],
    gene_sets="PanglaoDB_Augmented_2021",
    threads=32,
    min_size=5,
    max_size=1000
)
pre_res.res2d.sort_values("NES", ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]

2026-03-05 09:31:58,986 [WARNING] Duplicated values found in preranked stats: 9.00% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

                                Term       NES NOM p-val FWER p-val FDR q-val
0           Mammary Epithelial Cells  2.032868       0.0        0.0       0.0
1                    Principal Cells  1.998692       0.0        0.0       0.0
2           Luminal Epithelial Cells  1.976177       0.0      0.003  0.001648
3                        Trichocytes  1.862625  0.003597      0.028  0.010508
4                Gastric Chief Cells  1.796434       0.0      0.062  0.018296
6                          Sebocytes  1.740809  0.009375       0.12  0.030699
8                     Cholangiocytes  1.672694  0.006515      0.229   0.05563
9                      Keratinocytes  1.635431  0.003597      0.303  0.071855
10           Airway Epithelial Cells  1.616102   0.02029      0.363  0.079118
11                          Nuocytes  1.613408  0.035294       0.37  0.072689
16                Trigeminal Neurons   1.56428  0.026756      0.502   0.10092
17                 Trophoblast Cells  1.563283  0.004049      0.504  0.093231
18                      Goblet Cells   1.55871   0.01791      0.518  0.089483
24             Salivary Mucous Cells  1.533442  0.007326      0.601  0.102871
29  Pulmonary Alveolar Type II Cells  1.494898  0.029304      0.707  0.132522
30                   Transient Cells  1.492463  0.047923      0.711   0.12648
32                      Ductal Cells  1.490957  0.007067       0.72  0.120494
33                   Microfold Cells   1.49048  0.020619       0.72  0.114487
34                       Clara Cells  1.489686  0.046784      0.721  0.109177
40                     Spermatocytes  1.468681  0.069333      0.768   0.12084

In [ ]:
# MSig Hallmarks

pre_res = gseapy.prerank(
    rnk=dead_end_vs_control_rank_df[["scores"]], 
    gene_sets="MSigDB_Hallmark_2020",
    threads=32,
    min_size=5,
    max_size=1000
)
pre_res.res2d.sort_values("NES", ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]

2026-03-05 09:32:04,161 [WARNING] Duplicated values found in preranked stats: 9.00% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

                             Term       NES NOM p-val FWER p-val FDR q-val
0   TNF-alpha Signaling via NF-kB   2.23291       0.0        0.0       0.0
1                     p53 Pathway  2.080421       0.0        0.0       0.0
4                         Hypoxia  1.837935       0.0       0.01  0.005158
7                  UV Response Up  1.595374       0.0      0.175  0.075826
11      Unfolded Protein Response  1.436948  0.081301      0.477   0.21974
13               mTORC1 Signaling  1.398681  0.035484      0.576  0.239599
16             TGF-beta Signaling  1.300711  0.137931      0.792   0.37095
20        Estrogen Response Early   1.19468  0.152941      0.928  0.550124
21              Protein Secretion   1.17724  0.271186      0.936  0.531985
22       IL-6/JAK/STAT3 Signaling  1.161149  0.194529      0.945  0.512521
24                      Apoptosis  1.140574  0.173554      0.962  0.512774
25           IL-2/STAT5 Signaling  1.139142  0.182482      0.962  0.473525
29              Androgen Response  1.080247  0.312903      0.985  0.563516
31          Inflammatory Response  1.059484  0.293893      0.991  0.571347
32                     Myogenesis   1.05333  0.322709      0.992  0.548113
33        Cholesterol Homeostasis  0.992787  0.435583      0.999  0.656223
34              KRAS Signaling Dn  0.989549  0.468531      0.999  0.626633
36                heme Metabolism  0.976948  0.462264      0.999  0.618643
39                   Adipogenesis   0.95096  0.544484      0.999  0.645782
41                 Apical Surface  0.891274  0.579104      0.999  0.750831

In [ ]:
# GO biological process

pre_res = gseapy.prerank(
    rnk=dead_end_vs_control_rank_df[["scores"]], 
    gene_sets="GO_Biological_Process_2025",
    threads=32,
    min_size=5,
    max_size=1000
)
pre_res.res2d.sort_values("NES", ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]

2026-03-05 09:32:26,962 [WARNING] Duplicated values found in preranked stats: 9.00% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

,Term,NES,NOM p-val,FWER p-val,FDR q-val
0,Regulation of JNK Cascade (GO:0046328),1.805935,0.0,0.323,0.486163
1,Response to Endoplasmic Reticulum Stress (GO:0...,1.799198,0.003125,0.351,0.273211
2,Positive Regulation of JNK Cascade (GO:0046330),1.792325,0.0,0.382,0.202908
6,Macroautophagy (GO:0016236),1.670805,0.010929,0.913,0.949601
7,Anterograde Trans-Synaptic Signaling (GO:0098916),1.66677,0.012698,0.922,0.800535
8,Regulation of Translation (GO:0006417),1.651243,0.012012,0.959,0.820315
9,Positive Regulation of Granulocyte Chemotaxis ...,1.648447,0.010724,0.964,0.732454
10,Integrated Stress Response Signaling (GO:0140467),1.644288,0.002681,0.966,0.674985
13,Immunoglobulin Mediated Immune Response (GO:00...,1.632127,0.005602,0.977,0.697809
17,T Cell Chemotaxis (GO:0010818),1.615536,0.010724,0.984,0.766932
18,Regulation of Autophagy (GO:0010506),1.607687,0.012085,0.991,0.765549
20,Lymphocyte Chemotaxis (GO:0048247),1.598341,0.013405,0.994,0.788738
21,Regulation of Translational Initiation (GO:000...,1.592448,0.005495,0.995,0.778191
23,Regulation of Cytokine Production Involved in ...,1.588977,0.01983,0.995,0.751203
24,Positive Regulation of Neuron Apoptotic Proces...,1.587902,0.007874,0.995,0.709498
26,Chemical Synaptic Transmission (GO:0007268),1.576868,0.028662,0.999,0.752352
29,Autophagy of Mitochondrion (GO:0000422),1.564415,0.039106,0.999,0.806747
30,Regulation of Catabolic Process (GO:0009894),1.550644,0.042017,1.0,0.874219
31,Negative Regulation of Intracellular Signal Tr...,1.544512,0.0,1.0,0.880351
32,Positive Regulation of Intrinsic Apoptotic Sig...,1.540625,0.031977,1.0,0.863858

All the top terms are related to damage and stress signaling.

In [ ]:
# ENCODE ChIP-Seq
pre_res = gseapy.prerank(
    rnk=dead_end_vs_control_rank_df[["scores"]], 
    gene_sets="ENCODE_TF_ChIP-seq_2015",
    threads=32,
    min_size=5,
    max_size=1000
)
pre_res.res2d.sort_values("NES", ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]

2026-03-05 09:35:59,059 [WARNING] Duplicated values found in preranked stats: 9.00% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

                    Term       NES NOM p-val FWER p-val FDR q-val
2       FOSL2 HepG2 hg19  1.845511       0.0      0.032  0.049575
5        MAX myocyte mm9  1.794046       0.0      0.061  0.048158
6         PML MCF-7 hg19  1.772045  0.003846      0.083  0.042493
7       NR2F2 MCF-7 hg19  1.756168       0.0      0.096  0.038952
10       TAF1 MCF-7 hg19  1.739986       0.0      0.117  0.039093
11      NR3C1 ECC-1 hg19  1.739029  0.003484      0.117  0.032814
14        NFE2 K562 hg19  1.696168  0.009009      0.193  0.046944
15        USF1 K562 hg19  1.691845       0.0      0.198  0.042316
16      YY1 GM12891 hg19    1.6876  0.007117       0.21  0.039975
17       MEF2A K562 hg19  1.660891  0.003185      0.265  0.047308
23       RXRA HepG2 hg19  1.611333  0.003802      0.386  0.069147
24       USF1 HepG2 hg19  1.609797       0.0       0.39  0.063857
28      ZNF274 K562 hg19  1.579873  0.013746      0.467  0.079538
37       REST HepG2 hg19  1.507851  0.003953      0.667  0.140125
41       JUND MCF-7 hg19   1.49622  0.032258      0.706  0.147213
42    CEBPB GM12878 hg19  1.488604  0.026515      0.734  0.147573
43     CEBPB myocyte mm9  1.486338  0.011407      0.745  0.141726
45  eGFP-HDAC8 K562 hg19  1.472124  0.013333      0.779  0.150141
47       JUND HepG2 hg19  1.470481       0.0      0.784  0.144251
49     NFE2 GM12878 hg19  1.467246  0.004505      0.794   0.14143

In [ ]:
# Chsea
pre_res = gseapy.prerank(
    rnk=dead_end_vs_control_rank_df[["scores"]], 
    gene_sets="ChEA_2022",
    threads=32,
    min_size=5,
    max_size=1000
)
pre_res.res2d.sort_values("NES", ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]

2026-03-05 09:35:08,388 [WARNING] Duplicated values found in preranked stats: 9.00% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

,Term,NES,NOM p-val,FWER p-val,FDR q-val
2,FOXA1 33576154 ChIP-Seq Human HilarLN Prostate...,1.891787,0.0,0.013,0.01714
4,RELB 30642670 ChIP-Seq CTB1 Human Placenta Inf...,1.788053,0.003236,0.068,0.046145
6,TP63 17297297 ChIP-ChIP HaCaT Human,1.713096,0.003115,0.151,0.073832
8,NOTCH1 21737748 ChIP-Seq TLL Human,1.6068,0.018237,0.396,0.177659
9,PKCTHETA 26484144 Chip-Seq BREAST Human,1.601674,0.003676,0.414,0.150038
10,FOXA1 26457646 ChIP-Seq LHSAR Human ProstateCa...,1.591983,0.0,0.446,0.137337
11,FOXO1 32281255 ChIP-Seq Chondrocytes Human Ost...,1.590245,0.0,0.451,0.119036
12,MEIS1 20887958 ChIP-Seq HPC-7 Mouse,1.577726,0.0,0.489,0.116681
13,NUCKS1 24931609 ChIP-Seq HEPATOCYTES Mouse,1.572461,0.0,0.506,0.10899
14,BRD4 28847988 ChIP-Seq BCBL1 Human Blood Lymphoma,1.561826,0.019231,0.54,0.109166
16,KLF2 18264089 ChIP-ChIP MESCs Mouse,1.533513,0.022876,0.634,0.109024
15,KLF5 18264089 ChIP-ChIP MESCs Mouse,1.533513,0.022876,0.634,0.109024
17,KLF4 18264089 ChIP-ChIP MESCs Mouse,1.533513,0.022876,0.634,0.109024
18,HIF1A 21447827 ChIP-Seq MCF-7 Human,1.5248,0.007042,0.662,0.109807
22,TAF7L 23326641 ChIP-Seq C3H10T1-2 Mouse,1.500995,0.004132,0.733,0.126042
23,HNF4A 19761587 ChIP-ChIP CACO-2 Human,1.491879,0.013636,0.753,0.126322
25,FOXO3 23340844 ChIP-Seq DLD1 Human,1.47494,0.009709,0.8,0.135721
30,FOXA1 33576154 ChIP-Seq Human Liver ProstateCa...,1.45602,0.0,0.845,0.14825
33,CREB1 20920259 ChIP-Seq GC1-SPG Mouse,1.447992,0.0,0.86,0.149122
36,HCFC1 20581084 ChIP-Seq MESCs Mouse,1.442488,0.074405,0.874,0.148521

In [ ]:
# TF perturbation
pre_res = gseapy.prerank(
    rnk=dead_end_vs_control_rank_df[["scores"]], 
    gene_sets="TF_Perturbations_Followed_by_Expression",
    threads=32,
    min_size=5,
    max_size=1000
)
pre_res.res2d.sort_values("NES", ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]

2026-03-05 09:35:28,265 [WARNING] Duplicated values found in preranked stats: 9.00% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

,Term,NES,NOM p-val,FWER p-val,FDR q-val
2,GLI1 INHIBITION HUMAN GSE36855 CREEDSID GENE 6...,2.180205,0.0,0.0,0.0
20,FOXO1 KD MOUSE GSE6623 CREEDSID GENE 505 DOWN,1.988647,0.0,0.016,0.00618
29,SOX4 KD HUMAN GSE4225 CREEDSID GENE 64 UP,1.91645,0.0,0.061,0.016738
45,NFKB1 INACTIVATION HUMAN GSE20667 CREEDSID GEN...,1.857504,0.003115,0.132,0.02839
54,HEY2 KO MOUSE GSE6526 CREEDSID GENE 1512 DOWN,1.825931,0.0,0.204,0.031029
55,HEY2 KO MOUSE GSE6526 CREEDSID GENE 1511 UP,1.825931,0.0,0.204,0.031029
56,ZXDC DEPLET MOUSE GSE45417 CREEDSID GENE 1257 UP,1.819913,0.0,0.216,0.028693
62,PLAGL2 DEFICIENCY MOUSE GSE9123 CREEDSID GENE ...,1.806016,0.0,0.249,0.029838
79,CEBPA KO MOUSE GSE61468 CREEDSID GENE 1476 UP,1.775358,0.0,0.362,0.041458
82,ARID3B KO MOUSE GSE62069 CREEDSID GENE 2591 UP,1.772634,0.0,0.372,0.038703
99,TFEB OE HUMAN GSE16267 CREEDSID GENE 2976 UP,1.741278,0.0,0.473,0.050424
122,AIRE KO MOUSE GSE2585 CREEDSID GENE 272 UP,1.711396,0.0,0.585,0.066822
133,TCF7 KO MOUSE GSE20754 CREEDSID GENE 3010 DOWN,1.696387,0.0,0.625,0.070892
153,ARID3A KD MOUSE GSE56853 CREEDSID GENE 1337 UP,1.678154,0.0,0.698,0.079623
168,XBP1 KO MOUSE GSE52857 CREEDSID GENE 2765 UP,1.665491,0.0,0.726,0.084049
170,STAT3 ACTVATION MOUSE GSE21060 CREEDSID GENE 3...,1.661736,0.020958,0.74,0.081644
172,KCNIP3 KO MOUSE GSE16874 CREEDSID GENE 1030 DOWN,1.65977,0.003115,0.749,0.078887
177,SNAI1 OE HUMAN GSE14773 CREEDSID GENE 371 UP,1.653929,0.0,0.768,0.079568
182,KLF15 KO MOUSE GSE53231 CREEDSID GENE 446 UP,1.643062,0.004115,0.811,0.085626
201,SPDEF KD HUMAN GSE48928 CREEDSID GENE 2897 UP,1.622283,0.0,0.85,0.100001