In [1]:
import scanpy
import anndata
import matplotlib
from matplotlib import pyplot
import hdf5plugin
import numpy
import scvelo
import seaborn
import pandas
import warnings
import cellrank
import gseapy

In [3]:
# Read input file
working_directory = "RNA Sequencing Data/"

# adata = scanpy.read_h5ad(working_directory + "/velocity_sdevelo.h5ad")

# Or read saved anndata objects
base_name = "cellrank_1.4"
adata = scanpy.read_h5ad(
    working_directory+f"/{base_name} cells.h5ad"
)
dead_end_adata = scanpy.read_h5ad(
    working_directory+f"/{base_name} dead end genes.h5ad"
)
mESC_adata = scanpy.read_h5ad(
    working_directory+f"/{base_name} mESC genes.h5ad"
)
driver_df = pandas.read_csv(
    working_directory+f"{base_name} driver genes.csv",
)

print(adata)

AnnData object with n_obs × n_vars = 12791 × 2000
    obs: 'barcode', 'batch', 'sample', 'group', 'day', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'initial_size_unspliced', 'initial_size_spliced', 'initial_size', 'n_counts', 'latent_time', 'sde_velocity_self_transition', 'manual_root', 'manual_end', 'sde_velocity_pseudotime', 'macrostates_fwd', 'term_states_fwd', 'term_states_fwd_probs', 'init_states_fwd', 'init_states_fwd_probs', 'clusters_gradients', 'fate_probabilities_Day 12 Control', 'fate_probabilities_mESC'
    var: 'ensemble_ids', 'gene_symbol', 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'gene_count_corr', 'means', 'dispersions', 'dispersions_norm', 'highly_variable', 'fit_alpha', 'fit_beta', 'fit_gamma', 'fit_t_', 'fit_sigma_1', 'fit_sigma_2'
    uns: 'T_fwd_params', 'clusters_gradients_colors', 'coarse_fwd', 'eigendecomposition_fwd', 'init_states_fwd_colors', 'lineage_Day 12 Control_trend', 'lineage_mESC_trend', 'log1p', 'macrostates_fwd_colors', 'neighbors', 'pca', 'sample_colors', 'schur_matrix_fwd', 'sde_velocity_graph', 'sde_velocity_graph_neg', 'sde_velocity_params', 'term_states_fwd_colors'
    obsm: 'T_fwd_fdl', 'X_fdl', 'X_pca', 'X_umap', 'init_states_fwd_memberships', 'lineages_fwd', 'macrostates_fwd_memberships', 'schur_vectors_fwd', 'sde_velocity_fdl', 'term_states_fwd_memberships'
    varm: 'PCs', 'terminal_lineage_drivers'
    layers: 'Ms', 'Mu', 'ambiguous', 'matrix', 'pred_s', 'pred_u', 'sde_velocity', 'spliced', 'unspliced'
    obsp: 'connectivities', 'distances'

In [4]:
# Show all possible libraries
names = gseapy.get_library_name(organism="Mouse")
print(names)

['ARCHS4_Cell-lines', 'ARCHS4_IDG_Coexp', 'ARCHS4_Kinases_Coexp', 'ARCHS4_TFs_Coexp', 'ARCHS4_Tissues', 'Achilles_fitness_decrease', 'Achilles_fitness_increase', 'Aging_Perturbations_from_GEO_down', 'Aging_Perturbations_from_GEO_up', 'Allen_Brain_Atlas_10x_scRNA_2021', 'Allen_Brain_Atlas_down', 'Allen_Brain_Atlas_up', 'Azimuth_2023', 'Azimuth_Cell_Types_2021', 'BioCarta_2013', 'BioCarta_2015', 'BioCarta_2016', 'BioPlanet_2019', 'BioPlex_2017', 'CCLE_Proteomics_2020', 'CM4AI_U2OS_Protein_Localization_Assemblies', 'COMPARTMENTS_Curated_2025', 'COMPARTMENTS_Experimental_2025', 'CORUM', 'COVID-19_Related_Gene_Sets', 'COVID-19_Related_Gene_Sets_2021', 'Cancer_Cell_Line_Encyclopedia', 'Carcinogenome', 'CellMarker_2024', 'CellMarker_Augmented_2021', 'ChEA_2013', 'ChEA_2015', 'ChEA_2016', 'ChEA_2022', 'Chromosome_Location', 'Chromosome_Location_hg19', 'ClinVar_2019', 'ClinVar_2025', 'DGIdb_Drug_Targets_2024', 'DSigDB', 'Data_Acquisition_Method_Most_Popular_Genes', 'DepMap_CRISPR_GeneDependency_CellLines_2023', 'DepMap_WG_CRISPR_Screens_Broad_CellLines_2019', 'DepMap_WG_CRISPR_Screens_Sanger_CellLines_2019', 'Descartes_Cell_Types_and_Tissue_2021', 'Diabetes_Perturbations_GEO_2022', 'DisGeNET', 'Disease_Perturbations_from_GEO_down', 'Disease_Perturbations_from_GEO_up', 'Disease_Signatures_from_GEO_down_2014', 'Disease_Signatures_from_GEO_up_2014', 'DrugMatrix', 'Drug_Perturbations_from_GEO_2014', 'Drug_Perturbations_from_GEO_down', 'Drug_Perturbations_from_GEO_up', 'ENCODE_Histone_Modifications_2013', 'ENCODE_Histone_Modifications_2015', 'ENCODE_TF_ChIP-seq_2014', 'ENCODE_TF_ChIP-seq_2015', 'ENCODE_and_ChEA_Consensus_TFs_from_ChIP-X', 'ESCAPE', 'Elsevier_Pathway_Collection', 'Enrichr_Libraries_Most_Popular_Genes', 'Enrichr_Submissions_TF-Gene_Coocurrence', 'Enrichr_Users_Contributed_Lists_2020', 'Epigenomics_Roadmap_HM_ChIP-seq', 'FANTOM6_lncRNA_KD_DEGs', 'GO_Biological_Process_2021', 'GO_Biological_Process_2023', 'GO_Biological_Process_2025', 'GO_Cellular_Component_2021', 'GO_Cellular_Component_2023', 'GO_Cellular_Component_2025', 'GO_Molecular_Function_2021', 'GO_Molecular_Function_2023', 'GO_Molecular_Function_2025', 'GTEx_Aging_Signatures_2021', 'GTEx_Tissue_Expression_Down', 'GTEx_Tissue_Expression_Up', 'GTEx_Tissues_V8_2023', 'GWAS_Catalog_2019', 'GWAS_Catalog_2023', 'GWAS_Catalog_2025', 'GeDiPNet_2023', 'GeneSigDB', 'Gene_Perturbations_from_GEO_down', 'Gene_Perturbations_from_GEO_up', 'Genes_Associated_with_NIH_Grants', 'Genome_Browser_PWMs', 'GlyGen_Glycosylated_Proteins_2022', 'HDSigDB_Human_2021', 'HDSigDB_Mouse_2021', 'HMDB_Metabolites', 'HMS_LINCS_KinomeScan', 'HomoloGene', 'HuBMAP_ASCT_plus_B_augmented_w_RNAseq_Coexpression', 'HuBMAP_ASCTplusB_augmented_2022', 'HumanCyc_2015', 'HumanCyc_2016', 'Human_Gene_Atlas', 'Human_Phenotype_Ontology', 'IDG_Drug_Targets_2022', 'InterPro_Domains_2019', 'JASPAR_PWM_Human_2025', 'JASPAR_PWM_Mouse_2025', 'Jensen_COMPARTMENTS', 'Jensen_DISEASES', 'Jensen_DISEASES_Curated_2025', 'Jensen_DISEASES_Experimental_2025', 'Jensen_TISSUES', 'KEA_2013', 'KEA_2015', 'KEGG_2013', 'KEGG_2015', 'KEGG_2016', 'KEGG_2019_Human', 'KEGG_2019_Mouse', 'KEGG_2021_Human', 'KEGG_2026', 'KOMP2_Mouse_Phenotypes_2022', 'Kinase_Perturbations_from_GEO_down', 'Kinase_Perturbations_from_GEO_up', 'L1000_Kinase_and_GPCR_Perturbations_down', 'L1000_Kinase_and_GPCR_Perturbations_up', 'LINCS_L1000_CRISPR_KO_Consensus_Sigs', 'LINCS_L1000_Chem_Pert_Consensus_Sigs', 'LINCS_L1000_Chem_Pert_down', 'LINCS_L1000_Chem_Pert_up', 'LINCS_L1000_Ligand_Perturbations_down', 'LINCS_L1000_Ligand_Perturbations_up', 'Ligand_Perturbations_from_GEO_down', 'Ligand_Perturbations_from_GEO_up', 'MAGMA_Drugs_and_Diseases', 'MAGNET_2023', 'MCF7_Perturbations_from_GEO_down', 'MCF7_Perturbations_from_GEO_up', 'MGI_Mammalian_Phenotype_Level_4_2021', 'MGI_Mammalian_Phenotype_Level_4_2024', 'MSigDB_Computational', 'MSigDB_Hallmark_2020', 'MSigDB_Oncogenic_Signatures', 'Metabolomics_Workbench_Metabolites_2022', 'Microbe_Perturbations_from_GEO_down', 'Microbe_Perturbations_from_GEO_up', 'MoTrPAC_2023', 'Mouse_Gene_Atlas', 'NCI-60_Cancer_Cell_Lines', 'NCI-Nature_2016', 'NIBR_DRUGseq_2025_down', 'NIBR_DRUGseq_2025_up', 'NURSA_Human_Endogenous_Complexome', 'OMIM_Disease', 'OMIM_Expanded', 'Old_CMAP_down', 'Old_CMAP_up', 'Orphanet_Augmented_2021', 'PFOCR_Pathways_2023', 'PPI_Hub_Proteins', 'PanglaoDB_Augmented_2021', 'Panther_2015', 'Panther_2016', 'PerturbAtlas', 'PerturbAtlas_MouseGenePerturbationSigs', 'PerturbSeq_ReplogleK562', 'PerturbSeq_ReplogleRPE1', 'Pfam_Domains_2019', 'Pfam_InterPro_Domains', 'PheWeb_2019', 'PhenGenI_Association_2021', 'Phosphatase_Substrates_from_DEPOD', 'ProteomicsDB_2020', 'Proteomics_Drug_Atlas_2023', 'RNA-Seq_Disease_Gene_and_Drug_Signatures_from_GEO', 'Rare_Diseases_AutoRIF_ARCHS4_Predictions', 'Rare_Diseases_AutoRIF_Gene_Lists', 'Rare_Diseases_GeneRIF_ARCHS4_Predictions', 'Rare_Diseases_GeneRIF_Gene_Lists', 'Reactome_2022', 'Reactome_Pathways_2024', 'RummaGEO_DrugPerturbations_2025', 'RummaGEO_GenePerturbations_2025', 'Rummagene_kinases', 'Rummagene_signatures', 'Rummagene_transcription_factors', 'SILAC_Phosphoproteomics', 'Sciplex_Drug_Perturbation_Signatures_2025', 'SubCell_BarCode', 'SynGO_2022', 'SynGO_2024', 'SysMyo_Muscle_Gene_Sets', 'TF-LOF_Expression_from_GEO', 'TF_Perturbations_Followed_by_Expression', 'TG_GATES_2020', 'TISSUES_Curated_2025', 'TISSUES_Experimental_2025', 'TRANSFAC_and_JASPAR_PWMs', 'TRRUST_Transcription_Factors_2019', 'Table_Mining_of_CRISPR_Studies', 'Tabula_Muris', 'Tabula_Sapiens', 'TargetScan_microRNA', 'TargetScan_microRNA_2017', 'The_Kinase_Library_2023', 'The_Kinase_Library_2024', 'Tissue_Protein_Expression_from_Human_Proteome_Map', 'Tissue_Protein_Expression_from_ProteomicsDB', 'Transcription_Factor_PPIs', 'UK_Biobank_GWAS_v1', 'Virus-Host_PPI_P-HIPSTer_2020', 'VirusMINT', 'Virus_Perturbations_from_GEO_down', 'Virus_Perturbations_from_GEO_up', 'WikiPathway_2021_Human', 'WikiPathway_2023_Human', 'WikiPathways_2013', 'WikiPathways_2015', 'WikiPathways_2016', 'WikiPathways_2019_Human', 'WikiPathways_2019_Mouse', 'WikiPathways_2024_Human', 'WikiPathways_2024_Mouse', 'dbGaP', 'huMAP', 'lncHUB_lncRNA_Co-Expression', 'miRTarBase_2017']

## GO pathway

In [5]:
rank_data = driver_df[["gene_names", "Day 12 Control_corr"]].sort_values('Day 12 Control_corr', ascending=False).dropna()

# Run GSEA Prerank
pre_res = gseapy.prerank(
    rnk=rank_data, 
    gene_sets="GO_Biological_Process_2025",
    threads=16,
    min_size=5,
    max_size=1000,
    permutation_num=2000
)

2026-02-02 11:08:53,006 [WARNING] Duplicated values found in preranked stats: 0.15% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

In [6]:
# Enriched in dead end

pre_res.res2d.sort_values("NES", ascending=False).head(20)[["Term", "ES", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]] # Top Day 12

,Term,ES,NES,NOM p-val,FWER p-val,FDR q-val
0,Epidermis Development (GO:0008544),0.65148,1.832768,0.002571,0.4625,0.673351
1,Regulation of Trans-Synaptic Signaling (GO:009...,0.794156,1.804547,0.001188,0.593,0.504901
2,Regulation of Glycolytic Process (GO:0006110),0.816355,1.756093,0.00489,0.802,0.66826
3,Proteolysis Involved in Protein Catabolic Proc...,0.743789,1.755604,0.006105,0.803,0.504452
7,Antigen Processing and Presentation of Exogeno...,0.858342,1.711653,0.010753,0.935,0.505029
5,Antigen Processing and Presentation of Exogeno...,0.858342,1.711653,0.010753,0.935,0.505029
6,Antigen Processing and Presentation of Peptide...,0.858342,1.711653,0.010753,0.935,0.505029
10,Negative Regulation of Myeloid Leukocyte Diffe...,0.761694,1.639877,0.025862,0.9925,0.978021
11,Positive Regulation of Purine Nucleotide Catab...,0.871029,1.638283,0.009423,0.9925,0.795758
12,Positive Regulation of Glycolytic Process (GO:...,0.871029,1.638283,0.009423,0.9925,0.795758
14,Regulation of Stress-Activated MAPK Cascade (G...,0.861742,1.633115,0.012896,0.9935,0.762007
19,Negative Regulation of Carbohydrate Metabolic ...,0.847319,1.5783,0.022093,1.0,1.0
20,Protein Catabolic Process (GO:0030163),0.603459,1.575067,0.023839,1.0,1.0
21,Protein Tetramerization (GO:0051262),0.83498,1.561108,0.026997,1.0,1.0
22,Antigen Processing and Presentation of Peptide...,0.844698,1.558734,0.021251,1.0,1.0
23,Positive Regulation of Sprouting Angiogenesis ...,0.736308,1.557546,0.042067,1.0,1.0
25,Positive Regulation of Apoptotic Signaling Pat...,0.654014,1.544708,0.03744,1.0,1.0
28,Peptide Hormone Processing (GO:0016486),0.742659,1.529114,0.059929,1.0,1.0
33,Regulation of Mesenchymal Cell Proliferation (...,0.810176,1.516539,0.037759,1.0,1.0
34,Positive Regulation of ATP Metabolic Process (...,0.765289,1.51182,0.051251,1.0,1.0

In [7]:
# Enriched in iPSC path
pre_res.res2d.sort_values('NES', ascending=True).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]  # Top mESC

,Term,NES,NOM p-val,FWER p-val,FDR q-val
4,Chromatin Organization (GO:0006325),-1.740148,0.003165,0.508,0.95249
8,Protein Polyubiquitination (GO:0000209),-1.69159,0.002494,0.7605,1.0
9,DNA Metabolic Process (GO:0006259),-1.652498,0.011735,0.9135,1.0
13,Male Meiotic Nuclear Division (GO:0007140),-1.636868,0.000833,0.9525,1.0
15,Transcription by RNA Polymerase II (GO:0006366),-1.626133,0.004149,0.9685,1.0
16,Transcription Initiation-Coupled Chromatin Rem...,-1.600658,0.006071,0.9885,1.0
17,Regulation of Viral Genome Replication (GO:004...,-1.594761,0.017964,0.991,1.0
18,Regulation of Insulin Secretion (GO:0050796),-1.592851,0.008584,0.992,1.0
24,Visual System Development (GO:0150063),-1.552392,0.006809,0.999,1.0
26,Negative Regulation of Bone Remodeling (GO:004...,-1.538783,0.006843,1.0,1.0
27,Female Gamete Generation (GO:0007292),-1.530514,0.023009,1.0,1.0
29,Defense Response to Virus (GO:0051607),-1.525263,0.019716,1.0,1.0
30,Phospholipid Transport (GO:0015914),-1.522562,0.024452,1.0,1.0
31,Regulation of Cholesterol Efflux (GO:0010874),-1.517735,0.011607,1.0,1.0
32,ATP Metabolic Process (GO:0046034),-1.516903,0.019749,1.0,1.0
35,Regulation of Organelle Organization (GO:0033043),-1.509551,0.026339,1.0,1.0
37,Negative Regulation of Protein Phosphorylation...,-1.505115,0.036379,1.0,1.0
38,Carbohydrate Metabolic Process (GO:0005975),-1.503639,0.01815,1.0,1.0
39,Positive Regulation of Protein Secretion (GO:0...,-1.49335,0.038875,1.0,1.0
40,Chromatin Remodeling (GO:0006338),-1.492531,0.046319,1.0,1.0

## GO molecular function

In [8]:
rank_data = driver_df[["gene_names", "Day 12 Control_corr"]].sort_values('Day 12 Control_corr', ascending=False).dropna()

# Run GSEA Prerank
pre_res = gseapy.prerank(
    rnk=rank_data, 
    gene_sets="GO_Molecular_Function_2025",
    threads=16,
    min_size=5,
    max_size=1000,
    permutation_num=2000
)

2026-02-02 11:09:29,168 [WARNING] Duplicated values found in preranked stats: 0.15% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

In [9]:
# Enriched in dead end

pre_res.res2d.sort_values("NES", ascending=False).head(20)[["Term", "ES", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]] # Top Day 12

,Term,ES,NES,NOM p-val,FWER p-val,FDR q-val
0,Chemokine Receptor Binding (GO:0042379),0.785248,1.921597,0.0,0.0225,0.028389
1,Cysteine-Type Endopeptidase Activity (GO:0004197),0.679228,1.680922,0.014252,0.457,0.374682
3,Exopeptidase Activity (GO:0008238),0.800233,1.647327,0.023284,0.577,0.36138
4,Chemokine Activity (GO:0008009),0.710391,1.628463,0.024643,0.6415,0.330893
6,Cysteine-Type Peptidase Activity (GO:0008234),0.613392,1.593236,0.02439,0.7675,0.376664
7,Carboxypeptidase Activity (GO:0004180),0.763355,1.589139,0.029817,0.781,0.326742
11,Monoatomic Cation Channel Activity (GO:0005261),0.663853,1.555057,0.040342,0.8685,0.377016
12,GTP Binding (GO:0005525),0.534418,1.522445,0.021978,0.933,0.429786
13,Phosphatase Binding (GO:0019902),0.674406,1.491764,0.068075,0.9625,0.476126
14,Guanyl Ribonucleotide Binding (GO:0032561),0.489552,1.46521,0.035088,0.9835,0.516413
15,Endopeptidase Activity (GO:0004175),0.43109,1.452261,0.018362,0.9875,0.511636
18,G Protein-Coupled Peptide Receptor Activity (G...,0.673691,1.410032,0.092994,0.996,0.608802
19,Alcohol Dehydrogenase (NADP+) Activity (GO:000...,0.744777,1.403588,0.10782,0.9965,0.583026
22,Metalloexopeptidase Activity (GO:0008235),0.599792,1.355053,0.129545,0.9995,0.700199
28,Metallocarboxypeptidase Activity (GO:0004181),0.681644,1.290891,0.204152,1.0,0.881024
33,SH3 Domain Binding (GO:0017124),0.607021,1.261696,0.214876,1.0,0.938479
34,Protein Serine/Threonine Kinase Activator Acti...,0.544584,1.261308,0.190594,1.0,0.884976
35,Calcium Channel Activity (GO:0005262),0.603794,1.259642,0.209639,1.0,0.841226
37,Phosphatase Activator Activity (GO:0019211),0.672701,1.251967,0.223934,1.0,0.822577
39,Protein Kinase Activator Activity (GO:0030295),0.457253,1.239939,0.156331,1.0,0.821889

In [10]:
# Enriched in iPSC path
pre_res.res2d.sort_values('NES', ascending=True).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]  # Top mESC

,Term,NES,NOM p-val,FWER p-val,FDR q-val
2,mRNA Binding (GO:0003729),-1.662355,0.006809,0.282,0.370934
5,Iron Ion Binding (GO:0005506),-1.598965,0.004992,0.549,0.462834
8,2-Oxoglutarate-Dependent Dioxygenase Activity ...,-1.5827,0.007765,0.616,0.371886
9,Methylated Histone Binding (GO:0035064),-1.558144,0.009821,0.73,0.304556
10,Methylation-Dependent Protein Binding (GO:0140...,-1.558144,0.009821,0.73,0.304556
16,Protein Kinase C Binding (GO:0005080),-1.430195,0.064378,0.9865,0.924556
17,Guanyl-Nucleotide Exchange Factor Activity (GO...,-1.423662,0.079723,0.9915,0.841862
20,Single-Stranded DNA Binding (GO:0003697),-1.375777,0.094872,0.998,1.0
21,Ubiquitin Binding (GO:0043130),-1.359001,0.102322,0.999,1.0
23,GTPase Regulator Activity (GO:0030695),-1.328511,0.101404,1.0,1.0
24,Nuclear Receptor Binding (GO:0016922),-1.299989,0.14346,1.0,1.0
25,Epidermal Growth Factor Receptor Binding (GO:0...,-1.299211,0.124783,1.0,1.0
26,Ubiquitin-Like Ligase-Substrate Adaptor Activi...,-1.298579,0.150895,1.0,1.0
27,GTPase Activator Activity (GO:0005096),-1.297614,0.130506,1.0,1.0
29,Protein Serine/Threonine Kinase Inhibitor Acti...,-1.288885,0.154321,1.0,1.0
30,Ubiquitin-Protein Transferase Activity (GO:000...,-1.277568,0.128874,1.0,1.0
31,RNA Polymerase II-specific DNA-binding Transcr...,-1.273207,0.111806,1.0,1.0
32,Inorganic Cation Transmembrane Transporter Act...,-1.265459,0.172145,1.0,0.987834
36,Endopeptidase Activator Activity (GO:0061133),-1.253259,0.179595,1.0,1.0
38,Magnesium Ion Binding (GO:0000287),-1.246738,0.180051,1.0,0.987402

## MSigDB_Hallmark_2020

In [11]:
rank_data = driver_df[["gene_names", "Day 12 Control_corr"]].sort_values('Day 12 Control_corr', ascending=False).dropna()

# Run GSEA Prerank
pre_res = gseapy.prerank(
    rnk=rank_data, 
    gene_sets='MSigDB_Hallmark_2020', # Or other libraries
    threads=16,
    min_size=5,
    max_size=1000,
)

2026-02-02 11:09:46,565 [WARNING] Duplicated values found in preranked stats: 0.15% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

In [12]:
# Enriched in dead end

pre_res.res2d.sort_values('NES', ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]] # Top Day 12

                             Term       NES NOM p-val FWER p-val FDR q-val
1                     p53 Pathway  1.606321  0.002924      0.215  0.471552
2         Estrogen Response Early  1.566862  0.008086      0.284  0.317462
3         Cholesterol Homeostasis  1.501027  0.042184      0.433  0.370063
5               Androgen Response   1.43902  0.051213      0.555  0.410751
10            Allograft Rejection  1.363014  0.043732      0.738  0.535044
11         Estrogen Response Late  1.361683  0.043732       0.74  0.449274
12      Unfolded Protein Response  1.334365  0.142512      0.781  0.440256
13           IL-2/STAT5 Signaling  1.286976  0.059155      0.868  0.505433
15               mTORC1 Signaling  1.235128  0.136483      0.931  0.588099
16     Wnt-beta Catenin Signaling  1.231807  0.207254      0.935  0.536715
17       PI3K/AKT/mTOR  Signaling  1.212622  0.195804      0.953  0.532648
18                 Myc Targets V1  1.200494  0.252927      0.959  0.521523
19              KRAS Signaling Dn  1.161954  0.202532      0.973  0.576087
20  TNF-alpha Signaling via NF-kB  1.125914  0.197568      0.986  0.636648
21                    Pperoxisome  1.115511  0.320099       0.99  0.623909
22                      Apoptosis  1.115361  0.210526       0.99  0.585263
23                 UV Response Up   1.09651  0.278689       0.99  0.600197
24          Xenobiotic Metabolism  1.089579  0.288952      0.991   0.58552
25       IL-6/JAK/STAT3 Signaling  1.050553  0.355795      0.996    0.6573
27          Inflammatory Response  1.019662  0.403561      0.998  0.705935

In [13]:
# Enriched in iPSC path
pre_res.res2d.sort_values('NES', ascending=True).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]  # Top mESC

                                 Term       NES NOM p-val FWER p-val FDR q-val
0                     G2-M Checkpoint -1.633574  0.006154      0.136  0.073812
4                     Spermatogenesis -1.468485  0.060914      0.584  0.227791
6                          DNA Repair -1.435023  0.052901      0.678  0.197484
7           Oxidative Phosphorylation -1.399611  0.067395      0.779  0.204328
8                     Mitotic Spindle  -1.38439  0.061934      0.817  0.182331
9                         E2F Targets -1.378906  0.078947      0.831  0.159193
14          Interferon Alpha Response -1.272851  0.124611      0.967  0.275207
26                       Adipogenesis -1.022899  0.424961        1.0  0.798308
30               Bile Acid Metabolism -0.923083  0.587931        1.0  0.989322
31          Interferon Gamma Response -0.839844   0.77259        1.0       1.0
32                    Apical Junction -0.803911  0.834337        1.0       1.0
38                        Coagulation -0.760211     0.875        1.0       1.0
40                     UV Response Dn -0.730438  0.932847        1.0       1.0
41    Reactive Oxygen Species Pathway -0.723653  0.828423        1.0  0.968008
46              Fatty Acid Metabolism -0.647092  0.942717        1.0  0.961122
48  Epithelial Mesenchymal Transition  0.609131       1.0        1.0  0.976084
47                 Hedgehog Signaling  0.620506  0.946602        1.0       1.0
45                Pancreas Beta Cells  0.669182  0.860911        1.0       1.0
44                         Glycolysis  0.678488  0.975138        1.0       1.0
43                     Apical Surface  0.702693  0.874372        1.0       1.0

## Cell types

In [14]:
rank_data = driver_df[["gene_names", "Day 12 Control_corr"]].sort_values('Day 12 Control_corr', ascending=False).dropna()

# Run GSEA Prerank
pre_res = gseapy.prerank(
    rnk=rank_data, 
    gene_sets='PanglaoDB_Augmented_2021', # Or other libraries
    threads=16,
    min_size=5,
    max_size=1000,
)

# Enriched in dead end

pre_res.res2d.sort_values('NES', ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]] # Top Day 12

2026-02-02 11:10:02,435 [WARNING] Duplicated values found in preranked stats: 0.15% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

                        Term       NES NOM p-val FWER p-val FDR q-val
0        Gastric Chief Cells  2.220668       0.0        0.0       0.0
1      Salivary Mucous Cells  2.177413       0.0        0.0       0.0
2             Cholangiocytes  2.036495       0.0      0.003  0.001335
3   Mammary Epithelial Cells  2.030373       0.0      0.004  0.001335
4              Keratinocytes  1.999058       0.0      0.011  0.003203
5   Luminal Epithelial Cells  1.982635       0.0      0.016  0.003782
6             Foveolar Cells  1.968645       0.0      0.018  0.003623
8            Microfold Cells  1.925072       0.0      0.023  0.004004
9                  Sebocytes  1.910495       0.0      0.026  0.004152
10          Epithelial Cells  1.905622       0.0      0.029  0.004137
11          Urothelial Cells  1.898278  0.002445       0.03  0.004004
12               Trichocytes  1.881104   0.00271      0.039  0.004671
13    Trophoblast Stem Cells  1.872717       0.0      0.042  0.004928
14       Airway Goblet Cells  1.869159       0.0      0.044  0.005053
15              Goblet Cells  1.830768       0.0       0.07  0.007207
16              Hepatoblasts  1.798959  0.002681        0.1  0.010093
17              Ductal Cells  1.798245       0.0      0.102  0.009657
18              Merkel Cells  1.745493  0.005376      0.194  0.017795
19           Principal Cells  1.733442  0.005602      0.215  0.019528
21         Trophoblast Cells  1.705674  0.002755      0.272  0.024291

In [15]:
# Enriched in iPSC path
pre_res.res2d.sort_values('NES', ascending=True).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]  # Top mESC

                         Term       NES NOM p-val FWER p-val FDR q-val
7      Pluripotent Stem Cells -1.965991       0.0      0.002   0.00242
20             Epiblast Cells -1.723253  0.001567      0.147  0.079066
23       Embryonic Stem Cells -1.569442  0.002994      0.639  0.357948
24        Gamma Delta T Cells -1.568614  0.015385      0.641  0.270075
27              Oxyphil Cells -1.466755  0.054098      0.918  0.547491
30         Adrenergic Neurons -1.414405  0.055456      0.969  0.700029
31            Ependymal Cells  -1.40723  0.076285      0.972  0.635755
32                   Myocytes -1.403557  0.047544      0.974  0.573631
36                 Osteocytes -1.338558  0.067976      0.996  0.828668
39                  Microglia -1.309889  0.071429      0.999  0.903691
40      Proximal Tubule Cells -1.292699  0.152318        1.0  0.916959
42             Decidual Cells -1.250572   0.15873        1.0       1.0
44                Delta Cells -1.221862  0.177953        1.0       1.0
46              Reticulocytes -1.207186   0.22735        1.0       1.0
47           Gamma (PP) Cells  -1.20344    0.1952        1.0       1.0
51         T Regulatory Cells  -1.14458   0.25641        1.0       1.0
54                 Germ Cells -1.112678  0.309836        1.0       1.0
55  T Follicular Helper Cells -1.107958   0.31962        1.0       1.0
57                Eosinophils -1.104164  0.293578        1.0       1.0
58                Neutrophils -1.100323  0.331269        1.0       1.0

Epithelial markers are strongly enriched among the control drivers

## ChipSeq targets, ChEA

In [16]:
rank_data = driver_df[["gene_names", "Day 12 Control_corr"]].sort_values('Day 12 Control_corr', ascending=False).dropna()

# Run GSEA Prerank
pre_res = gseapy.prerank(
    rnk=rank_data, 
    gene_sets='ChEA_2022', # Or other libraries
    threads=16,
    min_size=5,
    max_size=1000
)

2026-02-02 11:10:14,662 [WARNING] Duplicated values found in preranked stats: 0.15% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

In [17]:
# Enriched in dead end

pre_res.res2d.sort_values('NES', ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]] # Top Day 12

,Term,NES,NOM p-val,FWER p-val,FDR q-val
24,RARG 19884340 ChIP-ChIP MEFs Mouse,1.730881,0.0,0.221,0.318778
26,JARID2 20075857 ChIP-Seq MESCs Mouse,1.713658,0.0,0.248,0.183671
29,SUZ12 18974828 ChIP-Seq MESCs Mouse,1.686985,0.0,0.3,0.154408
38,MTF2 20144788 ChIP-Seq MESCs Mouse,1.639123,0.0,0.429,0.183671
42,SUZ12 27294783 Chip-Seq ESCs Mouse,1.612293,0.0,0.503,0.183546
49,SUZ12 20075857 ChIP-Seq MESCs Mouse,1.550556,0.0,0.699,0.267101
51,TP63 17297297 ChIP-ChIP HaCaT Human,1.54484,0.007712,0.72,0.24104
52,PITX1 30713093 ChIP-Seq Epithelial Human Tongu...,1.543706,0.027569,0.724,0.212
58,TP63 30713093 ChIP-Seq Epithelial Human Tongue...,1.507623,0.0,0.819,0.253473
62,JARID2 20064375 ChIP-Seq MESCs Mouse,1.493164,0.0,0.852,0.25689
64,ESR1 26153859 ChIP-Seq MCF-7 Human BreastCancer,1.476982,0.0,0.889,0.26263
71,BMI1 19503595 ChIP-Seq MEFsC Mouse,1.447041,0.006369,0.931,0.309335
74,TFAP2C 20629094 ChIP-Seq MCF-7 Human,1.438241,0.0,0.942,0.305368
76,EED 16625203 ChIP-ChIP MESCs Mouse,1.415037,0.010381,0.963,0.339146
77,ESR1 20056654 ChIP-Seq MCF-7 Human BreastCancer,1.408286,0.019868,0.965,0.332973
78,PHC1 16625203 ChIP-ChIP MESCs Mouse,1.401036,0.010949,0.97,0.330919
80,P63 26484246 Chip-Seq KERATINOCYTES Human,1.387926,0.0,0.977,0.345001
85,BMI1 23680149 ChIP-Seq NPCS Mouse,1.371994,0.0,0.987,0.370524
88,WDR5 24793694 ChIP-Seq LNCAP Human,1.362843,0.022876,0.991,0.376845
92,TP53 32428506 ChIP-Seq Human Liver Heptoma,1.354299,0.04712,0.992,0.380479

In [18]:
# Enriched in iPSC path
pre_res.res2d.sort_values('NES', ascending=True).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]  # Top mESC

,Term,NES,NOM p-val,FWER p-val,FDR q-val
0,FOXM1 23109430 ChIP-Seq U2OS Human,-2.069772,0.0,0.0,0.0
1,SMAD1 18555785 ChIP-Seq MESCs Mouse,-2.06917,0.0,0.0,0.0
2,TCF3 18692474 ChIP-Seq MESCs Mouse,-2.031116,0.0,0.0,0.0
3,MYBL2 22936984 ChIP-ChIP MESCs Mouse,-2.028174,0.0,0.0,0.0
4,NACC1 18358816 ChIP-ChIP MESCs Mouse,-2.026743,0.0,0.0,0.0
5,NANOG 18700969 ChIP-ChIP MESCs Mouse,-1.998373,0.0,0.0,0.0
6,NANOG 18555785 ChIP-Seq MESCs Mouse,-1.925797,0.0,0.004,0.000518
7,SOX2 18692474 ChIP-Seq MESCs Mouse,-1.921982,0.0,0.004,0.000454
8,POU5F1 18358816 ChIP-ChIP MESCs Mouse,-1.919393,0.0,0.005,0.000504
9,POU5F1 18700969 ChIP-ChIP MESCs Mouse,-1.909834,0.0,0.006,0.000544
10,SALL4 18804426 ChIP-ChIP MESCs Mouse,-1.902568,0.0,0.006,0.000495
11,SOX2 18358816 ChIP-ChIP MESCs Mouse,-1.868639,0.0,0.014,0.001058
12,TCF3 18692474 ChIP-Seq MEFs Mouse,-1.865596,0.0,0.014,0.000977
13,SOX2 19030024 ChIP-ChIP MESCs Mouse,-1.858952,0.0,0.016,0.001037
14,SOX2 18555785 ChIP-Seq MESCs Mouse,-1.846268,0.0,0.022,0.001331
15,KDM5B 21448134 ChIP-Seq MESCs Mouse,-1.835099,0.0,0.027,0.001531
16,SMAD3 22036565 ChIP-Seq ESCs Mouse,-1.830427,0.0,0.031,0.001654
17,POU5F1 18555785 ChIP-Seq MESCs Mouse,-1.82865,0.0,0.031,0.001562
18,SOX2 18692474 ChIP-Seq MEFs Mouse,-1.821246,0.0,0.036,0.001719
19,MYC 19079543 ChIP-ChIP MESCs Mouse,-1.812203,0.0,0.042,0.001996

## Enriched targets from ChipSeq, Ensembl

In [19]:
rank_data = driver_df[["gene_names", "Day 12 Control_corr"]].sort_values('Day 12 Control_corr', ascending=False).dropna()

# Run GSEA Prerank
pre_res = gseapy.prerank(
    rnk=rank_data, 
    gene_sets='ENCODE_TF_ChIP-seq_2015', # Or other libraries
    threads=16,
    min_size=5,
    max_size=1000
)

2026-02-02 11:11:13,634 [WARNING] Duplicated values found in preranked stats: 0.15% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

In [20]:
# Enriched in dead end

pre_res.res2d.sort_values('NES', ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]] # Top Day 12

                     Term       NES NOM p-val FWER p-val FDR q-val
1         FOSL1 C2C12 mm9   1.96268       0.0      0.019  0.021294
8    SMARCC1 HeLa-S3 hg19  1.723216       0.0      0.208  0.135609
21        ZEB1 HepG2 hg19  1.635744   0.01039      0.412  0.216301
23       TAL1 G1E-ER4 mm9  1.616329       0.0      0.468  0.200051
25         ATF3 K562 hg19  1.570052       0.0      0.611  0.257993
31       EP300 ECC-1 hg19  1.540566  0.003077      0.698  0.279623
42   SMARCC2 HeLa-S3 hg19  1.498257  0.016393      0.799  0.350949
46        MAX myocyte mm9   1.47301  0.009375       0.86  0.381329
48       RAD21 ECC-1 hg19  1.462772  0.010239      0.878  0.370713
52      JUND GM12878 hg19  1.447306  0.033766      0.904  0.381609
65       JUND HCT116 hg19  1.403056  0.034286      0.951  0.504228
75        REST ECC-1 hg19  1.376335  0.009346      0.973  0.574842
87      JUND HeLa-S3 hg19  1.355251  0.008163       0.98  0.632697
88       EP300 MCF-7 hg19  1.352326  0.086849      0.981  0.603755
90      ZEB1 GM12878 hg19  1.345172  0.053521      0.983  0.597052
98        JUND MCF-7 hg19  1.333123  0.096953      0.989  0.618364
100     FOSL1 HCT116 hg19  1.332924  0.056047      0.989  0.582913
116     JUND SK-N-SH hg19  1.301097  0.015873      0.997   0.71098
117       MYOD1 C2C12 mm9  1.297376  0.012195      0.997  0.694854
123     REST U-87 MG hg19  1.291483  0.093085      0.997  0.692725

In [21]:
# Enriched in iPSC path
pre_res.res2d.sort_values('NES', ascending=True).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]  # Top mESC

                      Term       NES NOM p-val FWER p-val FDR q-val
0   E2F4 MEL cell line mm9 -2.037147       0.0        0.0       0.0
2         FOXM1 ECC-1 hg19 -1.840812       0.0      0.028  0.013301
3        IRF3 GM12878 hg19 -1.807172       0.0      0.046  0.015201
4         E2F4 CH12.LX mm9 -1.804058       0.0      0.048  0.011876
5       NANOG H1-hESC hg19 -1.740666  0.001751      0.147  0.033442
6        E2F4 HeLa-S3 hg19 -1.736897       0.0      0.155  0.029926
7            SP2 K562 hg19 -1.735902       0.0      0.158  0.026194
9        NFYA GM12878 hg19 -1.717984       0.0      0.213  0.031945
10           FOS K562 hg19 -1.694223       0.0      0.281  0.040535
11        FOXM1 MCF-7 hg19 -1.691418  0.003205      0.289  0.037812
12      FOXM1 GM12878 hg19 -1.688037  0.002994      0.296  0.035756
13          NFYA K562 hg19 -1.680696       0.0      0.321   0.03626
14        CEBPZ HepG2 hg19 -1.672155  0.003091      0.345  0.037344
15       IRF3 HeLa-S3 hg19 -1.667803  0.001416      0.354  0.036848
16         TCF12 A549 hg19  -1.66095   0.00597      0.375  0.037305
17        SETDB1 U2OS hg19 -1.654646  0.001429      0.401   0.03818
18          SP2 HepG2 hg19 -1.653259       0.0      0.407  0.036437
19     STAT5A GM12878 hg19 -1.652922  0.001572      0.408  0.034518
20       E2F4 GM12878 hg19 -1.638903       0.0      0.453  0.038702
22         KAT2B K562 hg19 -1.623784       0.0       0.52  0.044462

## Test if specific gene sets are enriched

In [33]:
# Get libraries

panglao_lib = gseapy.get_library(name='PanglaoDB_Augmented_2021', organism='Mouse')
go_lib = gseapy.get_library(name='GO_Biological_Process_2025', organism='Mouse')
go_molecular_function = gseapy.get_library(name='GO_Molecular_Function_2025', organism='Mouse')
hallmark_lib = gseapy.get_library(name='MSigDB_Hallmark_2020', organism='Mouse')

In [34]:
target_sets = {
    "Apoptosis Activation": go_lib["Positive Regulation of Apoptotic Process (GO:0043065)"],
    "Apoptosis Inhibition": go_lib["Negative Regulation of Apoptotic Process (GO:0043066)"],
    "Cell Cycle Inhibition": go_lib["Negative Regulation of Cell Cycle (GO:0045786)"],
    "Cell Cycle Activation": go_lib["Positive Regulation of Cell Cycle (GO:0045787)"],
    "Apoptosis Signaling Inhibition": go_lib["Negative Regulation of Apoptotic Signaling Pathway (GO:2001234)"],
    "Apoptosis Signaling Activation": go_lib["Positive Regulation of Apoptotic Signaling Pathway (GO:2001235)"],
    "Stem Cell Proliferation": go_lib["Positive Regulation of Stem Cell Proliferation (GO:2000648)"],
    "Stem Cell Inhibited Proliferation": go_lib["Negative Regulation of Stem Cell Population Maintenance (GO:1902455)"],
    "Stem Cell Inhibited Differentiation": go_lib["Negative Regulation of Stem Cell Differentiation (GO:2000737)"],
    "Stem Cell Differentiation": go_lib["Positive Regulation of Stem Cell Differentiation (GO:2000738)"],
    "DNA Damage Response": go_lib["DNA Damage Response (GO:0006974)"],
    "DNA_Repair": hallmark_lib['DNA Repair'],
    "P53_Pathway": hallmark_lib['p53 Pathway'],
    "Keratinocytes": panglao_lib["Keratinocytes"],
    "Epithelial cells": panglao_lib["Epithelial Cells"]
}

rank_data = driver_df[["gene_names", "Day 12 Control_corr"]].sort_values('Day 12 Control_corr', ascending=False).dropna()

# Run GSEA Prerank
pre_res = gseapy.prerank(
    rnk=rank_data, 
    gene_sets=target_sets,
    threads=16,
    min_size=5,
    max_size=2000,
    permutation_num=1000,
    seed=0
)

pre_res.res2d.sort_values("NES", ascending=False).head(20)

2026-02-02 11:19:48,524 [WARNING] Duplicated values found in preranked stats: 0.15% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

,Name,Term,ES,NES,NOM p-val,FDR q-val,FWER p-val,Tag %,Gene %,Lead_genes
0,prerank,Keratinocytes,0.624645,2.0251,0.0,0.001222,0.001,22/41,17.03%,Lgals7;Lad1;Pkp1;Perp;Ovol1;Anxa8;S100a14;Krt1...
1,prerank,Epithelial cells,0.541295,1.924159,0.0,0.001222,0.002,32/67,19.08%,Lad1;Crb3;Mal2;Ovol1;Krt8;Dgat2;Gpx2;Misp;S100...
2,prerank,P53_Pathway,0.465473,1.60209,0.003289,0.032179,0.078,24/60,18.48%,Ccnd2;Ifi30;Nupr1;Perp;Cdkn1a;Sat1;Gpx2;Krt17;...
3,prerank,Apoptosis Signaling Activation,0.654014,1.540293,0.045024,0.038187,0.118,5/11,16.88%,Nupr1;Bbc3;App;Tnfrsf12a;Ddit3
7,prerank,Apoptosis Inhibition,0.210775,0.79448,0.944444,0.966599,0.978,18/107,15.12%,Ccnd2;Nupr1;Prkaa2;Cd44;Myc;Anxa5;Tmbim1;Ddah2...
10,prerank,Cell Cycle Inhibition,0.281041,0.694447,0.905,0.916497,0.988,1/14,1.40%,Nupr1
12,prerank,Apoptosis Signaling Inhibition,-0.238535,-0.560375,0.964346,0.984178,1.0,4/14,33.20%,Tcf7l2;Bmp4;Thbs1;Clu
11,prerank,Stem Cell Proliferation,-0.283705,-0.572438,0.962838,1.0,1.0,1/8,7.46%,Nanog
9,prerank,Cell Cycle Activation,-0.29015,-0.707803,0.871545,1.0,1.0,2/16,4.96%,Tcf7l1;Cited2
8,prerank,Apoptosis Activation,-0.241989,-0.775089,0.896603,1.0,1.0,29/63,37.66%,Dlc1;Rest;Gadd45b;Top2a;Bnip3;Tsc22d1;Sfrp1;Ec...
6,prerank,DNA Damage Response,-0.337952,-0.92416,0.543974,1.0,0.996,11/24,21.48%,Ash2l;Msh6;Nedd4;Top2a;Acer2;Fam111a;Brca1;Fbx...
5,prerank,Stem Cell Differentiation,-0.533121,-0.985243,0.517921,1.0,0.978,2/6,22.28%,Tcf15;Nr5a2
4,prerank,DNA_Repair,-0.722468,-1.421948,0.058419,0.313226,0.302,5/7,24.39%,Gpx4;Arl6ip1;Bcam;Pold4;Cda