Environment: `velocity`

In [1]:
import scanpy
import anndata
import matplotlib
from matplotlib import pyplot
import hdf5plugin
import numpy
import scvelo
import seaborn
import pandas
import warnings
import cellrank
import gseapy
import decoupler
import IPython

In [2]:
# Read input file
working_directory = "RNA Sequencing Data/"

# adata = scanpy.read_h5ad(working_directory + "/velocity_sdevelo.h5ad")

# Or read saved anndata objects
working_directory = "RNA Sequencing Data/"
base_name = "cellrank_version_5"
adata = scanpy.read_h5ad(
    working_directory+f"/{base_name}_anndata.h5ad"
)
driver_df = pandas.read_csv(
    working_directory+f"{base_name}_driver_genes.csv",
    index_col=0
)
combined_driver_df = pandas.read_csv(
    working_directory+f"{base_name}_driver_genes_combined.csv",
    index_col=0
)

In [3]:
# Read ChIP-seq targets
base_name = "ChIP Sequencing Data/chipseq_targets"

hic2_target_scores = pandas.read_csv(f"{base_name}_hic2_scores.csv", index_col=0)
klf4_hic2_target_scores = pandas.read_csv(f"{base_name}_klf4_hic2_scores.csv", index_col=0)
klf4_control_target_scores = pandas.read_csv(f"{base_name}_klf4_control_scores.csv", index_col=0)

hic2_targets = numpy.loadtxt(f"{base_name}_hic2_targets.txt", dtype=numpy.dtypes.StrDType)
klf4_hic2_targets = numpy.loadtxt(f"{base_name}_klf4_hic2_targets.txt", dtype=numpy.dtypes.StrDType)
klf4_control_targets = numpy.loadtxt(f"{base_name}_klf4_control_targets.txt", dtype=numpy.dtypes.StrDType)
klf4_targets = numpy.intersect1d(klf4_hic2_targets, klf4_control_targets)
shared_targets = numpy.intersect1d(hic2_targets, klf4_targets)

In [4]:
# Load bulk differential expression results

bulk_de = pandas.read_csv("RNA Sequencing Data/bulk_differential_expression_combined.csv", index_col=0)
bulk_metadata = pandas.read_csv("RNA Sequencing Data/bulk_sequencing_metadata.csv", index_col=0)
samples = bulk_metadata.index.to_list()
reprogramming_columns = bulk_de.columns[bulk_de.columns.str.contains("Reprogramming")]
reprogramming_de = pandas.read_csv("RNA Sequencing Data/bulk_differential_expression_reprogramming.csv", index_col=0)
mef_de = pandas.read_csv("RNA Sequencing Data/bulk_differential_expression_mef.csv", index_col=0)
mesc_de = pandas.read_csv("RNA Sequencing Data/bulk_differential_expression_mesc.csv", index_col=0)
ipsc_de = pandas.read_csv("RNA Sequencing Data/bulk_differential_expression_ipsc.csv", index_col=0)

In [5]:
# Variable genes and Cellrank drivers
variable_genes = adata.var_names.to_numpy()
variable_in_bulk = numpy.intersect1d(variable_genes, bulk_de.index.to_numpy())
stem_cell_drivers = driver_df.sort_values("Day 12 Control_corr", ascending=True).head(100).index.to_numpy()
dead_end_drivers = driver_df.sort_values("Day 12 Control_corr", ascending=False).head(100).index.to_numpy()
differentially_expressed_genes = reprogramming_de.loc[variable_in_bulk].query("padj < 0.05").index.to_numpy()

In [6]:
# Load list of transcription factors

tf_df = pandas.read_csv("ChIP Sequencing Data/Mus_musculus_TF.txt", sep="\t")
tf_array = tf_df["Symbol"].to_numpy()

# All target transcription factors
target_tfs = numpy.intersect1d(shared_targets, tf_array)

# Target transcription factors for which Hic2 changes expression significantly
de_target_tfs = numpy.intersect1d(target_tfs, differentially_expressed_genes)

de_dead_end_drivers = numpy.intersect1d(de_target_tfs, dead_end_drivers)
de_stem_cell_drivers = numpy.intersect1d(de_target_tfs, stem_cell_drivers)

In [12]:
genes_of_interest = de_dead_end_drivers.tolist() + de_stem_cell_drivers.tolist() + ["Klf4", "Myc", "Hic2", "Cdh1"]

In [8]:
# Show all possible libraries
names = gseapy.get_library_name(organism="Mouse")
print(names)

['ARCHS4_Cell-lines', 'ARCHS4_IDG_Coexp', 'ARCHS4_Kinases_Coexp', 'ARCHS4_TFs_Coexp', 'ARCHS4_Tissues', 'Achilles_fitness_decrease', 'Achilles_fitness_increase', 'Aging_Perturbations_from_GEO_down', 'Aging_Perturbations_from_GEO_up', 'Allen_Brain_Atlas_10x_scRNA_2021', 'Allen_Brain_Atlas_down', 'Allen_Brain_Atlas_up', 'Azimuth_2023', 'Azimuth_Cell_Types_2021', 'BioCarta_2013', 'BioCarta_2015', 'BioCarta_2016', 'BioPlanet_2019', 'BioPlex_2017', 'CCLE_Proteomics_2020', 'CM4AI_U2OS_Protein_Localization_Assemblies', 'COMPARTMENTS_Curated_2025', 'COMPARTMENTS_Experimental_2025', 'CORUM', 'COVID-19_Related_Gene_Sets', 'COVID-19_Related_Gene_Sets_2021', 'Cancer_Cell_Line_Encyclopedia', 'Carcinogenome', 'CellMarker_2024', 'CellMarker_Augmented_2021', 'ChEA_2013', 'ChEA_2015', 'ChEA_2016', 'ChEA_2022', 'Chromosome_Location', 'Chromosome_Location_hg19', 'ClinVar_2019', 'ClinVar_2025', 'DGIdb_Drug_Targets_2024', 'DSigDB', 'Data_Acquisition_Method_Most_Popular_Genes', 'DepMap_CRISPR_GeneDependency_CellLines_2023', 'DepMap_WG_CRISPR_Screens_Broad_CellLines_2019', 'DepMap_WG_CRISPR_Screens_Sanger_CellLines_2019', 'Descartes_Cell_Types_and_Tissue_2021', 'Diabetes_Perturbations_GEO_2022', 'DisGeNET', 'Disease_Perturbations_from_GEO_down', 'Disease_Perturbations_from_GEO_up', 'Disease_Signatures_from_GEO_down_2014', 'Disease_Signatures_from_GEO_up_2014', 'DrugMatrix', 'Drug_Perturbations_from_GEO_2014', 'Drug_Perturbations_from_GEO_down', 'Drug_Perturbations_from_GEO_up', 'ENCODE_Histone_Modifications_2013', 'ENCODE_Histone_Modifications_2015', 'ENCODE_TF_ChIP-seq_2014', 'ENCODE_TF_ChIP-seq_2015', 'ENCODE_and_ChEA_Consensus_TFs_from_ChIP-X', 'ESCAPE', 'Elsevier_Pathway_Collection', 'Enrichr_Libraries_Most_Popular_Genes', 'Enrichr_Submissions_TF-Gene_Coocurrence', 'Enrichr_Users_Contributed_Lists_2020', 'Epigenomics_Roadmap_HM_ChIP-seq', 'FANTOM6_lncRNA_KD_DEGs', 'GO_Biological_Process_2021', 'GO_Biological_Process_2023', 'GO_Biological_Process_2025', 'GO_Cellular_Component_2021', 'GO_Cellular_Component_2023', 'GO_Cellular_Component_2025', 'GO_Molecular_Function_2021', 'GO_Molecular_Function_2023', 'GO_Molecular_Function_2025', 'GTEx_Aging_Signatures_2021', 'GTEx_Tissue_Expression_Down', 'GTEx_Tissue_Expression_Up', 'GTEx_Tissues_V8_2023', 'GWAS_Catalog_2019', 'GWAS_Catalog_2023', 'GWAS_Catalog_2025', 'GeDiPNet_2023', 'GeneSigDB', 'Gene_Perturbations_from_GEO_down', 'Gene_Perturbations_from_GEO_up', 'Genes_Associated_with_NIH_Grants', 'Genome_Browser_PWMs', 'GlyGen_Glycosylated_Proteins_2022', 'HDSigDB_Human_2021', 'HDSigDB_Mouse_2021', 'HMDB_Metabolites', 'HMS_LINCS_KinomeScan', 'HomoloGene', 'HuBMAP_ASCT_plus_B_augmented_w_RNAseq_Coexpression', 'HuBMAP_ASCTplusB_augmented_2022', 'HumanCyc_2015', 'HumanCyc_2016', 'Human_Gene_Atlas', 'Human_Phenotype_Ontology', 'IDG_Drug_Targets_2022', 'InterPro_Domains_2019', 'JASPAR_PWM_Human_2025', 'JASPAR_PWM_Mouse_2025', 'Jensen_COMPARTMENTS', 'Jensen_DISEASES', 'Jensen_DISEASES_Curated_2025', 'Jensen_DISEASES_Experimental_2025', 'Jensen_TISSUES', 'KEA_2013', 'KEA_2015', 'KEGG_2013', 'KEGG_2015', 'KEGG_2016', 'KEGG_2019_Human', 'KEGG_2019_Mouse', 'KEGG_2021_Human', 'KEGG_2026', 'KOMP2_Mouse_Phenotypes_2022', 'Kinase_Perturbations_from_GEO_down', 'Kinase_Perturbations_from_GEO_up', 'L1000_Kinase_and_GPCR_Perturbations_down', 'L1000_Kinase_and_GPCR_Perturbations_up', 'LINCS_L1000_CRISPR_KO_Consensus_Sigs', 'LINCS_L1000_Chem_Pert_Consensus_Sigs', 'LINCS_L1000_Chem_Pert_down', 'LINCS_L1000_Chem_Pert_up', 'LINCS_L1000_Ligand_Perturbations_down', 'LINCS_L1000_Ligand_Perturbations_up', 'Ligand_Perturbations_from_GEO_down', 'Ligand_Perturbations_from_GEO_up', 'MAGMA_Drugs_and_Diseases', 'MAGNET_2023', 'MCF7_Perturbations_from_GEO_down', 'MCF7_Perturbations_from_GEO_up', 'MGI_Mammalian_Phenotype_Level_4_2021', 'MGI_Mammalian_Phenotype_Level_4_2024', 'MSigDB_Computational', 'MSigDB_Hallmark_2020', 'MSigDB_Oncogenic_Signatures', 'Metabolomics_Workbench_Metabolites_2022', 'Microbe_Perturbations_from_GEO_down', 'Microbe_Perturbations_from_GEO_up', 'MoTrPAC_2023', 'Mouse_Gene_Atlas', 'NCI-60_Cancer_Cell_Lines', 'NCI-Nature_2016', 'NIBR_DRUGseq_2025_down', 'NIBR_DRUGseq_2025_up', 'NURSA_Human_Endogenous_Complexome', 'OMIM_Disease', 'OMIM_Expanded', 'Old_CMAP_down', 'Old_CMAP_up', 'Orphanet_Augmented_2021', 'PFOCR_Pathways_2023', 'PPI_Hub_Proteins', 'PanglaoDB_Augmented_2021', 'Panther_2015', 'Panther_2016', 'PerturbAtlas', 'PerturbAtlas_MouseGenePerturbationSigs', 'PerturbSeq_ReplogleK562', 'PerturbSeq_ReplogleRPE1', 'Pfam_Domains_2019', 'Pfam_InterPro_Domains', 'PheWeb_2019', 'PhenGenI_Association_2021', 'Phosphatase_Substrates_from_DEPOD', 'ProteomicsDB_2020', 'Proteomics_Drug_Atlas_2023', 'RNA-Seq_Disease_Gene_and_Drug_Signatures_from_GEO', 'Rare_Diseases_AutoRIF_ARCHS4_Predictions', 'Rare_Diseases_AutoRIF_Gene_Lists', 'Rare_Diseases_GeneRIF_ARCHS4_Predictions', 'Rare_Diseases_GeneRIF_Gene_Lists', 'Reactome_2022', 'Reactome_Pathways_2024', 'RummaGEO_DrugPerturbations_2025', 'RummaGEO_GenePerturbations_2025', 'Rummagene_kinases', 'Rummagene_signatures', 'Rummagene_transcription_factors', 'SILAC_Phosphoproteomics', 'Sciplex_Drug_Perturbation_Signatures_2025', 'SubCell_BarCode', 'SynGO_2022', 'SynGO_2024', 'SysMyo_Muscle_Gene_Sets', 'TF-LOF_Expression_from_GEO', 'TF_Perturbations_Followed_by_Expression', 'TG_GATES_2020', 'TISSUES_Curated_2025', 'TISSUES_Experimental_2025', 'TRANSFAC_and_JASPAR_PWMs', 'TRRUST_Transcription_Factors_2019', 'Table_Mining_of_CRISPR_Studies', 'Tabula_Muris', 'Tabula_Sapiens', 'TargetScan_microRNA', 'TargetScan_microRNA_2017', 'The_Kinase_Library_2023', 'The_Kinase_Library_2024', 'Tissue_Protein_Expression_from_Human_Proteome_Map', 'Tissue_Protein_Expression_from_ProteomicsDB', 'Transcription_Factor_PPIs', 'UK_Biobank_GWAS_v1', 'Virus-Host_PPI_P-HIPSTer_2020', 'VirusMINT', 'Virus_Perturbations_from_GEO_down', 'Virus_Perturbations_from_GEO_up', 'WikiPathway_2021_Human', 'WikiPathway_2023_Human', 'WikiPathways_2013', 'WikiPathways_2015', 'WikiPathways_2016', 'WikiPathways_2019_Human', 'WikiPathways_2019_Mouse', 'WikiPathways_2024_Human', 'WikiPathways_2024_Mouse', 'dbGaP', 'huMAP', 'lncHUB_lncRNA_Co-Expression', 'miRTarBase_2017']

# Gene set enrichment for Cellrank drivers

## GO pathway

In [23]:
rank_data = driver_df[["Day 12 Control_corr"]].sort_values('Day 12 Control_corr', ascending=False).dropna()

# Run GSEA Prerank
pre_res = gseapy.prerank(
    rnk=rank_data, 
    gene_sets="GO_Biological_Process_2025",
    threads=16,
    min_size=5,
    max_size=1000,
    permutation_num=2000
)

2026-03-06 08:12:51,014 [WARNING] Duplicated values found in preranked stats: 0.15% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

In [24]:
# Enriched in dead end

pre_res.res2d.sort_values("NES", ascending=False).head(20)[["Term", "ES", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]] # Top Day 12

,Term,ES,NES,NOM p-val,FWER p-val,FDR q-val
0,Regulation of Trans-Synaptic Signaling (GO:009...,0.7959,1.822757,0.003628,0.5035,0.768442
1,Epidermis Development (GO:0008544),0.649669,1.797313,0.002516,0.621,0.556069
2,Regulation of Glycolytic Process (GO:0006110),0.815407,1.78089,0.005006,0.697,0.473467
4,Proteolysis Involved in Protein Catabolic Proc...,0.740806,1.728133,0.013564,0.8955,0.714186
5,Antigen Processing and Presentation of Exogeno...,0.858955,1.708986,0.01171,0.9355,0.519213
6,Antigen Processing and Presentation of Peptide...,0.858955,1.708986,0.01171,0.9355,0.519213
7,Antigen Processing and Presentation of Exogeno...,0.858955,1.708986,0.01171,0.9355,0.519213
9,Negative Regulation of Myeloid Leukocyte Diffe...,0.758163,1.65506,0.016645,0.9925,0.843681
14,Positive Regulation of Purine Nucleotide Catab...,0.870543,1.606844,0.013564,0.999,1.0
15,Positive Regulation of Glycolytic Process (GO:...,0.870543,1.606844,0.013564,0.999,1.0
18,Positive Regulation of Sprouting Angiogenesis ...,0.741846,1.589602,0.023428,0.9995,1.0
19,Regulation of Stress-Activated MAPK Cascade (G...,0.855582,1.575427,0.018328,1.0,1.0
20,Antigen Processing and Presentation of Peptide...,0.845897,1.573031,0.030488,1.0,1.0
22,Positive Regulation of Apoptotic Signaling Pat...,0.655181,1.559475,0.03949,1.0,1.0
23,Negative Regulation of Carbohydrate Metabolic ...,0.846898,1.559193,0.019048,1.0,1.0
24,Protein Catabolic Process (GO:0030163),0.603124,1.558183,0.025543,1.0,1.0
25,Protein Tetramerization (GO:0051262),0.832224,1.54837,0.02619,1.0,1.0
28,Regulation of Mesenchymal Cell Proliferation (...,0.808912,1.530455,0.036188,1.0,1.0
32,Peptide Hormone Processing (GO:0016486),0.741865,1.513597,0.059343,1.0,1.0
37,Positive Regulation of Cation Transmembrane Tr...,0.765504,1.499857,0.062127,1.0,1.0

In [25]:
# Enriched in iPSC path
pre_res.res2d.sort_values('NES', ascending=True).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]  # Top mESC

,Term,NES,NOM p-val,FWER p-val,FDR q-val
3,Chromatin Organization (GO:0006325),-1.734612,0.000799,0.5315,1.0
8,Protein Polyubiquitination (GO:0000209),-1.693375,0.005907,0.7375,1.0
10,DNA Metabolic Process (GO:0006259),-1.646768,0.010779,0.919,1.0
11,Transcription by RNA Polymerase II (GO:0006366),-1.640818,0.003416,0.935,1.0
12,Male Meiotic Nuclear Division (GO:0007140),-1.618388,0.001753,0.9675,1.0
13,Transcription Initiation-Coupled Chromatin Rem...,-1.614653,0.005872,0.973,1.0
16,Regulation of Insulin Secretion (GO:0050796),-1.604333,0.012701,0.981,1.0
17,Visual System Development (GO:0150063),-1.596589,0.009378,0.986,1.0
21,Regulation of Viral Genome Replication (GO:004...,-1.569126,0.022709,0.996,1.0
26,Regulation of Cholesterol Efflux (GO:0010874),-1.540434,0.011844,1.0,1.0
27,Negative Regulation of Bone Remodeling (GO:004...,-1.537973,0.010508,1.0,1.0
29,Positive Regulation of Response to Wounding (G...,-1.524951,0.024043,1.0,1.0
30,Regulation of Organelle Organization (GO:0033043),-1.523495,0.022186,1.0,1.0
31,Phospholipid Transport (GO:0015914),-1.518775,0.018152,1.0,1.0
33,Female Gamete Generation (GO:0007292),-1.512246,0.038596,1.0,1.0
34,Negative Regulation of Protein Phosphorylation...,-1.511946,0.038026,1.0,1.0
35,Positive Regulation of Protein Secretion (GO:0...,-1.509554,0.033607,1.0,1.0
36,Chromatin Remodeling (GO:0006338),-1.502408,0.035774,1.0,1.0
38,Protein-Containing Complex Assembly (GO:0065003),-1.498707,0.019873,1.0,1.0
40,Carbohydrate Metabolic Process (GO:0005975),-1.492778,0.016479,1.0,1.0

## GO molecular function

In [32]:
# Run GSEA Prerank
pre_res = gseapy.prerank(
    rnk=rank_data, 
    gene_sets="GO_Molecular_Function_2025",
    threads=16,
    min_size=5,
    max_size=1000,
    permutation_num=2000
)

2026-03-06 08:13:22,269 [WARNING] Duplicated values found in preranked stats: 0.15% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

In [33]:
# Enriched in dead end

pre_res.res2d.sort_values("NES", ascending=False).head(20)[["Term", "ES", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]] # Top Day 12

,Term,ES,NES,NOM p-val,FWER p-val,FDR q-val
0,Chemokine Receptor Binding (GO:0042379),0.779504,1.874218,0.002421,0.052,0.064018
2,Exopeptidase Activity (GO:0008238),0.804972,1.65049,0.015837,0.5675,0.55066
3,Cysteine-Type Endopeptidase Activity (GO:0004197),0.67699,1.640115,0.025094,0.6055,0.408157
5,Chemokine Activity (GO:0008009),0.702967,1.607676,0.028605,0.728,0.424388
7,Cysteine-Type Peptidase Activity (GO:0008234),0.612025,1.577205,0.030713,0.8235,0.453548
8,Carboxypeptidase Activity (GO:0004180),0.763424,1.572703,0.03815,0.8345,0.394232
9,Monoatomic Cation Channel Activity (GO:0005261),0.665037,1.566582,0.033816,0.8515,0.355894
12,GTP Binding (GO:0005525),0.531162,1.545743,0.025538,0.8965,0.367965
13,Phosphatase Binding (GO:0019902),0.673177,1.489162,0.060932,0.964,0.500808
14,Guanyl Ribonucleotide Binding (GO:0032561),0.485501,1.478988,0.02642,0.972,0.481325
15,Endopeptidase Activity (GO:0004175),0.430081,1.438227,0.02289,0.9875,0.567231
18,G Protein-Coupled Peptide Receptor Activity (G...,0.671597,1.407473,0.117284,0.995,0.625528
19,Alcohol Dehydrogenase (NADP+) Activity (GO:000...,0.743794,1.393723,0.106332,0.9965,0.622147
23,Metalloexopeptidase Activity (GO:0008235),0.597301,1.336266,0.137698,0.9995,0.777162
29,Metallocarboxypeptidase Activity (GO:0004181),0.682994,1.282405,0.211429,1.0,0.926265
33,Phosphatase Activator Activity (GO:0019211),0.675342,1.268817,0.208568,1.0,0.919778
37,Protein Serine/Threonine Kinase Activator Acti...,0.541603,1.251167,0.20119,1.0,0.933839
38,Protein Kinase Activator Activity (GO:0030295),0.456656,1.24061,0.165605,1.0,0.922468
39,Calcium Channel Activity (GO:0005262),0.605617,1.240283,0.216667,1.0,0.87523
40,Calcium Ion Transmembrane Transporter Activity...,0.586982,1.225544,0.231567,1.0,0.88092

In [34]:
# Enriched in iPSC path
pre_res.res2d.sort_values('NES', ascending=True).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]  # Top mESC

,Term,NES,NOM p-val,FWER p-val,FDR q-val
1,mRNA Binding (GO:0003729),-1.693617,0.001637,0.205,0.249014
4,Iron Ion Binding (GO:0005506),-1.625518,0.004156,0.4485,0.330839
6,2-Oxoglutarate-Dependent Dioxygenase Activity ...,-1.585645,0.008313,0.626,0.367861
10,Methylated Histone Binding (GO:0035064),-1.555595,0.006114,0.752,0.317115
11,Methylation-Dependent Protein Binding (GO:0140...,-1.555595,0.006114,0.752,0.317115
16,Protein Kinase C Binding (GO:0005080),-1.415454,0.062609,0.994,1.0
17,Guanyl-Nucleotide Exchange Factor Activity (GO...,-1.411386,0.072908,0.995,0.927603
20,Ubiquitin Binding (GO:0043130),-1.367428,0.09777,1.0,1.0
21,Single-Stranded DNA Binding (GO:0003697),-1.359997,0.10087,1.0,1.0
22,Protein Serine/Threonine Kinase Inhibitor Acti...,-1.33747,0.119167,1.0,1.0
24,GTPase Regulator Activity (GO:0030695),-1.322815,0.09629,1.0,1.0
25,Nuclear Receptor Binding (GO:0016922),-1.308819,0.129837,1.0,1.0
26,GTPase Activator Activity (GO:0005096),-1.307764,0.126521,1.0,1.0
27,Inorganic Cation Transmembrane Transporter Act...,-1.291962,0.130544,1.0,1.0
28,Epidermal Growth Factor Receptor Binding (GO:0...,-1.291852,0.131218,1.0,1.0
30,Ubiquitin-Like Ligase-Substrate Adaptor Activi...,-1.281367,0.15338,1.0,1.0
31,Ubiquitin-Protein Transferase Activity (GO:000...,-1.277251,0.132166,1.0,0.965871
32,RNA Polymerase II-specific DNA-binding Transcr...,-1.271272,0.114534,1.0,0.944989
34,Protease Binding (GO:0002020),-1.260644,0.14996,1.0,0.951027
35,Magnesium Ion Binding (GO:0000287),-1.254666,0.182526,1.0,0.934013

## MSigDB_Hallmark_2020

In [35]:
rank_data = driver_df[["Day 12 Control_corr"]].sort_values('Day 12 Control_corr', ascending=False).dropna()

# Run GSEA Prerank
pre_res = gseapy.prerank(
    rnk=rank_data, 
    gene_sets='MSigDB_Hallmark_2020', # Or other libraries
    threads=16,
    min_size=5,
    max_size=1000,
)

2026-03-06 08:13:34,939 [WARNING] Duplicated values found in preranked stats: 0.15% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

In [36]:
# Enriched in dead end

pre_res.res2d.sort_values('NES', ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]] # Top Day 12

                             Term       NES NOM p-val FWER p-val FDR q-val
0                     p53 Pathway  1.631392       0.0      0.189  0.392934
2         Estrogen Response Early  1.565239  0.011364      0.304   0.34522
3         Cholesterol Homeostasis  1.479324  0.050938      0.477  0.424119
5               Androgen Response  1.442451  0.050378       0.57  0.403225
9          Estrogen Response Late  1.382278  0.030812      0.697  0.469275
11            Allograft Rejection  1.355872    0.0625      0.741  0.456552
12      Unfolded Protein Response  1.322898  0.144608      0.805  0.466175
14               mTORC1 Signaling  1.275806  0.086842      0.878  0.530695
15           IL-2/STAT5 Signaling  1.268076  0.077135      0.888  0.493558
16     Wnt-beta Catenin Signaling  1.255005  0.205811      0.904  0.476947
17                 Myc Targets V1  1.218209      0.25       0.94   0.52034
18       PI3K/AKT/mTOR  Signaling  1.191553  0.202597      0.955  0.541375
19              KRAS Signaling Dn  1.175222  0.206897      0.968  0.542335
20  TNF-alpha Signaling via NF-kB  1.143673  0.161194      0.977  0.579511
21                    Pperoxisome  1.142017  0.275168      0.977  0.544743
22                      Apoptosis  1.122821  0.198225      0.986  0.555721
23                 UV Response Up  1.122216  0.236769      0.986  0.524902
24          Xenobiotic Metabolism  1.069907    0.3125      0.996  0.629734
26       IL-6/JAK/STAT3 Signaling  1.028474  0.385827        1.0   0.70797
27          Inflammatory Response  1.004163  0.446875        1.0  0.739277

In [37]:
# Enriched in iPSC path
pre_res.res2d.sort_values('NES', ascending=True).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]  # Top mESC

                                 Term       NES NOM p-val FWER p-val FDR q-val
1                     G2-M Checkpoint -1.590507  0.004673      0.218  0.121152
4                     Spermatogenesis -1.457728   0.04886      0.605  0.246197
6           Oxidative Phosphorylation -1.394653  0.082759      0.789  0.275877
7                          DNA Repair  -1.39212  0.076014      0.801   0.21226
8                     Mitotic Spindle -1.384432  0.062405       0.82  0.180998
10                        E2F Targets -1.358079  0.068293      0.876  0.182945
13          Interferon Alpha Response -1.298227  0.096367      0.957  0.237578
25                       Adipogenesis -1.040436  0.381241        1.0  0.751119
30               Bile Acid Metabolism -0.933019   0.54766        1.0     0.959
31          Interferon Gamma Response  -0.85101  0.777612        1.0       1.0
33                    Apical Junction -0.820538  0.773791        1.0       1.0
34                        Coagulation -0.789483  0.855346        1.0       1.0
39    Reactive Oxygen Species Pathway -0.742507  0.824793        1.0       1.0
40                     UV Response Dn  -0.73457  0.929927        1.0  0.950207
46              Fatty Acid Metabolism -0.655406   0.92084        1.0  0.955107
48  Epithelial Mesenchymal Transition   0.59867       1.0        1.0  0.979253
47                 Hedgehog Signaling   0.64716  0.927184        1.0  0.991293
45                Pancreas Beta Cells  0.661207  0.870647        1.0       1.0
44                         Glycolysis  0.683399  0.980716        1.0       1.0
43                     Apical Surface  0.687882  0.918367        1.0       1.0

## Cell types

In [38]:
# Run GSEA Prerank
pre_res = gseapy.prerank(
    rnk=rank_data, 
    gene_sets='PanglaoDB_Augmented_2021', # Or other libraries
    threads=16,
    min_size=5,
    max_size=1000,
)

# Enriched in dead end

pre_res.res2d.sort_values('NES', ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]] # Top Day 12

2026-03-06 08:13:47,444 [WARNING] Duplicated values found in preranked stats: 0.15% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

                        Term       NES NOM p-val FWER p-val FDR q-val
0      Salivary Mucous Cells  2.237623       0.0        0.0       0.0
1        Gastric Chief Cells  2.219473       0.0        0.0       0.0
2   Mammary Epithelial Cells   2.05964       0.0      0.002  0.000885
3             Cholangiocytes  2.052431       0.0      0.003  0.000995
4   Luminal Epithelial Cells  2.035843       0.0      0.004  0.001062
5              Keratinocytes  1.990003       0.0      0.007   0.00177
6             Foveolar Cells  1.956646  0.002513      0.016  0.003413
8                  Sebocytes  1.933107       0.0      0.025  0.005143
9            Microfold Cells  1.927234       0.0      0.025  0.004571
10          Urothelial Cells  1.888582       0.0      0.041  0.006238
11          Epithelial Cells  1.882017       0.0      0.042  0.005791
12    Trophoblast Stem Cells  1.868371       0.0      0.048  0.006193
13       Airway Goblet Cells  1.861835       0.0      0.058   0.00684
14               Trichocytes  1.846223  0.002577      0.067  0.007299
15              Goblet Cells   1.80759  0.007692      0.089  0.009467
16              Ductal Cells   1.78771  0.002667      0.111  0.011447
17              Merkel Cells  1.783314     0.005      0.117   0.01132
18              Hepatoblasts  1.762978   0.00542      0.152  0.013935
19           Principal Cells  1.761344  0.002778      0.154  0.013411
21         Trophoblast Cells  1.674106  0.002833      0.309  0.029131

In [39]:
# Enriched in iPSC path
pre_res.res2d.sort_values('NES', ascending=True).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]  # Top mESC

                      Term       NES NOM p-val FWER p-val FDR q-val
7   Pluripotent Stem Cells  -1.93891       0.0      0.007  0.005691
20          Epiblast Cells -1.709858  0.001538      0.183  0.099181
23     Gamma Delta T Cells -1.579801  0.010292      0.601  0.321931
24    Embryonic Stem Cells -1.572849  0.001508      0.625  0.258317
26           Oxyphil Cells -1.499128  0.039669      0.847  0.430867
29      Adrenergic Neurons -1.423953  0.060403      0.958  0.679496
30                Myocytes  -1.40701  0.060559      0.971   0.66767
31         Ependymal Cells  -1.40181  0.095076      0.974  0.609209
34              Osteocytes -1.367737  0.044515      0.986  0.699323
36               Microglia -1.349372   0.07489      0.994  0.711012
39   Proximal Tubule Cells -1.310864  0.134185      0.998  0.840302
43        Gamma (PP) Cells -1.219043  0.172956        1.0       1.0
44             Delta Cells  -1.21797  0.186161        1.0       1.0
45          Decidual Cells -1.216914   0.19823        1.0       1.0
46           Reticulocytes -1.207218  0.259516        1.0       1.0
53      T Regulatory Cells -1.142003  0.266559        1.0       1.0
54    Serotonergic Neurons -1.124826  0.326889        1.0       1.0
55             Neutrophils  -1.12175  0.291217        1.0       1.0
57             Eosinophils   -1.1088  0.304416        1.0       1.0
60              Germ Cells  -1.09814  0.344605        1.0       1.0

Epithelial markers are strongly enriched among the control drivers

## ChipSeq targets, ChEA

In [40]:
# Run GSEA Prerank
pre_res = gseapy.prerank(
    rnk=rank_data, 
    gene_sets='ChEA_2022', # Or other libraries
    threads=16,
    min_size=5,
    max_size=1000
)

2026-03-06 08:14:06,477 [WARNING] Duplicated values found in preranked stats: 0.15% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

In [41]:
# Enriched in dead end

pre_res.res2d.sort_values('NES', ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]] # Top Day 12

,Term,NES,NOM p-val,FWER p-val,FDR q-val
26,JARID2 20075857 ChIP-Seq MESCs Mouse,1.699716,0.0,0.282,0.44995
28,RARG 19884340 ChIP-ChIP MEFs Mouse,1.679999,0.0,0.33,0.271608
31,SUZ12 18974828 ChIP-Seq MESCs Mouse,1.661903,0.0,0.38,0.211321
39,MTF2 20144788 ChIP-Seq MESCs Mouse,1.62774,0.0,0.482,0.219303
41,SUZ12 27294783 Chip-Seq ESCs Mouse,1.624151,0.0,0.493,0.183005
52,TP63 17297297 ChIP-ChIP HaCaT Human,1.538354,0.033505,0.734,0.299546
55,SUZ12 20075857 ChIP-Seq MESCs Mouse,1.523259,0.0,0.78,0.290964
56,TP63 30713093 ChIP-Seq Epithelial Human Tongue...,1.508663,0.0,0.818,0.285
57,ESR1 26153859 ChIP-Seq MCF-7 Human BreastCancer,1.506626,0.0,0.821,0.256414
60,PITX1 30713093 ChIP-Seq Epithelial Human Tongu...,1.499521,0.06506,0.834,0.244258
67,JARID2 20064375 ChIP-Seq MESCs Mouse,1.472581,0.0,0.892,0.274416
70,BMI1 19503595 ChIP-Seq MEFsC Mouse,1.453231,0.022293,0.927,0.293875
72,TFAP2C 20629094 ChIP-Seq MCF-7 Human,1.449672,0.003636,0.934,0.27951
76,ESR1 20056654 ChIP-Seq MCF-7 Human BreastCancer,1.420117,0.003378,0.961,0.325264
78,EED 16625203 ChIP-ChIP MESCs Mouse,1.406193,0.003731,0.973,0.340802
79,PHC1 16625203 ChIP-ChIP MESCs Mouse,1.393956,0.012245,0.98,0.351878
81,TP53 32428506 ChIP-Seq Human Liver Heptoma,1.382189,0.035503,0.985,0.364542
84,BMI1 23680149 ChIP-Seq NPCS Mouse,1.374876,0.004149,0.989,0.365786
86,P63 26484246 Chip-Seq KERATINOCYTES Human,1.370522,0.008584,0.989,0.359137
90,SUZ12 18692474 ChIP-Seq MESCs Mouse,1.359485,0.0,0.991,0.371681

In [42]:
# Enriched in iPSC path
pre_res.res2d.sort_values('NES', ascending=True).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]  # Top mESC

,Term,NES,NOM p-val,FWER p-val,FDR q-val
0,FOXM1 23109430 ChIP-Seq U2OS Human,-2.102492,0.0,0.0,0.0
1,NACC1 18358816 ChIP-ChIP MESCs Mouse,-2.041287,0.0,0.0,0.0
2,SMAD1 18555785 ChIP-Seq MESCs Mouse,-2.037721,0.0,0.0,0.0
3,MYBL2 22936984 ChIP-ChIP MESCs Mouse,-2.036544,0.0,0.0,0.0
4,TCF3 18692474 ChIP-Seq MESCs Mouse,-2.006263,0.0,0.0,0.0
5,NANOG 18700969 ChIP-ChIP MESCs Mouse,-1.983808,0.0,0.002,0.000301
6,SOX2 18692474 ChIP-Seq MESCs Mouse,-1.938704,0.0,0.003,0.000387
7,POU5F1 18700969 ChIP-ChIP MESCs Mouse,-1.934232,0.0,0.005,0.000564
8,POU5F1 18358816 ChIP-ChIP MESCs Mouse,-1.925726,0.0,0.006,0.000601
9,NANOG 18555785 ChIP-Seq MESCs Mouse,-1.903279,0.0,0.008,0.000722
10,SOX2 18358816 ChIP-ChIP MESCs Mouse,-1.893495,0.0,0.009,0.000738
11,SALL4 18804426 ChIP-ChIP MESCs Mouse,-1.884357,0.0,0.012,0.000902
12,SOX2 19030024 ChIP-ChIP MESCs Mouse,-1.879663,0.0,0.014,0.000971
13,SOX2 18555785 ChIP-Seq MESCs Mouse,-1.86545,0.0,0.016,0.001031
14,TCF3 18692474 ChIP-Seq MEFs Mouse,-1.85033,0.0,0.02,0.001203
15,SOX2 18692474 ChIP-Seq MEFs Mouse,-1.826345,0.0,0.032,0.00186
16,KDM5B 21448134 ChIP-Seq MESCs Mouse,-1.826005,0.0,0.032,0.001751
17,SMAD3 22036565 ChIP-Seq ESCs Mouse,-1.823262,0.0,0.033,0.001704
18,POU5F1 18555785 ChIP-Seq MESCs Mouse,-1.820795,0.001517,0.033,0.001614
19,MYC 19079543 ChIP-ChIP MESCs Mouse,-1.814912,0.0,0.035,0.001624

## Enriched targets from ChipSeq, Ensembl

In [43]:
# Run GSEA Prerank
pre_res = gseapy.prerank(
    rnk=rank_data, 
    gene_sets='ENCODE_TF_ChIP-seq_2015', # Or other libraries
    threads=16,
    min_size=5,
    max_size=1000
)

2026-03-06 08:14:40,109 [WARNING] Duplicated values found in preranked stats: 0.15% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

In [44]:
# Enriched in dead end

pre_res.res2d.sort_values('NES', ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]] # Top Day 12

                     Term       NES NOM p-val FWER p-val FDR q-val
1         FOSL1 C2C12 mm9  1.934997       0.0      0.025  0.028715
13   SMARCC1 HeLa-S3 hg19  1.698293       0.0      0.284  0.203212
22        ZEB1 HepG2 hg19  1.601671    0.0125      0.526  0.332061
23         ATF3 K562 hg19   1.59631  0.003086       0.54  0.262298
27       TAL1 G1E-ER4 mm9  1.566733  0.003077      0.621  0.267047
28       EP300 ECC-1 hg19  1.566008  0.005865      0.622  0.223828
36   SMARCC2 HeLa-S3 hg19  1.523065  0.019886      0.755  0.285886
48        MAX myocyte mm9  1.466098  0.015625       0.88  0.411809
53      JUND GM12878 hg19  1.446921  0.026738      0.908  0.429985
55       RAD21 ECC-1 hg19  1.444632  0.006472       0.91  0.395049
71       JUND HCT116 hg19  1.385786  0.063218      0.973  0.586042
76        REST ECC-1 hg19  1.378971  0.006897      0.975  0.568037
82       EP300 MCF-7 hg19  1.367893  0.087533      0.978  0.571917
86      JUND HeLa-S3 hg19  1.363597  0.011765      0.979  0.551418
100       JUND MCF-7 hg19  1.335985  0.076923       0.99  0.647923
102     ZEB1 GM12878 hg19  1.332873  0.063889      0.993  0.624477
107     REST U-87 MG hg19  1.328096  0.067204      0.994  0.611975
110       MYOD1 C2C12 mm9  1.321521  0.007194      0.995  0.609637
112     JUND SK-N-SH hg19  1.312121  0.003731      0.996  0.622599
123         CTCF NB4 hg19  1.293926  0.024561      0.999  0.686394

In [45]:
# Enriched in iPSC path
pre_res.res2d.sort_values('NES', ascending=True).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]  # Top mESC

                      Term       NES NOM p-val FWER p-val FDR q-val
0   E2F4 MEL cell line mm9  -2.08111       0.0        0.0       0.0
2         FOXM1 ECC-1 hg19 -1.842079       0.0      0.031  0.015764
3        IRF3 GM12878 hg19 -1.827508       0.0       0.04  0.013376
4         E2F4 CH12.LX mm9 -1.824025       0.0      0.043  0.010987
5        E2F4 HeLa-S3 hg19 -1.772204       0.0      0.095   0.02121
6         FOXM1 MCF-7 hg19 -1.742919  0.004717      0.147  0.028185
7            SP2 K562 hg19 -1.725061       0.0      0.187  0.031529
8        NFYA GM12878 hg19  -1.72164       0.0      0.193  0.028782
9           NFYA K562 hg19 -1.719114       0.0      0.198  0.026221
10      NANOG H1-hESC hg19 -1.716418  0.003378      0.205   0.02465
11      FOXM1 GM12878 hg19 -1.713815       0.0      0.211  0.023799
12           FOS K562 hg19 -1.700286       0.0      0.253  0.026831
14       IRF3 HeLa-S3 hg19 -1.682087  0.001435       0.31  0.031823
15         TCF12 A549 hg19  -1.66865  0.001548      0.358   0.03576
16          SP2 HepG2 hg19 -1.662867  0.001499      0.377  0.036178
17        SETDB1 U2OS hg19 -1.654043       0.0      0.411  0.038157
18        CEBPZ HepG2 hg19  -1.64442  0.003175      0.444   0.04097
19     STAT5A GM12878 hg19 -1.642102       0.0      0.449  0.039862
20       E2F4 GM12878 hg19 -1.638025  0.001441       0.47  0.040479
21         KAT2B K562 hg19 -1.628654  0.002911      0.501  0.043089

## TF Perturbation followed by expression

In [46]:
# Run GSEA Prerank
pre_res = gseapy.prerank(
    rnk=rank_data, 
    gene_sets="TF_Perturbations_Followed_by_Expression",
    threads=16,
    min_size=5,
    max_size=1000
)

2026-03-06 08:14:52,738 [WARNING] Duplicated values found in preranked stats: 0.15% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

In [47]:
# Enriched in dead end

pre_res.res2d.sort_values('NES', ascending=False).head(30) # Top Day 12

,Name,Term,ES,NES,NOM p-val,FDR q-val,FWER p-val,Tag %,Gene %,Lead_genes
20,prerank,HSF1 KO MOUSE GSE41005 CREEDSID GENE 2143 DOWN,0.691633,1.923269,0.00266,0.123783,0.107,9/20,5.66%,Lad1;Ccnd2;Pla2g12a;Fabp5;Tuba4a;Ifrd1;Myc;Atf...
22,prerank,IRF6 KO MOUSE GSE5800 CREEDSID GENE 153 UP,0.53671,1.914283,0.0,0.068328,0.118,29/70,15.42%,Lgals7;S100a16;Prr13;Lad1;Dsp;Pkp1;Gsto1;Perp;...
23,prerank,PPARA KO MOUSE GSE6864 CREEDSID GENE 981 UP,0.532728,1.900752,0.0,0.060076,0.149,31/67,17.28%,Ctsz;Prr13;Lad1;Gsto1;Ifi30;Cdkn1a;Krt8;Dgat2;...
28,prerank,PPARA KO MOUSE GSE6864 CREEDSID GENE 1371 DOWN,0.520718,1.860592,0.0,0.072785,0.226,31/68,17.28%,Ctsz;Prr13;Lad1;Gsto1;Ifi30;Cdkn1a;Krt8;Dgat2;...
40,prerank,PPARA DEFICIENCY MOUSE GSE6864 CREEDSID GENE 6...,0.511269,1.812715,0.0,0.108533,0.366,30/67,17.28%,Ctsz;Prr13;Lad1;Dsp;Gsto1;Krt8;Sat1;Tuba4a;Spi...
41,prerank,MYC KD HUMAN GSE22139 CREEDSID GENE 712 DOWN,0.633966,1.810695,0.002597,0.0916,0.369,13/22,13.87%,Ccnd2;Fabp5;Ifrd1;Myc;Tmem147;Zfas1;Snhg1;Ppa1...
44,prerank,OVOL2 OE MOUSE GSE55074 CREEDSID GENE 2603 DOWN,0.522185,1.793472,0.0,0.09549,0.433,26/56,14.22%,Lgals7;S100a16;Dsp;Ccnd2;Pkp1;Gsto1;Perp;Fabp5...
45,prerank,PPARG OE MOUSE GSE2192 CREEDSID GENE 863 UP,0.527031,1.793181,0.0,0.083801,0.435,21/48,13.87%,Nupr1;Pla2g12a;Fabp5;Cdkn1a;Mgst3;Tob1;Tmem147...
49,prerank,MYC OE MOUSE GSE55272 CREEDSID GENE 1822 DOWN,0.53103,1.781451,0.0,0.083843,0.465,13/50,6.01%,Lgals7;Dsp;Mal2;Perp;Ly6g6c;Ovol1;Anxa8;Krt17;...
51,prerank,YY1 KD MOUSE GSE31784 CREEDSID GENE 1333 UP,0.549218,1.778067,0.0,0.078132,0.476,16/40,14.17%,Lad1;Gsto1;Ly6g6c;Dgat2;Tubb3;Gpx2;Gatm;Pcolce...
53,prerank,ESR2 KO MOUSE GSE1050 CREEDSID GENE 901 UP,0.635563,1.760532,0.007407,0.084983,0.538,6/21,5.31%,Homer2;Gsto1;Pla2g12a;Tuba4a;Mgst3;Ablim1
60,prerank,RUNX1 KO MOUSE GSE47375 CREEDSID GENE 2899 UP,0.464703,1.730587,0.0,0.107279,0.659,29/91,14.32%,Lgals7;S100a16;Lad1;Kcnn4;Pkp1;Fabp5;Cdkn1a;Kr...
61,prerank,KLF1 KO MOUSE GSE36427 CREEDSID GENE 1562 DOWN,0.595785,1.730438,0.005195,0.099331,0.659,10/26,7.91%,Prr13;Homer2;Kcnn4;B2m;Plek2;Ifrd1;Ptp4a3;Mgst...
64,prerank,NFE2L2 KO MOUSE GSE18344 CREEDSID GENE 965 DOWN,0.492992,1.723382,0.0,0.099239,0.678,13/65,6.26%,Tmem238;Uchl1;Lad1;Gsto1;Tppp3;Aldh3a1;Gpx2;Mi...
70,prerank,KLF3 KO MOUSE GSE35592 CREEDSID GENE 2672 UP,0.487612,1.706178,0.0,0.111372,0.742,25/57,15.97%,Crip2;Prr13;Dkkl1;Tppp3;Cdkn1a;Nrip3;Plek2;Lmn...
76,prerank,MBD3 KD MOUSE GSE31008 CREEDSID GENE 1325 UP,0.461907,1.685271,0.003155,0.130158,0.807,25/78,12.47%,Lgals7;Lad1;Crb3;Mal2;Perp;Gpx2;Tnfrsf13c;S100...
79,prerank,NR1I2 KO MOUSE GSE23780 CREEDSID GENE 2165 DOWN,0.635625,1.673435,0.019704,0.137006,0.834,5/17,12.92%,Tppp3;Cdkn1a;Alox12b;Map4k1;Pdlim4
81,prerank,HNF4A MUT MOUSE GSE3116 CREEDSID GENE 850 DOWN,0.480836,1.668254,0.00554,0.136492,0.851,26/55,18.88%,Rtn4r;Ifi30;Krt8;Spint2;Gatm;Smpdl3a;Mgst3;Tob...
85,prerank,HSF1 KD HUMAN GSE3697 CREEDSID GENE 782 UP,0.480109,1.650436,0.009036,0.154586,0.887,21/57,16.68%,Dsp;Nupr1;Sat1;Plek2;Ifrd1;Krt17;Smagp;Krt14;A...
87,prerank,KDM2B KD MOUSE GSE41298 CREEDSID GENE 1376 UP,0.458321,1.648829,0.0,0.149283,0.891,25/67,17.68%,Crip2;Ccnd2;Gsto1;Perp;Krt8;Gatm;Cbr3;Myc;Anxa...
88,prerank,OVOL1 KO MOUSE GSE55071 CREEDSID GENE 2560 UP,0.46401,1.63693,0.0,0.159999,0.913,21/60,17.43%,Lgals7;Mal2;Fabp5;Ly6g6c;Krt17;Myc;Krt14;Ggh;C...
94,prerank,PAX5 OE HUMAN GSE44244 CREEDSID GENE 575 DOWN,0.634697,1.604698,0.013089,0.201789,0.964,8/16,12.72%,Psmb10;Emp3;Emb;Gng2;Tubgcp3;Tenm3;Abracl;Atf5
96,prerank,FOXP3 OE SW780 HUMAN GSE81157 RNASEQ DOWN,0.475404,1.602494,0.005525,0.197408,0.967,13/50,7.41%,Lad1;Dsp;Perp;Cd44;Cdkn1a;Tuba4a;Krt17;Lmna;Kr...
108,prerank,NR3C1 KO MOUSE GSE23724 CREEDSID GENE 3014 DOWN,0.455541,1.572874,0.002882,0.247195,0.988,18/56,12.87%,Mal2;Gsto1;Cgref1;Krt8;Tuba4a;Ifrd1;Krt13;Myl7...
112,prerank,PPARA KO MOUSE GSE6864 CREEDSID GENE 1373 UP,0.43682,1.565887,0.002907,0.251607,0.989,22/71,13.72%,Ctsz;Prr13;Ifi30;Cgref1;Krt8;B2m;Tuba4a;Gpx2;S...
118,prerank,OVOL1 KO MOUSE GSE55072 CREEDSID GENE 2617 UP,0.437777,1.558073,0.009434,0.258917,0.994,30/71,17.43%,Mal2;Pkp1;Gsto1;Nupr1;Fabp5;Ly6g6c;B2m;Emp2;Sp...
120,prerank,HEY2 KO MOUSE GSE6526 CREEDSID GENE 1511 UP,0.423681,1.5568,0.006024,0.242934,0.994,30/78,17.38%,S100a16;Pkp1;Cd44;Cdkn1a;Sat1;Anxa8;Tuba4a;Ifr...
119,prerank,HEY2 KO MOUSE GSE6526 CREEDSID GENE 1512 DOWN,0.423681,1.5568,0.006024,0.242934,0.994,30/78,17.38%,S100a16;Pkp1;Cd44;Cdkn1a;Sat1;Anxa8;Tuba4a;Ifr...
122,prerank,MYC KD HUMAN GSE54872 CREEDSID GENE 1311 DOWN,0.557268,1.547737,0.043928,0.254362,0.995,11/20,20.13%,Ctsz;Uchl1;Cgref1;Fkbp11;Npr3;Barx2;Ccdc141;Fl...
124,prerank,PPARA KO MOUSE GSE6864 CREEDSID GENE 1372 DOWN,0.426902,1.533923,0.002907,0.275888,0.998,22/72,13.72%,Ctsz;Prr13;Ifi30;Cgref1;Krt8;B2m;Tuba4a;Gpx2;S...

Many proteins related to Ovol1 appear, including Myc, Ovol2 and Ovol1 itself. Directions are inconsistent.

In [48]:
# Enriched in iPSC path
pre_res.res2d.sort_values('NES', ascending=True).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]  # Top mESC

,Term,NES,NOM p-val,FWER p-val,FDR q-val
0,NEUROG3 OE MOUSE GSE3653 CREEDSID GENE 1660 DOWN,-2.484484,0.0,0.0,0.0
1,NEUROG3 OE MOUSE GSE3653 CREEDSID GENE 2289 DOWN,-2.483431,0.0,0.0,0.0
2,MTF2 KD MOUSE GSE16364 CREEDSID GENE 1355 UP,-2.412573,0.0,0.0,0.0
3,ZFP42 KD MOUSE GSE9978 CREEDSID GENE 1334 UP,-2.369883,0.0,0.0,0.0
4,ZFP42 KD MOUSE GSE9978 CREEDSID GENE 1335 UP,-2.243264,0.0,0.0,0.0
5,ZFX KO MOUSE GSE7069 CREEDSID GENE 177 DOWN,-2.213218,0.0,0.0,0.0
6,MSGN1 OE MOUSE GSE29848 CREEDSID GENE 1629 DOWN,-2.197723,0.0,0.0,0.0
7,SRF MUT MOUSE GSE1948 CREEDSID GENE 1400 DOWN,-2.134755,0.0,0.0,0.0
8,SOX2 KD MOUSE GSE39771 CREEDSID GENE 1757 DOWN,-2.1341,0.0,0.0,0.0
9,FOXD3 OE MOUSE GSE58960 CREEDSID GENE 1415 DOWN,-2.126921,0.0,0.0,0.0
10,NEUROG3 OE MOUSE GSE3653 CREEDSID GENE 2585 DOWN,-2.118152,0.0,0.0,0.0
11,KLF5 KO MOUSE GSE9244 CREEDSID GENE 580 DOWN,-2.018141,0.0,0.008,0.00067
12,SRF MUT MOUSE GSE1948 CREEDSID GENE 1395 UP,-1.995482,0.0,0.012,0.000928
13,FOXD3 KO MOUSE GSE58960 CREEDSID GENE 1417 DOWN,-1.969985,0.0,0.018,0.001292
14,NEUROG3 OE MOUSE GSE3653 CREEDSID GENE 1658 DOWN,-1.965413,0.0,0.018,0.001273
15,PCGF6 KD MOUSE GSE56126 CREEDSID GENE 1340 DOWN,-1.942064,0.0,0.027,0.001759
16,TET1 KD MOUSE GSE26830 CREEDSID GENE 1353 DOWN,-1.941988,0.0,0.027,0.001655
17,CHD1 KO 22RV1 HUMAN GSE84610 RNASEQ DOWN,-1.937042,0.0,0.032,0.001899
18,GTF2I KO MOUSE GSE48790 CREEDSID GENE 1452 UP,-1.929232,0.0,0.042,0.002328
19,MSGN1 OE MOUSE GSE29848 CREEDSID GENE 1630 DOWN,-1.928353,0.0,0.042,0.002211

## Test if specific gene sets are enriched

In [49]:
# Get libraries

panglao_lib = gseapy.get_library(name='PanglaoDB_Augmented_2021', organism='Mouse')
go_lib = gseapy.get_library(name='GO_Biological_Process_2025', organism='Mouse')
go_molecular_function = gseapy.get_library(name='GO_Molecular_Function_2025', organism='Mouse')
hallmark_lib = gseapy.get_library(name='MSigDB_Hallmark_2020', organism='Mouse')

In [51]:
target_sets = {
    "Apoptosis Activation": go_lib["Positive Regulation of Apoptotic Process (GO:0043065)"],
    "Apoptosis Inhibition": go_lib["Negative Regulation of Apoptotic Process (GO:0043066)"],
    "Cell Cycle Inhibition": go_lib["Negative Regulation of Cell Cycle (GO:0045786)"],
    "Cell Cycle Activation": go_lib["Positive Regulation of Cell Cycle (GO:0045787)"],
    "Apoptosis Signaling Inhibition": go_lib["Negative Regulation of Apoptotic Signaling Pathway (GO:2001234)"],
    "Apoptosis Signaling Activation": go_lib["Positive Regulation of Apoptotic Signaling Pathway (GO:2001235)"],
    "Stem Cell Proliferation": go_lib["Positive Regulation of Stem Cell Proliferation (GO:2000648)"],
    "Stem Cell Inhibited Proliferation": go_lib["Negative Regulation of Stem Cell Population Maintenance (GO:1902455)"],
    "Stem Cell Inhibited Differentiation": go_lib["Negative Regulation of Stem Cell Differentiation (GO:2000737)"],
    "Stem Cell Differentiation": go_lib["Positive Regulation of Stem Cell Differentiation (GO:2000738)"],
    "DNA Damage Response": go_lib["DNA Damage Response (GO:0006974)"],
    "DNA_Repair": hallmark_lib['DNA Repair'],
    "P53_Pathway": hallmark_lib['p53 Pathway'],
    "Keratinocytes": panglao_lib["Keratinocytes"],
    "Epithelial cells": panglao_lib["Epithelial Cells"]
}

rank_data = driver_df[["Day 12 Control_corr"]].sort_values('Day 12 Control_corr', ascending=False).dropna()

# Run GSEA Prerank
pre_res = gseapy.prerank(
    rnk=rank_data, 
    gene_sets=target_sets,
    threads=16,
    min_size=5,
    max_size=2000,
    permutation_num=1000,
    seed=0
)

pre_res.res2d.sort_values("NES", ascending=False).head(20)

2026-03-06 08:15:33,259 [WARNING] Duplicated values found in preranked stats: 0.15% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

,Name,Term,ES,NES,NOM p-val,FDR q-val,FWER p-val,Tag %,Gene %,Lead_genes
0,prerank,Keratinocytes,0.624423,2.04658,0.0,0.0,0.0,21/41,15.77%,Lgals7;Lad1;Pkp1;Perp;Ovol1;Anxa8;S100a14;Krt1...
1,prerank,Epithelial cells,0.541963,1.944477,0.0,0.000591,0.001,29/67,16.78%,Lad1;Crb3;Mal2;Ovol1;Krt8;Dgat2;Gpx2;Misp;S100...
2,prerank,P53_Pathway,0.465663,1.624594,0.005714,0.033498,0.079,24/60,18.58%,Ccnd2;Ifi30;Nupr1;Perp;Cdkn1a;Sat1;Gpx2;Krt17;...
3,prerank,Apoptosis Signaling Activation,0.655181,1.540787,0.048951,0.045813,0.14,5/11,16.68%,Nupr1;Bbc3;App;Tnfrsf12a;Ddit3
7,prerank,Apoptosis Inhibition,0.210176,0.803516,0.957187,0.966857,0.98,18/107,15.02%,Ccnd2;Nupr1;Prkaa2;Cd44;Myc;Anxa5;Tmbim1;Ddah2...
10,prerank,Cell Cycle Inhibition,0.278801,0.698768,0.899314,0.92197,0.989,1/14,1.45%,Nupr1
12,prerank,Stem Cell Proliferation,-0.276325,-0.560267,0.96587,0.983849,1.0,1/8,7.81%,Nanog
11,prerank,Apoptosis Signaling Inhibition,-0.250039,-0.584337,0.988411,1.0,1.0,4/14,32.65%,Tcf7l2;Bmp4;Thbs1;Clu
9,prerank,Cell Cycle Activation,-0.292296,-0.706391,0.9018,1.0,0.999,2/16,4.81%,Tcf7l1;Cited2
8,prerank,Apoptosis Activation,-0.246637,-0.797562,0.867717,1.0,0.999,28/63,36.55%,Dlc1;Rest;Gadd45b;Top2a;Bnip3;Sfrp1;Tsc22d1;Ec...
6,prerank,DNA Damage Response,-0.335776,-0.903467,0.600355,1.0,0.993,11/24,21.68%,Ash2l;Msh6;Nedd4;Top2a;Acer2;Fam111a;Brca1;Fbx...
5,prerank,Stem Cell Differentiation,-0.522734,-0.970186,0.530756,1.0,0.982,2/6,22.53%,Tcf15;Nr5a2
4,prerank,DNA_Repair,-0.722386,-1.409292,0.060976,0.335647,0.313,5/7,24.39%,Gpx4;Arl6ip1;Bcam;Pold4;Cda

# Differential expression analysis with Scanpy

Scanpy uses a Wilcoxon rank sum test.

In [9]:
# Assign each cell to the most likely macrostate

macrostates = adata.uns["coarse_fwd"].obs["coarse_init_dist"].index.to_list()
macrostate_assignment = [macrostates[numpy.argmax(macrostate_probabilities)] for macrostate_probabilities in adata.obsm["macrostates_fwd_memberships"]]
adata.obs["macrostate"] = macrostate_assignment
adata.uns["macrostate_colors"] = [
    adata.uns["macrostates_fwd_colors"][5],
    adata.uns["macrostates_fwd_colors"][2],
    adata.uns["macrostates_fwd_colors"][3],
    adata.uns["macrostates_fwd_colors"][4],
    adata.uns["macrostates_fwd_colors"][1],
    adata.uns["macrostates_fwd_colors"][0],
    adata.uns["macrostates_fwd_colors"][6]
]

## Comparison between all macrostates

In [25]:
# perform differential expression using the standard wilcoxon rank-sum test
scanpy.tl.rank_genes_groups(
    adata,
    groupby="macrostate",
    method="wilcoxon",
    use_raw=False,
    key_added="macrostate_rank_genes"
)

# extract the results into a dataframe for a specific target macrostate
dead_end_rank_df = scanpy.get.rank_genes_groups_df(
    adata,
    key="macrostate_rank_genes",
    group="Day 12 Control"
)
dead_end_rank_df.index = dead_end_rank_df["names"]
dead_end_rank_df = dead_end_rank_df.drop(columns="names")

control_rank_df = scanpy.get.rank_genes_groups_df(
    adata,
    key="macrostate_rank_genes",
    group="Day 4 Control"
)
control_rank_df.index = control_rank_df["names"]
control_rank_df = control_rank_df.drop(columns="names")

In [26]:
dead_end_rank_df.head(20)

                  scores  logfoldchanges          pvals      pvals_adj
names
Zfas1          26.189415        2.912675  3.507877e-151  7.015755e-148
2410006H16Rik  25.884188        2.383039  1.003519e-147  1.003519e-144
Snhg1          24.932861        2.789920  3.276535e-137  2.184357e-134
1110038B12Rik  24.600237        2.454037  1.255827e-133  6.279133e-131
Snhg12         24.165182        3.138035  5.170944e-129  2.068378e-126
Gas5           23.397280        1.672911  4.554957e-121  1.518319e-118
Ifrd1          22.545397        2.568011  1.490053e-112  4.257295e-110
Cdkn1a         21.841169        2.205297  9.431106e-106  2.357776e-103
Ppp1r15a       21.520761        2.846743  9.951511e-103  2.211447e-100
Aqp3           21.424622        4.537375  7.877358e-102   1.575472e-99
Crb3           21.262957        2.924304  2.501539e-100   4.548253e-98
Bbc3           20.421621        2.746830   1.074389e-92   1.652905e-90
Perp           19.625084        2.268659   9.442086e-86   1.258945e-83
Dkkl1          19.578817        3.210852   2.343994e-85   2.929992e-83
Lgals7         19.447018        3.746449   3.088836e-84   3.251406e-82
Cstb           19.170475        1.550161   6.531087e-82   6.220083e-80
Atf3           18.789471        4.924244   9.209480e-79   8.372254e-77
Dsp            18.772705        2.404867   1.262886e-78   1.057323e-76
Tmem43         18.663662        2.369165   9.779289e-78   7.823431e-76
Gch1           18.633204        3.026248   1.728618e-77   1.329706e-75

In [55]:
# Most upregulated transcription factors in dead end

dead_end_rank_df.loc[numpy.intersect1d(tf_array, adata.var_names)].sort_values("scores", ascending=False).head(30)

            scores  logfoldchanges         pvals     pvals_adj
names
Atf3     18.789471        4.924244  9.209480e-79  8.372254e-77
Maff     14.781541        3.392600  1.927055e-49  5.416949e-48
Ddit3    13.226619        2.166627  6.159631e-40  1.140672e-38
Myc      12.562806        1.828156  3.381229e-36  5.162181e-35
Ovol1    12.100735        2.972715  1.046704e-33  1.443730e-32
Klf10    12.000822        1.918085  3.517865e-33  4.753872e-32
Arid3a   10.603693        1.693256  2.864403e-26  2.822072e-25
Zbtb7c   10.598906        1.849738  3.014877e-26  2.955762e-25
Junb     10.341942        1.311702  4.552173e-25  4.234580e-24
Zbtb10   10.224051        2.126627  1.547362e-24  1.369347e-23
Crebrf    8.973886        1.998747  2.862334e-19  1.889330e-18
Klf4      8.294026        1.242020  1.094780e-16  6.185198e-16
Phox2a    7.614943        2.153333  2.638079e-14  1.253244e-13
Zfp296    7.220187        1.331148  5.191626e-13  2.297180e-12
Bhlhe40   6.915652        1.692661  4.657153e-12  1.944531e-11
Barx2     6.472987        2.666481  9.608440e-11  3.660358e-10
Hes1      5.985631        1.224554  2.155524e-09  7.549997e-09
Zfp750    5.818898        3.017764  5.923691e-09  1.994509e-08
Rora      5.491565        2.064828  3.983887e-08  1.235314e-07
Dmrtc2    5.071731        1.206740  3.942134e-07  1.124717e-06
Fosl2     4.655017        1.037758  3.239530e-06  8.469360e-06
Tlx2      4.417089        0.874272  1.000390e-05  2.513543e-05
Gata2     4.296226        2.146550  1.737303e-05  4.252883e-05
Zfhx3     4.086668        0.396962  4.376116e-05  1.028464e-04
Klf6      4.005980        0.701633  6.176074e-05  1.427994e-04
Lef1      3.979739        1.373406  6.899086e-05  1.587822e-04
Hoxa9     3.939977        0.952770  8.148932e-05  1.852030e-04
Pax8      3.912894        5.944145  9.119650e-05  2.065606e-04
Hopx      3.820691        1.268440  1.330782e-04  2.960584e-04
Tet2      3.521431        0.745068  4.292236e-04  9.161657e-04

Really exciting! The top three TFs are involved in stress response, suggesting that this macrostate corresponds to high activity of

In [56]:
hic2_target_scores.loc["Klf10"]

chip_score    4.637256
Name: Klf10, dtype: float64

In [57]:
# Most upregulated transcription factors in dead end that are shared targets

dead_end_rank_df.loc[numpy.intersect1d(target_tfs, adata.var_names)].sort_values("scores", ascending=False).head(30)

           scores  logfoldchanges         pvals     pvals_adj
names
Ddit3   13.226619        2.166627  6.159631e-40  1.140672e-38
Myc     12.562806        1.828156  3.381229e-36  5.162181e-35
Ovol1   12.100735        2.972715  1.046704e-33  1.443730e-32
Klf10   12.000822        1.918085  3.517865e-33  4.753872e-32
Arid3a  10.603693        1.693256  2.864403e-26  2.822072e-25
Zbtb7c  10.598906        1.849738  3.014877e-26  2.955762e-25
Junb    10.341942        1.311702  4.552173e-25  4.234580e-24
Klf4     8.294026        1.242020  1.094780e-16  6.185198e-16
Phox2a   7.614943        2.153333  2.638079e-14  1.253244e-13
Zfp296   7.220187        1.331148  5.191626e-13  2.297180e-12
Barx2    6.472987        2.666481  9.608440e-11  3.660358e-10
Fosl2    4.655017        1.037758  3.239530e-06  8.469360e-06
Tlx2     4.417089        0.874272  1.000390e-05  2.513543e-05
Gata2    4.296226        2.146550  1.737303e-05  4.252883e-05
Zfhx3    4.086668        0.396962  4.376116e-05  1.028464e-04
Pou5f1   3.226679        0.674562  1.252360e-03  2.542863e-03
Fosl1    3.133848        0.988354  1.725300e-03  3.416436e-03
Atf5     2.960264        0.496857  3.073757e-03  5.922461e-03
Hoxa7    1.941820        0.450179  5.215889e-02  8.426314e-02
Ehf      1.198227        1.233144  2.308285e-01  3.262594e-01
Tlx3     1.103218        1.058666  2.699326e-01  3.730928e-01
Tfap2c   1.074170        0.414310  2.827465e-01  3.894579e-01
Nr4a1    0.542760        0.430856  5.872950e-01  7.250556e-01
Gata6    0.294290        0.517615  7.685360e-01  8.828673e-01
Tshz1   -0.137669        0.050887  8.905020e-01  9.592936e-01
Dbp     -0.547977        0.012784  5.837078e-01  7.215176e-01
Klf5    -0.570924       -0.076190  5.680508e-01  7.052152e-01
Zim1    -0.654832       -1.837232  5.125761e-01  6.480102e-01
Zfp710  -0.722436       -0.059473  4.700262e-01  6.018262e-01
Tshz2   -0.890135       -0.329163  3.733932e-01  4.935799e-01

In [58]:
# Most downregulated transcription factors in dead end

dead_end_rank_df.loc[numpy.intersect1d(tf_array, adata.var_names)].sort_values("scores", ascending=True).head(30)

             scores  logfoldchanges         pvals     pvals_adj
names
Cenpa    -14.694151       -2.029778  7.027420e-49  1.873979e-47
Hmgb2    -12.436042       -1.655495  1.665552e-35  2.485899e-34
Tcf7l1   -10.125731       -1.699106  4.247917e-24  3.646281e-23
Prrx1     -9.667671       -3.502777  4.136854e-22  3.182196e-21
Jarid2    -9.106974       -1.539088  8.471185e-20  5.782379e-19
Terf1     -8.995116       -1.125859  2.359814e-19  1.578471e-18
Nfib      -8.488363       -2.268551  2.095683e-17  1.240049e-16
Prrx2     -8.243245       -5.525078  1.676023e-16  9.337178e-16
Zeb1      -8.197787       -3.580868  2.448527e-16  1.345345e-15
Twist1    -8.100400       -2.155874  5.477875e-16  2.945094e-15
Mis18bp1  -7.673030       -1.367189  1.679800e-14  8.114978e-14
Klf2      -7.583708       -2.094071  3.358169e-14  1.591549e-13
Id2       -7.550376       -1.184700  4.340032e-14  2.042368e-13
Id3       -7.495310       -3.318421  6.614180e-14  3.069225e-13
Zfp42     -7.309782       -1.655304  2.675775e-13  1.197215e-12
Tcf4      -7.186566       -1.106846  6.644120e-13  2.926925e-12
Cdc5l     -6.540979       -0.656287  6.111730e-11  2.359741e-10
Zfhx4     -6.538495       -1.480847  6.214110e-11  2.390042e-10
Hmgb3     -6.408444       -1.023359  1.470117e-10  5.506056e-10
Nfix      -6.227951       -2.367974  4.725747e-10  1.724725e-09
Tsc22d1   -5.737269       -0.728544  9.621546e-09  3.170196e-08
Nanog     -5.631834       -2.367001  1.783035e-08  5.714856e-08
Creb3l1   -5.540720       -2.650271  3.012301e-08  9.457773e-08
Sall1     -5.400377       -1.482890  6.650108e-08  2.018242e-07
Lin28a    -5.321290       -1.042207  1.030339e-07  3.080237e-07
Nfia      -5.268825       -1.933072  1.373003e-07  4.062138e-07
Mycn      -5.258531       -3.436124  1.452107e-07  4.285233e-07
Rest      -5.134597       -0.644595  2.827485e-07  8.124958e-07
Klf7      -5.008699       -1.349867  5.479909e-07  1.543636e-06
Zfp36l1   -4.837344       -0.572680  1.315858e-06  3.587976e-06

In [59]:
# Most upregulated transcription factors in day 4 control

control_rank_df.loc[numpy.intersect1d(tf_array, adata.var_names)].sort_values("scores", ascending=False).head(30)

           scores  logfoldchanges          pvals      pvals_adj
names
Tlx2    56.619308        4.156113   0.000000e+00   0.000000e+00
Dmrtc2  47.219395        3.756907   0.000000e+00   0.000000e+00
Zbtb7c  43.116035        2.244280   0.000000e+00   0.000000e+00
Hmgb3   39.926929        1.578542   0.000000e+00   0.000000e+00
Myc     39.168621        1.562202   0.000000e+00   0.000000e+00
Ovol1   35.878239        3.140644  6.674091e-282  1.026783e-280
Zbtb32  35.045231        2.059280  4.609327e-269  6.778422e-268
Hoxa9   28.716011        1.644503  2.407959e-181  2.239962e-180
Phox2a  28.670206        2.174598  8.977100e-181  8.273825e-180
Hopx    25.439432        1.816934  9.241419e-143  6.820235e-142
Zfp296  24.941698        0.973205  2.627576e-137  1.890343e-136
Klf10   19.644541        0.667286   6.437581e-86   3.147961e-85
Hoxa7   18.515795        0.826159   1.540081e-76   6.952961e-76
Lef1    17.094074        1.325687   1.642844e-65   6.637753e-65
Fosl1   15.086825        0.802691   1.977283e-51   6.748405e-51
Nr4a1   14.922898        0.694146   2.338905e-50   7.888380e-50
Barx2   14.731534        2.407695   4.044217e-49   1.339145e-48
Cenpa   12.991665        0.515136   1.364260e-38   3.965872e-38
Tshz1   12.974904        0.369741   1.698086e-38   4.921989e-38
Twist2  12.756365        0.812957   2.872983e-37   8.173495e-37
Pou5f1  12.480664        0.613602   9.518884e-36   2.662625e-35
Runx1   12.446761        0.519876   1.456363e-35   4.062379e-35
Tlx3    11.660106        1.660184   2.037899e-31   5.369958e-31
Tet2    11.040770        0.487917   2.429427e-28   6.088790e-28
Ehf     10.153599        2.532096   3.193658e-24   7.594906e-24
Hmga2    9.090936        0.295891   9.819020e-20   2.162780e-19
Atf3     8.887947        0.548021   6.224843e-19   1.347369e-18
Hes1     8.433112        0.257376   3.365910e-17   7.089842e-17
Hoxa10   7.813334        0.370618   5.569468e-15   1.134311e-14
Gata2    7.710498        0.901278   1.253275e-14   2.531868e-14

In [13]:
dead_end_rank_df.loc[genes_of_interest].sort_values("scores", ascending=False)

           scores  logfoldchanges         pvals     pvals_adj
names
Cdh1    13.483566        1.765469  1.954279e-41  3.908557e-40
Myc     12.562806        1.828156  3.381229e-36  5.162181e-35
Ovol1   12.100735        2.972715  1.046704e-33  1.443730e-32
Zbtb7c  10.598906        1.849738  3.014877e-26  2.955762e-25
Klf4     8.294026        1.242020  1.094780e-16  6.185198e-16
Tlx2     4.417089        0.874272  1.000390e-05  2.513543e-05
Hic2    -1.219937       -0.087063  2.224888e-01  3.171616e-01
Rest    -5.134597       -0.644595  2.827485e-07  8.124958e-07
Zfp42   -7.309782       -1.655304  2.675775e-13  1.197215e-12
Jarid2  -9.106974       -1.539088  8.471185e-20  5.782379e-19
Tcf7l1 -10.125731       -1.699106  4.247917e-24  3.646281e-23

## GSEA for dead end

In [61]:
# Cell types in the dead end

pre_res = gseapy.prerank(
    rnk=dead_end_rank_df[["scores"]], 
    gene_sets="PanglaoDB_Augmented_2021",
    threads=32,
    min_size=5,
    max_size=1000
)
pre_res.res2d.sort_values("NES", ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]

2026-03-06 08:16:03,198 [WARNING] Duplicated values found in preranked stats: 3.00% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

                        Term       NES NOM p-val FWER p-val FDR q-val
0   Mammary Epithelial Cells  2.588875       0.0        0.0       0.0
1                Trichocytes  2.454958       0.0        0.0       0.0
2              Keratinocytes  2.450678       0.0        0.0       0.0
3   Luminal Epithelial Cells  2.435519       0.0        0.0       0.0
4        Gastric Chief Cells  2.295272       0.0        0.0       0.0
5            Principal Cells  2.268925       0.0        0.0       0.0
6             Cholangiocytes  2.253806       0.0        0.0       0.0
7      Salivary Mucous Cells  2.175057       0.0        0.0       0.0
8                  Sebocytes  2.173433       0.0        0.0       0.0
9        Airway Goblet Cells  2.135118       0.0        0.0       0.0
10              Goblet Cells  2.103665       0.0      0.001  0.000117
11          Epithelial Cells  2.053371       0.0      0.004  0.000537
12         Trophoblast Cells  2.038128       0.0      0.005  0.000594
13              Ductal Cells  1.991828       0.0      0.009   0.00092
14              Hepatoblasts  1.968511       0.0      0.014  0.001374
19          Urothelial Cells  1.891786       0.0      0.053  0.004829
21               Clara Cells  1.881585   0.00271      0.059  0.005151
23               Basal Cells  1.873168       0.0      0.065  0.005294
25           Microfold Cells  1.841262       0.0      0.096  0.007591
27    Trophoblast Stem Cells  1.814927  0.002793      0.112  0.008692

In [62]:
# MSig Hallmarks in dead end

pre_res = gseapy.prerank(
    rnk=dead_end_rank_df[["scores"]], 
    gene_sets="MSigDB_Hallmark_2020",
    threads=32,
    min_size=5,
    max_size=1000
)
pre_res.res2d.sort_values("NES", ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]

2026-03-06 08:16:10,767 [WARNING] Duplicated values found in preranked stats: 3.00% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

                             Term       NES NOM p-val FWER p-val FDR q-val
0                     p53 Pathway   2.27238       0.0        0.0       0.0
3   TNF-alpha Signaling via NF-kB  1.981754       0.0      0.003  0.002193
6         Estrogen Response Early  1.623119       0.0        0.2  0.107212
7                  UV Response Up  1.613178  0.005952      0.213  0.087354
8                mTORC1 Signaling  1.591396  0.006135       0.24  0.082164
9                         Hypoxia  1.571308       0.0      0.268  0.079678
12              Androgen Response  1.432537  0.041056      0.565   0.18066
14              KRAS Signaling Dn    1.3821  0.082621      0.671  0.221126
17         Estrogen Response Late  1.338374   0.04893      0.782  0.254548
18      Unfolded Protein Response  1.335315  0.135135      0.788  0.232895
20                 Myc Targets V1  1.265891  0.191816      0.895  0.304359
22             TGF-beta Signaling  1.247817  0.156627      0.911  0.302388
25          Xenobiotic Metabolism  1.212866  0.145833      0.941  0.332546
26                Notch Signaling  1.189417  0.250667       0.95  0.345865
27        Cholesterol Homeostasis  1.186966  0.171831       0.95  0.326121
28                heme Metabolism  1.158767  0.225989      0.964  0.349141
29       IL-6/JAK/STAT3 Signaling  1.135154  0.246612      0.976  0.367905
30           IL-2/STAT5 Signaling  1.134056  0.213376      0.976  0.349172
31     Wnt-beta Catenin Signaling  1.130945  0.308483      0.976  0.334641
37                 Apical Surface  1.054794   0.38814      0.994  0.446126

In [ ]:
# GO biological process in dead end

pre_res = gseapy.prerank(
    rnk=dead_end_rank_df[["scores"]], 
    gene_sets="GO_Biological_Process_2025",
    threads=32,
    min_size=5,
    max_size=1000
)
pre_res.res2d.sort_values("NES", ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]

2026-03-06 08:16:11,517 [WARNING] Duplicated values found in preranked stats: 3.00% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

,Term,NES,NOM p-val,FWER p-val,FDR q-val
0,Positive Regulation of Intrinsic Apoptotic Sig...,1.760335,0.007937,0.85,1.0
5,Regulation of Autophagy (GO:0010506),1.720115,0.004975,0.953,1.0
10,Antigen Processing and Presentation of Peptide...,1.702887,0.007895,0.971,0.841609
11,Antigen Processing and Presentation of Exogeno...,1.702887,0.007895,0.971,0.841609
9,Antigen Processing and Presentation of Exogeno...,1.702887,0.007895,0.971,0.841609
15,Positive Regulation of Sprouting Angiogenesis ...,1.646528,0.023018,0.996,1.0
18,Intracellular Iron Ion Homeostasis (GO:0006879),1.634716,0.026247,0.999,1.0
19,Regulation of Glycolytic Process (GO:0006110),1.62813,0.028796,0.999,1.0
20,Antigen Processing and Presentation of Peptide...,1.623347,0.018182,0.999,1.0
24,Positive Regulation of Neuron Apoptotic Proces...,1.609309,0.039578,1.0,1.0
27,Response to Endoplasmic Reticulum Stress (GO:0...,1.593984,0.027933,1.0,1.0
31,Protein Catabolic Process (GO:0030163),1.584296,0.021164,1.0,1.0
35,Negative Regulation of Transport (GO:0051051),1.558176,0.045822,1.0,1.0
38,Cellular Response to Hypoxia (GO:0071456),1.545509,0.028329,1.0,1.0
39,Cellular Response to Decreased Oxygen Levels (...,1.545509,0.028329,1.0,1.0
42,Anterograde Trans-Synaptic Signaling (GO:0098916),1.542249,0.034574,1.0,1.0
45,Regulation of Intrinsic Apoptotic Signaling Pa...,1.537231,0.067708,1.0,1.0
46,Positive Regulation of Response to Endoplasmic...,1.536927,0.049479,1.0,1.0
50,Signal Transduction by P53 Class Mediator (GO:...,1.521659,0.049505,1.0,1.0
55,Calcium Ion Transmembrane Transport (GO:0070588),1.515867,0.052493,1.0,1.0

In [ ]:
# TFs whose targets are upregulated in dead end, perturbation followed by expression
pre_res = gseapy.prerank(
    rnk=dead_end_rank_df[["scores"]], 
    gene_sets="TF_Perturbations_Followed_by_Expression",
    threads=32,
    min_size=5,
    max_size=1000
)
print("Top")
IPython.display.display(pre_res.res2d.sort_values("NES", ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]])
print("Bottom")
IPython.display.display(pre_res.res2d.sort_values("NES", ascending=True).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]])

2026-03-06 08:53:52,343 [WARNING] Duplicated values found in preranked stats: 3.00% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

Top

,Term,NES,NOM p-val,FWER p-val,FDR q-val
108,MYC OE MOUSE GSE55272 CREEDSID GENE 1822 DOWN,1.967528,0.0,0.056,0.042759
142,IRF6 KO MOUSE GSE5800 CREEDSID GENE 153 UP,1.914332,0.0,0.12,0.045275
143,PLAGL2 DEFICIENCY MOUSE GSE9123 CREEDSID GENE ...,1.913938,0.0,0.12,0.030393
154,ARID3A KD MOUSE GSE56853 CREEDSID GENE 1337 UP,1.90636,0.0,0.135,0.025467
159,HEY2 KO MOUSE GSE6526 CREEDSID GENE 1511 UP,1.896851,0.0,0.156,0.019598
158,HEY2 KO MOUSE GSE6526 CREEDSID GENE 1512 DOWN,1.896851,0.0,0.156,0.019598
171,PPARA KO MOUSE GSE6864 CREEDSID GENE 981 UP,1.874495,0.0,0.217,0.023626
176,FOXO1 KD MOUSE GSE6623 CREEDSID GENE 505 DOWN,1.870261,0.0,0.23,0.022166
187,GLI1 INHIBITION HUMAN GSE36855 CREEDSID GENE 6...,1.858362,0.0,0.257,0.022498
200,PPARA KO MOUSE GSE6864 CREEDSID GENE 1371 DOWN,1.840598,0.0,0.308,0.025027
211,XBP1 KO MOUSE GSE52857 CREEDSID GENE 2765 UP,1.830522,0.0,0.332,0.025324
223,NR1I2 KO MOUSE GSE23780 CREEDSID GENE 2165 DOWN,1.821299,0.002688,0.357,0.025153
243,AIRE KO MOUSE GSE2585 CREEDSID GENE 272 UP,1.803,0.0,0.412,0.02849
299,TFEB OE HUMAN GSE16267 CREEDSID GENE 2976 UP,1.755569,0.0,0.576,0.044736
345,PPARA DEFICIENCY MOUSE GSE6864 CREEDSID GENE 6...,1.702908,0.003077,0.765,0.072565
367,MBD3 KD MOUSE GSE31008 CREEDSID GENE 1325 UP,1.684703,0.0,0.811,0.081864
405,SREBF2 KD HUMAN GSE50588 CREEDSID GENE 2823 UP,1.661303,0.0,0.861,0.096912
406,MYC KD HUMAN GSE22139 CREEDSID GENE 712 DOWN,1.660848,0.010499,0.861,0.092087
433,HOXC13 OE MOUSE GSE2374 CREEDSID GENE 201 DOWN,1.639923,0.0,0.901,0.107296
442,SNAI1 OE HUMAN GSE14773 CREEDSID GENE 371 UP,1.628183,0.00625,0.915,0.113533

Bottom

,Term,NES,NOM p-val,FWER p-val,FDR q-val
0,FOXA1 KD HUMAN GSE25315 CREEDSID GENE 2164 DOWN,-2.463419,0.0,0.0,0.0
1,OVOL2 OE PC3 HUMAN GSE48230 RNASEQ DOWN,-2.452743,0.0,0.0,0.0
2,DNMT1 KO MOUSE GSE31626 CREEDSID GENE 1237 DOWN,-2.417583,0.0,0.0,0.0
3,E2F1 OE HUMAN GSE2715 CREEDSID GENE 1129 DOWN,-2.407181,0.0,0.0,0.0
4,TAL1 KD JURKAT HUMAN GSE72299 RNASEQ DOWN,-2.372448,0.0,0.0,0.0
5,MYB KD HUMAN GSE49286 CREEDSID GENE 1842 DOWN,-2.353719,0.0,0.0,0.0
6,MEIS2 KD KASUMI1 HUMAN GSE81328 RNASEQ UP,-2.337821,0.0,0.0,0.0
7,ZNF750 KD HUMAN GSE38039 CREEDSID GENE 204 UP,-2.336913,0.0,0.0,0.0
8,ZNF750 KD HUMAN GSE38039 CREEDSID GENE 2704 DOWN,-2.336913,0.0,0.0,0.0
9,ZMAT4 SIRNA T47D HUMAN GSE79586 RNASEQ DOWN,-2.332155,0.0,0.0,0.0
10,FLI1 KD HUMAN GSE27524 CREEDSID GENE 1597 DOWN,-2.318018,0.0,0.0,0.0
11,MYCN SHRNA SKNBE2 HUMAN GSE84389 RNASEQ DOWN,-2.316172,0.0,0.0,0.0
12,PRDM16 DEPLETION MOUSE GSE35011 CREEDSID GENE ...,-2.307331,0.0,0.0,0.0
13,NFKB1 INACTIVATION HUMAN GSE20667 CREEDSID GEN...,-2.301931,0.0,0.0,0.0
14,YEATS2 SHRNA H1299 HUMAN GSE90781 RNASEQ DOWN,-2.300333,0.0,0.0,0.0
15,ADAR KD HUVEC HUMAN GSE60217 RNASEQ DOWN,-2.288659,0.0,0.0,0.0
16,TFAP2C SIRNA HUMAN GSE15481 CREEDSID GENE 2893...,-2.264936,0.0,0.0,0.0
17,DNMT1 KO MOUSE GSE31626 CREEDSID GENE 1236 DOWN,-2.261227,0.0,0.0,0.0
18,RC3H1 SIRNA HEK293 HUMAN GSE68611 RNASEQ UP,-2.254065,0.0,0.0,0.0
19,DUX4 OE HUMAN GSE33799 CREEDSID GENE 1430 DOWN,-2.251097,0.0,0.0,0.0

In [146]:
# TFs whose targets are upregulated in dead end, Chea
pre_res = gseapy.prerank(
    rnk=dead_end_rank_df[["scores"]], 
    gene_sets="ChEA_2022",
    threads=32,
    min_size=5,
    max_size=1000
)
print("Top")
IPython.display.display(pre_res.res2d.sort_values("NES", ascending=False).head(30)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]])
print("Bottom")
IPython.display.display(pre_res.res2d.sort_values("NES", ascending=True).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]])

2026-03-06 09:15:54,894 [WARNING] Duplicated values found in preranked stats: 3.00% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

Top

,Term,NES,NOM p-val,FWER p-val,FDR q-val
3,TP63 17297297 ChIP-ChIP HaCaT Human,1.829356,0.008772,0.081,0.084076
8,FOXA1 33576154 ChIP-Seq Human HilarLN Prostate...,1.684291,0.003472,0.298,0.182961
14,ESR1 26153859 ChIP-Seq MCF-7 Human BreastCancer,1.611439,0.0,0.513,0.245222
17,NOTCH1 21737748 ChIP-Seq TLL Human,1.595993,0.012195,0.573,0.214012
22,RELB 30642670 ChIP-Seq CTB1 Human Placenta Inf...,1.566168,0.008902,0.661,0.221655
25,HCFC1 20581084 ChIP-Seq MESCs Mouse,1.55914,0.046753,0.684,0.196655
31,NUCKS1 24931609 ChIP-Seq HEPATOCYTES Mouse,1.539307,0.0,0.742,0.200363
36,CDX2 20551321 ChIP-Seq CACO-2 Human,1.516565,0.006173,0.815,0.213415
37,ELF1 20517297 ChIP-Seq JURKAT Human,1.510851,0.0,0.83,0.200212
38,TP63 30713093 ChIP-Seq Epithelial Human Tongue...,1.503021,0.0,0.846,0.192802
48,RUNX1 27514584 ChIP-Seq MCF-7 Human BreastCancer,1.458835,0.006849,0.926,0.245627
53,TAF7L 23326641 ChIP-Seq C3H10T1-2 Mouse,1.451698,0.015337,0.935,0.238136
56,FOXA1 33576154 ChIP-Seq Human Liver ProstateCa...,1.449039,0.0,0.936,0.224081
61,GATA2 22383799 ChIP-Seq G1ME Mouse,1.439483,0.007519,0.947,0.22227
62,FOXA1 26457646 ChIP-Seq LHSAR Human ProstateCa...,1.438114,0.015748,0.947,0.209299
67,PHF8 20622854 ChIP-Seq HELA Human,1.427926,0.0,0.954,0.214131
68,BRD4 28847988 ChIP-Seq BCBL1 Human Blood Lymphoma,1.42713,0.04878,0.954,0.202491
77,P63 26484246 Chip-Seq KERATINOCYTES Human,1.406611,0.0,0.977,0.22484
78,TCF7 22412390 ChIP-Seq EML Mouse,1.403155,0.008264,0.981,0.218588
81,MEIS1 20887958 ChIP-Seq HPC-7 Mouse,1.401635,0.006211,0.981,0.209999
82,PKCTHETA 26484144 Chip-Seq BREAST Human,1.39775,0.026471,0.982,0.206414
83,CREB1 20920259 ChIP-Seq GC1-SPG Mouse,1.395913,0.003937,0.983,0.199203
89,NFE2L2 22581777 ChIP-Seq LYMPHOBLASTOID Human,1.38283,0.054662,0.991,0.210024
105,RUNX1 27514584 Chip-Seq MCF-7 Human,1.352675,0.009302,0.995,0.251432
116,SMAD3 18955504 ChIP-ChIP HaCaT Human,1.336771,0.0,0.997,0.262517
115,SMAD2 18955504 ChIP-ChIP HaCaT Human,1.336771,0.0,0.997,0.262517
119,SOX2 27498859 Chip-Seq STOMACH Mouse,1.33381,0.008511,0.997,0.259129
139,TP53 22127205 ChIP-Seq IMR90 Human,1.297763,0.056291,1.0,0.329651
141,TP53 16413492 ChIP-PET HCT116 Human,1.294997,0.062305,1.0,0.324313
142,ESR1 20056654 ChIP-Seq MCF-7 Human BreastCancer,1.294662,0.047101,1.0,0.314362

Bottom

,Term,NES,NOM p-val,FWER p-val,FDR q-val
0,FOXM1 23109430 ChIP-Seq U2OS Human,-2.304463,0.0,0.0,0.0
1,FOXM1 25889361 ChIP-Seq OE33 AND U2OS Human,-2.008273,0.0,0.001,0.000508
2,E2F4 17652178 ChIP-ChIP JURKAT Human,-1.948152,0.0,0.002,0.000678
4,EKLF 21900194 ChIP-Seq ERYTHROCYTE Mouse,-1.779874,0.0,0.064,0.018295
5,E2F4 21247883 ChIP-Seq LYMPHOBLASTOID Human,-1.766155,0.0,0.077,0.017482
6,FOXM1 26456572 ChIP-Seq MCF-7 Human BreastCancer,-1.76615,0.0,0.077,0.014569
7,GABP 19822575 ChIP-Seq HepG2 Human,-1.735868,0.0,0.132,0.022071
9,RUNX2 24655370 ChIP-Seq MC3T3E1 Mouse Bone,-1.662657,0.0,0.326,0.054632
10,MYBL2 22936984 ChIP-ChIP MESCs Mouse,-1.65339,0.0,0.366,0.056467
11,EWS 26573619 Chip-Seq HEK293 Human,-1.631371,0.0,0.456,0.069726
12,KDM5B 21448134 ChIP-Seq MESCs Mouse,-1.62185,0.0,0.502,0.071703
13,SALL4 18804426 ChIP-ChIP MESCs Mouse,-1.61651,0.0,0.531,0.070556
15,SMAD1 18555785 ChIP-Seq MESCs Mouse,-1.610064,0.001395,0.563,0.071305
16,NANOG 18358816 ChIP-ChIP MESCs Mouse,-1.598641,0.0,0.613,0.075069
18,ELK1 19687146 ChIP-ChIP HELA Human,-1.594585,0.001486,0.633,0.073724
19,SOX17 20123909 ChIP-Seq XEN Mouse,-1.593697,0.0,0.634,0.070069
20,NACC1 18358816 ChIP-ChIP MESCs Mouse,-1.586361,0.001316,0.676,0.073541
21,NANOG 18555785 ChIP-Seq MESCs Mouse,-1.577771,0.002976,0.71,0.076005
23,SOX2 19030024 ChIP-ChIP MESCs Mouse,-1.564418,0.001418,0.763,0.08463
24,POU3F2 20337985 ChIP-ChIP 501MEL Human,-1.562323,0.002751,0.767,0.081516

In [147]:
# TFs whose targets are upregulated in dead end, ENCODE
pre_res = gseapy.prerank(
    rnk=dead_end_rank_df[["scores"]], 
    gene_sets="ENCODE_TF_ChIP-seq_2015",
    threads=32,
    min_size=5,
    max_size=1000
)
print("Top")
IPython.display.display(pre_res.res2d.sort_values("NES", ascending=False).head(30)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]])
print("Bottom")
IPython.display.display(pre_res.res2d.sort_values("NES", ascending=True).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]])

2026-03-06 09:16:10,062 [WARNING] Duplicated values found in preranked stats: 3.00% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

Top

                                 Term       NES NOM p-val FWER p-val FDR q-val
4                     MAX myocyte mm9  1.941958       0.0      0.027  0.028555
7                    NR2F2 MCF-7 hg19  1.860825       0.0      0.062  0.034164
10                    ZEB1 HepG2 hg19  1.805283       0.0      0.112  0.043173
14                   FOSL2 HepG2 hg19  1.788335       0.0      0.129  0.037734
16                   YY1 GM12891 hg19  1.748837       0.0       0.19  0.045893
20                     ATF3 K562 hg19  1.711503       0.0      0.265  0.057111
22                     PML MCF-7 hg19  1.703937   0.00304      0.281   0.05274
25                    TAF1 MCF-7 hg19  1.677512       0.0      0.345  0.060425
27                    JUND MCF-7 hg19  1.671517  0.005556      0.359  0.056431
29                  REST HeLa-S3 hg19  1.664067       0.0      0.376  0.054153
30                    MEF2A K562 hg19  1.649704  0.015666      0.415  0.057945
32                   NR3C1 ECC-1 hg19  1.638513  0.008929      0.444  0.059065
37                     USF1 K562 hg19  1.610927  0.003049      0.517  0.069349
38                     NFE2 K562 hg19  1.609434  0.037234      0.522  0.065852
40                  JUND GM12878 hg19  1.604116  0.005291      0.537   0.06391
45                     SIX5 A549 hg19  1.558653  0.013624      0.632  0.089299
55                   EP300 ECC-1 hg19  1.520265  0.006154      0.748  0.116681
56                    REST MCF-7 hg19  1.504052  0.018072      0.796  0.126913
61               eGFP-HDAC8 K562 hg19  1.493454  0.009615      0.813  0.131183
67                   TAL1 G1E-ER4 mm9  1.465546  0.016447      0.859  0.156799
73                   TCF12 MCF-7 hg19  1.455801  0.072022      0.876  0.162251
81                  NFE2 GM12878 hg19  1.429969  0.003165      0.925   0.19349
83                   JUND HCT116 hg19  1.429077  0.021472      0.926  0.186098
84                    EP300 T47D hg19  1.428908  0.003311      0.927  0.178513
86  POLR2A bone marrow macrophage mm9  1.425541       0.0      0.934   0.17639
90                    REST ECC-1 hg19  1.419323  0.012579      0.947  0.178942
92                   CREBBP K562 hg19  1.416518  0.013514      0.948  0.177413
93              MAX MEL cell line mm9  1.414682  0.007353      0.949  0.173882
96                    USF1 HepG2 hg19  1.409511  0.018018      0.953  0.175763
99                    FOSL2 A549 hg19  1.404429  0.028662      0.958  0.176873

Bottom

                            Term       NES NOM p-val FWER p-val FDR q-val
0               FOXM1 ECC-1 hg19 -2.328247       0.0        0.0       0.0
1         E2F4 MEL cell line mm9 -2.104461       0.0        0.0       0.0
2              E2F4 HeLa-S3 hg19 -2.030328       0.0        0.0       0.0
3               FOXM1 MCF-7 hg19 -1.976726       0.0      0.002  0.000496
5              IRF3 HeLa-S3 hg19 -1.907565       0.0      0.007  0.001587
6              NFYA GM12878 hg19 -1.879223       0.0      0.012  0.002149
8                 SP2 HepG2 hg19 -1.841056       0.0      0.027  0.003968
9               SP2 H1-hESC hg19 -1.831186       0.0      0.034  0.004463
11             IRF3 GM12878 hg19 -1.800409       0.0      0.055  0.006613
12              E2F4 CH12.LX mm9 -1.797015       0.0      0.058  0.006249
13                 FOS K562 hg19 -1.794122       0.0      0.061  0.006132
15                 SP2 K562 hg19 -1.749251       0.0      0.126  0.011985
17        FLI1 megakaryocyte mm9 -1.744719       0.0      0.133  0.011597
18              SETDB1 U2OS hg19 -1.714819       0.0      0.195  0.017145
19              FOS GM12878 hg19 -1.711803       0.0      0.205  0.016928
21              SRF H1-hESC hg19 -1.704008       0.0      0.227  0.017916
23  POLR2AphosphoS5 SK-N-MC hg19 -1.702963  0.001488      0.228  0.017037
24      POLR2A erythroblast hg19 -1.690636       0.0      0.264  0.019562
26   POLR2AphosphoS5 PFSK-1 hg19 -1.674981       0.0      0.325  0.023596
28             CHD2 HeLa-S3 hg19 -1.667269       0.0      0.346  0.025194

In [148]:
# Motif enrichment analysis, TRANSFAC and JASPAR

# Motifs upregulated in dead end
pre_res = gseapy.prerank(
    rnk=dead_end_rank_df[["scores"]], 
    gene_sets="TRANSFAC_and_JASPAR_PWMs",
    threads=32,
    min_size=5,
    max_size=1000
)
print("Top")
IPython.display.display(pre_res.res2d.sort_values("NES", ascending=False).head(30)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]])
print("Bottom")
IPython.display.display(pre_res.res2d.sort_values("NES", ascending=True).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]])

2026-03-06 09:16:21,924 [WARNING] Duplicated values found in preranked stats: 3.00% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

Top

               Term       NES NOM p-val FWER p-val FDR q-val
2     SNAI1 (human)  1.698159       0.0      0.217  0.125241
1      TCF3 (human)  1.698159       0.0      0.217  0.125241
3     SNAI2 (human)  1.686804       0.0       0.24  0.095421
9     CEBPB (human)   1.45279       0.0      0.812    0.4453
12    NCOA1 (human)  1.438102  0.094737       0.84  0.398782
13   MIR210 (human)  1.431728  0.077135      0.854  0.347228
14   TFAP2C (human)  1.431336  0.008097      0.856  0.299328
24    MYOD1 (human)  1.334539  0.126344      0.967  0.491271
25     MIB2 (human)  1.328755  0.015385      0.974  0.454577
28    SMAD4 (human)  1.306174  0.008163      0.987   0.47661
31      JUN (mouse)  1.298234  0.032922       0.99  0.455782
32     NFE2 (human)  1.293136  0.005814      0.993  0.432378
40    CREB1 (human)  1.254696  0.004386      0.999   0.51549
43  ZNF354C (human)  1.231578      0.09        1.0  0.562376
54      MYC (human)  1.202963  0.072917        1.0  0.631504
58    NR5A2 (mouse)  1.198664  0.075188        1.0  0.609616
64     USF2 (human)  1.189416  0.014851        1.0  0.610592
65    FOXF2 (human)  1.188553  0.130719        1.0  0.579873
66     GFI1 (human)  1.186308   0.11236        1.0  0.558247
70     ATF4 (human)  1.179423  0.089606        1.0  0.554239
72    PITX1 (human)  1.175545  0.114187        1.0  0.540816
75    GTF2I (human)  1.164871      0.25        1.0  0.555767
76   ZNF148 (human)  1.162637  0.096491        1.0  0.538474
78     NRF1 (mouse)  1.151759   0.14966        1.0  0.553519
80     KLF4 (human)  1.147589  0.106838        1.0  0.546208
83    KLF11 (human)  1.142772  0.121339        1.0  0.542633
84    STAT1 (mouse)  1.141606  0.279006        1.0  0.526511
86    IKZF1 (human)  1.139672  0.170139        1.0  0.515198
90      MYC (mouse)  1.112168  0.157258        1.0  0.593436
95     TP63 (human)  1.096662  0.215488        1.0  0.637866

Bottom

                Term       NES NOM p-val FWER p-val FDR q-val
0     Nkx2-5 (mouse) -1.743336   0.00321      0.046  0.047112
4      HNF1B (human) -1.657876  0.004808      0.191   0.10475
5      SOX10 (human) -1.498589  0.022117      0.783  0.528927
6       NFYA (mouse) -1.479768  0.002688      0.832  0.485407
7       NRF1 (human) -1.456635  0.008559      0.892  0.498789
8     HIVEP1 (human) -1.456613  0.025994      0.892  0.415991
10  EIF4EBP1 (human) -1.446871   0.05414      0.919    0.3958
11       SP3 (mouse) -1.439081  0.002685      0.932  0.377399
15       SRF (mouse) -1.412439  0.020891      0.971  0.444504
16     Nr2e3 (mouse)  -1.40943  0.059295      0.971  0.411781
17       PGR (human) -1.380667  0.010796      0.992  0.495909
18      NFYB (human) -1.374816     0.072      0.992  0.480478
19      Pax6 (human) -1.372682  0.083981      0.993   0.45254
20     CREB1 (mouse) -1.365062  0.035112      0.994  0.450789
21    SREBF1 (mouse) -1.351758   0.02038      0.997  0.479476
22      ESR2 (human) -1.350086  0.079675      0.998  0.456463
23      NFYA (human) -1.334542  0.015464      0.999  0.490935
26     CEBPE (human)  -1.32448  0.114701      0.999   0.51016
27      BCL6 (human) -1.320782  0.028378      0.999  0.500034
29     FOXI1 (human) -1.303403  0.114148        1.0  0.556777

In [149]:
# Motifs upregulated in dead end, 
pre_res = gseapy.prerank(
    rnk=dead_end_rank_df[["scores"]], 
    gene_sets="JASPAR_PWM_Mouse_2025",
    threads=32,
    min_size=5,
    max_size=1000
)
print("Top")
IPython.display.display(pre_res.res2d.sort_values("NES", ascending=False).head(30)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]])
print("Bottom")
IPython.display.display(pre_res.res2d.sort_values("NES", ascending=True).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]])

2026-03-06 09:16:34,766 [WARNING] Duplicated values found in preranked stats: 3.00% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

Top

            Term       NES NOM p-val FWER p-val FDR q-val
8          TCF12  1.350296       0.0      0.345  0.349353
9          NPAS2  1.341644  0.037162      0.369  0.190975
25         HAND1  1.237528  0.032864      0.671  0.378261
31          RARB   1.20734  0.052632      0.754  0.387486
44       CREB3L2  1.146858  0.140893      0.892  0.552199
49         NR1H4  1.097714  0.174468      0.955  0.716235
59       TFCP2L1   1.06455  0.239521       0.98  0.834458
64         ARNTL  1.038151  0.385093      0.993  0.903827
73     AHR::ARNT  1.007965  0.374016      0.998       1.0
74          SPZ1  1.005296  0.402597      0.998  0.931443
75          HIC1  1.004255   0.42616      0.998  0.852917
78    ZIC1::ZIC2  0.995141  0.446429      0.999  0.838682
80           ZFX  0.992649  0.472103      0.999  0.788409
81          EBF4  0.990517  0.504545      0.999   0.74299
88           JUN   0.96264  0.560976        1.0  0.840005
100        CREB5  0.928776  0.642405        1.0  0.955723
106         EBF2  0.909156  0.818182        1.0  0.986806
108  BACH1::MAFK  0.902788  0.794521        1.0  0.956312
109         RXRA  0.899868  0.825328        1.0  0.914979
113        NR1H3  0.890958  0.857143        1.0  0.897369
114        NANOG  0.888734  0.777419        1.0  0.860612
126        NPAS4  0.853968  0.801136        1.0  0.898739
144        DMBX1  -0.63029  0.984779        1.0   0.99838
143         MAFG -0.756825  0.993734        1.0  0.981974
142         DLX2 -0.757269  0.935302        1.0  0.989829
141        ASCL2  -0.76003  0.986164        1.0  0.996389
140         RARG -0.769647   0.98739        1.0  0.997939
139       TWIST2 -0.776891  0.917261        1.0       1.0
138         ATF1 -0.782487  0.759411        1.0       1.0
137         ARNT -0.785176  0.852187        1.0       1.0

Bottom

      Term       NES NOM p-val FWER p-val FDR q-val
0      ARX -1.623406       0.0      0.051  0.065311
1    SOX11 -1.596687       0.0      0.072  0.046731
2     ALX1 -1.563339  0.002618      0.104  0.046919
3     ALX4 -1.441919  0.015603      0.385  0.172568
4     LHX4 -1.410246  0.026201      0.493  0.213049
5    STAT2 -1.407999  0.007732      0.502  0.182421
6    GFI1B -1.407851  0.001261      0.502  0.156682
7    FOXF1  -1.37432  0.009695      0.654  0.220847
10   SOX17 -1.329395   0.01715      0.789  0.343822
11    SOX5 -1.325497  0.031208      0.802  0.322614
12  HOXA13  -1.31648  0.024707      0.831  0.323587
13   NOBOX  -1.31607  0.041096      0.832  0.297372
14   HMGA1 -1.296606  0.033245      0.878  0.340415
15   FOXO1 -1.288367  0.032345      0.894  0.345538
16     DUX -1.267936   0.03871      0.926  0.403878
17    IRF1  -1.26714  0.033245      0.929  0.381451
18   FOXJ2 -1.261511  0.044213      0.937  0.380606
19    SOX1 -1.258409  0.043478      0.938  0.372098
20    HMX2 -1.257316  0.033898      0.938  0.356426
21   FOXL2 -1.254748  0.051656      0.941  0.348626

## GSEA for day 4 control

In [135]:
# Cell types in control

pre_res = gseapy.prerank(
    rnk=control_rank_df[["scores"]], 
    gene_sets="PanglaoDB_Augmented_2021",
    threads=32,
    min_size=5,
    max_size=1000
)
pre_res.res2d.sort_values("NES", ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]

2026-03-06 08:57:38,496 [WARNING] Duplicated values found in preranked stats: 0.55% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

                         Term       NES NOM p-val FWER p-val FDR q-val
0            Epithelial Cells  2.172779       0.0        0.0       0.0
1               Keratinocytes  2.171084       0.0        0.0       0.0
2    Mammary Epithelial Cells  2.167204       0.0        0.0       0.0
3         Gastric Chief Cells  2.129438       0.0        0.0       0.0
4    Luminal Epithelial Cells  2.125696       0.0        0.0       0.0
5              Cholangiocytes  2.077497       0.0        0.0       0.0
6                 Trichocytes  2.049509       0.0      0.001  0.000147
9                Hepatoblasts   1.97248  0.001916      0.003  0.000387
13            Principal Cells  1.939494       0.0      0.006  0.000688
14      Salivary Mucous Cells  1.938638       0.0      0.006  0.000619
15               Ductal Cells   1.91405       0.0      0.011  0.001032
16                  Sebocytes  1.910094       0.0      0.011  0.000946
17        Airway Goblet Cells  1.868329       0.0      0.034  0.002938
21             Foveolar Cells  1.844266       0.0      0.055  0.004498
22               Goblet Cells  1.827066  0.001808      0.068  0.005299
23  Undefined Placental Cells  1.823746  0.001946      0.072  0.005226
28               Merkel Cells  1.769781   0.00365      0.124  0.009716
30          Trophoblast Cells  1.739257  0.001786       0.18  0.013593
31     Trophoblast Stem Cells  1.735057       0.0      0.193  0.013584
33                Basal Cells  1.725889       0.0      0.217  0.015072

In [63]:
# MSig Hallmarks in day 4 control

pre_res = gseapy.prerank(
    rnk=control_rank_df[["scores"]], 
    gene_sets="MSigDB_Hallmark_2020",
    threads=32,
    min_size=5,
    max_size=1000
)
pre_res.res2d.sort_values("NES", ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]

2026-03-06 08:16:11,166 [WARNING] Duplicated values found in preranked stats: 0.55% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

                          Term       NES NOM p-val FWER p-val FDR q-val
0       Estrogen Response Late  1.650953  0.001751       0.15  0.162436
2      Estrogen Response Early  1.568822  0.010363      0.318  0.192184
4               Myc Targets V1  1.406796   0.09589      0.753  0.486363
5                  E2F Targets  1.397855  0.062278      0.771  0.390271
7                  p53 Pathway  1.348818  0.069027      0.861  0.429322
8   Wnt-beta Catenin Signaling  1.346102  0.142562      0.865  0.364536
9             mTORC1 Signaling  1.345051  0.075134      0.865  0.314888
10             Notch Signaling  1.342163  0.138493       0.87  0.278478
11       Xenobiotic Metabolism  1.282317  0.109319      0.947  0.353098
12           Androgen Response  1.269339   0.15283      0.958  0.341587
13             G2-M Checkpoint  1.229624  0.161525      0.983  0.380934
14    PI3K/AKT/mTOR  Signaling  1.209172  0.208872      0.987  0.386651
17           KRAS Signaling Dn  1.126822  0.283688      0.999  0.527698
19         Allograft Rejection  1.111855  0.273703        1.0  0.524206
20              Apical Surface  1.085981  0.365503        1.0  0.547434
21             heme Metabolism  1.080596  0.344828        1.0  0.524316
23       Fatty Acid Metabolism  1.058745  0.381044        1.0  0.536305
24     Cholesterol Homeostasis  1.044386  0.421642        1.0  0.536783
29        IL-2/STAT5 Signaling  0.992774  0.445545        1.0  0.617584
33              UV Response Up  0.962919  0.525641        1.0  0.648232

In [134]:
# TFs whose targets are affected in control
pre_res = gseapy.prerank(
    rnk=control_rank_df[["scores"]], 
    gene_sets="TF_Perturbations_Followed_by_Expression",
    threads=32,
    min_size=5,
    max_size=1000
)
print("Top")
IPython.display.display(pre_res.res2d.sort_values("NES", ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]])
print("Bottom")
IPython.display.display(pre_res.res2d.sort_values("NES", ascending=True).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]])

2026-03-06 08:54:49,726 [WARNING] Duplicated values found in preranked stats: 0.55% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

Top

,Term,NES,NOM p-val,FWER p-val,FDR q-val
7,OVOL2 OE MOUSE GSE55074 CREEDSID GENE 2603 DOWN,2.05011,0.0,0.005,0.003324
9,MYC OE MOUSE GSE55272 CREEDSID GENE 1822 DOWN,2.039413,0.0,0.007,0.002327
10,IRF6 KO MOUSE GSE5800 CREEDSID GENE 153 UP,2.039194,0.0,0.007,0.001551
38,HSF1 KO MOUSE GSE41005 CREEDSID GENE 2143 DOWN,1.856263,0.0,0.234,0.048202
39,YY1 KD MOUSE GSE31784 CREEDSID GENE 1333 UP,1.850319,0.0,0.257,0.042418
56,MBD3 KD MOUSE GSE31008 CREEDSID GENE 1325 UP,1.805803,0.001669,0.429,0.070475
62,PPARA DEFICIENCY MOUSE GSE6864 CREEDSID GENE 6...,1.793981,0.0,0.474,0.06943
63,KLF1 KO MOUSE GSE36427 CREEDSID GENE 1562 DOWN,1.790153,0.001855,0.496,0.06499
65,NFE2L2 KO MOUSE GSE18344 CREEDSID GENE 965 DOWN,1.785133,0.0,0.512,0.061093
78,HNF4A MUT MOUSE GSE3116 CREEDSID GENE 850 DOWN,1.763923,0.0,0.604,0.073135
84,MYC KD HUMAN GSE54872 CREEDSID GENE 1311 DOWN,1.74751,0.007576,0.664,0.082503
95,MYC KD HUMAN GSE22139 CREEDSID GENE 712 DOWN,1.719662,0.003831,0.784,0.107984
101,PPARA KO MOUSE GSE6864 CREEDSID GENE 981 UP,1.704649,0.0,0.826,0.120595
103,PPARA KO MOUSE GSE6864 CREEDSID GENE 1371 DOWN,1.694853,0.001631,0.85,0.125374
104,DEAF1 OE MOUSE GSE12367 CREEDSID GENE 1682 UP,1.691967,0.003745,0.858,0.120473
112,NFE2L2 KO MOUSE GSE18344 CREEDSID GENE 959 DOWN,1.678631,0.0,0.889,0.132432
113,NR3C1 KO MOUSE GSE23724 CREEDSID GENE 3014 DOWN,1.67673,0.001715,0.893,0.127731
115,NFE2L2 KO MOUSE GSE18344 CREEDSID GENE 1263 UP,1.672043,0.004975,0.906,0.126804
118,FOXP1 KD HUMAN GSE51382 CREEDSID GENE 2764 DOWN,1.670945,0.001792,0.908,0.121494
122,NR1I2 KO MOUSE GSE23780 CREEDSID GENE 2165 DOWN,1.664305,0.015595,0.919,0.12383

Bottom

,Term,NES,NOM p-val,FWER p-val,FDR q-val
0,TCF3 KO MOUSE GSE19923 CREEDSID GENE 2167 UP,-2.135971,0.0,0.003,0.004398
1,MYC KD HUMAN GSE22139 CREEDSID GENE 712 UP,-2.114692,0.0,0.003,0.002199
2,NEUROG3 OE MOUSE GSE3653 CREEDSID GENE 2289 DOWN,-2.108357,0.0,0.003,0.001466
3,ZFX KO MOUSE GSE7069 CREEDSID GENE 177 UP,-2.102751,0.0,0.004,0.001466
4,MYC OE HUMAN GSE43730 CREEDSID GENE 359 DOWN,-2.068408,0.0,0.004,0.001173
5,NEUROG3 OE MOUSE GSE3653 CREEDSID GENE 1660 DOWN,-2.064367,0.0,0.004,0.000977
6,CDX2 KO MOUSE GSE12999 CREEDSID GENE 773 UP,-2.056295,0.0,0.004,0.000838
8,EBF1 OE MOUSE GSE2192 CREEDSID GENE 859 DOWN,-2.046406,0.0,0.004,0.000733
11,GATA3 OE MOUSE GSE12999 CREEDSID GENE 2531 DOWN,-2.031703,0.0,0.007,0.001303
12,REST SHRNA C2 HUMAN GSE90068 PBPA RNASEQ DOWN,-2.016792,0.0,0.014,0.002199
13,PPARG OE MOUSE GSE2192 CREEDSID GENE 861 DOWN,-2.015861,0.0,0.015,0.002133
14,NEUROG3 OE MOUSE GSE3653 CREEDSID GENE 2290 DOWN,-2.006726,0.0,0.02,0.002688
15,TCF21 SIRNA HCASMC HUMAN GSE44461 RNASEQ UP,-2.005579,0.0,0.021,0.002594
16,PPARG OE MOUSE GSE2192 CREEDSID GENE 863 DOWN,-1.994479,0.0,0.025,0.002828
17,IRF1 OE MOUSE GSE6505 CREEDSID GENE 2076 DOWN,-1.978448,0.0,0.035,0.003714
18,FOXQ1 SIRNA BT549 HUMAN GSE79586 RNASEQ UP,-1.974513,0.0,0.038,0.003757
19,FOXF2 OE HUVEC HUMAN GSE79306 RNASEQ DOWN,-1.953526,0.0,0.051,0.00483
20,PAX2 SIRNA REP HUMAN GSE59781 RNASEQ UP,-1.943633,0.0,0.054,0.004806
21,PPARG OE MOUSE GSE2192 CREEDSID GENE 865 DOWN,-1.942313,0.0,0.056,0.004707
22,SP3 DEFICIENCY MOUSE GSE9124 CREEDSID GENE 637 UP,-1.93001,0.0,0.063,0.004985

These results suggest that the control pathway has low Ovol2 activity, which is consistent with high Ovol1 activity as Ovol1 downregulates Ovol2.

## Compare day 12 control with day 4 control

In [68]:
# Compare day 12 control with day 4 control
scanpy.tl.rank_genes_groups(
    adata,
    groupby="macrostate",
    method="wilcoxon",
    use_raw=False,
    reference="Day 4 Control",
    key_added="macrostate_vs_control_rank_genes"
)
dead_end_vs_control_rank_df = scanpy.get.rank_genes_groups_df(
    adata,
    group="Day 12 Control",
    key="macrostate_vs_control_rank_genes"
)
dead_end_vs_control_rank_df.index = dead_end_vs_control_rank_df["names"]
dead_end_vs_control_rank_df = dead_end_vs_control_rank_df.drop(columns="names")
dead_end_vs_control_rank_df.head(30)

                  scores  logfoldchanges          pvals      pvals_adj
names
2410006H16Rik  26.126083        2.549994  1.843133e-150  3.686265e-147
Zfas1          25.591373        2.887306  1.903077e-144  1.903077e-141
1110038B12Rik  25.104904        2.706954  4.396385e-139  2.930924e-136
Snhg1          24.437115        2.785392  6.898948e-132  3.449474e-129
Gas5           24.352331        1.764712  5.476893e-131  2.190757e-128
Snhg12         24.150040        3.244454  7.459324e-129  2.486441e-126
Ppp1r15a       21.102528        2.884851   7.539659e-99   1.507932e-96
Sqstm1         19.848444        2.438090   1.136654e-87   1.623791e-85
Cstb           19.777744        1.662232   4.629430e-87   6.172574e-85
Rps18          19.569803        0.519270   2.797598e-85   3.496997e-83
Ifrd1          19.545010        2.051183   4.549128e-85   5.351915e-83
Bbc3           19.291471        2.545764   6.334500e-83   7.038333e-81
Aqp3           19.283178        3.667204   7.436396e-83   7.827785e-81
Cdkn1a         19.278427        1.397393   8.151741e-83   8.151741e-81
Zfand5         18.958574        2.441425   3.751751e-80   3.262393e-78
Gabarap        18.629305        1.253917   1.859251e-77   1.549376e-75
Ahnak2         18.060299        2.188858   6.546684e-73   4.849396e-71
Atf3           17.293951        4.182650   5.224525e-67   3.483017e-65
Rassf1         17.226147        1.868825   1.690456e-66   1.090617e-64
Ddit3          15.975071        3.221851   1.906363e-57   9.776220e-56
Btg1           15.888432        2.660064   7.621059e-57   3.810530e-55
5430416N02Rik  15.588060        2.431265   8.775829e-55   3.815578e-53
1810032O08Rik  15.483035        3.059274   4.516496e-54   1.921913e-52
Tmem43         15.396733        1.651869   1.721496e-53   7.172898e-52
Cxcl16         14.973992        3.142614   1.086017e-50   4.098178e-49
Maff           14.538376        3.518187   6.921518e-48   2.307173e-46
Mdm2           14.519401        1.977894   9.130484e-48   2.993601e-46
Btg2           14.483277        1.957621   1.545485e-47   4.985435e-46
Renbp          14.397650        2.673156   5.353311e-47   1.699464e-45
Impact         14.345840        1.213049   1.131217e-46   3.535054e-45

In [69]:
# Most upregulated transcription factors in dead end

dead_end_vs_control_rank_df.loc[numpy.intersect1d(tf_array, adata.var_names)].sort_values("scores", ascending=False).head(30)

            scores  logfoldchanges         pvals     pvals_adj
names
Atf3     17.293951        4.182650  5.224525e-67  3.483017e-65
Ddit3    15.975071        3.221851  1.906363e-57  9.776220e-56
Maff     14.538376        3.518187  6.921518e-48  2.307173e-46
Crebrf   11.278059        3.426975  1.684214e-29  2.716475e-28
Zbtb10    9.688887        2.093428  3.361729e-22  3.954976e-21
Junb      9.540514        1.198861  1.421259e-21  1.615067e-20
Arid3a    9.539727        1.519866  1.432088e-21  1.618178e-20
Klf6      9.515185        1.901875  1.813887e-21  2.026689e-20
Klf4      9.149061        1.463191  5.743040e-20  5.771900e-19
Klf10     9.013310        1.398984  1.999277e-19  1.941046e-18
Bhlhe40   8.519645        2.346466  1.600439e-17  1.428963e-16
Rora      7.284762        4.426298  3.222391e-13  2.237771e-12
Ovol1     6.053084        1.239698  1.420988e-09  7.722761e-09
Myc       5.996467        0.733084  2.016562e-09  1.084173e-08
Fosl2     5.336549        1.440460  9.473203e-08  4.479056e-07
Zfp750    4.971072        2.548014  6.658383e-07  2.876191e-06
Hes1      4.402319        1.008520  1.070997e-05  4.119218e-05
Pax8      3.837615        6.719035  1.242349e-04  4.240098e-04
Atf5      3.776979        0.706474  1.587422e-04  5.335873e-04
Zfhx3     3.443773        0.264773  5.736570e-04  1.776028e-03
Esrrb     3.351118        1.652081  8.048614e-04  2.431852e-03
Klf5      3.304284        1.015113  9.521941e-04  2.825502e-03
Barx2     3.283594        1.221190  1.024926e-03  3.020433e-03
Rest      3.244519        0.294803  1.176493e-03  3.435017e-03
Zbtb7c    3.167943        0.454898  1.535217e-03  4.405213e-03
Smad7     3.135474        0.802623  1.715766e-03  4.881269e-03
Tfap2c    3.030702        1.276647  2.439856e-03  6.767977e-03
Zfp296    2.880306        0.636075  3.972896e-03  1.065119e-02
Gata2     2.626909        1.461320  8.616446e-03  2.189694e-02
Zbtb20    2.501334        1.250793  1.237263e-02  3.062531e-02

Top 4 TFs are all involved in stress responses

In [70]:
# Most downregulated transcription factors in dead end

dead_end_vs_control_rank_df.loc[numpy.intersect1d(tf_array, adata.var_names)].sort_values("scores", ascending=True).head(30)

             scores  logfoldchanges         pvals     pvals_adj
names
Cenpa    -18.378662       -2.361419  1.947120e-75  1.557696e-73
Hmgb3    -14.654617       -2.041724  1.258640e-48  4.266575e-47
Hmgb2    -11.795198       -1.436325  4.132265e-32  7.313744e-31
Id2       -8.479613       -1.096260  2.259429e-17  1.990686e-16
Tlx2      -8.452542       -1.106642  2.850273e-17  2.500239e-16
Prrx1     -8.317663       -2.595609  8.971450e-17  7.700815e-16
Mis18bp1  -7.335813       -1.151761  2.203806e-13  1.541123e-12
Terf1     -7.233290       -0.849773  4.714325e-13  3.217969e-12
Zfhx4     -6.941576       -1.290629  3.877483e-12  2.493558e-11
Nfib      -6.733551       -1.549937  1.655713e-11  1.025209e-10
Twist2    -6.236287       -1.747624  4.480797e-10  2.524393e-09
Twist1    -6.073015       -1.395535  1.255308e-09  6.878397e-09
Nfia      -5.823525       -1.717294  5.761910e-09  3.024625e-08
Hmga2     -5.701999       -0.597955  1.184104e-08  6.119400e-08
Nfix      -5.622528       -1.842449  1.881831e-08  9.456439e-08
Dmrtc2    -5.308241       -0.692599  1.106881e-07  5.196625e-07
Egr1      -4.994685       -0.494330  5.893177e-07  2.556693e-06
Prrx2     -4.883111       -4.057743  1.044252e-06  4.443625e-06
Lin28a    -4.755962       -0.766256  1.975033e-06  8.263735e-06
Nr2f2     -4.538492       -0.862550  5.665803e-06  2.252804e-05
Zbtb32    -4.537395       -0.606537  5.695328e-06  2.260051e-05
Jarid2    -4.346265       -0.551580  1.384752e-05  5.255225e-05
Zfp42     -4.107964       -0.588239  3.991626e-05  1.441020e-04
Tcf7l1    -4.097703       -0.527595  4.172700e-05  1.498276e-04
Id3       -3.595407       -1.702959  3.238854e-04  1.043109e-03
Tcf4      -3.255257       -0.346625  1.132897e-03  3.317414e-03
Hoxa10    -3.076693       -0.730383  2.093108e-03  5.879518e-03
Cdc5l     -3.058645       -0.335620  2.223402e-03  6.201959e-03
Nanog     -3.039586       -1.175820  2.369038e-03  6.589814e-03
Tshz1     -2.806822       -0.209857  5.003283e-03  1.323620e-02

In [71]:
dead_end_vs_control_rank_df.loc[genes_of_interest].sort_values("scores", ascending=False)

          scores  logfoldchanges         pvals     pvals_adj
names
Klf4    9.149061        1.463191  5.743040e-20  5.771900e-19
Ovol1   6.053084        1.239698  1.420988e-09  7.722761e-09
Myc     5.996467        0.733084  2.016562e-09  1.084173e-08
Rest    3.244519        0.294803  1.176493e-03  3.435017e-03
Zbtb7c  3.167943        0.454898  1.535217e-03  4.405213e-03
Hic2    1.094972        0.462989  2.735291e-01  4.687730e-01
Tcf7l1 -4.097703       -0.527595  4.172700e-05  1.498276e-04
Zfp42  -4.107964       -0.588239  3.991626e-05  1.441020e-04
Jarid2 -4.346265       -0.551580  1.384752e-05  5.255225e-05
Tlx2   -8.452542       -1.106642  2.850273e-17  2.500239e-16

The dead end state is signified by high expression of Klf4, Myc and Ovol1.

Tlx2 is downregulated in the dead end, suggesting it does not bring cells into the dead end. It could just be correlated with the control pathway.

In [72]:
# Cell types in the dead end

pre_res = gseapy.prerank(
    rnk=dead_end_vs_control_rank_df[["scores"]],
    gene_sets="PanglaoDB_Augmented_2021",
    threads=32,
    min_size=5,
    max_size=1000
)
pre_res.res2d.sort_values("NES", ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]

2026-03-06 08:16:19,628 [WARNING] Duplicated values found in preranked stats: 9.00% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

                                Term       NES NOM p-val FWER p-val FDR q-val
0           Mammary Epithelial Cells  2.032868       0.0        0.0       0.0
1                    Principal Cells  1.998692       0.0        0.0       0.0
2           Luminal Epithelial Cells  1.976177       0.0      0.003  0.001648
3                        Trichocytes  1.862625  0.003597      0.028  0.010508
4                Gastric Chief Cells  1.796434       0.0      0.062  0.018296
6                          Sebocytes  1.740809  0.009375       0.12  0.030699
8                     Cholangiocytes  1.672694  0.006515      0.229   0.05563
9                      Keratinocytes  1.635431  0.003597      0.303  0.071855
10           Airway Epithelial Cells  1.616102   0.02029      0.363  0.079118
11                          Nuocytes  1.613408  0.035294       0.37  0.072689
16                Trigeminal Neurons   1.56428  0.026756      0.502   0.10092
17                 Trophoblast Cells  1.563283  0.004049      0.504  0.093231
18                      Goblet Cells   1.55871   0.01791      0.518  0.089483
24             Salivary Mucous Cells  1.533442  0.007326      0.601  0.102871
29  Pulmonary Alveolar Type II Cells  1.494898  0.029304      0.707  0.132522
30                   Transient Cells  1.492463  0.047923      0.711   0.12648
32                      Ductal Cells  1.490957  0.007067       0.72  0.120494
33                   Microfold Cells   1.49048  0.020619       0.72  0.114487
34                       Clara Cells  1.489686  0.046784      0.721  0.109177
40                     Spermatocytes  1.468681  0.069333      0.768   0.12084

In [73]:
# MSig Hallmarks

pre_res = gseapy.prerank(
    rnk=dead_end_vs_control_rank_df[["scores"]], 
    gene_sets="MSigDB_Hallmark_2020",
    threads=32,
    min_size=5,
    max_size=1000
)
pre_res.res2d.sort_values("NES", ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]

2026-03-06 08:16:19,865 [WARNING] Duplicated values found in preranked stats: 9.00% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

                             Term       NES NOM p-val FWER p-val FDR q-val
0   TNF-alpha Signaling via NF-kB   2.23291       0.0        0.0       0.0
1                     p53 Pathway  2.080421       0.0        0.0       0.0
4                         Hypoxia  1.837935       0.0       0.01  0.005158
7                  UV Response Up  1.595374       0.0      0.175  0.075826
11      Unfolded Protein Response  1.436948  0.081301      0.477   0.21974
13               mTORC1 Signaling  1.398681  0.035484      0.576  0.239599
16             TGF-beta Signaling  1.300711  0.137931      0.792   0.37095
20        Estrogen Response Early   1.19468  0.152941      0.928  0.550124
21              Protein Secretion   1.17724  0.271186      0.936  0.531985
22       IL-6/JAK/STAT3 Signaling  1.161149  0.194529      0.945  0.512521
24                      Apoptosis  1.140574  0.173554      0.962  0.512774
25           IL-2/STAT5 Signaling  1.139142  0.182482      0.962  0.473525
29              Androgen Response  1.080247  0.312903      0.985  0.563516
31          Inflammatory Response  1.059484  0.293893      0.991  0.571347
32                     Myogenesis   1.05333  0.322709      0.992  0.548113
33        Cholesterol Homeostasis  0.992787  0.435583      0.999  0.656223
34              KRAS Signaling Dn  0.989549  0.468531      0.999  0.626633
36                heme Metabolism  0.976948  0.462264      0.999  0.618643
39                   Adipogenesis   0.95096  0.544484      0.999  0.645782
41                 Apical Surface  0.891274  0.579104      0.999  0.750831

In [74]:
# GO biological process

pre_res = gseapy.prerank(
    rnk=dead_end_vs_control_rank_df[["scores"]], 
    gene_sets="GO_Biological_Process_2025",
    threads=32,
    min_size=5,
    max_size=1000
)
pre_res.res2d.sort_values("NES", ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]

2026-03-06 08:16:19,964 [WARNING] Duplicated values found in preranked stats: 9.00% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

,Term,NES,NOM p-val,FWER p-val,FDR q-val
0,Regulation of JNK Cascade (GO:0046328),1.805935,0.0,0.323,0.486163
1,Response to Endoplasmic Reticulum Stress (GO:0...,1.799198,0.003125,0.351,0.273211
2,Positive Regulation of JNK Cascade (GO:0046330),1.792325,0.0,0.382,0.202908
6,Macroautophagy (GO:0016236),1.670805,0.010929,0.913,0.949601
7,Anterograde Trans-Synaptic Signaling (GO:0098916),1.66677,0.012698,0.922,0.800535
8,Regulation of Translation (GO:0006417),1.651243,0.012012,0.959,0.820315
9,Positive Regulation of Granulocyte Chemotaxis ...,1.648447,0.010724,0.964,0.732454
10,Integrated Stress Response Signaling (GO:0140467),1.644288,0.002681,0.966,0.674985
13,Immunoglobulin Mediated Immune Response (GO:00...,1.632127,0.005602,0.977,0.697809
17,T Cell Chemotaxis (GO:0010818),1.615536,0.010724,0.984,0.766932
18,Regulation of Autophagy (GO:0010506),1.607687,0.012085,0.991,0.765549
20,Lymphocyte Chemotaxis (GO:0048247),1.598341,0.013405,0.994,0.788738
21,Regulation of Translational Initiation (GO:000...,1.592448,0.005495,0.995,0.778191
23,Regulation of Cytokine Production Involved in ...,1.588977,0.01983,0.995,0.751203
24,Positive Regulation of Neuron Apoptotic Proces...,1.587902,0.007874,0.995,0.709498
26,Chemical Synaptic Transmission (GO:0007268),1.576868,0.028662,0.999,0.752352
29,Autophagy of Mitochondrion (GO:0000422),1.564415,0.039106,0.999,0.806747
30,Regulation of Catabolic Process (GO:0009894),1.550644,0.042017,1.0,0.874219
31,Negative Regulation of Intracellular Signal Tr...,1.544512,0.0,1.0,0.880351
32,Positive Regulation of Intrinsic Apoptotic Sig...,1.540625,0.031977,1.0,0.863858

All the top terms are related to damage and stress signaling.

In [75]:
# ENCODE ChIP-Seq
pre_res = gseapy.prerank(
    rnk=dead_end_vs_control_rank_df[["scores"]], 
    gene_sets="ENCODE_TF_ChIP-seq_2015",
    threads=32,
    min_size=5,
    max_size=1000
)
pre_res.res2d.sort_values("NES", ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]

2026-03-06 08:16:21,105 [WARNING] Duplicated values found in preranked stats: 9.00% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

                    Term       NES NOM p-val FWER p-val FDR q-val
2       FOSL2 HepG2 hg19  1.845511       0.0      0.032  0.049575
5        MAX myocyte mm9  1.794046       0.0      0.061  0.048158
6         PML MCF-7 hg19  1.772045  0.003846      0.083  0.042493
7       NR2F2 MCF-7 hg19  1.756168       0.0      0.096  0.038952
10       TAF1 MCF-7 hg19  1.739986       0.0      0.117  0.039093
11      NR3C1 ECC-1 hg19  1.739029  0.003484      0.117  0.032814
14        NFE2 K562 hg19  1.696168  0.009009      0.193  0.046944
15        USF1 K562 hg19  1.691845       0.0      0.198  0.042316
16      YY1 GM12891 hg19    1.6876  0.007117       0.21  0.039975
17       MEF2A K562 hg19  1.660891  0.003185      0.265  0.047308
23       RXRA HepG2 hg19  1.611333  0.003802      0.386  0.069147
24       USF1 HepG2 hg19  1.609797       0.0       0.39  0.063857
28      ZNF274 K562 hg19  1.579873  0.013746      0.467  0.079538
37       REST HepG2 hg19  1.507851  0.003953      0.667  0.140125
41       JUND MCF-7 hg19   1.49622  0.032258      0.706  0.147213
42    CEBPB GM12878 hg19  1.488604  0.026515      0.734  0.147573
43     CEBPB myocyte mm9  1.486338  0.011407      0.745  0.141726
45  eGFP-HDAC8 K562 hg19  1.472124  0.013333      0.779  0.150141
47       JUND HepG2 hg19  1.470481       0.0      0.784  0.144251
49     NFE2 GM12878 hg19  1.467246  0.004505      0.794   0.14143

In [76]:
# Chsea
pre_res = gseapy.prerank(
    rnk=dead_end_vs_control_rank_df[["scores"]], 
    gene_sets="ChEA_2022",
    threads=32,
    min_size=5,
    max_size=1000
)
pre_res.res2d.sort_values("NES", ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]

2026-03-06 08:16:22,387 [WARNING] Duplicated values found in preranked stats: 9.00% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

,Term,NES,NOM p-val,FWER p-val,FDR q-val
2,FOXA1 33576154 ChIP-Seq Human HilarLN Prostate...,1.891787,0.0,0.013,0.01714
4,RELB 30642670 ChIP-Seq CTB1 Human Placenta Inf...,1.788053,0.003236,0.068,0.046145
6,TP63 17297297 ChIP-ChIP HaCaT Human,1.713096,0.003115,0.151,0.073832
8,NOTCH1 21737748 ChIP-Seq TLL Human,1.6068,0.018237,0.396,0.177659
9,PKCTHETA 26484144 Chip-Seq BREAST Human,1.601674,0.003676,0.414,0.150038
10,FOXA1 26457646 ChIP-Seq LHSAR Human ProstateCa...,1.591983,0.0,0.446,0.137337
11,FOXO1 32281255 ChIP-Seq Chondrocytes Human Ost...,1.590245,0.0,0.451,0.119036
12,MEIS1 20887958 ChIP-Seq HPC-7 Mouse,1.577726,0.0,0.489,0.116681
13,NUCKS1 24931609 ChIP-Seq HEPATOCYTES Mouse,1.572461,0.0,0.506,0.10899
14,BRD4 28847988 ChIP-Seq BCBL1 Human Blood Lymphoma,1.561826,0.019231,0.54,0.109166
16,KLF4 18264089 ChIP-ChIP MESCs Mouse,1.533513,0.022876,0.634,0.109024
15,KLF5 18264089 ChIP-ChIP MESCs Mouse,1.533513,0.022876,0.634,0.109024
17,KLF2 18264089 ChIP-ChIP MESCs Mouse,1.533513,0.022876,0.634,0.109024
18,HIF1A 21447827 ChIP-Seq MCF-7 Human,1.5248,0.007042,0.662,0.109807
22,TAF7L 23326641 ChIP-Seq C3H10T1-2 Mouse,1.500995,0.004132,0.733,0.126042
23,HNF4A 19761587 ChIP-ChIP CACO-2 Human,1.491879,0.013636,0.753,0.126322
25,FOXO3 23340844 ChIP-Seq DLD1 Human,1.47494,0.009709,0.8,0.135721
30,FOXA1 33576154 ChIP-Seq Human Liver ProstateCa...,1.45602,0.0,0.845,0.14825
33,CREB1 20920259 ChIP-Seq GC1-SPG Mouse,1.447992,0.0,0.86,0.149122
36,HCFC1 20581084 ChIP-Seq MESCs Mouse,1.442488,0.074405,0.874,0.148521

In [77]:
# TF perturbation
pre_res = gseapy.prerank(
    rnk=dead_end_vs_control_rank_df[["scores"]], 
    gene_sets="TF_Perturbations_Followed_by_Expression",
    threads=32,
    min_size=5,
    max_size=1000
)
pre_res.res2d.sort_values("NES", ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]

2026-03-06 08:16:23,610 [WARNING] Duplicated values found in preranked stats: 9.00% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

,Term,NES,NOM p-val,FWER p-val,FDR q-val
2,GLI1 INHIBITION HUMAN GSE36855 CREEDSID GENE 6...,2.180205,0.0,0.0,0.0
20,FOXO1 KD MOUSE GSE6623 CREEDSID GENE 505 DOWN,1.988647,0.0,0.016,0.00618
29,SOX4 KD HUMAN GSE4225 CREEDSID GENE 64 UP,1.91645,0.0,0.061,0.016738
45,NFKB1 INACTIVATION HUMAN GSE20667 CREEDSID GEN...,1.857504,0.003115,0.132,0.02839
54,HEY2 KO MOUSE GSE6526 CREEDSID GENE 1511 UP,1.825931,0.0,0.204,0.031029
55,HEY2 KO MOUSE GSE6526 CREEDSID GENE 1512 DOWN,1.825931,0.0,0.204,0.031029
56,ZXDC DEPLET MOUSE GSE45417 CREEDSID GENE 1257 UP,1.819913,0.0,0.216,0.028693
62,PLAGL2 DEFICIENCY MOUSE GSE9123 CREEDSID GENE ...,1.806016,0.0,0.249,0.029838
79,CEBPA KO MOUSE GSE61468 CREEDSID GENE 1476 UP,1.775358,0.0,0.362,0.041458
82,ARID3B KO MOUSE GSE62069 CREEDSID GENE 2591 UP,1.772634,0.0,0.372,0.038703
99,TFEB OE HUMAN GSE16267 CREEDSID GENE 2976 UP,1.741278,0.0,0.473,0.050424
122,AIRE KO MOUSE GSE2585 CREEDSID GENE 272 UP,1.711396,0.0,0.585,0.066822
133,TCF7 KO MOUSE GSE20754 CREEDSID GENE 3010 DOWN,1.696387,0.0,0.625,0.070892
153,ARID3A KD MOUSE GSE56853 CREEDSID GENE 1337 UP,1.678154,0.0,0.698,0.079623
168,XBP1 KO MOUSE GSE52857 CREEDSID GENE 2765 UP,1.665491,0.0,0.726,0.084049
170,STAT3 ACTVATION MOUSE GSE21060 CREEDSID GENE 3...,1.661736,0.020958,0.74,0.081644
172,KCNIP3 KO MOUSE GSE16874 CREEDSID GENE 1030 DOWN,1.65977,0.003115,0.749,0.078887
177,SNAI1 OE HUMAN GSE14773 CREEDSID GENE 371 UP,1.653929,0.0,0.768,0.079568
182,KLF15 KO MOUSE GSE53231 CREEDSID GENE 446 UP,1.643062,0.004115,0.811,0.085626
201,SPDEF KD HUMAN GSE48928 CREEDSID GENE 2897 UP,1.622283,0.0,0.85,0.100001

## Other macrostates

### MEF

In [17]:
mef_rank_df = scanpy.get.rank_genes_groups_df(
    adata,
    key="macrostate_rank_genes",
    group="MEF"
)
mef_rank_df.index = mef_rank_df["names"]
mef_rank_df = mef_rank_df.drop(columns="names")

In [21]:
mef_rank_df.loc[numpy.intersect1d(target_tfs, adata.var_names)].sort_values("scores", ascending=False).head(20)

            scores  logfoldchanges          pvals      pvals_adj
names
Tcf4     22.032331        3.015500  1.411167e-107  1.512375e-105
Prrx1    19.597130        3.227617   1.635962e-85   4.674177e-84
Snai2    18.127380        3.744907   1.937707e-73   3.429570e-72
Atf5     17.698309        2.213542   4.320908e-70   6.647551e-69
Creb3l1  17.047623        2.918983   3.640356e-65   4.919400e-64
Twist1   16.896849        2.630791   4.746084e-64   6.286205e-63
Ddit3    15.490962        2.365666   3.992722e-54   3.784570e-53
Nfix     14.685015        2.538224   8.041650e-49   6.185884e-48
Id3      13.723390        2.272552   7.354487e-43   4.699353e-42
Zmiz1    13.674485        2.083391   1.442250e-42   9.099371e-42
Setbp1   13.279610        2.915771   3.039739e-40   1.831168e-39
Creb3l2  12.761719        1.930926   2.682178e-37   1.515355e-36
Zfhx3    12.196051        1.263510   3.262684e-34   1.681796e-33
Fosl2    12.185386        2.234346   3.718912e-34   1.912037e-33
Tsc22d1  12.169586        1.378011   4.513643e-34   2.314689e-33
Klf7     11.410269        1.929325   3.715790e-30   1.716300e-29
Nfil3    11.391047        2.737674   4.633864e-30   2.135421e-29
Tshz1    10.697692        1.663293   1.043450e-26   4.468735e-26
Zfp36l1  10.373015        1.225048   3.289767e-25   1.365048e-24
Lhx9      9.770912        4.013871   1.500952e-22   5.840282e-22

In [22]:
mef_rank_df.loc[genes_of_interest].sort_values("scores", ascending=False).head(20)

           scores  logfoldchanges         pvals     pvals_adj
names
Rest     0.831551        0.005710  4.056624e-01  5.154542e-01
Tcf7l1  -2.511146       -0.392221  1.203400e-02  1.904113e-02
Ovol1   -4.395990      -27.196196  1.102691e-05  2.184011e-05
Klf4    -4.772457       -1.034347  1.819917e-06  3.775761e-06
Myc     -5.386568       -1.016510  7.181592e-08  1.597685e-07
Tlx2    -6.352568       -7.615314  2.117498e-10  5.429482e-10
Zbtb7c  -7.334432       -3.338338  2.226635e-13  6.520161e-13
Hic2    -8.569461       -2.538984  1.039707e-17  3.494815e-17
Jarid2 -10.025214       -2.096941  1.181037e-23  4.752662e-23
Cdh1   -10.808813       -4.300139  3.126910e-27  1.347806e-26
Zfp42  -12.810161       -4.415439  1.438359e-37  8.195778e-37

In [49]:
# Cell types

pre_res = gseapy.prerank(
    rnk=mef_rank_df[["scores"]], 
    gene_sets="PanglaoDB_Augmented_2021",
    threads=32,
    min_size=5,
    max_size=1000
)
pre_res.res2d.sort_values("NES", ascending=False).head(20)

2026-03-09 13:51:09,658 [WARNING] Duplicated values found in preranked stats: 2.20% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

,Name,Term,ES,NES,NOM p-val,FDR q-val,FWER p-val,Tag %,Gene %,Lead_genes
4,prerank,Airway Smooth Muscle Cells,0.746741,2.232371,0.0,0.0,0.0,46/72,15.75%,Col12a1;Col5a2;Col3a1;Col5a1;Col1a1;Col1a2;Bgn...
5,prerank,Osteoblasts,0.712196,2.219959,0.0,0.0,0.0,73/100,26.35%,Col12a1;Col5a2;Col3a1;Col5a1;Col1a1;Col1a2;Bgn...
6,prerank,Myofibroblasts,0.738854,2.210997,0.0,0.0,0.0,46/73,15.65%,Col12a1;Col5a2;Col3a1;Col5a1;Col1a1;Col1a2;Bgn...
8,prerank,Pancreatic Stellate Cells,0.722599,2.185598,0.0,0.0,0.0,50/82,14.35%,Col12a1;Col5a2;Col3a1;Col5a1;Col1a1;Col1a2;Bgn...
10,prerank,Chondrocytes,0.703991,2.154509,0.0,0.0,0.0,53/94,16.50%,Col12a1;Col5a2;Col3a1;Col5a1;Col1a1;Col1a2;Bgn...
12,prerank,Hepatic Stellate Cells,0.701484,2.128608,0.0,0.0,0.0,47/84,15.65%,Col12a1;Col5a2;Col3a1;Col5a1;Col1a1;Col1a2;Bgn...
13,prerank,Mesangial Cells,0.686661,2.128004,0.0,0.0,0.0,60/100,21.40%,Col12a1;Col5a2;Col3a1;Col5a1;Col1a1;Col1a2;Bgn...
14,prerank,Myoblasts,0.710322,2.124545,0.0,0.0,0.0,37/61,18.70%,Col12a1;Col5a2;Col3a1;Col5a1;Col1a1;Col1a2;Bgn...
15,prerank,Vascular Smooth Muscle Cells,0.699649,2.097212,0.0,0.0,0.0,53/72,25.00%,Col12a1;Col5a2;Col3a1;Col5a1;Col1a1;Col1a2;Bgn...
16,prerank,Smooth Muscle Cells,0.681828,2.091595,0.0,0.0,0.0,51/92,19.40%,Col12a1;Col5a2;Col3a1;Col5a1;Col1a1;Col1a2;Bgn...
17,prerank,Pulmonary Vascular Smooth Muscle Cells,0.708876,2.089261,0.0,0.0,0.0,40/68,15.65%,Col5a2;Col3a1;Col5a1;Col1a1;Col1a2;Bgn;Mfap4;F...
18,prerank,Peritubular Myoid Cells,0.695378,2.081001,0.0,0.0,0.0,36/70,14.05%,Col12a1;Col5a2;Col3a1;Col1a1;Col1a2;Bgn;Mfap4;...
19,prerank,Fibroblasts,0.651928,2.078407,0.0,0.0,0.0,91/145,26.90%,Cthrc1;Col12a1;Col5a2;Col3a1;Col5a1;Col1a1;Col...
20,prerank,Melanocytes,0.690924,2.038382,0.0,0.0,0.0,48/62,22.75%,Col12a1;Col5a2;Col1a1;Fstl1;Tnc;Col6a1;Ccdc80;...
21,prerank,Juxtaglomerular Cells,0.683148,2.03822,0.0,0.0,0.0,33/66,14.45%,Col12a1;Col3a1;Col1a1;Col1a2;Bgn;Mfap4;Aspn;Tp...
22,prerank,Stromal Cells,0.669593,2.036129,0.0,0.0,0.0,60/89,26.90%,Col5a2;Col3a1;Col5a1;Col1a1;Col1a2;Bgn;Mfap4;F...
25,prerank,Osteocytes,0.691112,1.997651,0.0,0.0,0.0,31/52,19.15%,Col1a1;Fstl1;Mfap2;Tnc;Serpinh1;Tpm1;Cdh11;Lox...
27,prerank,Pericytes,0.649605,1.99094,0.0,0.0,0.0,37/88,15.65%,Col5a2;Col3a1;Col1a1;Col1a2;Bgn;Mfap4;Fstl1;Sp...
28,prerank,Endothelial Cells (Aorta),0.635739,1.979196,0.0,0.0,0.0,45/88,21.25%,Col12a1;Col5a2;Col3a1;Col5a1;Col1a1;Col1a2;Bgn...
31,prerank,Müller Cells,0.641792,1.924714,0.0,0.000119,0.003,30/75,15.35%,Col3a1;Col5a1;Col1a1;Col1a2;Bgn;Fstl1;Sparc;Co...

### Day 2 control

In [27]:
early_rank_df = scanpy.get.rank_genes_groups_df(
    adata,
    key="macrostate_rank_genes",
    group="Day 2 Control"
)
early_rank_df.index = early_rank_df["names"]
early_rank_df = early_rank_df.drop(columns="names")

In [34]:
early_rank_df.loc[genes_of_interest].sort_values("scores", ascending=False).head(20)

           scores  logfoldchanges          pvals      pvals_adj
names
Tcf7l1  -5.049325       -0.307710   4.433749e-07   6.333927e-07
Rest    -9.274354       -0.426103   1.786991e-20   3.086340e-20
Klf4   -10.298006       -0.637572   7.193706e-25   1.296163e-24
Ovol1  -15.122104       -4.998144   1.157831e-51   2.570101e-51
Tlx2   -21.331772       -4.334157  5.758435e-101  1.683753e-100
Zbtb7c -22.501848       -2.530346  3.981161e-112  1.230653e-111
Myc    -23.374834       -1.289301  7.706647e-121  2.506227e-120
Hic2   -25.126188       -1.832231  2.573806e-139  8.999320e-139
Cdh1   -38.846001       -4.595285   0.000000e+00   0.000000e+00
Jarid2 -39.582317       -2.643583   0.000000e+00   0.000000e+00
Zfp42  -44.694649       -4.516070   0.000000e+00   0.000000e+00

In [50]:
# Cell types

pre_res = gseapy.prerank(
    rnk=early_rank_df[["scores"]], 
    gene_sets="PanglaoDB_Augmented_2021",
    threads=32,
    min_size=5,
    max_size=1000
)
pre_res.res2d.sort_values("NES", ascending=False).head(20)

2026-03-09 13:52:18,493 [WARNING] Duplicated values found in preranked stats: 0.10% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

,Name,Term,ES,NES,NOM p-val,FDR q-val,FWER p-val,Tag %,Gene %,Lead_genes
5,prerank,Myoblasts,0.72998,2.200489,0.0,0.0,0.0,45/61,22.25%,Cald1;Col1a1;Col5a2;Col1a2;Tpm1;Fstl1;Tpm2;Col...
6,prerank,Airway Smooth Muscle Cells,0.721296,2.200083,0.0,0.0,0.0,42/72,13.70%,Cald1;Serpinh1;Col1a1;Igfbp7;Col5a2;Col1a2;Tpm...
7,prerank,Osteoblasts,0.687937,2.177178,0.0,0.0,0.0,67/100,25.10%,Cald1;Col1a1;Igfbp7;Sparc;Col5a2;Col1a2;Fstl1;...
8,prerank,Pancreatic Stellate Cells,0.695538,2.164514,0.0,0.0,0.0,52/82,20.80%,Cald1;Col1a1;Sparc;Col5a2;Col1a2;Fstl1;Lox;Col...
11,prerank,Hepatic Stellate Cells,0.684521,2.136636,0.0,0.0,0.0,53/84,22.60%,Cald1;Col1a1;Igfbp7;Sparc;Col5a2;Col1a2;Fstl1;...
12,prerank,Myofibroblasts,0.694664,2.129217,0.0,0.0,0.0,48/73,22.60%,Cald1;Col1a1;Sparc;Col5a2;Col1a2;Tpm1;Fstl1;Tp...
13,prerank,Mesangial Cells,0.673959,2.116045,0.0,0.0,0.0,57/100,20.80%,Cald1;Col1a1;Sparc;Col5a2;Col1a2;Tpm1;Fstl1;Tp...
15,prerank,Chondrocytes,0.669175,2.115248,0.0,0.0,0.0,56/94,22.60%,Cald1;Col1a1;Igfbp7;Sparc;Col5a2;Col1a2;Fstl1;...
16,prerank,Fibroblasts,0.649721,2.104909,0.0,0.0,0.0,86/145,25.15%,Serpinh1;Col1a1;Igfbp7;Sparc;Col5a2;Col1a2;Fst...
19,prerank,Smooth Muscle Cells,0.660003,2.07724,0.0,0.0,0.0,57/92,25.25%,Cald1;Col1a1;Col5a2;Col1a2;Tpm1;Fstl1;Lox;Tpm2...
20,prerank,Pulmonary Vascular Smooth Muscle Cells,0.687048,2.075672,0.0,0.0,0.0,44/68,22.60%,Cald1;Col1a1;Igfbp7;Sparc;Col5a2;Col1a2;Fstl1;...
21,prerank,Melanocytes,0.685551,2.070459,0.0,0.0,0.0,47/62,24.35%,Cald1;Col1a1;Col5a2;Fstl1;Lox;Prrx1;Fn1;Mmp14;...
22,prerank,Peritubular Myoid Cells,0.67614,2.067258,0.0,0.0,0.0,43/70,22.60%,Cald1;Col1a1;Col5a2;Col1a2;Tpm1;Fstl1;Tpm2;Col...
25,prerank,Stromal Cells,0.648597,2.021995,0.0,0.0,0.0,47/89,20.80%,Col1a1;Igfbp7;Sparc;Col5a2;Col1a2;Fstl1;Col3a1...
28,prerank,Vascular Smooth Muscle Cells,0.647311,1.978736,0.0,0.0,0.0,42/72,22.60%,Cald1;Col1a1;Sparc;Col5a2;Col1a2;Fstl1;Col3a1;...
29,prerank,Adipocyte Progenitor Cells,0.658039,1.970834,0.0,0.000046,0.001,35/61,21.20%,Cald1;Serpinh1;Col1a1;Col5a2;Fstl1;Gpx8;Lox;Co...
30,prerank,Endothelial Cells (Aorta),0.631427,1.968113,0.0,0.000043,0.001,50/88,23.00%,Cald1;Col1a1;Igfbp7;Col5a2;Col1a2;Fstl1;Lox;Co...
33,prerank,Osteocytes,0.668035,1.954427,0.0,0.000041,0.001,30/52,17.75%,Cald1;Serpinh1;Col1a1;Tpm1;Fstl1;Gpx8;Cdh11;Lo...
34,prerank,Juxtaglomerular Cells,0.639976,1.936699,0.0,0.000039,0.001,45/66,30.35%,Cald1;Col1a1;Col1a2;Tpm1;Col3a1;Cdh11;Tagln;Ac...
35,prerank,Adipocytes,0.620041,1.925119,0.0,0.000037,0.001,41/84,21.10%,Col1a1;Igfbp7;Col1a2;Lox;Col3a1;Tagln;Acta2;Bg...

Still fibroblasts

### Day 4 Hic2 OX

In [30]:
hic2_rank_df = scanpy.get.rank_genes_groups_df(
    adata,
    key="macrostate_rank_genes",
    group="Day 4 Hic2 OX"
)
hic2_rank_df.index = hic2_rank_df["names"]
hic2_rank_df = hic2_rank_df.drop(columns="names")

In [52]:
hic2_rank_df.sort_values("scores", ascending=False).head(20)

             scores  logfoldchanges          pvals      pvals_adj
names
Krt20     50.681782        3.986395   0.000000e+00   0.000000e+00
Krtdap    49.634972        3.220684   0.000000e+00   0.000000e+00
Hbb-y     48.800888        3.551641   0.000000e+00   0.000000e+00
Pfn1      42.958733        0.865490   0.000000e+00   0.000000e+00
Ggh       39.460499        1.800804   0.000000e+00   0.000000e+00
Isg15     38.423088        2.758160   0.000000e+00   0.000000e+00
Oasl2     37.218948        2.134203  3.369941e-303  9.628404e-301
Uchl1     35.828896        1.908738  3.920448e-281  8.712106e-279
Bex1      35.728615        1.729572  1.421534e-279  2.843068e-277
Tuba1a    35.263786        1.134071  2.109312e-272  3.835113e-270
Marcksl1  35.172199        1.239878  5.322164e-271  8.870274e-269
Lgals9    34.954041        1.564578  1.124292e-267  1.729679e-265
Tmem147   34.815212        1.018751  1.431785e-265  2.045407e-263
Esd       34.198318        1.057371  2.561234e-256  3.201543e-254
Dusp14    34.029152        1.758308  8.257530e-254  9.714741e-252
Mfap5     33.142529        1.797955  7.256562e-241  8.062847e-239
Abracl    32.430378        1.071150  1.024350e-230  1.024350e-228
Gsto1     32.367729        1.346160  7.812826e-230  7.440786e-228
Cd320     32.227909        1.377444  7.175797e-228  6.523452e-226
Cfl1      32.185848        0.518468  2.784799e-227  2.421564e-225

In [36]:
hic2_rank_df.loc[numpy.intersect1d(target_tfs, adata.var_names)].sort_values("scores", ascending=False).head(20)

            scores  logfoldchanges          pvals      pvals_adj
names
Msc      27.601393        2.815124  1.070682e-167  3.965488e-166
Fosl1    26.082756        1.788012  5.720943e-150  1.658244e-148
Id2      24.631092        1.344160  5.868540e-134  1.414106e-132
Hmga2    20.150198        0.812654   2.680445e-90   4.000663e-89
Hic2     15.447442        0.845011   7.849686e-54   5.793126e-53
Tcf7l2   13.495073        0.549340   1.671893e-41   9.777154e-41
Myc      13.462667        0.575639   2.593794e-41   1.503649e-40
Arid3a   10.510388        0.559938   7.737457e-26   3.076524e-25
Atf5      9.983627        0.333068   1.797723e-23   6.670587e-23
Zfp36l1   8.360637        0.325789   6.238091e-17   1.943330e-16
Stat2     8.321202        0.686201   8.707532e-17   2.687510e-16
Klf10     7.831338        0.337294   4.827034e-15   1.383104e-14
Tlx3      7.603967        1.704349   2.871882e-14   7.999672e-14
Twist1    4.385013        0.092688   1.159787e-05   2.262999e-05
Zfat      4.268746        0.737802   1.965751e-05   3.794886e-05
En1       4.056455        0.620159   4.982311e-05   9.463080e-05
Hoxa7     3.410014        0.180947   6.495945e-04   1.141642e-03
Zfhx3     2.912601        0.125180   3.584319e-03   5.880753e-03
Gata6     2.729004        0.319274   6.352602e-03   1.019679e-02
Fosb      2.252879        0.244342   2.426677e-02   3.619205e-02

In [33]:
hic2_rank_df.loc[genes_of_interest].sort_values("scores", ascending=False).head(20)

           scores  logfoldchanges          pvals      pvals_adj
names
Hic2    15.447442        0.845011   7.849686e-54   5.793126e-53
Myc     13.462667        0.575639   2.593794e-41   1.503649e-40
Zbtb7c  -0.098243       -0.222021   9.217393e-01   9.596453e-01
Tcf7l1  -4.097978       -0.321196   4.167752e-05   7.938576e-05
Klf4    -5.762605       -0.614489   8.282545e-09   1.880260e-08
Ovol1   -7.336517       -1.586220   2.192231e-13   5.893095e-13
Tlx2    -8.593602       -1.362809   8.428459e-18   2.705765e-17
Rest   -17.573996       -0.794881   3.897295e-69   3.916880e-68
Jarid2 -17.899170       -1.343034   1.196946e-71   1.266610e-70
Zfp42  -19.104193       -1.970869   2.330003e-81   3.106671e-80
Cdh1   -22.337255       -2.116000  1.606118e-110  3.118677e-109

In [ ]:
# Cell types

pre_res = gseapy.prerank(
    rnk=hic2_rank_df[["scores"]], 
    gene_sets="PanglaoDB_Augmented_2021",
    threads=32,
    min_size=5,
    max_size=1000
)
pre_res.res2d.sort_values("NES", ascending=False).head(20)

In [ ]:
# Cell types

pre_res = gseapy.prerank(
    rnk=hic2_rank_df[["scores"]], 
    gene_sets="PanglaoDB_Augmented_2021",
    threads=32,
    min_size=5,
    max_size=1000
)
pre_res.res2d.sort_values("NES", ascending=False).head(20)

2026-03-09 13:51:00,448 [WARNING] Duplicated values found in preranked stats: 0.80% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

,Name,Term,ES,NES,NOM p-val,FDR q-val,FWER p-val,Tag %,Gene %,Lead_genes
0,prerank,Kupffer Cells,0.683866,1.963881,0.0,0.010314,0.009,3/33,5.80%,Lgals9;Hck;Dok2
1,prerank,Osteoclast Precursor Cells,0.643053,1.80056,0.001996,0.059307,0.097,3/29,6.25%,Lgals9;Hck;Ifih1
2,prerank,Neutrophils,0.647191,1.794089,0.0,0.044007,0.108,4/27,5.80%,Mme;Hck;Hdc;Dok2
5,prerank,Alveolar Macrophages,0.595126,1.725795,0.0,0.06859,0.207,4/34,7.20%,Lgals9;Hck;Ifi30;Plet1
7,prerank,Monocytes,0.536578,1.674711,0.003738,0.094685,0.325,8/51,5.80%,Lgals9;Hck;Rgs2;Ifi30;Ifit1;Ly6e;Vcan;Dok2
9,prerank,Noradrenergic Neurons,0.828487,1.565582,0.029915,0.257169,0.666,5/6,14.55%,Ddc;Fetub;Rbp4;Dlk1;Ahsg
11,prerank,Eosinophils,0.541306,1.524645,0.026365,0.312227,0.777,2/25,5.80%,Hck;Dok2
12,prerank,Langerhans Cells,0.537416,1.494656,0.034413,0.349782,0.843,2/27,2.30%,Lgals9;Hck
13,prerank,Olfactory Epithelial Cells,0.558734,1.468446,0.044402,0.381054,0.89,8/22,11.90%,Dusp14;Rnf128;Pfn2;Fam81a;Abhd16a;Fetub;Atf5;H...
14,prerank,Decidual Cells,0.771674,1.455336,0.054622,0.378017,0.902,1/6,5.80%,Dok2
15,prerank,Macrophages,0.447395,1.448212,0.016698,0.360436,0.912,5/59,6.85%,Lgals9;Hck;Dok2;Lgals3;Ccl7
17,prerank,Myeloid-derived Suppressor Cells,0.518907,1.418921,0.065134,0.407069,0.953,2/25,5.80%,Hck;Dok2
19,prerank,Tuft Cells,0.524804,1.405581,0.065041,0.412729,0.965,3/24,2.65%,Lgals9;Hck;Rgs2
20,prerank,Dendritic Cells,0.446687,1.382767,0.050657,0.447123,0.974,6/48,6.20%,Lgals9;Hck;Vcan;Dok2;Lgals3;Anxa1
21,prerank,B Cells Naive,0.53515,1.378748,0.094862,0.427904,0.977,2/20,5.80%,Mme;Dok2
29,prerank,Neurons,0.4364,1.30831,0.104364,0.62008,0.999,7/42,12.65%,Bex1;Tubb3;Kcnk1;Nefh;Miat;Fbln2;Prph
30,prerank,Microglia,0.418636,1.307324,0.079848,0.587366,0.999,4/46,5.80%,Lgals9;Hck;Aldh1a2;Dok2
35,prerank,Oligodendrocytes,0.4633,1.276442,0.130859,0.662175,0.999,3/25,11.50%,Ddc;Plekhh1;Aspa
36,prerank,Microfold Cells,0.432199,1.266374,0.119318,0.6606,0.999,12/40,10.90%,Marcksl1;Anxa5;Fabp5;Ifi30;Gbp3;Lgals3;Cyba;If...
37,prerank,Enteric Neurons,0.46512,1.254229,0.1611,0.672386,0.999,4/26,11.75%,Map1b;Dmkn;Crmp1;Atf5

Interestingly, the Hic2 OX cells look like immune cells

In [53]:
# MSig Hallmarks in Hic2 OX pathway

pre_res = gseapy.prerank(
    rnk=hic2_rank_df[["scores"]], 
    gene_sets="MSigDB_Hallmark_2020",
    threads=32,
    min_size=5,
    max_size=1000
)
pre_res.res2d.sort_values("NES", ascending=False).head(20)

2026-03-09 13:58:02,613 [WARNING] Duplicated values found in preranked stats: 0.80% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

,Name,Term,ES,NES,NOM p-val,FDR q-val,FWER p-val,Tag %,Gene %,Lead_genes
0,prerank,Interferon Alpha Response,0.689688,2.044943,0.0,0.0,0.0,24/38,21.20%,Isg15;Ifi35;B2m;Ifi30;Rtp4;Rsad2;Ly6e;Lgals3bp...
1,prerank,Interferon Gamma Response,0.602988,1.968047,0.0,0.0,0.0,22/64,10.35%,Isg15;Xaf1;Zbp1;Psmb10;Ifi35;B2m;Ifi30;Rtp4;Rs...
2,prerank,E2F Targets,0.60779,1.703624,0.00611,0.023674,0.077,15/28,18.70%,Ccne1;Cdkn2a;Birc5;Rrm2;Cdkn1a;Pttg1;Myc;Aurka...
3,prerank,Fatty Acid Metabolism,0.617043,1.540223,0.037657,0.116965,0.406,6/17,16.15%,Mgll;Hsp90aa1;Cbr3;Eno3;Hmgcs1;Glul
4,prerank,mTORC1 Signaling,0.506861,1.499783,0.027613,0.129793,0.502,14/36,12.80%,Ppa1;Psph;Cth;Ifi30;Nupr1;Rrm2;Cdkn1a;Ctsc;Ifr...
5,prerank,Myc Targets V1,0.796374,1.448456,0.073922,0.157284,0.622,3/5,17.75%,Ifrd1;Myc;Cdc20
9,prerank,Inflammatory Response,0.416672,1.353401,0.055028,0.259104,0.846,19/60,17.90%,Rtp4;Ly6e;Cdkn1a;Atp2b1;Ccl7;Emp3;Gch1;Myc;Pla...
10,prerank,Cholesterol Homeostasis,0.503217,1.345944,0.099029,0.236814,0.858,10/24,15.45%,Clu;Anxa5;Fabp5;Lgals3;S100a11;Plaur;Atf5;Cd9;...
11,prerank,Complement,0.406522,1.303914,0.068898,0.273041,0.909,10/58,10.75%,Pfn1;Clu;Calm1;Anxa5;Lgals3;Pla2g7;Ctsc;Hspa5;...
14,prerank,PI3K/AKT/mTOR Signaling,0.511857,1.25762,0.162602,0.319511,0.946,6/16,13.55%,Pfn1;Cfl1;Cdkn1a;Pla2g12a;Cdk1;Stat2
16,prerank,IL-2/STAT5 Signaling,0.361262,1.182761,0.174081,0.422743,0.986,17/59,13.80%,Gsto1;Tgm2;Emp1;Smpdl3a;Ccne1;Phlda1;Ahnak;Pli...
17,prerank,G2-M Checkpoint,0.396065,1.166428,0.229412,0.419845,0.993,17/37,21.30%,Ncl;Birc5;Pttg1;Myc;Aurka;Atf5;Lmnb1;Cdk1;Plk1...
19,prerank,Spermatogenesis,0.511582,1.149478,0.285425,0.420533,0.995,5/11,12.75%,Scg5;Aurka;Nefh;Pcsk1n;Cdk1
20,prerank,Allograft Rejection,0.385456,1.148012,0.221545,0.392968,0.995,6/38,10.35%,Psmb10;B2m;Cdkn2a;Ccl7;Cd47;Tapbp
26,prerank,Xenobiotic Metabolism,0.339983,1.025099,0.398855,0.604517,1.0,13/42,17.50%,Gsto1;Psmb10;Ddc;Id2;Gch1;Pmm1;Fetub;Rbp4;Hmox...
28,prerank,Apoptosis,0.296293,0.979968,0.481481,0.667275,1.0,12/66,9.85%,Clu;Lmna;Dcn;Cth;Emp1;Cdkn1a;Lgals3;Anxa1;Gch1...
30,prerank,Pancreas Beta Cells,0.512619,0.93164,0.556989,0.735602,1.0,2/5,19.80%,Dcx;Lmo2
36,prerank,TNF-alpha Signaling via NF-kB,0.250248,0.857137,0.771379,0.855768,1.0,21/83,16.95%,Phlda2;Msc;Fosl1;Id2;Phlda1;Cdkn1a;Ifih1;Atp2b...
38,prerank,Glycolysis,0.280548,0.845218,0.742857,0.835398,1.0,11/40,16.25%,Dcn;Cth;Vcan;Cln6;Hs6st2;Hspa5;Aurka;Rragd;Cdk...
41,prerank,Angiogenesis,0.318742,0.821659,0.719745,0.840503,1.0,4/19,10.80%,Lrpap1;Vcan;Fstl1;Col3a1

In [54]:
# GO biological process in Hic2 OX pathway

pre_res = gseapy.prerank(
    rnk=hic2_rank_df[["scores"]], 
    gene_sets="GO_Biological_Process_2025",
    threads=32,
    min_size=5,
    max_size=1000
)
pre_res.res2d.sort_values("NES", ascending=False).head(20)[["Term", "NES", "NOM p-val", "FWER p-val", "FDR q-val"]]

2026-03-09 14:00:00,485 [WARNING] Duplicated values found in preranked stats: 0.80% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

,Term,NES,NOM p-val,FWER p-val,FDR q-val
0,Negative Regulation of Viral Genome Replicatio...,1.743962,0.008511,0.747,1.0
1,Mitotic Cell Cycle Phase Transition (GO:0044772),1.741767,0.006579,0.751,0.94428
3,Regulation of Cell Cycle Process (GO:0010564),1.70615,0.006224,0.883,1.0
4,Regulation of Cytokine Production (GO:0001817),1.693619,0.005871,0.92,0.906386
6,Protein Localization to Nucleus (GO:0034504),1.682094,0.004292,0.94,0.84505
7,Positive Regulation of Pattern Recognition Rec...,1.679265,0.013304,0.949,0.732609
8,Negative Regulation of Leukocyte Degranulation...,1.67372,0.002179,0.965,0.674485
9,Negative Regulation of Viral Process (GO:0048525),1.67054,0.020284,0.97,0.614182
10,Regulation of Interleukin-10 Production (GO:00...,1.669307,0.012821,0.972,0.555145
11,Regulation of Viral Genome Replication (GO:004...,1.663897,0.018367,0.974,0.540584
12,Response to Cytokine (GO:0034097),1.65492,0.011952,0.978,0.546643
13,Antiviral Innate Immune Response (GO:0140374),1.636403,0.010331,0.989,0.630697
14,Negative Regulation of Supramolecular Fiber Or...,1.631654,0.025896,0.991,0.619115
15,Peptide Hormone Processing (GO:0016486),1.630923,0.018908,0.992,0.580609
16,Defense Response to Virus (GO:0051607),1.627907,0.008163,0.993,0.56004
17,Catecholamine Biosynthetic Process (GO:0042423),1.623769,0.004329,0.996,0.550692
18,Positive Regulation of Cation Channel Activity...,1.61397,0.032397,0.996,0.576891
19,Regulation of Mitotic Cell Cycle Phase Transit...,1.603371,0.020243,0.999,0.612887
20,Positive Regulation of Innate Immune Response ...,1.601806,0.027719,1.0,0.591383
23,Pattern Recognition Receptor Signaling Pathway...,1.58691,0.013793,1.0,0.655724

### Day 9 Hic2 OX

In [37]:
late_rank_df = scanpy.get.rank_genes_groups_df(
    adata,
    key="macrostate_rank_genes",
    group="Day 9 Hic2 OX"
)
late_rank_df.index = late_rank_df["names"]
late_rank_df = late_rank_df.drop(columns="names")

In [41]:
late_rank_df.loc[numpy.intersect1d(target_tfs, adata.var_names)].sort_values("scores", ascending=False).head(20)

            scores  logfoldchanges          pvals      pvals_adj
names
Tcf7l2   37.064835        1.508311  1.036050e-300  1.883727e-298
Jarid2   30.248821        1.286976  5.406728e-201  2.922556e-199
Tcf7l1   23.495508        1.071344  4.533657e-122  9.158904e-121
Zfp42    22.298857        0.912690  3.790599e-110  6.535515e-109
Fos      20.607384        1.226833   2.356247e-94   3.390283e-93
Tfcp2l1  18.570190        0.933905   5.600398e-77   6.087390e-76
Tfap2c   18.173567        1.414879   8.358384e-74   8.844851e-73
Sall1    15.699179        0.991098   1.532119e-55   1.174037e-54
Hic2     11.966811        0.668471   5.302742e-33   2.537197e-32
Arid3a   11.541954        0.692182   8.106209e-31   3.684640e-30
Fosb     10.892230        1.237225   1.255289e-27   5.296579e-27
Rest      9.504901        0.263599   2.002378e-21   7.176981e-21
Tsc22d1   7.782866        0.298603   7.089988e-15   2.113260e-14
Pou5f1    5.375675        0.313989   7.629646e-08   1.724214e-07
Mycn      4.481123        0.094368   7.425139e-06   1.501545e-05
Zfp710    3.959528        0.156325   7.509801e-05   1.440039e-04
Id2       3.858542        0.351938   1.140656e-04   2.162382e-04
Zfp36l1   3.657126        0.116028   2.550592e-04   4.723319e-04
Peg3      3.473407        0.229469   5.138957e-04   9.301280e-04
Egr1      2.952149        0.118953   3.155707e-03   5.335092e-03

In [40]:
# Cell types

pre_res = gseapy.prerank(
    rnk=late_rank_df[["scores"]], 
    gene_sets="PanglaoDB_Augmented_2021",
    threads=32,
    min_size=5,
    max_size=1000
)
pre_res.res2d.sort_values("NES", ascending=False).head(20)

2026-03-09 13:43:14,698 [WARNING] Duplicated values found in preranked stats: 0.30% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

,Name,Term,ES,NES,NOM p-val,FDR q-val,FWER p-val,Tag %,Gene %,Lead_genes
0,prerank,Kupffer Cells,0.785404,2.070219,0.0,0.0,0.0,5/33,10.50%,Pltp;Lgals9;Hck;Dok2;Ncf2
6,prerank,Osteoclast Precursor Cells,0.693428,1.813739,0.0,0.018252,0.048,6/29,20.60%,Lgals9;Hck;Cd68;Ncf2;Laptm5;Samd9l
11,prerank,Pluripotent Stem Cells,0.684123,1.762792,0.0,0.025552,0.095,19/25,22.70%,Gdf3;Terf1;Trim71;Sall4;Dnmt3b;Msh6;Hells;Mcm3...
18,prerank,Macrophages,0.551475,1.65649,0.001355,0.081403,0.315,9/59,10.50%,Pltp;Ucp2;Lgals9;Hck;Cd68;Dusp5;Cd200;Dok2;Ncf2
19,prerank,Langerhans Cells,0.639908,1.653216,0.004673,0.067458,0.323,5/27,22.55%,Lgals9;Hck;Ncf2;Laptm5;Snx20
21,prerank,Red Pulp Macrophages,0.644078,1.645733,0.001534,0.063394,0.356,4/26,19.55%,Hck;Ncf2;Hmox1;Slc7a7
22,prerank,Microglia,0.575776,1.640523,0.004348,0.058093,0.368,8/46,11.85%,Ucp2;Lgals9;Hck;Fos;Sall1;Dok2;Ncf2;Pecam1
25,prerank,Eosinophils,0.618619,1.580054,0.01214,0.106499,0.565,7/25,28.25%,Hck;Dok2;Laptm5;Ltc4s;Snx20;Pglyrp1;Arhgap30
26,prerank,Alveolar Macrophages,0.593271,1.579414,0.007278,0.095396,0.569,7/34,18.20%,Plet1;Lgals9;Hck;Cd68;Ncf2;Gngt2;Laptm5
28,prerank,Gamma Delta T Cells,0.709927,1.545743,0.026362,0.123017,0.687,9/12,19.90%,Hmgb2;Top2a;Cenpa;Cenpf;Aurkb;Birc5;Mki67;Nusa...
29,prerank,T Regulatory Cells,0.621536,1.535679,0.01964,0.12524,0.732,2/24,8.80%,Folr1;Dok2
34,prerank,Delta Cells,0.589062,1.510188,0.027113,0.148995,0.823,6/26,14.40%,Ucp2;Atp1b1;Nrxn1;Unc5b;Rcan2;Ppp1r1a
35,prerank,Myeloid-derived Suppressor Cells,0.589401,1.505981,0.028919,0.143936,0.832,3/25,10.50%,Hck;Dok2;Ncf2
37,prerank,Neutrophils,0.56769,1.485405,0.041979,0.161136,0.88,5/27,13.90%,Hck;Dok2;Ncf2;Pecam1;Mme
38,prerank,Oxyphil Cells,0.640803,1.484616,0.037855,0.151221,0.881,6/17,21.00%,Mapt;Hrc;Ppp1r1a;Atp1a2;Smyd1;Prex2
47,prerank,Oligodendrocytes,0.561686,1.437591,0.046926,0.214229,0.959,5/25,19.35%,Ddc;Plekhh1;Nrxn1;Atp1a2;Aspa
48,prerank,T Follicular Helper Cells,0.597326,1.433395,0.057971,0.209272,0.963,4/19,22.55%,Cd200;Dok2;Laptm5;Snx20
49,prerank,Ependymal Cells,0.674729,1.432377,0.06822,0.199471,0.964,3/12,4.10%,Pltp;Capsl;Trim71
52,prerank,Thymocytes,0.576704,1.396348,0.069307,0.251989,0.979,4/20,22.55%,Ucp2;Dok2;Laptm5;Snx20
57,prerank,Reticulocytes,0.728559,1.365149,0.107143,0.301956,0.993,4/7,11.75%,Folr1;Dhx16;Mcm3;Incenp

Still like immune cells, but also pluripotent stem cells.

### Stem cells

In [43]:
mesc_rank_df = scanpy.get.rank_genes_groups_df(
    adata,
    key="macrostate_rank_genes",
    group="mESC"
)
mesc_rank_df.index = mesc_rank_df["names"]
mesc_rank_df = mesc_rank_df.drop(columns="names")

In [47]:
mesc_rank_df.loc[genes_of_interest].sort_values("scores", ascending=False).head(20)

           scores  logfoldchanges          pvals      pvals_adj
names
Zfp42   67.341812        4.388525   0.000000e+00   0.000000e+00
Rest    62.072388        2.318409   0.000000e+00   0.000000e+00
Jarid2  60.975414        3.011444   0.000000e+00   0.000000e+00
Klf4    33.226761        1.959148  4.422481e-242  2.862447e-241
Tcf7l1  25.351522        1.151651  8.645614e-142  3.800270e-141
Cdh1    25.069399        1.208922  1.072874e-138  4.644478e-138
Hic2    16.042459        0.843960   6.454696e-58   1.705336e-57
Ovol1  -12.893654       -3.375580   4.887225e-38   1.117080e-37
Tlx2   -19.955168       -4.166796   1.351705e-88   4.388653e-88
Zbtb7c -23.692108       -3.065755  4.348611e-124  1.739444e-123
Myc    -27.924755       -1.787152  1.335760e-171  6.563932e-171

In [46]:
# Cell types

pre_res = gseapy.prerank(
    rnk=mesc_rank_df[["scores"]], 
    gene_sets="PanglaoDB_Augmented_2021",
    threads=32,
    min_size=5,
    max_size=1000
)
pre_res.res2d.sort_values("NES", ascending=False).head(20)

2026-03-09 13:48:47,693 [WARNING] Duplicated values found in preranked stats: 0.30% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

,Name,Term,ES,NES,NOM p-val,FDR q-val,FWER p-val,Tag %,Gene %,Lead_genes
0,prerank,Epiblast Cells,0.79995,2.347374,0.0,0.0,0.0,21/33,14.95%,Tdgf1;Phc1;Sall4;Nanog;Fgf4;Trim71;Cecr2;Ina;M...
1,prerank,Pluripotent Stem Cells,0.854374,2.344033,0.0,0.0,0.0,24/25,14.95%,Tdgf1;Nasp;Msh6;Hells;Mcm3;Sall4;Dppa2;Nanog;F...
3,prerank,Oxyphil Cells,0.758383,1.922956,0.0,0.002552,0.011,5/17,8.55%,Esrrb;Cecr2;Tfdp2;Lrrc2;Ppp1r1a
12,prerank,Gamma Delta T Cells,0.785635,1.798505,0.002141,0.01601,0.077,9/12,14.10%,Ifitm1;Hmgb2;Top2a;Cenpf;Nusap1;Aspm;Mki67;Aur...
28,prerank,Reticulocytes,0.787768,1.581462,0.035556,0.164138,0.589,4/7,10.00%,Mcm3;Dhx16;Incenp;Folr1
34,prerank,Embryonic Stem Cells,0.449199,1.521405,0.015054,0.226925,0.759,31/66,17.45%,Tdgf1;Zfp42;Utf1;Dppa4;Fbxo15;Sall4;Enah;Dppa2...
37,prerank,Proximal Tubule Cells,0.614215,1.481963,0.043197,0.263719,0.853,6/14,18.70%,Apoe;Alpl;Folr1;Napsa;Ass1;Lrp2
44,prerank,Glycinergic Neurons,0.610196,1.405129,0.087398,0.39303,0.948,5/12,17.95%,Ina;Aplp1;Ckb;Gng3;Elavl3
45,prerank,Adrenergic Neurons,0.617804,1.401959,0.073684,0.355315,0.949,4/11,14.75%,Fxyd6;Mycn;Pcsk1n;Palm3
47,prerank,Retinal Ganglion Cells,0.509504,1.383505,0.071279,0.362315,0.97,3/24,6.35%,Rbpms2;Ina;Aplp1
53,prerank,Cholinergic Neurons,0.540847,1.329814,0.12043,0.46271,0.99,3/14,10.20%,Ina;Aplp1;Brca1
54,prerank,Germ Cells,0.534429,1.323967,0.102908,0.438478,0.991,10/16,18.55%,Hook1;Cox6b2;Brca1;Tfap2c;Mki67;Pou5f1;Smc1b;D...
63,prerank,Acinar Cells,0.635782,1.260925,0.188017,0.58011,0.998,2/8,9.60%,Pla2g1b;Spink1
70,prerank,Cajal-Retzius Cells,0.439382,1.224134,0.176591,0.6586,0.999,3/27,6.35%,Zdbf2;Ina;Aplp1
74,prerank,Enterocytes,0.403655,1.17175,0.215569,0.80352,0.999,5/33,9.60%,Col18a1;Klf5;Ephx2;Nr5a2;Spink1
75,prerank,Serotonergic Neurons,0.583835,1.17091,0.25,0.756606,0.999,3/7,17.85%,Spink1;Glod5;Tfpi
80,prerank,Epithelial Cells,0.337752,1.119738,0.239741,0.906759,1.0,15/67,16.25%,Zfp42;Klf5;Epcam;Kif20b;Ect2;Hmmr;Hirip3;Incen...
87,prerank,Retinal Progenitor Cells,0.402015,1.09196,0.311159,0.971006,1.0,7/23,19.65%,Ina;Aplp1;Otx2;Nefh;Elavl3;Sall3;Notch1
93,prerank,B Cells Memory,0.39549,1.036956,0.401766,1.0,1.0,4/20,21.65%,Rasgrp2;Laptm5;Arhgap30;Aim2
95,prerank,Nuocytes,0.509538,1.016579,0.449561,1.0,1.0,8/8,49.25%,Crlf2;Tnfsf8;Ptprc;Gbp5;Arg1;Rora;Il1rl1;Gata3

# Find which transcription factors are upregulated in the dead end with Decoupler

Databases available in Decoupler: https://omnipathdb.org/info.html

## CollecTRI

In [80]:
# Load CollecTRI database

collectri_df = decoupler.op.collectri(organism="mouse")

In [141]:
# TF activity in dead end CollecTRI

data = dead_end_rank_df[["scores"]].T.dropna(axis=1)
tf_acts, tf_padj = decoupler.mt.ulm(data=data, net=collectri_df)
activities_df = pandas.DataFrame(data={"Activity": tf_acts.transpose()["scores"], "Adjusted p-value": tf_padj.transpose()["scores"]}, index=tf_acts.columns)
activities_df.sort_values("Activity", ascending=False).head(30)

         Activity  Adjusted p-value
Trp73    4.029077          0.016108
Ppara    3.984019          0.016108
Atf4     3.839768          0.019429
Atf6     3.703987          0.025015
Klf4     3.611301          0.026601
Arnt     3.387582          0.047047
Klf6     3.351070          0.047047
Pparg    3.284603          0.048020
Trp53    3.282625          0.048020
Spdef    3.254378          0.048211
Irf1     2.931467          0.108922
Brca1    2.886016          0.108922
Trp63    2.878817          0.108922
Kdm5a    2.789967          0.125740
Etv6     2.780474          0.125740
Nfe2l2   2.654015          0.133597
Kmt2a    2.637267          0.133597
Klf8     2.636528          0.133597
Ing4     2.591043          0.138453
Creb1    2.520182          0.164221
Bmal1    2.503348          0.167153
Nfatc3   2.486332          0.169236
Neurog2  2.465378          0.169236
Tbpl1    2.440625          0.169236
Elk3     2.412668          0.178291
Esr2     2.379508          0.186046
Relb     2.355520          0.189579
Mef2d    2.318438          0.189579
Bhlha15  2.312199          0.189579
Dmtf1    2.288020          0.189579

In [100]:
# Most downregulated in dead end

activities_df.sort_values("Activity", ascending=True).head(25)

        Activity  Adjusted p-value
Thrb   -3.934584          0.013187
Ovol1  -3.554015          0.033014
Atf3   -3.525898          0.033014
Smad3  -3.192313          0.093985
Smad4  -3.086192          0.117917
Tcf21  -2.984713          0.146517
Pgr    -2.727191          0.268868
Hbp1   -2.688656          0.276686
Tfcp2  -2.589001          0.286822
Zfp42  -2.580047          0.286822
Smad2  -2.528043          0.286822
Zbtb7a -2.520715          0.286822
Hdgf   -2.518212          0.286822
Max    -2.476784          0.306140
Snai2  -2.403476          0.340264
Foxo3  -2.382883          0.340264
Hdac1  -2.349771          0.340264
Zeb2   -2.339212          0.340264
Zeb1   -2.287075          0.340264
Rest   -2.269945          0.340264
Cebpe  -2.268719          0.340264
Twist1 -2.251479          0.340264
Scx    -2.192510          0.362836
Hoxb13 -2.131985          0.370891
Foxo1  -2.070655          0.420959

In [143]:
# TF activity in day 4 control, CollecTRI

data = control_rank_df[["scores"]].T.dropna(axis=1)
tf_acts, tf_padj = decoupler.mt.ulm(data=data, net=collectri_df)
activities_df = pandas.DataFrame(data={"Activity": tf_acts.transpose()["scores"], "Adjusted p-value": tf_padj.transpose()["scores"]}, index=tf_acts.columns)
print("Top")
IPython.display.display(activities_df.sort_values("Activity", ascending=False).head(30))
print("Bottom")
IPython.display.display(activities_df.sort_values("Activity", ascending=True).head(30))

Top

         Activity  Adjusted p-value
Klf8     4.716857          0.001175
Mybl2    4.475703          0.001846
Relb     3.659164          0.029789
Kmt2a    2.742200          0.268868
Sox17    2.588997          0.286822
Kdm5b    2.523081          0.286822
Tcf4     2.364670          0.340264
Meis1    2.329665          0.340264
Hnf4a    2.295128          0.340264
Isl1     2.252731          0.340264
Gtf2i    2.251688          0.340264
Stat5a   2.232469          0.345859
Phox2b   2.222329          0.345859
Myog     2.171722          0.370891
Mbd2     2.150647          0.370891
Hoxb2    2.146505          0.370891
Elf1     2.136963          0.370891
Crebbp   2.043111          0.429503
Tbpl1    2.014110          0.450144
Hoxa1    1.991429          0.454797
Mtf1     1.978918          0.458640
Zfp354c  1.951414          0.479115
Ncoa1    1.874860          0.500205
Nfkb2    1.873183          0.500205
Bach1    1.867009          0.500205
Shox2    1.859622          0.500205
Tal1     1.858989          0.500205
Zic1     1.843622          0.500205
Klf4     1.824020          0.505947
Ascl1    1.812613          0.510303

Bottom

        Activity  Adjusted p-value
Thrb   -3.934584          0.013187
Ovol1  -3.554015          0.033014
Atf3   -3.525898          0.033014
Smad3  -3.192313          0.093985
Smad4  -3.086192          0.117917
Tcf21  -2.984713          0.146517
Pgr    -2.727191          0.268868
Hbp1   -2.688656          0.276686
Tfcp2  -2.589001          0.286822
Zfp42  -2.580047          0.286822
Smad2  -2.528043          0.286822
Zbtb7a -2.520715          0.286822
Hdgf   -2.518212          0.286822
Max    -2.476784          0.306140
Snai2  -2.403476          0.340264
Foxo3  -2.382883          0.340264
Hdac1  -2.349771          0.340264
Zeb2   -2.339212          0.340264
Zeb1   -2.287075          0.340264
Rest   -2.269945          0.340264
Cebpe  -2.268719          0.340264
Twist1 -2.251479          0.340264
Scx    -2.192510          0.362836
Hoxb13 -2.131985          0.370891
Foxo1  -2.070655          0.420959
Foxc1  -2.060414          0.421514
Sp1    -1.997241          0.454797
Foxf2  -1.929449          0.494036
Sirt1  -1.890378          0.500205
Jdp2   -1.858142          0.500205

Dorothea is an alternative, but it has fewer TFs and targets.

## Progeny database

In [ ]:
# Load database

progeny_df = decoupler.op.progeny(organism="mouse")

In [122]:
# Progeny pathways in dead end

data = dead_end_rank_df[["scores"]].T.dropna(axis=1)
tf_acts, tf_padj = decoupler.mt.ulm(data=data, net=progeny_df)
activities_df = pandas.DataFrame(data={"Activity": tf_acts.transpose()["scores"], "Adjusted p-value": tf_padj.transpose()["scores"]}, index=tf_acts.columns)

IPython.display.display(activities_df.sort_values("Activity", ascending=False))

           Activity  Adjusted p-value
p53       11.175544      5.049649e-27
Hypoxia    4.085607      2.132595e-04
NFkB       2.682470      2.063120e-02
VEGF       2.560395      2.327722e-02
Trail      2.525243      2.327722e-02
TNFa       2.147510      5.577717e-02
Androgen   1.364986      2.194324e-01
EGFR       1.102954      3.152097e-01
MAPK       0.268889      7.880430e-01
WNT       -0.282407      7.880430e-01
TGFb      -1.366368      2.194324e-01
JAK-STAT  -2.079611      5.862645e-02
Estrogen  -3.354724      2.832536e-03
PI3K      -5.698334      9.726712e-08

## Hallmark database

In [123]:
# Load database

hallmark_df = decoupler.op.hallmark(organism="mouse")

In [126]:
# Hallmark pathways in dead end

data = dead_end_rank_df[["scores"]].T.dropna(axis=1)
tf_acts, tf_padj = decoupler.mt.ulm(data=data, net=hallmark_df)
activities_df = pandas.DataFrame(data={"Activity": tf_acts.transpose()["scores"], "Adjusted p-value": tf_padj.transpose()["scores"]}, index=tf_acts.columns)

print("Top")
IPython.display.display(activities_df.sort_values("Activity", ascending=False).head(20))
print("Bottom")
IPython.display.display(activities_df.sort_values("Activity", ascending=True).head(20))

Top

                            Activity  Adjusted p-value
P53_PATHWAY                 7.402222      9.618454e-12
TNFA_SIGNALING_VIA_NFKB     5.438254      5.919235e-07
MTORC1_SIGNALING            3.577776      2.287099e-03
HYPOXIA                     3.512976      2.466146e-03
ESTROGEN_RESPONSE_EARLY     3.297621      4.537892e-03
UV_RESPONSE_UP              3.290162      4.537892e-03
ANDROGEN_RESPONSE           2.225769      8.539350e-02
MYC_TARGETS_V1              2.137684      9.539345e-02
UNFOLDED_PROTEIN_RESPONSE   2.104697      9.648170e-02
ESTROGEN_RESPONSE_LATE      2.044442      1.005498e-01
KRAS_SIGNALING_DN           1.746707      1.865790e-01
TGF_BETA_SIGNALING          1.660290      1.997225e-01
CHOLESTEROL_HOMEOSTASIS     1.656275      1.997225e-01
WNT_BETA_CATENIN_SIGNALING  1.470995      2.537209e-01
IL6_JAK_STAT3_SIGNALING     1.458052      2.537209e-01
NOTCH_SIGNALING             1.434143      2.563005e-01
IL2_STAT5_SIGNALING         1.354060      2.779886e-01
XENOBIOTIC_METABOLISM       1.309266      2.918485e-01
HEME_METABOLISM             1.216578      3.324704e-01
PROTEIN_SECRETION           0.966848      4.419762e-01

Bottom

                                   Activity  Adjusted p-value
EPITHELIAL_MESENCHYMAL_TRANSITION -7.094219      4.406731e-11
G2M_CHECKPOINT                    -6.797039      2.294860e-10
E2F_TARGETS                       -5.995401      2.943103e-08
MITOTIC_SPINDLE                   -5.051003      3.915482e-06
INTERFERON_ALPHA_RESPONSE         -3.564292      2.287099e-03
OXIDATIVE_PHOSPHORYLATION         -2.650596      3.144966e-02
UV_RESPONSE_DN                    -2.640461      3.144966e-02
ANGIOGENESIS                      -2.391771      5.900746e-02
APICAL_JUNCTION                   -2.132399      9.539345e-02
SPERMATOGENESIS                   -2.059392      1.005498e-01
GLYCOLYSIS                        -1.730081      1.865790e-01
PEROXISOME                        -1.575656      2.259163e-01
DNA_REPAIR                        -1.536990      2.345481e-01
BILE_ACID_METABOLISM              -1.403722      2.622430e-01
ALLOGRAFT_REJECTION               -1.179568      3.422185e-01
COMPLEMENT                        -1.164299      3.422185e-01
INTERFERON_GAMMA_RESPONSE         -1.105290      3.663664e-01
COAGULATION                       -0.931537      4.483913e-01
FATTY_ACID_METABOLISM             -0.437499      7.500635e-01
REACTIVE_OXYGEN_SPECIES_PATHWAY   -0.399888      7.500635e-01

In [128]:
# Hallmark pathways in day 4 control

data = control_rank_df[["scores"]].T.dropna(axis=1)
tf_acts, tf_padj = decoupler.mt.ulm(data=data, net=hallmark_df)
activities_df = pandas.DataFrame(data={"Activity": tf_acts.transpose()["scores"], "Adjusted p-value": tf_padj.transpose()["scores"]}, index=tf_acts.columns)

print("Top")
IPython.display.display(activities_df.sort_values("Activity", ascending=False).head(20))
print("Bottom")
IPython.display.display(activities_df.sort_values("Activity", ascending=True).head(20))

Top

                            Activity  Adjusted p-value
ESTROGEN_RESPONSE_LATE      3.900823          0.002426
ESTROGEN_RESPONSE_EARLY     2.895034          0.062595
MYC_TARGETS_V1              2.642994          0.081162
MTORC1_SIGNALING            2.541076          0.088094
G2M_CHECKPOINT              2.484186          0.088094
E2F_TARGETS                 2.443250          0.088094
P53_PATHWAY                 2.225636          0.128134
WNT_BETA_CATENIN_SIGNALING  1.998669          0.203066
NOTCH_SIGNALING             1.928981          0.203066
ANDROGEN_RESPONSE           1.794024          0.255362
XENOBIOTIC_METABOLISM       1.754661          0.259604
PI3K_AKT_MTOR_SIGNALING     1.501979          0.369829
KRAS_SIGNALING_DN           1.112887          0.542861
CHOLESTEROL_HOMEOSTASIS     0.916961          0.673456
HEME_METABOLISM             0.869219          0.673456
ALLOGRAFT_REJECTION         0.744281          0.698239
APICAL_SURFACE              0.722222          0.698239
PEROXISOME                  0.652654          0.737391
PANCREAS_BETA_CELLS         0.383476          0.867099
IL6_JAK_STAT3_SIGNALING     0.374817          0.867099

Bottom

                                   Activity  Adjusted p-value
EPITHELIAL_MESENCHYMAL_TRANSITION -5.090008          0.000019
UV_RESPONSE_DN                    -2.691453          0.081162
INTERFERON_ALPHA_RESPONSE         -2.406862          0.088094
HYPOXIA                           -1.957955          0.203066
APICAL_JUNCTION                   -1.690011          0.279244
ADIPOGENESIS                      -1.492006          0.369829
OXIDATIVE_PHOSPHORYLATION         -1.407434          0.411224
BILE_ACID_METABOLISM              -1.347908          0.435710
DNA_REPAIR                        -1.319693          0.436541
APOPTOSIS                         -1.283101          0.444576
COAGULATION                       -1.225323          0.469970
KRAS_SIGNALING_UP                 -0.929283          0.673456
TNFA_SIGNALING_VIA_NFKB           -0.889521          0.673456
COMPLEMENT                        -0.830645          0.679743
INTERFERON_GAMMA_RESPONSE         -0.813254          0.679743
MYOGENESIS                        -0.786103          0.682681
ANGIOGENESIS                      -0.633151          0.737391
INFLAMMATORY_RESPONSE             -0.515678          0.825019
TGF_BETA_SIGNALING                -0.458526          0.856340
UNFOLDED_PROTEIN_RESPONSE         -0.399832          0.867099

## Trrust database

In [131]:
# Load database

trrust_df = decoupler.op.resource("TRRUST", organism="human")

AssertionError: name must be one of these: {'ComPPI', 'SignaLink_function', 'PanglaoDB', 'TFcensus', 'Kirouac2010', 'KEGG-PC', 'GO_Intercell', 'Guide2Pharma', 'connectomeDB2020', 'Matrisome', 'CancerGeneCensus', 'Almen2009', 'MSigDB', 'Surfaceome', 'HPA_tissue', 'CellCall', 'Wang', 'InterPro', 'Phosphatome', 'CellChatDB_complex', 'MatrixDB', 'Membranome', 'LRdb', 'MCAM', 'Vesiclepedia', 'iTALK', 'CPAD', 'KEGG', 'SIGNOR', 'Adhesome', 'Baccin2019', 'Integrins', 'DGIdb', 'HPA_subcellular', 'HPMR', 'NetPath', 'Cellinker', 'Ramilowski_location', 'TopDB', 'GPCRdb', 'ICELLNET_complex', 'PROGENy', 'OPM', 'scConnect_complex', 'HGNC', 'TCDB', 'Zhong2015', 'kinase.com', 'ICELLNET', 'CellPhoneDB', 'EMBRACE', 'DisGeNet', 'LOCATE', 'talklr', 'HumanCellMap', 'CellTypist', 'CancerDrugsDB', 'UniProt_family', 'CSPA_celltype', 'CellPhoneDB_complex', 'CytoSig', 'CORUM_Funcat', 'SignaLink_pathway', 'CellTalkDB', 'IntOGen', 'Cellinker_complex', 'Exocarta', 'Phobius', 'CellCellInteractions', 'CellChatDB', 'Lambert2018', 'UniProt_keyword', 'HPA_secretome', 'UniProt_location', 'CORUM_GO', 'scConnect', 'UniProt_topology', 'CancerSEA', 'Ramilowski2015', 'UniProt_tissue', 'CSPA'}